// Cadde demo içerikleri — yalnız mode==='demo' veya Supabase yapılandırılmadığında kullanılır.
// Gerçek moddaki hata durumlarında ASLA demo veri dönülmez (bkz. cadde-api.ts).

import type {
  CaddeBillboardCard,
  CaddeCafe,
  CaddeCity,
  CaddeCountry,
  CaddePost,
  CaddeSponsoredPlacement,
} from "./cadde-types";

export const DEMO_COUNTRIES: CaddeCountry[] = [
  { id: "country-de", code: "DE", name: "Almanya" },
  { id: "country-nl", code: "NL", name: "Hollanda" },
  { id: "country-gb", code: "GB", name: "Birleşik Krallık" },
  { id: "country-us", code: "US", name: "Amerika Birleşik Devletleri" },
  { id: "country-tr", code: "TR", name: "Türkiye" },
];

export const DEMO_CITIES: CaddeCity[] = [
  { id: "city-berlin", countryId: "country-de", name: "Berlin", timezone: "Europe/Berlin" },
  { id: "city-hamburg", countryId: "country-de", name: "Hamburg", timezone: "Europe/Berlin" },
  { id: "city-amsterdam", countryId: "country-nl", name: "Amsterdam", timezone: "Europe/Amsterdam" },
  { id: "city-london", countryId: "country-gb", name: "Londra", timezone: "Europe/London" },
  { id: "city-newyork", countryId: "country-us", name: "New York", timezone: "America/New_York" },
  { id: "city-istanbul", countryId: "country-tr", name: "İstanbul", timezone: "Europe/Istanbul" },
];

export const DEMO_POSTS: CaddePost[] = [
  {
    id: "demo-post-1",
    mode: "demo",
    type: "question",
    title: "Berlin'de yaz stajı için topluluk arayışı",
    body: "2 haftadır Berlin'deyim. Hem ürün tarafında hem de etkinliklerde dahil olabileceğim samimi bir çevre arıyorum.",
    authorName: "Elif Demir",
    authorRole: "Yeni Taşınan",
    authorAvatarUrl: null,
    authorUserId: null,
    country: "Almanya",
    city: "Berlin",
    isBridge: false,
    pinned: true,
    createdAt: "2026-05-28T10:00:00.000Z",
    needCategory: "new_arrival",
    interests: ["new_arrival", "networking"],
    reactionCounts: { like: 8, support: 5, idea: 2 },
    totalReactionCount: 15,
    commentCount: 2,
    comments: [
      { id: "demo-comment-1", postId: "demo-post-1", userId: "demo", body: "Berlin product meetuplarını paylaşabilirim.", authorName: "Mert Koca", createdAt: "2026-05-28T12:00:00.000Z" },
      { id: "demo-comment-2", postId: "demo-post-1", userId: "demo", body: "Cumartesi ortak çalışma buluşmasına bekleriz.", authorName: "Seda Yalçın", createdAt: "2026-05-28T13:00:00.000Z" },
    ],
    viewerReactions: [],
  },
  {
    id: "demo-post-2",
    mode: "demo",
    type: "offer",
    title: "Amsterdam ortak çalışma buluşması",
    body: "Perşembe günü saat 19:00'da merkezde serbest çalışma + networking oturumu yapıyoruz. Ürün, ihracat ve freelancer herkes gelebilir.",
    authorName: "Mert Koca",
    authorRole: "Topluluk Lideri",
    authorAvatarUrl: null,
    authorUserId: null,
    country: "Hollanda",
    city: "Amsterdam",
    isBridge: false,
    pinned: false,
    createdAt: "2026-05-27T16:00:00.000Z",
    needCategory: "networking",
    interests: ["networking", "entrepreneurship"],
    reactionCounts: { like: 10, support: 3, idea: 4 },
    totalReactionCount: 17,
    commentCount: 1,
    comments: [{ id: "demo-comment-3", postId: "demo-post-2", userId: "demo", body: "İlk kez gelenler için de uygun.", authorName: "Deniz O.", createdAt: "2026-05-27T18:00:00.000Z" }],
    viewerReactions: [],
  },
  {
    id: "demo-post-3",
    mode: "demo",
    type: "event",
    title: "Londra girişimci kahvesi açıldı",
    body: "Bu hafta sonu Londra'da yatırım, diaspora networkü ve yeni pazar açılışı konularını konuşacağız.",
    authorName: "Seda Yalçın",
    authorRole: "Kurucu",
    authorAvatarUrl: null,
    authorUserId: null,
    country: "Birleşik Krallık",
    city: "Londra",
    isBridge: true,
    pinned: false,
    createdAt: "2026-05-26T09:30:00.000Z",
    needCategory: "entrepreneurship",
    interests: ["entrepreneurship", "career"],
    reactionCounts: { like: 12, support: 6, idea: 5 },
    totalReactionCount: 23,
    commentCount: 0,
    comments: [],
    viewerReactions: [],
  },
];

export const DEMO_CAFES: CaddeCafe[] = [
  {
    id: "demo-cafe-1",
    title: "Berlin Sabah Kahvesi",
    summary: "Yeni gelenler ve uzun süredir burada olanlar için hızlı tanışma odası.",
    hostName: "Ayşe U.",
    country: "Almanya",
    city: "Berlin",
    isBridge: false,
    isFree: true,
    startsAt: "2026-05-29T08:00:00.000Z",
    endsAt: "2026-05-29T11:00:00.000Z",
    isActive: true,
    memberCount: 12,
    joinedByViewer: false,
    mode: "demo",
    slug: null,
    themeKey: "Genel",
    entryMode: "open",
    entryQuestion: null,
    capacity: null,
    archivedAt: null,
    hostUserId: null,
    viewerMemberStatus: null,
  },
  {
    id: "demo-cafe-2",
    title: "TR-Köprü Mentor Cafe",
    summary: "Türkiye ile diaspora arasında taşınma ve iş bağlantıları için ortak oda.",
    hostName: "Can E.",
    country: "Türkiye",
    city: "İstanbul",
    isBridge: true,
    isFree: true,
    startsAt: "2026-05-29T09:00:00.000Z",
    endsAt: "2026-05-29T12:00:00.000Z",
    isActive: true,
    memberCount: 18,
    joinedByViewer: false,
    mode: "demo",
    slug: null,
    themeKey: "Genel",
    entryMode: "open",
    entryQuestion: null,
    capacity: null,
    archivedAt: null,
    hostUserId: null,
    viewerMemberStatus: null,
  },
];

export const DEMO_BILLBOARDS: CaddeBillboardCard[] = [
  {
    id: "demo-board-1",
    type: "consultant",
    title: "Oturum ve Taşınma Danışmanı",
    subtitle: "Berlin",
    description: "Yeni taşınanlar için resmi süreçler, oturum ve ilk 90 gün kontrol listesi.",
    badgeText: "Danışman",
    ctaLabel: "Görüşme Talep Et",
    ctaUrl: "/directory?country=Almanya&city=Berlin",
    imageUrl: null,
    isFeatured: true,
  },
  {
    id: "demo-board-2",
    type: "business",
    title: "Anadolu Taste Kitchen",
    subtitle: "Amsterdam",
    description: "Hafta içi networking masası ve topluluk kampanyalarıyla işletmenizi öne çıkarın.",
    badgeText: "Business",
    ctaLabel: "Mekânı Keşfet",
    ctaUrl: "/commercial/community-leader",
    imageUrl: null,
    isFeatured: false,
  },
  {
    id: "demo-board-3",
    type: "event",
    title: "Londra Diaspora Growth Night",
    subtitle: "Haziran 2026",
    description: "Kurucular, içerik üreticileri ve topluluk liderleri için aksiyon odaklı buluşma.",
    badgeText: "Etkinlik",
    ctaLabel: "Etkinliğe Git",
    ctaUrl: "/anket",
    imageUrl: null,
    isFeatured: true,
  },
];

export const DEMO_SPONSORED: CaddeSponsoredPlacement = {
  id: "demo-sponsored-1",
  title: "Sponsorlu Görünüm",
  description: "Danışman, etkinlik veya topluluk teklifinizi Cadde akışında görünür hale getirin.",
  badgeText: "Sponsorlu",
  ctaLabel: "Talep Bırak",
  ctaUrl: "/login?mode=signup",
  imageUrl: null,
};
