import { waPlaceholderImage } from "@/lib/whatsapp-landing-presentation";
import type { WhatsAppLanding } from "@/lib/whatsapp-landings";

export const placeholderLandings: WhatsAppLanding[] = [
  {
    id: "placeholder-berlin-girisim",
    groupName: "Berlin Girişim Ağı",
    platform: "Discord",
    category: "yatirim",
    country: "Almanya",
    city: "Berlin",
    mode: "visual",
    heroImage: waPlaceholderImage,
    tagline: "",
    callToActionText: "Girişimciler, operatörler ve yatırım odaklı profesyoneller için tanışma ve bilgi paylaşım alanı.",
    conditions: "",
    whatsappLink: "#",
    description: "Erken aşama girişimlerden büyüme evresindeki projelere kadar nitelikli bağlantılar kurmak isteyenler için.",
    submitterRole: "manager",
    status: "approved",
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "placeholder-dubai-yatirim",
    groupName: "Dubai Yatırım Çevresi",
    platform: "LinkedIn",
    category: "yatirim",
    country: "Birleşik Arap Emirlikleri",
    city: "Dubai",
    mode: "visual",
    heroImage: waPlaceholderImage,
    tagline: "",
    callToActionText: "Melek yatırım, fonlar ve girişim ekosistemi etrafında buluşan Türk profesyoneller için seçili topluluk.",
    conditions: "",
    whatsappLink: "#",
    description: "Yatırım, ortaklık ve bölgesel network geliştirmek isteyenler için tasarlandı.",
    submitterRole: "manager",
    status: "approved",
    createdAt: "2026-01-02T00:00:00.000Z",
  },
  {
    id: "placeholder-londra-kariyer",
    groupName: "Londra Kariyer ve İş İlişkileri",
    platform: "WhatsApp",
    category: "is",
    country: "Birleşik Krallık",
    city: "Londra",
    mode: "visual",
    heroImage: waPlaceholderImage,
    tagline: "",
    callToActionText: "Kurumsal kariyer, iş geliştirme ve sektör içi bağlantılar için aktif Türk profesyonel topluluğu.",
    conditions: "",
    whatsappLink: "#",
    description: "Deneyim paylaşımı, yönlendirme ve iş birlikleri odaklı bir ağ.",
    submitterRole: "member",
    status: "approved",
    createdAt: "2026-01-03T00:00:00.000Z",
  },
  {
    id: "placeholder-amsterdam-akademik",
    groupName: "Amsterdam Akademik Türkler",
    platform: "Telegram",
    category: "akademik",
    country: "Hollanda",
    city: "Amsterdam",
    mode: "visual",
    heroImage: waPlaceholderImage,
    tagline: "",
    callToActionText: "Araştırmacılar, yüksek lisans öğrencileri ve akademisyenler için bilgi ve duyuru topluluğu.",
    conditions: "",
    whatsappLink: "#",
    description: "Konferans, burs ve ortak çalışma fırsatları etrafında buluşan akademik çevre.",
    submitterRole: "manager",
    status: "approved",
    createdAt: "2026-01-04T00:00:00.000Z",
  },
  {
    id: "placeholder-toronto-dayanisma",
    groupName: "Toronto Dayanışma Hattı",
    platform: "Facebook",
    category: "dayanisma",
    country: "Kanada",
    city: "Toronto",
    mode: "visual",
    heroImage: waPlaceholderImage,
    tagline: "",
    callToActionText: "Yeni taşınanlar ve yerleşik üyeler arasında hızlı destek, yönlendirme ve yardımlaşma için kuruldu.",
    conditions: "",
    whatsappLink: "#",
    description: "Şehirde hayata uyum, sosyal destek ve güvenilir tavsiyeler için canlı topluluk.",
    submitterRole: "member",
    status: "approved",
    createdAt: "2026-01-05T00:00:00.000Z",
  },
  {
    id: "placeholder-paris-hobi",
    groupName: "Paris Sosyal ve Hobi Kulübü",
    platform: "Instagram",
    category: "hobi",
    country: "Fransa",
    city: "Paris",
    mode: "visual",
    heroImage: waPlaceholderImage,
    tagline: "",
    callToActionText: "Etkinlik, kültür, hafta sonu planları ve ortak ilgi alanları etrafında buluşan sosyal grup.",
    conditions: "",
    whatsappLink: "#",
    description: "Gündelik sosyalleşme ve şehirde birlikte aktivite yapmak isteyenler için.",
    submitterRole: "manager",
    status: "approved",
    createdAt: "2026-01-06T00:00:00.000Z",
  },
];
