project_id = "injprdrsklkxgnaiixzh"

[functions.find-matches]
verify_jwt = true

[functions.send-submission-email]
verify_jwt = true

[functions.lansman-admin]
verify_jwt = true

[functions.submit-survey-response]
verify_jwt = false
