// Ürün güncellemeleri — Eylül 2026 kayıtları (en yeniden eskiye).
// Tek kaynak barrel: ../admin-updates.ts — ekranlar oradan okur, buradan DEĞİL.

import type { AdminUpdateEntry } from "./types.ts";

export const ADMIN_UPDATES_2026_09: AdminUpdateEntry[] = [
  {
    id: "20260914-13-eylul-toplu-ozet-ve-kapanan-todolar",
    date: "14 Eylül 2026",
    title:
      "13 Eylül'ün tam dökümü: 55 commit, Komuta Merkezi'nde 57 madde kapandı, 11'i gerekçesiyle açık kaldı — ve bir güvenlik açığı sessizce kapatıldı",
    items: [
      "BU KAYIT NEDEN TOPLU VE GERİYE DÖNÜK: 13 Eylül tek günde 55 commit'lik çok yoğun bir gün oldu ve gün içinde yedi ayrı duyuru kaydı açıldı. Ama o kayıtlar parça parça yazıldığı için birkaç konu hiç duyurulmadan kaldı, kapatılan todo'ların ADLARI hiçbir yerde yazılmadı ve gün sonunda hazırlanan devir notunun içeriği panele yansımadı. Bu kayıt o boşlukları kapatıyor. Ayrıntılı teknik anlatım için günün kendi kayıtlarına bakın; bu bir toplu özettir.",
      "⚠️ ÖNCE DÜRÜST OLALIM — '57 MADDE KAPANDI' 57 İŞ YAPILDI DEMEK DEĞİL: Komuta Merkezi'nde son iki günde 68 maddeye dokunuldu, 57'si 'Tamamlandı' işaretlendi. Ama bunların yalnız bir bölümü gerçekten yapılmış işti (koda/veritabanına/dokümana bakılarak doğrulandı); geri kalanı 'artık geçerli değil' denilerek veya benzerleriyle tek maddede birleştirilerek kapatıldı. Hiçbiri silinmedi, hepsi gerekçesiyle kayıtlı ve gerekirse yeniden açılabilir. İptal/birleştirme kararları `docs/notes/2026-09-13-komuta-merkezi-iptal-edilenler.md` dosyasında tek tek yazılı.",
      "KAPANAN MADDELER — ARAYÜZ VE GÖRSEL DİL (12 madde, GERÇEKTEN YAPILDI): Cadde design-token dokümanı yazıldı ve arayüz ona hizalandı · üst navigasyondaki dört renk tek nötr renge indirildi · buton dili üç seviyeye indirildi · rozetler üç tipe indirildi · kart üstündeki gökkuşağı şeridi pillar renk koduna çevrildi · marka altını (#aa8c42) birincil eylem rengi yapıldı · arayüzdeki İngilizce kalıntılar (Pinned, Feedback Ver, Host) Türkçeleştirildi · yüzey sistemi sabitlendi (tek köşe yarıçapı, iki gölge seviyesi) · Cafe oda arayüzü düzenlendi · sıfır sayıları gizlendi ve boş şehirde otomatik ülke akışına düşüldü · 'Caddeye Çık' butonu ele alındı · Cadde header yığını düşürüldü.",
      "KAPANAN MADDELER — CONTRIBUTOR PAKETİ (7 madde): Contributor soruları toplandı, sorular konu başlıklarına göre tasnif edildi, FAQ dokümanı yazıldı, contributorların toplayacağı kaynak tipleri listelendi, kaynakların panele giriş süreci yazıldı, CONTRIBUTOR ADMIN ve CONTRIBUTOR DASHBOARD maddeleri kapatıldı. ⚠️ FAQ'nun tüm contributorlara YAZILI OLARAK PAYLAŞILMASI hâlâ açık — çünkü gelir modeli/şehir sahipliği kararı sizin onayınızı bekliyor.",
      "KAPANAN MADDELER — WHATSAPP BOT (6 madde): Role-based bot, Mastermind bot, Kanal bot kurguları; multi-lingual + DM + kategori bot yapısı tasarımı; bot → admin paneli Müşteri Talepleri entegrasyonu; resmî Meta Cloud API temeli. Bunların bir kısmı zaten canlıda çalışıyordu ve pano bunu bilmiyordu — 10 Eylül kaydındaki 'BU BEŞ MADDE ZATEN YAPILMIŞ' bulgusunun devamı.",
      "KAPANAN MADDELER — İNSAN KAYNAKLARI VE EKİP (9 madde): HR klasör yapısı üç parça hâlinde (teklifler / CV'ler / görev tanımları), ekip ücret & hisse breakdown analizi, aday araştırması, stajyer/proje desteği, Cihan görüşmesi ve değerlendirmesi, sosyal medya içerik yöneticisi rolünün netleştirilmesi. Beş ayrı İK maddesi tek çatı altında birleştirildi ve o birleşik madde BEKLEMEDE olarak açık duruyor.",
      "KAPANAN MADDELER — İŞ MODELİ VE PAZARLAMA (14 madde): B+B Business Set-Up firmaları için ücretlendirme kurgusu, teklif modeli (saatlik/part-time/full-time, gecikmeli vs anlık ödeme), umbrella company araştırması, pilot ülkelerin netleştirilmesi (Almanya + BAE), veri stratejisi, AR-GE klasörü, sosyal medya hesaplarının tamamlanması, gerilla paylaşım planı, Seren Uzluer marketing/lansman paketi, Dubai HR grubu postu, Tahsin grubu lansman postları, 19 Mayıs faaliyet postları, Clemta CEO'su ile affiliate toplantısı, Almanya'daki dernek üyeleriyle yazışma, ambassador bulma süreci, kayıt olanlara e-posta otomasyonu, Drive yapısının yeniden organizasyonu, platform giriş güvenliği/filtreleme kurgusu, yönetim kullanıcı profili.",
      "AÇIK KALAN 11 MADDE — HEPSİ GEREKÇELİ: Sizin kararınızı bekleyenler → Profil paketleme/abonelik sistemi (Default/Talep Edilebilir + checkout), FAQ'nın contributorlara paylaşımı, Google Auth + admin yetkilendirme rehberinin Burak'a iletilmesi. Beklemede olanlar → İnsan Kaynakları operasyonu (birleşik), WhatsApp bot kartları (birleşik), Teklif modeli Circle 1-2-3-4 (birleşik), MVP V2 merge (WhatsApp grup gönderi akışının ürünleştirilmesi). Başlanmamış olanlar → Proje kütüphanesi + NDA erişim yapısı + takım eşleştirme, Referans eşleştirme mantığının platform içinde çalışması, Profil Workshop WS1 açık maddeleri (doğrulama + tek profil + rol etiketleme + tüzel kişilik + Gmail geçişi). Devam eden → Landing page + affiliate genişlemesi (InnoVenture + VIP davet sayfası + Business Set-Up affiliate sistematiği).",
      "GÜVENLİK — HİÇ DUYURULMAMIŞ BİR AÇIK KAPATILDI: Sitenin kullandığı bir alt kütüphanede (postcss-selector-parser) düşük önemli bir servis dışı bırakma açığı vardı (GHSA-w9m9-85wc-3x92). Kapatıldı. Sadece kilit dosyası değişti, paket listesi aynı kaldı; derleme ve tüm testler sonrasında doğrulandı. Kullanıcı tarafında hiçbir etkisi yok, ama bu tür şeyler duyurulmazsa 'kimse bakmıyor' sanılır — o yüzden buraya yazıldı.",
      "VERİ ÇEKME BORCU KAPANDI, SONRA ÖLÇÜMÜN YANLIŞ OLDUĞU ANLAŞILDI: Gün boyunca 19 ekran, veritabanına doğrudan bağlanmak yerine ortak bir ara katmana taşındı (S ve R serileri). Gün sonunda 'artık hiç doğrudan bağlantı kalmadı' diye ölçüldü — ama bu ölçüm YANLIŞTI. Doğrusu 2 tane kaldı, ikisi de giriş/oturum dosyasında. Sebep: arama deseni tek satıra bakıyordu, bu iki bağlantı ise iki satıra yayılmıştı. Düzeltildi ve madde tekrar 'açık' işaretlendi. Yanlış ölçümü düzeltmeden bırakmak, ödenmemiş bir borcu ödenmiş sanmaya yol açardı.",
      "GÜN SONU: KODUN EN ŞİŞMİŞ 11 DOSYASI PARÇALANDI: 16.615 satır tek dosyalık yığınlardan küçük ve odaklı modüllere taşındı; 800 satır sınırını aşan dosya 13'ten 5'e indi. Kullanıcı tarafında hiçbir şey değişmedi. Ayrıntısı bir önceki kayıtta (13 Eylül, 'Kodun en şişmiş 11 dosyası').",
      "YENİ BİR DEVİR NOTU YAZILDI — `docs/handover/2026-09-13-buyuk-dosya-temizligi.md`: Sıfırdan gelen birinin başka hiçbir şey okumadan devam edebilmesi için hazırlandı. İçinde: otuz saniyede durum tablosu, 11 dosyanın önce/sonra dökümü, kopyalanacak teknik desen, ve en önemlisi ÜÇ SESSİZ KIRILMA NOKTASI — bu üçü ne otomatik testlerin ne de kod denetiminin yakalayabildiği türden (site paketleme kuralları, kaynak dosyayı doğrudan okuyan arka plan betikleri, ve yönetici panelindeki araç listesini besleyen katalog). Ayrıca gün içinde yapılan üç ölçüm hatası da dürüstçe yazıldı, 'kaldığımız yer' bölümüyle sıradaki iş sıraya kondu.",
      "DÜRÜST NOT — BU GÜNÜN TAMAMI HENÜZ CANLIDA DEĞİL: 55 commit'in tamamı kod deposunda ama canlıya çıkılmadı. Ayrıca bugün taşınan 16.615 satırın hiçbiri tarayıcıda açılıp gözle görülmedi — otomatik testler kodun mantığını doğrular, ekranın doğru göründüğünü doğrulamaz. Yayından sonra özellikle Profil sayfası, WhatsApp topluluk sayfası, Komuta Merkezi, Katalog yönetimi ve Kaynak/Link yöneticisi gözle kontrol edilmeli. Bu duyurunun kendisi de yayınlanmadan panelde görünmeyecek.",
      "BİLEREK YAPILMAYAN: Cadde'nin iki büyük dosyası (cadde-api ve Cadde sayfası) kasten ellenmedi — bu ikisine 25 ve 19 ayrı yerden bağlanılıyor ve birinin hiç otomatik testi yok. Cadde tarafında geçmişte üç ayrı arıza aylarca fark edilmeden canlıda kaldı. Doğru sıra önce koruyucu test yazmak, sonra bölmek; ayrı bir oturuma bırakıldı.",
      "KONTROLLER: 55 commit main dalında ve gönderildi · tip denetimi 0 hata · kod denetimi 0 hata · 278 dosyada 1.958 testin tamamı yeşil · canlı paket derlemesi başarılı · erişilemez dosya taraması temiz · veritabanı göç kontrolü 393/393 sapmasız · Komuta Merkezi'nde 68 maddeye dokunuldu (57 kapandı, 11 gerekçeli açık).",
    ],
  },
  {
    id: "20260913-buyuk-dosya-temizligi",
    date: "13 Eylül 2026",
    title:
      "Kodun en şişmiş 11 dosyası parçalara ayrıldı — 16.615 satır taşındı, kullanıcı tarafında hiçbir şey değişmedi",
    items: [
      "GÜNÜN ÖZETİ: Bugünkü son parti tamamen 'temiz kod' çalışmasıydı. Projenin kendi kuralı bir dosyanın en fazla 800 satır olmasını söylüyor; 13 dosya bu sınırı aşmıştı, en büyüğü 2.934 satırdı. Bunların 11'i küçük ve odaklı parçalara bölündü. Sınırı aşan dosya sayısı 13'ten 5'e indi — kalan 5'in ikisi test dosyası, biri veri dosyası, ikisi de bilerek sonraya bırakıldı.",
      "KULLANICI TARAFINDA HİÇBİR ŞEY DEĞİŞMEDİ: Bu bir 'düzenleme' işiydi, 'değiştirme' değil. Hiçbir ekran, hiçbir buton, hiçbir metin, hiçbir kural değişmedi. Kod aynı işi yapıyor, sadece tek bir dev dosya yerine anlamlı isimlerle ayrılmış küçük dosyalarda duruyor. Faydası ileriye dönük: bundan sonra bir ekranda değişiklik yapmak hem daha hızlı hem daha az riskli olacak, çünkü değiştirilen yerin çevresinde binlerce ilgisiz satır durmayacak.",
      "BÖLÜNEN DOSYALAR: Profil sayfası (2.782→795), Komuta Merkezi yöneticisi (2.127→25), sosyal paylaşım içerik havuzu (2.934→37), ürün güncellemeleri listesi (2.210→31 — şu an okuduğunuz bu liste), WhatsApp topluluk ekleme sayfası (1.747→493), Burak paylaşım araçları (1.418→49), Komuta Merkezi madde katmanı (1.276→107), Katalog yönetim sayfası (1.249→393), sosyal test araçları (1.189→32), Kaynak/Link yöneticisi (967→131), yönetici menü kayıtları (849→40).",
      "ÜÇ SESSİZ ARIZA ÖNLENDİ — ÜÇÜ DE TESTTEN GEÇERDİ: (1) Site paketleme ayarları dosyaları tam adıyla tanıyordu; bölünen parçalar bu gruplandırmanın dışında kalacak ve sayfa yüklenme davranışı sessizce değişecekti. (2) Bir arka plan betiği Burak paylaşım araçlarının kaynağını doğrudan okuyup 12 eşleşme çıkarıyor, bulamazsa hata veriyordu — bölünmeden sonra çalışmayacaktı. (3) Yönetici panelindeki 'Araç Kaydı' ve 'Ajan Analitiği' ekranlarını besleyen dosya listesi bayat kalmıştı. Üçü de düzeltildi; hiçbirini otomatik testler yakalamıyor, bu yüzden ayrıca kontrol edildi.",
      "İŞİ YAPAN VE İŞİ DENETLEYEN AYRILDI: Her dosyayı bölen ile onu kontrol eden ayrı ayrı çalıştı; denetleyenin görevi 'onaylamak' değil 'kusur bulmaya çalışmak' olarak tanımlandı. Yukarıdaki üç arızadan ikisini ve aşağıdaki ölçüm hatalarını bölme işini yapan taraf değil, denetleyen taraf buldu. Ayrıca kullanılmayan iki parça (bir profil kartı ve bir görünmez karakter hatası) bu sayede yakalanıp temizlendi.",
      "DÜRÜST NOT — KENDİ ÖLÇÜM HATALARIM: Bu partide üç kez yanlış ölçüm yaptım ve üçü de belgelendi. Bir ara 'doğrudan veritabanı çağrısı hiç kalmadı' dedim, doğrusu 2 taneydi (giriş/oturum dosyasında); arama desenim çok satıra yayılan çağrıları görmüyordu. Satır sayarken kullandığım komut boş satırları saymıyormuş, bu yüzden bir ara size olduğundan küçük rakamlar verdim. Bir kontrolü de iş bitmeden çalıştırıp yanlış alarm ürettim. Üçü de düzeltildi ve nasıl tekrarlanmayacağı proje kurallarına yazıldı.",
      "BİLEREK YAPILMAYAN: Cadde'nin iki büyük dosyası (cadde-api ve Cadde sayfası) bu partide KASITEN ellenmedi. Sebebi: bu iki dosyaya 25 ve 19 ayrı yerden bağlanılıyor ve birinin hiç otomatik testi yok. Cadde tarafında geçmişte üç ayrı arıza aylarca fark edilmeden canlıda kaldı; zaman kutulu bir çalışmada bu riski almak doğru olmaz. Doğru sıra önce koruyucu test yazmak, sonra bölmek — ayrı bir oturumda yapılacak.",
      "KONTROLLER: Tip denetimi 0 hata · kod denetimi 0 hata · 278 dosyada 1.958 testin tamamı yeşil (23 yeni test eklendi) · canlı paket derlemesi başarılı · erişilemez dosya taraması temiz · veritabanı göç kontrolü sapma yok. 8 ayrı commit main dalına gönderildi.",
      "HENÜZ YAPILMADI — GÖZLE KONTROL VE YAYIN BEKLİYOR: Bu 16.615 satırlık taşımanın hiçbiri henüz tarayıcıda açılıp görülmedi ve canlıya çıkılmadı. Testler kodun mantığını doğrular, ekranın doğru göründüğünü doğrulamaz. Özellikle Profil sayfası, WhatsApp topluluk sayfası ve Komuta Merkezi'nde yerleşimin bozulmadığı yayından sonra gözle kontrol edilmeli.",
    ],
  },
  {
    id: "20260913-workshop-panolari-tamamen-kapandi",
    date: "13 Eylül 2026",
    title:
      "Cadde ve Profil workshop panolarındaki tüm eski maddeler gözden geçirildi — 56 maddenin 55'i kapandı, 1 tanesi bilerek açık bırakıldı",
    items: [
      "GÜNÜN ÖZETİ: Daha önceki bir turda yarım kalan Cadde WS2 triyajı bitirildi, hiç başlanmamış Cadde WS1 ve WS3 panoları da tamamlandı. Hiç işaretlenmemiş 56 workshop maddesinin (Profil WS1 18/18 zaten bitmişti) tamamı artık gözden geçirilmiş durumda.",
      "CADDE WS2 — KALAN 12 MADDE KAPANDI: Modül geliştirme sırası (Cadde → Profil → Çarşı → Taşınma motoru → WhatsApp botu, 4 madde) onaylanıp işaretlendi. Ertelenmiş ödeme programı (2 madde) ve WordPress taşıma + maliyet optimizasyonu (2 madde) hâlâ geçerli sayılıp açık bırakıldı — ayrı takip ediliyor. Proje kütüphanesi + NDA erişim yapısı + takım eşleştirme sistemi (3 madde) birleştirilip Komuta Merkezi'ne tek yeni todo olarak taşındı. Yorum hatası maddesi (m134) BİLEREK DOKUNULMADI — ayrı araştırılıyor, kullanıcı cevabı bekleniyor.",
      "CADDE WS1 — İKİ MADDE SORU SORULMADAN, KOD KANITIYLA KAPANDI: '+90 numarasıyla kayıtlı kullanıcı yalnız Köprü'ye girebilir' ve '+90 dışı doğrulanmış diaspora üyesi tüm ülke/şehir + Köprü'yü görebilir' kuralları zaten koda geçmiş: is_tr_resident/is_diaspora_resident fonksiyonları ve can_post_kopru truth table'ı bunu TELEFON NUMARASINA GÖRE DEĞİL, profildeki ülke bilgisine göre yapıyor — bilerek öyle tasarlandı, çünkü +90 numaralı bir üye Berlin'de yaşıyor olabilir. Üçüncü madde (viral video/Jukebox fikri) somut bir karar gerektirmediği için açık fikir olarak bırakıldı.",
      "CADDE WS3 — DÖRT MADDE ZATEN BAŞKA YERDE SAHİPLİ ÇIKTI: içerik/soğuk-başlangıç maddelerinin dördü (test içeriği için ayrı görünürlük, dört şehir için gerçek içerik, resmî hesaptan yayın, blog↔Cadde döngüsü) mevcut batch planında zaten UBT/Burak'a atanmış bulundu — yeni bir karar gerekmedi, sadece 'gözden geçirildi' işaretlendi.",
      "DÜRÜST NOT: Bu partide de üretim kodu değişmedi — WS1'deki iki maddenin arkasındaki kural zaten önceden yazılmıştı, bu turda sadece doğrulanıp panoda kapatıldı. Veritabanında sadece workshop_items işaretleri güncellendi ve bir yeni Komuta Merkezi todo'su eklendi. 'Kapandı' denen maddeler kalıcı silinmedi, gerektiğinde yeniden açılabilir.",
      "KONTROLLER: workshop_items artık Cadde WS1 0/54 açık, Cadde WS2 1/82 açık (yalnız m134), Cadde WS3 0/31 açık, Profil WS1 0/26 açık durumunda. Kod/test/deploy değişikliği yok, yalnızca veritabanı kayıtları güncellendi.",
    ],
  },
  {
    id: "20260913-komuta-merkezi-76-madde-triyaji",
    date: "13 Eylül 2026",
    title:
      "Komuta Merkezi'ndeki 76 eski maddenin tamamı tek tek gözden geçirildi — 91 madde artık 'Tamamlandı', 20 madde gerekçesiyle açık kaldı",
    items: [
      "GÜNÜN ÖZETİ: Bugünkü Radar/acil-liste çalışmasının ardından, Komuta Merkezi'ndeki 'yapılacak işler' panosunun kendisi de baştan sona tarandı. Bazıları Nisan 2026'dan (5 aylık), hiçbiri kod tarafından doğrulanıp kapatılmamıştı — pano sürekli kalabalık görünüyordu.",
      "İLK TARAMA — 21 MADDE GERÇEK KANITLA KAPATILDI: Görsel dil kuralları (köşe yuvarlaklığı, buton dili, rozet tipleri, marka rengi, İngilizce kalıntılar — 9-10 Eylül çalışmasından), Cafe oda arayüzü, Contributor kaynak/FAQ paketinin dört alt maddesi, WhatsApp bot altyapısı, Müşteri Talepleri paneli, Burak'ın yönetici hesabı ataması — hepsi koda/dokümana/veritabanına bakılarak doğrulandı, tahmin edilmedi.",
      "İKİNCİ TARAMA — KALAN 55 MADDE TEK TEK SORULDU, EN ESKİDEN BAŞLANARAK: 76 maddenin geri kalanı kategori kategori değil, en eskiden (17 Nisan 2026) en yeniye doğru soruldu. Sonuç: 35 madde 'artık geçerli değil' denip kapatıldı, birkaçı birbirine benzeyen konularda tek maddede birleştirildi (üç ayrı teklif modeli maddesi, dört ayrı WhatsApp bot kartı, beş ayrı İnsan Kaynakları maddesi, üç ayrı büyüme/affiliate maddesi tek çatı altında toplandı).",
      "12 MADDE 'HÂLÂ GEÇERLİ' ONAYI ALDI, DOKUNULMADI: RASCI modeli, tech cost matrisi, işe alım metodolojisi, marketing içerik planı, LinkedIn takipçi artırma, Aramıza Katılanlar şablonu, chat grupları post planı gibi maddeler hâlâ öncelikli sayıldı — bunlar açık kalmaya devam ediyor, iptal edilmedi.",
      "20 MADDE GEREKÇELİ OLARAK AÇIK KALDI: Beşi zaten bugünkü acil listedeki WhatsApp grup maddeleriyle aynı (Burak'ın cevabı bekleniyor), biri ürün sahibinin (kendi) gelir modeli/şehir sahipliği kararını bekliyor (Contributor FAQ'sının paylaşımı), biri kapsamı zaten başka bir maddeye taşınmış durumda (MVP V2 merge), biri de kanıt belirsiz olduğu için dokunulmadı (Cadde'de dört şehrin gerçekten 'tohumlanıp' tohumlanmadığı netleşmedi) — geri kalan 12'si yukarıdaki 'hâlâ geçerli' maddeleri.",
      "İPTAL/BİRLEŞTİRME KARARLARI AYRI BİR DOSYADA TUTULUYOR: `docs/notes/2026-09-13-komuta-merkezi-iptal-edilenler.md` — hangi maddenin neden kapatıldığı, hangisinin hangi maddeyle birleştiği tek tek yazılı. Bu liste, panonun neden yenilenmesi/temizlenmesi gerektiğini anlatan bir sonuç dokümanı hazırlamak için kullanılacak.",
      "DÜRÜST NOT: Bu partide hiçbir kod yazılmadı, hiçbir özellik değişmedi — yalnızca veritabanındaki kayıtların durumu güncellendi ve kararlar not edildi. 'İptal edildi' denen maddeler kalıcı olarak reddedilmiş değil; ileride yeniden gündeme gelebilir, o yüzden silinmedi, yalnızca 'Tamamlandı' işaretiyle kapatılıp gerekçe notu eklendi.",
      "KONTROLLER: Kod/test/deploy değişikliği yok, yalnızca veritabanı kayıtları güncellendi. Karar geçmişi her maddenin kendi kaydında ve ayrı dosyada korunuyor.",
    ],
  },
  {
    id: "20260913-acil-liste-radar-tamiri-ve-komuta-merkezi-temizligi",
    date: "13 Eylül 2026",
    title:
      "Acil listedeki 3 madde ele alındı, 2 aydır sessizce bozuk olan günlük haber taraması onarıldı, Komuta Merkezi'nde 21 madde kapatıldı",
    items: [
      "GÜNÜN ÖZETİ: Komuta Merkezi'ndeki 'acil' listeye (Top 10 Hot Fix) günlerdir cevap gelmiyordu. Üç maddesi bugün ele alındı, ayrıca listenin GERİSİNDEKİ 'yapılacaklar' tablosu da (76 madde) tek tek gözden geçirilip gerçekten bitmiş olanlar işaretlendi.",
      "PROFİL MENÜSÜ VE GOOGLE GİRİŞ MALİYETİ — BURAK'A SORULDU: İki maddenin kararı tasarım/maliyet onayı gerektirdiği için Burak'a hazır sorularla iletildi (Perşembe toplantısı notu olarak kaydedildi): profil sayfasındaki sabit menünün sola alınıp alınmayacağı, ve Google girişindeki çirkin adresi düzeltmek için aylık ek ücretli bir Supabase özelliğinin (Custom Domain) onaylanıp onaylanmayacağı.",
      "ETKİNLİK ÖZELLİĞİ İÇİN DE BURAK'IN AÇIKLAMASI İSTENDİ: 'Etkinlikler' fikrinin tam olarak ne tür bir özellik olduğu netleşmemişti — bunun dışındaki üç karar (kimler oluşturabilir, kullanıcı ne yapabilir, Cadde'deki süzgeç geri gelsin mi) verildi, yalnız 'ne tür bir özellik' sorusu Burak'a yöneltildi.",
      "⚠️ EN ÖNEMLİ BULGU — RADAR 2 AYDIR SESSİZCE BOZUKMUŞ, KÖK NEDEN BULUNUP DÜZELTİLDİ: Günlük haber taraması her sabah 05:00'te çalışıp 'başarılı' diyordu ama 20 Temmuz'dan beri tek bir haber taramamıştı. Kök neden: fonksiyonun kullandığı gizli anahtar ile veritabanındaki anahtar birbirinden FARKLIYMIŞ — muhtemelen bir güncelleme sırasında biri değişmiş diğeri değişmemiş. Sonuç: cron her sabah çağırıyor, fonksiyon 'yetkisiz erişim' deyip anında duruyordu, ama cron'un kendi kaydı bunu görmüyordu (sadece isteği gönderme adımını izliyor, cevabı değil) — bu yüzden 2 ay boyunca kimse fark etmedi. Anahtar senkronize edildi; yarın sabahki (05:00) gerçek çalışmayla doğrulanacak.",
      "KOMUTA MERKEZİ'NDE 21 MADDE 'TAMAMLANDI'YA ÇEVRİLDİ: Panodaki 76 gerçek 'yapılacak iş' maddesinin çoğu aslında bitmiş ama hiç işaretlenmemişti — pano sürekli kalabalık görünüyordu. Her biri gerçek kanıtla (kod, dokuman veya veritabanı kaydı) doğrulanıp işaretlendi: görsel dil kuralları (köşe yuvarlaklığı, buton dili, rozet tipleri, marka rengi, İngilizce kalıntılar — 9-10 Eylül'deki çalışmadan), Cafe oda arayüzü düzeltmeleri, Contributor kaynak/FAQ paketinin dört alt maddesi, WhatsApp bot altyapısı ve Müşteri Talepleri paneli, Burak'ın yönetici hesabı ataması.",
      "GERİYE KALAN 55 MADDE BİLEREK DOKUNULMADI: Beşi zaten acil listedeki WhatsApp grup maddeleriyle aynı (Burak'ın cevabı bekleniyor). Kalan 50'si tamamen iş/insan kararı — RASCI modeli, teklif modelleri, HR klasörleri, pilot ülke seçimi, sosyal medya planları gibi kodda hiçbir izi olmayan, gerçek dünyada yapılması/karar verilmesi gereken işler. Hoş geldin maili otomasyonu da ayrıca kontrol edildi — hâlâ canlıda kapalı, yanlışlıkla açık sanılmadı.",
      "KONTROLLER: Radar düzeltmesi ve Komuta Merkezi güncellemeleri veritabanı kayıtları üzerinde yapıldı, kod/deploy gerekmedi. Herhangi bir kullanıcı deneyimi değişmedi.",
    ],
  },
  {
    id: "20260913-on-madde-daha-ve-komuta-merkezi-senkronu",
    date: "13 Eylül 2026",
    title:
      "Bugünün dördüncü partisi: on ekran/dosya daha güvenli koda taşındı, Komuta Merkezi'ndeki bir karar maddesi kapatıldı",
    items: [
      "GÜNÜN ÖZETİ: Bugünün dördüncü ve son partisinde on küçük iş daha yapıldı — sekizi doğrudan veritabanına yazan ekranları güvenli koda taşımak, ikisi iç teknik belgelerdeki bayat bilgileri düzeltmekti. Ayrıca Komuta Merkezi ve Workshop panolarındaki maddeler bugünkü işle karşılaştırıldı.",
      "TAŞINAN SEKİZ EKRAN: MVP Yapısal Liste, WhatsApp topluluk editör atama ekranı, Roller ve Özellikler ekranı, Referral (davet kodu) yönetimi, Anket oluşturma ekranı, yeni üye rehberi, durum raporu ekranı ve — iki ayrı yerde birebir tekrarlanan bir rol listesi sorgusu (tek yerde birleştirildi, kod tekrarı da gitti).",
      "GÖZLE GÖRÜNÜR HİÇBİR DEĞİŞİKLİK YOK: Bu on maddenin hiçbiri ekranda görüneni değiştirmedi — amaç kodun veritabanına NASIL ulaştığını düzenlemekti, NE gösterdiğini değil.",
      "İKİ İÇ BELGE DÜZELTİLDİ: Geliştirici belgeleri hâlâ Eylül başında kaldırılan eski bir oturum-açma yöntemini (AuthContext) 'yakında kaldırılacak' diye anlatıyordu — oysa aylar önce kaldırılmıştı. Aynı belgelerde 'tip denetiminde 98 hata var' yazıyordu, gerçek sayı sıfırdı. İkisi de düzeltildi.",
      "BİR GÖRSEL DENETİM BULGUSU DÜZELTİLDİ: Geçen ayki bir denetim üç görsel çiftini 'muhtemelen gereksiz kopya' diye işaretlemişti. Tek tek kontrol edildi: üçü de gerçekten farklı iki yerde kullanılıyor (aynı görsel iki farklı sayfa katmanında görev yapıyor) — hiçbiri silinmedi, yanlış işaretli not düzeltildi.",
      "KOMUTA MERKEZİ'NDE BİR KARAR MADDESİ KAPATILDI: 'Cafe formatı async-first mi, programlı canlı slotlar mı' karar maddesi (B+B, yani ikinizin birlikte karar vermesi gereken bir madde) 'Tamamlandı'ya çevrildi — çünkü async-first seçeneği bugünün ilk partisinde zaten uygulanmıştı (Cafe odaları artık 1-7 gün açık kalıyor, eskiden 2 saatti). Karara ekli notta uygulamanın ne yaptığı yazıyor.",
      "WORKSHOP PANOSU KONTROL EDİLDİ, EK İŞLEM GEREKMEDİ: Cafe format kararı ve tepki seti sadeleştirmesiyle ilgili altı workshop maddesi zaten önceki bir partide UBT tarafında işaretliydi — yalnız Burak'ın kendi onay kutusu bekliyor, bu ikinizin panelden yapması gereken bir şey. Yorum hatası şikayeti (madde 134) hâlâ açık — kod tarafında bir sorun bulunamadı, cevap bekleniyor.",
      "KONTROLLER: Otomatik testlerin tamamı yeşil (276 dosya / 1.927 test), kod ve tip denetimi temiz, veritabanı sapması yok — bu partinin hiçbiri şema değiştirmedi (tek DB yazısı yukarıdaki karar maddesinin durumuydu).",
    ],
  },
  {
    id: "20260913-dort-domain-daha-api-katmanina-tasindi",
    date: "13 Eylül 2026",
    title:
      "Dört form/ekran daha güvenli koda taşındı, geliştirici belgesindeki bayat rakamlar düzeltildi, iki eski yedek klasörü rapor edildi (silinmedi)",
    items: [
      "GÜNÜN ÖZETİ: Bugünün üçüncü ve son partisinde, doğrudan veritabanına yazan dört ayrı ekran/form projenin standart güvenli-katman kalıbına taşındı. Hiçbirinde kullanıcı tarafında görünür bir değişiklik yok — davranış birebir korundu, yalnızca kodun veritabanına NASIL ulaştığı değişti (dolaylı yoldan, tek bir kontrol noktasından geçerek).",
      "TAŞINANLAR: 'Hoş Geldin Paketi' sipariş formu, Hizmet Talebi formu ve listesi, Kaynak/Link yöneticisi ekranı (5 ayrı yazma noktası), Mesaj Kutusu ekranı (4 ayrı okuma/yazma noktası).",
      "BİLEREK DOKUNULMAYAN BİR KUSUR: Hizmet Talebi listesi taşınırken içinde küçük ama kırılgan bir eşleştirme mantığı fark edildi. Bu partinin amacı SADECE taşımaktı, davranış değiştirmek değil — kusur düzeltilmeden, olduğu gibi, yazılı notla birlikte taşındı. İleride ayrı bir düzeltme maddesi olabilir.",
      "DÖRT KULLANILMAYAN GÖRSEL SİLİNDİ, BİR TANESİNDE DENETİM HATASI BULUNDU: Geçen ayki bir görsel denetiminde 'belki kullanılıyordur' diye elle kontrole bırakılmış 4 dosya tek tek yeniden doğrulanıp silindi. Bu sırada denetimin kendisinde bir hata yakalandı: 'kullanılmıyor' diye işaretlenmiş bir dosya (mail şablonu logosu) aslında hoş geldin mailinde kullanılıyormuş — o dosyaya dokunulmadı.",
      "GELİŞTİRİCİ BELGESİNDEKİ BAYAT RAKAMLAR DÜZELTİLDİ: İç teknik belge hâlâ 'tip denetiminde 9 uyarı kaldı' diyordu; gerçek sayı SIFIRDI (bir önceki partide kapanmış ama belge güncellenmemişti). 'Doğrudan veritabanına yazan ekran sayısı' da yeniden ölçüldü: bugünün başında 32+4 iken 8+3'e indi.",
      "İKİ ESKİ YEDEK KLASÖRÜ BULUNDU, RAPOR EDİLDİ — DOKUNULMADI: Depoda iki eski prototip kopyası duruyor (biri ~19 MB, biri ~152 MB), ikisi de günlük kullanımda hiç açılmıyor. Karar için soruldu, cevap: 'şimdilik dokunma, sadece rapor et'. Bu karar kayda geçti; ikisine de dokunulmadı.",
      "KONTROLLER: Otomatik testlerin tamamı yeşil (271 dosya / 1.897 test), kod denetimi temiz, tip denetimi SIFIR hata, veritabanı şeması hiç değişmedi — bugünün üç partisinden hiçbiri veritabanına dokunmadı.",
    ],
  },
  {
    id: "20260913-tip-denetimi-borcu-sifira-indi",
    date: "13 Eylül 2026",
    title:
      "Aylardır biriken tip-denetimi uyarılarının sonuncusu da kapandı, bir form daha güvenli koda taşındı",
    items: [
      "GÜNÜN ÖZETİ: Bir süre önce 109 olarak ölçülen 'tip denetimi uyarısı' sayısı, art arda yapılan küçük düzeltmelerle bugün SIFIRA indi (109 → 22 → 16 → 12 → 9 → 0). Bu sayı kodun çalışırken hata vermeden ama arka planda 'yanlış yazılmış' sayılan yerlerini gösteriyordu; kullanıcı hiçbir zaman doğrudan görmedi ama biriken her satır ileride gerçek bir hataya dönüşme riski taşıyordu.",
      "KULLANILMAYAN BİR GÖRSEL SİLİNDİ: 600 KB'lık kullanılmayan bir görsel kaldırıldı; ekranda hâlâ kullanılan benzer isimli başka bir dosyayla karıştırılmasın diye önce tek tek doğrulandı.",
      "MOBİLDE ÜST MENÜ DÜZELTİLDİ: Telefon genişliğinde üst menüdeki 'Geri Bildirim' yazısı kelimenin ortasından ikiye bölünüp yanındaki linklerle çakışıyordu. Düzeltildi ve ekran görüntüsüyle doğrulandı.",
      "EN ZOR TİP HATASI SINIFI KAPATILDI: Komuta Merkezi'nin arka planında bir sorgu kodu kendi kendini tekrar tekrar sarmalıyor, derleyici de bu yüzden 'çok derin, pes ediyorum' diyordu. Projede zaten kullanılan güvenli ve dar bir gevşetme kalıbıyla çözüldü.",
      "ROZET GÖRSELİ DOĞRULANDI, YENİ BİR BULGU ÇIKTI: 'Sabit' rozeti doğru renkte çiziliyor. Ama 'Sponsorlu' kartın kendisi hâlâ eski turuncu çerçeveyle çiziliyor — yalnız üstündeki rozet düzeldi, kartın arka planı düzelmedi. Bu bir ürün kararı gerektiriyor; onay alınana kadar ŞİMDİLİK dokunulmadı.",
      "İLGİ ALANI FORMU GÜVENLİ KATMANA TAŞINDI: Doğrudan veritabanına yazan bir form, projenin standart güvenli-katman kalıbına taşındı — kullanıcı için görünür bir değişiklik yok, davranış birebir aynı.",
      "ARAŞTIRILDI AMA KAPATILAMADI — 'YORUM YAZINCA HATA VERİYOR' ŞİKAYETİ: Workshop panosundaki bir şikayet ('yorum yazmaya çalışınca sayfa hataya geçiyor, eklenen görsel netliğini kaybediyor') araştırıldı. Kod tarafında bunu açıklayacak bir sorun BULUNAMADI — hata kayıtları tablosu bu konuda sıfır satır, yani hiç yakalanmamış. Kesin teşhis için 5 somut soru hazırlandı (hangi tarayıcı, ne zaman, hangi dosya formatı); madde şu an kod tarafında değil, cevap tarafında bekliyor.",
      "KONTROLLER: Otomatik testlerin tamamı yeşil, kod denetimi temiz, tip denetimi SIFIR hata (bu depoda ilk kez).",
    ],
  },
  {
    id: "20260913-worktree-kurtarma-async-cafe-ve-gozle-denetim",
    date: "13 Eylül 2026",
    title:
      "Bir bilgisayarda unutulmuş yarım kalmış Cafe kararı bitirilip yayına alındı, tepki seçenekleri sadeleşti, gözle denetimde gerçek bir çelişki yakalandı",
    items: [
      "GÜNÜN ÖZETİ: 3 gündür yeni bir işlem yapılmamıştı ve acil sorulara cevap gelmemişti. Tarama sırasında bir geliştiricinin bilgisayarında unutulmuş, hiçbir zaman ana koda birleştirilmemiş bir çalışma kopyası bulundu — içinde bitmemiş ama neredeyse tamamlanmış bir karar duruyordu.",
      "CAFE ODALARI ARTIK GÜNLERCE AÇIK KALIYOR: Cafe odaları eskiden 2 saat sonra kendiliğinden kapanıyordu. Bu, unutulmuş çalışma kopyasında zaten '1-7 gün açık kalsın' diye değiştirilip test edilmiş ama hiç yayına alınmamıştı. Bugün bitirilip yayına alındı; oda süresi dolduğunda kullanıcıya bunu söyleyen metin de aynı pakette geldi.",
      "TEPKİ SEÇENEKLERİ 5'TEN 3'E İNDİ: Beğendim / Destek / Soru dışında Kalp ve Gülme seçenekleri de vardı. Ölçtük: ikisi de canlıda BİR KEZ BİLE kullanılmamış — sıfır satır. Kaldırıldılar, ekran sadeleşti.",
      "YANLIŞLIKLA SİLİNMİŞ BİR SORU GRUBU GERİ GETİRİLDİ: Komuta Merkezi'ndeki 'GOOGLE AUTH ID' maddesinin altındaki 6 soruluk açıklama 10 Eylül sabahı yanlışlıkla silinmiş bulundu. Aynen geri eklendi.",
      "GÖZLE DENETİMDE GERÇEK BİR ÇELİŞKİ BULUNDU: Cafe kartındaki rozet 'Canlı' diyordu ama hemen altındaki açıklama metni 'asenkron çalışır, hemen yanıt beklemeyin' diyordu — aynı kartta birbirini yalanlayan iki mesaj. 'Canlı' yazısı 'Açık' olarak düzeltildi. Bu bulgu, 5 ekranlık bir gözle-denetim altyapısının ilk kez gerçekten çalıştırılıp sonuçlarının tek tek incelenmesiyle ortaya çıktı.",
      "TEK BİR TEST ODASI TEMİZLENDİ: Başlığı 'Test' olan, gerçek kullanıcı verisi taşımayan bir Cafe odası arşivlendi (silinmedi, istenirse geri açılabilir).",
      "KAPSAM DIŞI BIRAKILAN BİR BULGU — SADECE KAYDA GEÇTİ: Telefon ekranında üst menüde 'Geri Bildirim' yazısının ortadan bölünüp diğer linklerle çakıştığı görüldü. Bugünün konusu değildi; kayda geçti, ayrı bir güne bırakıldı.",
      "KONTROLLER: Otomatik testlerin tamamı yeşil, kod ve yazı denetimi temiz, veritabanı sapması yok.",
    ],
  },
  {
    id: "20260910-whatsapp-grup-maddeleri",
    date: "10 Eylül 2026",
    title: "13 Mayıs'tan kalan beş WhatsApp grup maddesi acil listesine taşındı — ve ölçüm hepsini değiştirdi",
    items: [
      "NE YAPILDI: Komuta Merkezi'ndeki todo listesinde bekleyen beş madde (WhatsApp grubu ekleme politikası, onay akışı, form alanları, şehir gruplarını toplama, sosyal medya çağrısı) acil işler listesine taşındı. Liste artık 4 yerine 9 madde; tavan 10, yani bir slot boş duruyor.",
      "HER MADDEYE 6 SORU YAZILDI: Dokuz maddenin her birinin altında artık 6 soru var — toplam 54 soru. Hepsi günlük dille, teknik terim yok. Cevaplar aynı yere yazılıyor.",
      "⚠️ EN ÖNEMLİ BULGU — BU BEŞ MADDE ZATEN YAPILMIŞ: Maddeler 'şunu belirle, şunu yaz, şunu netleştir' diye yazılmış ama 13 Mayıs'tan bu yana kod onları geçmiş. Grup ekleme özelliği CANLIDA ÇALIŞIYOR: adresi açık, ana sayfadan link veriliyor, üye giriş yapıp grup gönderebiliyor, gönderi admin onayına düşüyor, onaylanmadan görünmüyor, reddedilirse gerekçe yazılabiliyor, moderasyon ekranı da yönetici menüsünde duruyor. 'Grup yöneticisi miyim / sadece üyeyim' ayrımı bile formda var. Yani sorulan kararların çoğu koda çoktan girmiş.",
      "O YÜZDEN SORULAR DEĞİŞTİ: 'Yapalım mı?' diye sormak anlamsız olurdu. Sorular 'hazır olanı nasıl kullanacağız, hangi kararı veriyorsun' biçiminde yazıldı. Yanlış soru sorsaydık, yapılmış işi yeniden yaptırıyor olacaktık.",
      "GERÇEK KUSUR 1 — ŞEHİR BİLGİSİ YOK: Listedeki 10 grubun 10'unda şehir alanı 'Genel' yazıyor. Yani 'şehrindeki grubu ekle' çağrısı yapılsa bilgi hiçbir yere düzgün yazılmıyor. 'Berlin'deki gruplar' gibi bir filtre bugün kurulamaz.",
      "GERÇEK KUSUR 2 — ÜLKE ALANI KONTROLSÜZ: Serbest metin olduğu için içine ne isterse yazılmış: 'GCC', 'Global', 'GCC-Global', 'EU+MENA', 'KATAR' ve bir kayıtta ülke alanına şehir yazılmış ('İstanbul'). Bu, Cadde tarafında da yaşadığımız aynı sorunun ikinci kopyası.",
      "GERÇEK KUSUR 3 — HİÇ KULLANILMAYAN ONAY: Grup sayfasında 'Üye onaylı!' diye bir rozet çizilebiliyor ama 10 grubun 10'unda o alan boş — rozet canlıda bugüne kadar HİÇ görünmemiş. Alan var, hiç kullanılmamış.",
      "GERÇEK KUSUR 4 — SIFIR TALEP: 'Gruba katılma talebi' kaydı bugüne kadar tek bir tane bile yok. Ayrıca 10 gruptan birinin WhatsApp linki hiç yok — sayfası açılıyor ama kullanıcı gruba katılamıyor. Üye sayısı da 10 grubun sadece 1'inde dolu.",
      "GERÇEK KUSUR 5 — YAZILI KURAL YOK: Hangi grubun kabul, hangisinin ret edileceği hiçbir yerde yazılı değil. Çağrı yapılıp başvurular gelmeye başlarsa 'neden reddettiniz' sorusuna yazılı cevabımız olmayacak. Bir de: bu sayfa arama motorlarına bildirilmiyor, yani çağrı sadece bizim paylaşımımız kadar duyulur.",
      "MEVCUT 10 GRUBUN TAMAMI BİZDEN: Dışarıdan gelen tek bir grup başvurusu yok; 10 grubun hepsi bizim iki hesabımızdan eklenmiş. Yani planlanan çağrı, sistemin ilk gerçek sınavı olacak.",
      "TODO'LAR SİLİNMEDİ: Beş madde artık acil listesinde ama todo listesinden kaldırılmadı — bu depoda bir işin iki yerde birlikte durması yerleşik düzen. Silmek geri alınması zor bir karar, istenmeden yapılmaz.",
      "KORUMA: Bu düzeni koruyan 8 maddelik bir sözleşme testi eklendi. En çok işe yarayan ikisi: liste tavanının (10) aşılmasını ve bir maddenin sorularının sessizce eksilmesini engelliyor — ikisi de bozulsa hiçbir şey patlamaz, kimse fark etmezdi.",
      "KONTROLLER: Otomatik testlerin tamamı yeşil, kod ve yazı denetimi temiz, veritabanı sapması yok. Türkçe karakterler kayıt sonrası tek tek kontrol edildi.",
    ],
  },
  {
    id: "20260910-gorsel-dil-ve-acil-liste",
    date: "10 Eylül 2026",
    title:
      "Cadde'nin görsel dili tek kurala bağlandı, acil işler listesine soru-cevap bölümü eklendi",
    items: [
      "GÜNÜN ÖZETİ: 27 Ağustos denetiminin 31 maddesinden 23'ü artık kapandı (dün 14'tü). Bugün kapatılanların tamamı görsel dille ilgili — yani sitenin dağınık görünmesinin asıl sebebiyle.",
      "SORUNUN KÖKÜ NEYDİ: Denetim, tek tek kusurlardan çok 'tanımlı bir tasarım kuralının olmaması'nı işaret ediyordu. Ölçtük, haklıydı: Cadde sayfalarında DOKUZ farklı köşe yuvarlaklığı ve ONÜÇ farklı rozet stili aynı anda dolaşıyordu. Her sayfa kendi kuralını uydurmuştu.",
      "KÖŞE YUVARLAKLIĞI TEKE İNDİ: Dokuz farklı değer vardı (kimi kart çok yuvarlak, kimi köşeli). Artık tek bir değer var; istisna yalnız yuvarlak düğmeler ve profil fotoğrafları. Ayrıca bu değer artık tek bir yerden geliyor, ileride değiştirmek istersek tüm site birlikte değişecek.",
      "OKUNMAYAN GRİ YAZILAR DÜZELTİLDİ: Bazı açıklama metinleri o kadar açık griydi ki erişilebilirlik ölçütünü karşılamıyordu — hesapladık, beyaz zeminde 2.56 kontrast veriyordu (geçer not 4.5). Bu metinler koyulaştırıldı; artık 4.76. Görme zorluğu olan ya da güneş altında telefona bakan kullanıcı için gerçek bir fark.",
      "ROZETLER ÜÇ TİPE İNDİ: Onüç ayrı rozet stili vardı ve hiçbirinin görsel ağırlığı önemiyle örtüşmüyordu. En çarpıcı iki örnek: 'Sabit' rozeti siyah dolguyla sayfadaki EN dikkat çekici rozetti ama en az bilgi taşıyordu; 'Sponsorlu' turuncu dolguyla akıştaki en göze batan şeydi — yani reklam içeriği en yüksek görsel önceliğe sahipti, ki bu yanlış bir sinyal. Artık üç tip var: durum (Canlı, Arşiv, Sabit), kimlik (rol, Sponsorlu), kategori (ilgi alanı, tür).",
      "KARTLARDAKİ GÖKKUŞAĞI ŞERİT ANLAM KAZANDI: Her kartın üstünde beş renkli bir şerit vardı; güzel duruyordu ama hiçbir bilgi taşımıyor, her kartta tekrarlandığı için de kartlar arası farkı siliyordu. Artık şerit kartın hangi bölüme ait olduğunu söylüyor (Cadde / Cafe / Çarşı). Gökkuşağı logoda duruyor.",
      "CAFE KARTINDAKİ ÇELİŞKİ GİDERİLDİ: Kart turuncu çerçeveliyken içindeki 'Canlı' rozeti ve üstündeki şerit yeşildi — aynı kartta iki farklı renk, üç ayrı sinyal. Artık kimliği yalnız şerit taşıyor.",
      "MARKA RENGİ ARAYÜZE GİRDİ: Markanın imza rengi (bronz) sitenin hiçbir yerinde kullanılmıyordu; ölçtük, kod tabanında tek bir yerde bile geçmiyordu. Artık birincil düğmelerde. Bir de kontrast hesabı yaptık: bu rengin açık tonu beyaz yazıyla okunaklı değil, o yüzden düğme zemininde daha koyu tonu kullanılıyor.",
      "ACİL İŞLER LİSTESİNE SORU-CEVAP BÖLÜMÜ: Komuta Merkezi'ndeki her acil maddenin altında artık bir 'Soru / cevap' bölümü var. Bugüne kadar bir maddenin ne demek istediği sohbette ya da mailde konuşuluyor, sonra madde ile cevabı birbirinden kopuyordu. Artık ikisi aynı yerde duruyor.",
      "DÖRT ACİL MADDE İNCELENDİ VE DÖRDÜ DE YAZILANDAN FARKLI ÇIKTI: Her maddenin gerçek durumu tek tek ölçüldü ve altına 6'şar soru yazıldı. En çarpıcısı Radar: 'kapattığımızı açalım' diye yazılmıştı ama Radar kapalı değil — günlük görevi her sabah çalışıyor ve 'başarılı' diyor, buna rağmen 20 Temmuz'dan beri tek bir haber taraması yapmamış. Yaklaşık yedi haftadır sessizce bozuk ve hata vermediği için kimse fark etmemiş. Bu bir 'aç' işi değil, tamir işi.",
      "DİĞER ÜÇ MADDE: WhatsApp grup sayfaları 4 Ağustos'ta silinmiş (kimse ulaşamadığı için), verisi duruyor. Etkinlik altyapısı yarım ve içi tamamen boş; üstelik Cadde'deki süzgeci yine 4 Ağustos'ta kaldırılmış. Google giriş ekranı için hazırlanmış bir plan zaten var (2 Ağustos'ta yazılmış) ama hiçbir adımı başlamamış.",
      "BİR KUSURU KENDİM YAPIP KENDİM BULDUM: Soru-cevap bölümünü ilk kurduğumda, yorumları yalnız bölüm açıldığında yüklenecek şekilde ayarlamıştım (gereksiz yük olmasın diye). Sonuç: dört maddeye 6'şar soru yazılmasına rağmen panoda hiçbiri belli olmuyordu, çünkü kapalıyken sayı bilinmiyordu. Endişem yersizdi — liste en fazla 10 satır. Düzeltildi; düğme artık 'Soru / cevap (6)' diyor.",
      "DÜRÜST NOT — HÂLÂ GÖZLE KONTROL BEKLİYOR: Bugünün işlerinin tamamı görsel ve otomatik testler görsel yerleşimi ölçemiyor. Özellikle köşelerin daha az yuvarlak olması 48 kartı birden etkiledi, rozetlerin sadeleşmesi de akışın görünümünü değiştirdi. Ayrıca 'Sponsorlu' rozetinin nötr tona inmesi reklam görünürlüğünü düşürür — bu bir ürün kararı olarak gözden geçirilmeli.",
      "KONTROLLER: 264 dosyadaki 1.862 otomatik testin tamamı geçti (dün 262/1.851), kod denetimi temiz, yazı denetimi temiz, üretim derlemesi başarılı. Bugünkü kuralları koruyan üç yeni sözleşme testi de eklendi — biri kasten bozularak gerçekten koruduğu doğrulandı.",
    ],
  },
  {
    id: "20260909-cadde-sadelestirme",
    date: "9 Eylül 2026",
    title:
      "Cadde sadeleştirme günü: boş sayfada artık dolu bir yol gösteriliyor, üstteki gereksiz katmanlar kalktı, her kartta yazan sıfırlar gizlendi",
    items: [
      "GÜNÜN ÖZETİ: 27 Ağustos'ta dışarıdan yapılan iki değerlendirme (biri kullanım kolaylığı, biri görsel dil) 31 açık madde çıkarmıştı. Bugün bunların 14'ü kapatıldı. Hepsi Cadde'nin üst yarısıyla ve boş sayfa deneyimiyle ilgili — yani üyenin siteye girdiğinde ilk gördüğü yer.",
      "EN ÖNEMLİSİ — BOŞ ŞEHİRDE ARTIK ÇIKMAZ YOK: Üye filtreden bir şehir seçtiğinde, o şehirde paylaşım yoksa ekranda tek yazan şey 'ilk paylaşımı sen yapabilirsin' idi. Ölçtük: 58 şehrimizin yalnız 10'unda paylaşım var, yani şehir seçen üyenin yaklaşık %83'ü boş ekranla karşılaşıyordu. Ve kullanıcı ilk paylaşımı yapmıyor. Artık sistem bir üst kapsama bakıyor ve doluysa gerçek sayısıyla öneriyor: 'Almanya akışındaki 3 paylaşım → gör'. Üst kapsam da boşsa düğme hiç çıkmıyor — boş bir yerden boş bir yere yollamanın anlamı yok.",
      "BU ÖNERİ SİTEYE EK YÜK BİNDİRMİYOR: Sayı, zaten yapılan tek bir sorgudan geliyor; tıklandığında da yeni bir sorgu gitmiyor, hazır veri gösteriliyor. Filtre kullanmayan üyelerde ise bu kontrol hiç çalışmıyor. Sunucumuz küçük olduğu için buna özellikle dikkat edildi ve otomatik testlerle kilitlendi.",
      "EKRANDA DURAN BİR YANLIŞ CÜMLE KALDIRILDI: Boş akışta 'Bu bölgede içerik azsa ülke geneli ve global akış da devreye girer' yazıyordu. Böyle bir şey olmuyordu — akış daraltılınca daralıyor, kendiliğinden genişlemiyordu. Yani sisteme güvenip bekleyen üyeye yanlış bilgi veriliyordu. Metin artık duruma göre doğru olanı söylüyor.",
      "HER KARTTA YAZAN SIFIRLAR GİZLENDİ: Beğeni, yorum ve paylaşım sayaçları henüz kimse etkileşmemişken bile '0' yazıyordu. Boş bir platformda bu, boşluğu bağıran bir ayrıntı. Artık sayı ancak 1'e ulaşınca görünüyor. Ekran okuyucu kullananlar için sayı yine okunuyor — yalnız görsel rakam gizlendi, bilgi kaybı yok.",
      "'CADDEYE ÇIK' DÜĞMESİ KALDIRILDI: Sağ kolonda siyah, dikkat çeken bir düğme vardı ama kullanıcı zaten Cadde'deydi ve düğme sadece sayfayı biraz aşağı kaydırıyordu — yani hiçbir yere götürmüyordu. Kaldırıldı.",
      "ÜSTTEKİ KALABALIK AZALDI: İçerik başlamadan önce dört ayrı katman vardı ve ilk paylaşım ekranın altında kalıyordu. Üçü ele alındı: (1) 'CorteQS açık beta yayında' bandı artık kapatılabiliyor ve kapattığınızda bir daha gelmiyor, (2) giriş yapmış üyeye artık pazarlama sloganı gösterilmiyor — o slogan siteye ilk gelen ziyaretçi için anlamlı, (3) Cadde'nin kendi kimlik şeridi (ikinci bir logo, 'Diaspora Cadde' başlığı, rozet ve tanıtım cümlesi) tamamen kaldırıldı.",
      "O ŞERİTTEKİ TEK İŞE YARAR ŞEY KORUNDU: Bildirim zili siliniyor değil, hemen altındaki filtre satırına taşındı. Sayfanın kimliği ise ekran okuyuculara görünmeye devam ediyor; hatta Cadde sayfasının daha önce hiç olmayan ana başlığı bu vesileyle eklendi, arama motorları açısından da doğrusu bu.",
      "SAYFAYI AŞAĞI KAYDIRINCA ÜST BAR İNCELİYOR: Kaydırdıkça logo ve menü küçülüyor, yukarı dönünce eski haline geliyor. Titreme olmaması için iki ayrı eşik kullanıldı. Bu davranış şimdilik yalnız Cadde sayfasında; sitenin diğer 60 sayfası hiç etkilenmedi.",
      "ARAYÜZDEKİ İNGİLİZCE KALINTILAR TÜRKÇELEŞTİ: Sabitlenmiş gönderilerdeki 'Pinned' → 'Sabit', üst bardaki 'Feedback Ver' → 'Geri Bildirim', Cafe sayfasındaki 'Host' → 'Ev Sahibi'. Sekiz ayrı yerde düzeltildi — beş yer bekliyorduk, tarayınca sekiz çıktı.",
      "CAFE ODASINDA İKİ DÜZELTME: (1) '2/100 üye' yazısındaki payda kaldırıldı. Payda, olması gereken 100 kişiden 2'sinin geldiğini söylüyordu — davet değil, başarısızlık ilanı. Oda gerçekten dolmaya başlayınca (beşte bir) payda kendiliğinden geri geliyor. (2) Oda canlıyken sayfadaki en görünür düğme 'Cafe'yi Arşivle' idi; yani oda sahibine sunulan ilk davranış odasını kapatmaktı. Bu işlem artık sağ üstteki üç nokta menüsünün içinde.",
      "GÖRSEL DİL İÇİN TEMEL ATILDI: Değerlendirmenin ana tespiti, tek tek kusurlardan çok 'tanımlı bir tasarım kuralının olmaması'ydı — aynı ekranda dört ayrı düğme stili, altı ayrı rozet stili dolaşıyor. Bugün bu kural yazıldı (renk, düğme, rozet, köşe/gölge, dil). Uygulaması sonraki adımlarda. Bu arada markanın imza rengi olan bronzun arayüzde hiç kullanılmadığı ölçüldü; kural sayfası onu birincil düğme rengi olarak tanımlıyor.",
      "ARKA PLANDA KAPANAN ESKİ İŞLER: Önceki oturumlardan commit'lenmemiş kalan işler de bugün tamamlandı — kullanılmayan 33 dosyanın temizliği, bildirim gönderim şifresinin düz metinden güvenli kasaya taşınması ve iki tip hatası. Silme işleminden önce geri dönüş noktası işaretlendi.",
      "DÜZENSİZ ÇALIŞAN DÖRT TEST DÜZELTİLDİ: Bazı otomatik testler tek başına çalışınca geçip, hepsi bir arada koşunca rastgele düşüyordu. Böyle testler her seferinde 'bir şey mi bozuldu?' diye durup bakmaya yol açıyor. Dördünün de asıl sebebi bulunup kökten çözüldü, üstünü örtmek yerine.",
      "DÜRÜST NOT — GÖZLE KONTROL BEKLİYOR: Bugünkü değişikliklerin büyük kısmı görsel ve otomatik testler görsel yerleşimi ölçemiyor. Özellikle üst barın kaydırmadaki incelmesi, kimlik şeridi kalktıktan sonraki üst boşluk ve zilin yeni yeri gerçek tarayıcıda gözden geçirilmeli. Kazanç olarak söylenen yükseklik rakamları da hesapla çıkarıldı, ekranda ölçülmedi.",
      "KONTROLLER: 260 dosyadaki 1.822 otomatik testin tamamı geçti (gün başında 256 dosya / 1.768 idi), kod denetimi temiz, yazı denetimi temiz, üretim derlemesi başarılı.",
    ],
  },
  {
    id: "20260907-atlanan-uc-duzeltme",
    date: "7 Eylül 2026",
    title:
      "5 Eylül akşamı yapılıp duyuruda atlanan üç düzeltme: dizinde görünen yönetici hesabı, taşınma testindeki tıklanmayan düğmeler, hangi konumu gösterdiğini söylemeyen Cafe başlığı",
    items: [
      "BU KAYIT NEDEN GERİYE DÖNÜK: Aşağıdaki işler 5 Eylül akşamı yapıldı ama o günün duyurusu yazılırken atlandı — düzeltmeler 21:33'te, duyuru 23:41'de girilmiş. Yapılmış bir işin duyurulmaması, ileride 'bu hâlâ bozuk mu?' diye ikinci kez bakılmasına yol açıyor. Bu yüzden silinip birleştirilmek yerine ayrı bir kayıt olarak eklendi.",
      "ÜÇÜ DE ŞU AN CANLIDA — TAHMİN DEĞİL, ÖLÇÜLDÜ: Canlı sitenin yayındaki dosyaları indirilip içindeki metinler tek tek arandı. Yeni metinler ('tüm konumlar', 'Hedef ülkende henüz şehir verimiz yok') VAR; eski hatalı metinler ('Aktif Cafeler', 'Yakında' kilidi) YOK. Yani bu üç düzeltmenin görünmesi için ayrıca yayın almaya gerek yok, hâlihazırda çalışıyorlar.",
      "DİZİN ARAMASINDA YÖNETİCİ HESABI ÇIKIYORDU: Üye dizininde arama yapınca süper admin hesabı sıradan bir üye gibi listeleniyordu. Sebep, aynı kuralın iki yerde farklı yazılmış olması: veri tabanı tarafı yönetici rollerini 'Admin_ ile başlayan' diye tanıyor, site tarafı ise elle yazılmış 7 anahtarlık sabit bir liste kullanıyordu. Canlıdaki gerçek anahtar o listede olmadığı için filtre sessizce delikti — hata vermiyor, sadece gizlemesi gerekeni gösteriyordu. Artık iki taraf da aynı 'ile başlayan' kuralını kullanıyor; ileride yeni bir yönetici rolü açıldığında listeye eklemeyi unutmak sorun çıkarmayacak.",
      "TAŞINMA TESTİ SONUCUNDAKİ DÜĞMELER TIKLANMIYORDU: Test sonucu ekranındaki yönlendirme düğmeleri 'Yakında' rozetiyle kilitliydi. Bu kilit aslında 30 Temmuz'da kaldırılmıştı; 2 Ağustos'ta bambaşka bir konuyla ilgili bir düzenlemenin yan ürünü olarak sessizce geri gelmiş. O düzenlemenin açıklamasında kilit hakkında tek kelime yok — yani bilinçli bir 'şimdilik kapalı kalsın' kararı değil, kaza. Kilidin ilk gerekçesi de (düğmelerin var olmayan adreslere işaret etmesi) 30 Temmuz'daki veri tabanı güncellemesiyle zaten çözülmüştü. Yedi hedef adresin her biri tek tek doğrulanıp düğmeler geri getirildi.",
      "AYNI DÜZELTMEDE İKİ YAN BULGU: Birincisi, düğme tıklamalarını sayan ölçüm bağlantısı da 2 Ağustos'ta kopmuştu, geri bağlandı — dürüst not: bu ölçüm hâlâ hiçbir sayfadan beslenmiyor, yani tıklama sayısı canlıda henüz üretilmiyor; o ayrı bir iş olarak duruyor. İkincisi, veri tabanında tam adresle ('https://...') tanımlanmış bir düğme sessizce bozuk bir bağlantıya dönüşüyordu; artık böyle bir durumda kullanıcı boşluğa değil Araçlar sayfasına düşüyor.",
      "'ARADIĞIN KRİTERDE ŞEHİR BULUNAMADI' DURUMU ARTIK EKRANDA YAZIYOR: Şehir eşleştirme testinde seçtiğiniz ülke için yeterli veri yoksa sistem sıralamayı başka ülkelerin şehirlerinden üretiyor, ama bunu size söylemiyordu — sonuç doğru görünüyor, yalnızca yanlış ülkeden geliyordu. Artık sonucun üstünde turuncu bir uyarı şeridi çıkıp durumu Türkçe anlatıyor ve ülke verisi eklendiğinde testi tekrar çözmeyi öneriyor. Bu şerit yalnız şehir eşleştirme aracında çıkar; diğer araçlar bu bilgiyi üretmiyor.",
      "CAFE BAŞLIĞI ARTIK HANGİ KONUMU GÖSTERDİĞİNİ SÖYLÜYOR: Başlık 'Aktif Cafeler' diyordu. 'Aktif' kelimesi olmayan bir ikinci boyut ima ediyordu ('demek ki aktif olmayan cafeler de var'), üstelik listenin hangi konuma göre süzüldüğünü hiç söylemiyordu. Artık 'Cafeler · Berlin (2)' biçiminde yazıyor; konum seçili değilse 'tüm konumlar' diyor. Başlık ile ekran okuyucu etiketi tek kaynaktan üretiliyor, yani biri güncellenip diğerinin unutulması artık mümkün değil.",
      "PAYLAŞIM KUTUSUNDA ETİKETLEME İPUCU: Cadde'de '@' ile üye etiketleme ve '#' ile konu etiketi zaten çalışıyordu, ama bunu söyleyen tek bir satır yoktu — özellik keşfedilemediği için pratikte yok sayılıyordu. Metin kutusunun altına '@ ile üye etiketle, # ile konu etiketi ekle.' ipucu eklendi. Yeni bir özellik değil, var olanın görünür kılınması.",
      "BURAK İÇİN ELLE TEST KILAVUZU: 5 Eylül'de değişen her şey için, geliştirici aracı açmadan yalnız tarayıcıdan yapılabilecek 12 adımlık bir test kılavuzu hazırlandı. Maddeler bilerek ikiye ayrıldı, çünkü hepsi aynı anda test edilemiyordu: bir kısmı (kafe teması, ABD/İngiltere üyelerinin paylaşabilmesi, yazı tipleri) veri tabanı tarafında zaten canlıydı, gerisi yeni sürüm çıkmadan görünmüyordu. Kılavuz en başta beş saniyelik tek adımlık bir kontrol veriyor: hangi listenin o an test edilebilir olduğunu hemen söylüyor.",
      "6 VE 7 EYLÜL'DE KULLANICI TARAFINDA YENİ DEĞİŞİKLİK YOK: Bu iki günde yalnız iç belgeler yazıldı — devir notu ve kalan işlerin tek tek yapılabilir maddelere bölünmesi. 6 Eylül'ün büyük temizliği bir alttaki kayıtta duruyor, tekrar edilmedi.",
      "KONTROLLER: 259 dosyadaki 1.818 otomatik testin tamamı geçti, kod denetimi temiz (0 sorun), yazı denetimi 1.391 dosyada temiz. Bu kaydın kendisi de teste bağlandı: içindeki 'canlıda mı' ve 'kapanmamış iş' cümleleri silinirse testler düşer.",
    ],
  },
  {
    id: "20260906-buyuk-temizlik",
    date: "6 Eylül 2026",
    title:
      "Büyük temizlik: artık kullanılmayan 150 dosya kaldırıldı, panelde açılmayan üç ekran silindi, belgelerdeki yanlış rakamlar düzeltildi",
    items: [
      "ÖNCE EN ÖNEMLİSİ: KULLANICININ GÖREBİLDİĞİ HİÇBİR ŞEY SİLİNMEDİ. Silinen her dosya, uygulamanın hiçbir yerinden ulaşılamayan koddu — yani zaten kimse açamıyordu. Bunu tahminle değil, uygulamanın giriş noktasından başlayıp hangi dosyanın hangisini çağırdığını adım adım izleyerek doğruladık; ayrıca her partiden sonra tüm testler, tip denetimi ve gerçek bir üretim derlemesi çalıştırıldı.",
      "PANELDE AÇILMAYAN ÜÇ EKRANIN DOSYALARI KALMIŞTI: 'Roller ve Özellikler', 'Nitelikler' ve 'Profil Bölümleri' ekranları bir süre önce tek bir 'Rol Matrisi' ekranında birleştirilmişti. Adresleri hâlâ çalışıyor ama sizi doğrudan Rol Matrisi'ne gönderiyor — yani o eski ekranlar zaten açılmıyordu. Kodları ortada duruyordu, temizlendi.",
      "ARTIK VAR OLMAYAN BİR VERİ TABLOSUNA BAĞLI EKRANLAR: Üç ekran daha, aylar önce kaldırılmış bir tabloyu sorguluyordu. Bunlardan biri panele bağlansaydı hiçbir veri yükleyemeyecek, sadece hata verecekti. Üçü de kaldırıldı.",
      "İKİ GİRİŞ SİSTEMİNDEN BİRİ KAPATILDI: Oturum bilgisine ulaşmanın iki ayrı yolu vardı; ikincisi geçiş dönemi için bırakılmış bir köprüydü. 16 dosya tek ve asıl sisteme taşındı, köprü kaldırıldı. Kullanıcı tarafında hiçbir değişiklik yok — amaç, ileride 'hangisini kullanacağım' sorusunun bir daha sorulmaması.",
      "ESKİ ÜRÜN SAYFALARI: Danışmanlar, Bloggerlar, İşletmeler, Etkinlik Detayı, İş İlanları, Radyo Şarkı İsteği gibi bir dönem denenip menüden çıkarılmış sayfaların dosyaları da duruyordu. Hiçbirine bağlantı yoktu; kaldırıldılar.",
      "TEST SAYISI NEDEN AZALDI: 1.881'den 1.816'ya indi ve bu iyi bir haber. Silinen kodun kendi testleri de birlikte gitti — yani artık kimsenin kullanmadığı kodu kontrol eden testler. Çalışan hiçbir test kaybedilmedi, hepsi yeşil.",
      "BELGELERDEKİ RAKAMLAR YANLIŞTI, DÜZELTİLDİ: Geliştirici belgesi 'kod denetiminde 1.280 sorun var' diyordu; ölçtük, gerçek sayı SIFIRDI. Aynı şekilde 'temizlenecek 89 yer' denilen şey 9'du, '78 MB video' 16 MB'tı, 'yayında olan bir dosya' zaten silinmişti. Bu yanlış rakamlar, ileride birinin çoktan bitmiş bir işi yeniden yapmasına yol açacaktı.",
      "TİP HATALARI YARIYA İNDİ: 22'den 9'a düştü. Bunların 6'sı aslında hata değil, yukarıdaki ölü ekranların ihbarıymış — dosyalar silinince kendiliğinden kapandılar. Kalanların her biri de artık 'ne olduğu ve nasıl kapanacağı' yazılı hâlde belgede duruyor.",
      "SİTE HAFİFLEDİ: Toplamda yaklaşık 29 bin satır kod ve 150 dosya kaldırıldı. 300 satırdan uzun dosya sayısı 126'dan 92'ye indi. Daha az dosya, bozulacak daha az yer demek.",
      "KONTROLLER: 259 dosyadaki 1.816 otomatik testin tamamı geçti, kod denetimi temiz (0 sorun), üretim derlemesi yeşil, veri tabanı güncellemelerinin tamamı canlıda kayıtlı.",
      "NOT: 5 Eylül'de yapılan işler (Cadde tepki kartı, Çarşı kategori bağlantıları, taşınma araçlarında şehir seçimi, sonuca dönüş şeridi, renkli sonuç grafikleri ve üç sessiz canlı kusur) aşağıdaki iki kayıtta duruyor.",
    ],
  },
  {
    id: "20260905-ikinci-parti-cadde-carsi-araclar",
    date: "5 Eylül 2026",
    title:
      "Günün ikinci yarısı: aylardır sessizce bozuk olan üç şey düzeldi, Çarşı rozetleri tıklanır oldu, taşınma araçlarına şehir seçimi ve renkli sonuçlar geldi",
    items: [
      "YAZI TİPLERİ AYLARDIR HİÇ YÜKLENMİYORDU: Site, tasarlanan yazı tipi yerine bilgisayarın varsayılan yazı tipiyle görünüyormuş. Sebep, yazı tipini çağıran satırın güvenlik ayarımız yüzünden hiç çalışmaması. Kimse fark etmemişti çünkü sayfa 'bozuk' görünmüyor, sadece yanlış görünüyordu. Düzeltildi ve canlı sitede yazı tipinin gerçekten yüklendiği ölçülerek doğrulandı.",
      "6 ÜYE HİÇ PAYLAŞIM YAPAMIYORDU: Profil formunda ülkesini 'ABD' seçen üyenin paylaşımı reddediliyordu, çünkü Cadde tarafı aynı ülkeyi 'Amerika Birleşik Devletleri' adıyla tanıyor. Yazım farkı değil, apayrı kelimeler. İki listeyi birbirine bağlayan bir köprü kuruldu; artık formun ürettiği her eş-ad kalıcı olarak çözülüyor. Paylaşım yapabilen üye 107'den 113'e çıktı.",
      "'EK HEDEF' DÜĞMESİ PAYLAŞIMI KAYBETTİRİYORDU: Normal bir üye Cadde'de 'Ek hedef' ekleyip paylaşmaya çalıştığında sunucu paylaşımı reddediyor ve yazılan içerik gidiyordu. Yöneticiler bu kontrolden muaf olduğu için sorun test hesaplarında hiç görünmemiş. Düğme artık yetkisi olmayan üyeye kapalı, yani kayıp durdu. Özelliğin kimlere açılacağı ayrı bir karar olarak bekliyor.",
      "KAFE AÇARKEN 'İŞ' TEMASI YOKTU: Tema listesinde olması gereken 'İş' hiç yoktu; 'İK' ise İngilizce 'HR' etiketiyle duruyordu. İkisi de düzeltildi. Mevcut kafeler etkilenmedi ve bu değişiklik için yeni sürüm çıkmasına gerek yok, liste doğrudan veritabanından okunuyor.",
      "TEPKİLER TEK DÜĞMENİN ARKASINDA TOPLANDI: Paylaşımın altındaki beş tepki düğmesi yan yana durmak yerine 'Beğen' düğmesinin üzerine gelince açılan küçük bir kartta toplanıyor. Klavyeyle de erişilebiliyor. Yol boyunca gerçek bir kusur da bulundu: kart, üzerine gitmeye çalıştığınız anda kapanıyordu, yani tepki düğmelerine fareyle hiç tıklanamıyordu.",
      "BOŞ ALANLARA MASKOT KONDU: Sağdaki tanıtım ve öne çıkanlar kutuları boşken düz metin yerine maskot görselini gösteriyor.",
      "ÇARŞI KATEGORİ ROZETLERİ ARTIK TIKLANIYOR: İlan kartındaki, üstteki kayan şeritteki ve ilan detayındaki kategori rozeti sadece etiketti. Artık tıklayınca o kategorideki ilanların listesine gidiyor.",
      "TAŞINMA SİHİRBAZINDA ÜLKE ADI GÖRÜNÜYOR: Ülke seçim listesinde 'DE', 'GB', 'US' gibi kodlar yazıyordu; artık 'Almanya', 'İngiltere', 'ABD' yazıyor.",
      "ARAÇLARDA ŞEHİR ARTIK LİSTEDEN SEÇİLİYOR: Şehir adını elle yazmak gerekiyordu ve yazım hatası sessizce kaydediliyordu. Artık önce ülke, sonra şehir seçiliyor. Listede olmayan bir şehri hâlâ elle yazabiliyorsunuz, yani kimse tıkanmıyor.",
      "ŞEHİR ADIMI ARTIK ÜLKENİZİ HATIRLIYOR: Testin 4. sorusunda ülkelerinizi seçiyordunuz ama 12. sorudaki şehir adımı bunu bilmiyordu; ülkeyi ikinci kez seçmeden hiçbir şehir göremiyordunuz. Artık seçtiğiniz ülkelerin şehirleri doğrudan geliyor, istersen başka bir ülkeye de geçebiliyorsun.",
      "TESTTEN ÇIKINCA SONUCA DÖNÜŞ KOLAYLAŞTI: Sonuç ekranındaki bir düğmeye basıp Cadde'ye veya dizine gittiğinizde test sonucuna dönmenin hiçbir yolu yoktu. Artık üstte ince bir 'Test sonucuna dön' şeridi çıkıyor; istemezseniz kapatabiliyorsunuz.",
      "SONUÇ GRAFİKLERİ RENKLENDİ: Puan çubukları tek renkti; 0,35 ile 0,92 aynı gri görünüyordu ve hangi alanın zayıf olduğunu ancak sayıyı okuyarak anlıyordunuz. Artık her çubuk puanına göre renk, ikon ve 'Güçlü / İyi / Orta / Zayıf' etiketi taşıyor. Renkler gözle seçilmedi: renk körlüğü ve kontrast denetiminden geçirilerek belirlendi, bu yüzden bilgi renk görülmese de etiketten okunuyor.",
      "RADAR REHBERLERİNE ÜLKE FİLTRESİ ve dizinde kurum kayıtlarının kart görünümü de bu turda eklendi.",
      "KONTROLLER: 1.881 otomatik test geçti (sabah 1.768'di), kod denetimi temiz, veri tabanı güncellemelerinin tamamı canlıda kayıtlı (383/383).",
    ],
  },
  {
    id: "20260905-profil-formu-ilk-parti",
    date: "5 Eylül 2026",
    title:
      "Profil formunun ilk partisi yapıldı: telefon en üstte, profil tipi görünür, rozetlerde açıklama; kayıt formu kısaldı",
    items: [
      "TELEFON ARTIK PROFİL FORMUNUN İLK KUTUSU: Toplantı kararı gereği telefon numarası en üste alındı. Numara her zaman gizli tutuluyor; yanında görünürlük anahtarı yerine 'Yalnız sen' kilidi duruyor ve herkese açık profilde hiçbir koşulda gösterilmiyor.",
      "TELEFON ALANI ÖNCEDEN HİÇ GÖRÜNMÜYORDU: 116 üyenin kayıtlı numarası olmasına rağmen alan profil ekranında yoktu, çünkü hiçbir role tanımlanmamıştı. 78 aktif rolün tamamına eklendi.",
      "NUMARA BİÇİMİ KONTROL EDİLİYOR: Ülke kodu olmayan veya eksik numara kaydedilmiyor, ekranda ne yapılması gerektiğini söyleyen kısa bir uyarı çıkıyor. Boşluk, tire ve parantez otomatik temizleniyor.",
      "ÜLKE TELEFONDAN TAHMİN EDİLMİYOR: +90 numaralı bir üye Berlin'de yaşıyor olabilir. Ülke yalnız üyenin kendi seçimiyle belirleniyor; bu kural artık otomatik bir denetimle korunuyor, ileride yanlışlıkla eklenirse testler düşer.",
      "PROFİL TİPİ ARTIK NET GÖRÜNÜYOR: Profil başlığında 'Profil tipi: …' etiketi ve yanında ne anlama geldiğini anlatan bilgi (i) ikonu var. Profil durumu kartına da ayrı bir satır olarak eklendi.",
      "ROZETLERE AÇIKLAMA EKLENDİ: 'İş Arıyorum', 'Yakında Taşınacağım' ve 'Gönüllü Mentörlük' rozetlerinin yanındaki (i) ikonuna gelince rozetin ne işe yaradığı yazıyor.",
      "İLGİ ALANLARI HERKESE AÇIK OLDU: Toplantı kararı gereği bireysel ilgi alanları artık gizlenemiyor; eşleştirme ve ağ önerileri bu bilgiyle çalıştığı için gizleme anahtarı kaldırılıp yerine 'Herkese açık' rozeti kondu.",
      "LINKEDIN OPSİYONEL KALDI AMA ÖNE ÇIKTI: Kartta 'Tavsiye edilir' rozeti ve nedenini anlatan kısa bir açıklama var. Zorunlu değil.",
      "'BİZİ NEREDEN BULDUNUZ?' SORUSU KALDIRILDI: Kayıt formu, davet aktivasyon ekranı, destek formları ve yapay zekâ sohbet akışı dahil olmak üzere sorunun sorulduğu her yerden çıkarıldı; sohbet akışı iki adım kısaldı. Geçmiş cevaplar silinmedi, başvuru detayında görünmeye devam ediyor.",
      "GİRİŞ EKRANI DOĞRULAMAYA HAZIRLANDI: E-posta doğrulaması açıldığında kullanıcı ham İngilizce hata yerine ne yapması gerektiğini Türkçe görecek ve 'Doğrulama e-postasını yeniden gönder' düğmesini kullanabilecek. Kayıt sonrası mesaj da artık gerçek sonuca göre yazılıyor.",
      "TARAYICI HATALARI ARTIK KAYBOLMUYOR: Cadde'de paylaşım/yorum gönderilemediğinde veya bir sayfa 'Bir hata oluştu' ekranına düştüğünde hata kaydı veritabanına yazılıyor. Yeni 'İstemci Hataları' ekranından (Roller ve Yetkiler menüsü) kaynak ve metne göre filtrelenebiliyor. Kayıtlar 90 gün saklanıyor, kişisel içerik gönderilmiyor.",
      "WORKSHOP PANOSUNA ONAY KUYRUĞU FİLTRESİ: Cadde panosunda 65 madde 'UBT tamam, Burak bekliyor' durumundaydı ve bunu süzmenin yolu yoktu. Artık 'Burak onayı bekleyenler' ve 'UBT onayı bekleyenler' filtreleri var; Burak onayı kartı da kaç maddenin onunla beklediğini yazıyor.",
      "KONTROLLER: 1.760'tan fazla otomatik test geçti, kod denetimi temiz, veri tabanı güncellemelerinin tamamı canlıda kayıtlı (381/381).",
    ],
  },
  {
    id: "20260904-profil-toplantisi-ve-workshop-panosu",
    date: "4 Eylül 2026",
    title:
      "3 Eylül Profiller toplantısı panele işlendi — kararlar Komuta Merkezi'nde, profil maddeleri yeni Profil Workshop panosunda",
    items: [
      "KOMUTA MERKEZİ'NE 3 EYLÜL TOPLANTISI EKLENDİ: Toplantının tamamı 24 kayıt olarak girildi — 17 yapılacak iş ve 7 karar. Kayıtlar 'Toplantı 19 / 3 Eylül 2026' etiketiyle süzülebiliyor. UBT'de 14, Burak'ta 3 iş var.",
      "ORTAK KARARLAR ARTIK ORTAK SORUMLUYLA GİRİLİYOR: Toplantıda birlikte alınan 7 karar, tek bir kişiye yazılmak yerine ilk kez 'B+B' etiketiyle kaydedildi. Böylece bunlar kimsenin kişisel yapılacak listesini şişirmiyor ama kapsam kaydı olarak panelde duruyor.",
      "YENİ PROFİL WORKSHOP PANOSU: Menüye Workshop > Profil eklendi. Toplantının yalnız profil ile ilgili 26 maddesi, Cadde workshop'uyla birebir aynı düzende burada duruyor: madde listesi, yanında UBT ve Burak için iki ayrı onay kutusu, iki onay tamamsa madde bitmiş sayılıyor.",
      "MADDELER ALTI BAŞLIKTA TOPLANDI: Profil formu ve alanlar (6), doğrulama ve giriş (6), rol ve etiket mimarisi (4), referans sistemi (3), paketleme ve yetkiler (4), operasyon (3).",
      "NEDEN İKİ AYRI YERDE DURUYOR: Komuta Merkezi toplantının TAMAMINI tutuyor (WordPress taşıma, Excel dokümantasyonu, operasyon dahil). Profil Workshop ise yalnız profil maddelerinin kopyasını, iki onay kutulu workshop düzeninde tutuyor. Amaçları farklı olduğu için kopya bilerek bırakıldı.",
      "İKİ WORKSHOP TEK ALTYAPIDAN BESLENİYOR: Cadde ve Profil panoları artık aynı ortak bileşeni kullanıyor. Birinde yapılan iyileştirme diğerine de geliyor; ileride üçüncü bir workshop açmak tek satırlık iş.",
      "ZATEN BİTMİŞ TEK MADDE İŞARETLENDİ: Burak'ın yönetici yetkisinin geri verilmesi 3 Eylül'de tamamlandığı için 'Tamamlandı' girildi. Burak'ın panelde kendi doğrulamasını yapması ayrıca bekleniyor.",
      "KONTROLLER: 1.718 otomatik test geçti, kod denetimi temiz, 379 veri tabanı güncellemesinin tamamının canlıda kayıtlı olduğu doğrulandı.",
    ],
  },
  {
    id: "20260903-top-10-hot-fix-ve-yonetici-yetkisi",
    date: "3 Eylül 2026",
    title: "Komuta Merkezi'ne TOP 10 HOT FIX listesi eklendi, Burak'ın yönetici yetkisi geri verildi",
    items: [
      "TOP 10 HOT FIX BLOĞU: Komuta Merkezi'nin üstüne, platformda acilen yapılması gereken işlerin durduğu ayrı bir liste eklendi. Amaç, yüzlerce kaydın arasında 'önce şunlar' diyebilmek.",
      "SINIR: AYNI ANDA EN FAZLA 10 AÇIK MADDE: Onbirinci açık madde eklenmek istendiğinde sistem izin vermiyor. Sınır yalnız ekranda değil veri tarafında da uygulanıyor, yani başka bir yoldan da aşılamıyor.",
      "TAMAMLANAN MADDE YER İŞGAL ETMİYOR: Bir işi bitirir bitirmez yenisini girebiliyorsunuz. Tamamlanan madde listeden kaybolmuyor, sadece en alta iniyor — bu yüzden tablo geçici olarak 10'dan fazla satır gösterebilir, bu normal.",
      "ANA TABLODAN BİLEREK FARKLI: Komuta Merkezi'nin ana tablosunda tamamlanan işler en alttaki ayrı 'Tamamlanan Görevler' kutusuna taşınıyor. Hot fix listesinde bu yapılmıyor; ne yapıldığı bir bakışta görünsün diye bitmiş maddeler aynı listede kalıyor.",
      "AYRI LİSTE OLARAK KURULDU: Hot fix kayıtları ana tabloya karışmıyor. Böylece filtrelere, kaynak dağılım kartına, rozet sayaçlarına ve Todo / Toplantı Notları ekranlarına sızmıyorlar.",
      "LİSTE ŞU AN BOŞ: İlk 10 maddenin önceliklendirilip girilmesi Burak'ta.",
      "BURAK'IN YÖNETİCİ YETKİSİ GERİ VERİLDİ: Yanlışlıkla silinen yetki geri verildi; hesap en yüksek yönetici seviyesine (SuperAdmin) alındı ve admin paneline erişimi açıldı.",
      "BİR KİŞİ, BİR ROL: Sistemde her kullanıcı aynı anda tek rol taşıyor. Bu yüzden yeni rol vermek eskisinin üzerine yazmak demek — yetki değişikliklerinde bu kural akılda tutulmalı.",
    ],
  },
];
