// Ürün güncellemeleri — Ekim 2026 kayıtları (en yeniden eskiye).
// Tek kaynak barrel: ../admin-updates.ts — ekranlar oradan okur, buradan DEĞİL.

import type { AdminUpdateEntry } from "./types.ts";

export const ADMIN_UPDATES_2026_10: AdminUpdateEntry[] = [
  {
    id: "20261005-g14-grup-sikayet-sistemi",
    date: "5 Ekim 2026",
    title: "Grup şikayet sistemi kuruldu — telefon doğrulaması açılınca kullanılabilecek",
    items: [
      "NE GELDİ: Grup sayfasına “Şikayet et” bölümü eklendi. Üye, politikadaki 7 kırmızı çizgiden birini (ölü link, vize/randevu satışı, kripto/MLM, kişisel veri isteme, nefret/taciz, doğrulanmamış çocuk grubu, siyasi kampanya) ya da “Diğer”i seçer; “Diğer”de kısa açıklama zorunlu. Şikayet edenin kimliği grup sahibine hiçbir yoldan gösterilmez — yalnız yöneticiler görür.",
      "KİM ŞİKAYET EDEBİLİR: Giriş yapmış, telefonu doğrulanmış ve hesabı en az 7 günlük üye. Aynı kişi aynı gruba 30 gün içinde yalnız bir kez şikayet edebilir. Kendi eklediği ya da sahibi olduğu gruba şikayet edemez (bu kişilere düğme hiç gösterilmez). Kurala uymayan şikayet sayılmaz ve saklanmaz.",
      "EŞİK: Üç farklı uygun hesaptan şikayet gelince grup otomatik olarak dizinden gizlenir ve moderasyon kuyruğuna düşer. Eşik ve diğer sayılar ayarlardan gelir, kodda sabit değildir.",
      "MODERASYON: /admin/gruplar sayfasındaki “Şikayetler” sekmesi artık dolu: grup bazında sebep dağılımı, kaç farklı kişinin şikayet ettiği, notlar. Onaylanırsa uyarı merdiveni işler (tek onay = tek ihlal; vize satışı, kişisel veri isteme ve çocuk grubu maddeleri ilk seferde kalıcı kaldırma). Reddedilirse ve başka açık şikayet kalmadıysa grup yeniden yayına döner. Kısayollar (A onayla, R reddet, J/K gez) bu sekmede de çalışıyor.",
      "⚠️ BUGÜN KİMSE ŞİKAYET EDEMEZ: Telefon doğrulaması için SMS sağlayıcısı (Twilio) kimlikleri hâlâ girilmedi; bu yüzden hiçbir üye telefonunu doğrulayamıyor ve sayfada dürüstçe “Şikayet için telefon doğrulaması gerekir” yazıyor. Kimlikler girilip telefon doğrulama kartı profil sayfasına bağlanınca sistem kendiliğinden açılır.",
      "SİZDEN BEKLEYENLER: (1) SMS sağlayıcı kimlikleri, (2) eşikle gizlenen grubun sahibine ve şikayetçiye mail gitsin mi (bugün gitmiyor), (3) uyarı (1. ihlal) onaylandığında grup otomatik yayına dönsün mü (bugün gizli kalıyor), (4) sebep ↔ kırmızı çizgi eşlemesinin teyidi. Ayrıntı: docs/handover/2026-10-05-g14-kullanici-adimlari.md.",
      "KANIT: canlı kabul testi 13/13 (geri alınan işlemde gerçek senaryo: 3 uygun hesap grubu gizledi, 2 hesap gizlemedi, 6 günlük ve telefonsuz hesabın şikayeti sayılmadı); aynı kişinin eşzamanlı iki şikayetinden yalnız biri kaydedildi (ölçüldü); kuralı bozan 7 kasıtlı değişikliğin 7'si de testlerce yakalandı; tam test takımı yeşil.",
    ],
  },
  {
    id: "20261004-gunun-ozeti-sade-dille",
    date: "4 Ekim 2026",
    title: "4 Ekim’in tamamı sade dille: ne yapıldı, ne bekliyor",
    items: [
      "KISACA: Bugün üç büyük iş vardı — (1) sistemdeki güvenlik açıkları arandı ve altısı kapatıldı, (2) kapanan açıkların daha önce kullanılıp kullanılmadığına bakıldı, (3) bir dizi yeni özellik tamamlandı ya da hazırlandı. Aşağıda hepsi sırayla, teknik terim kullanmadan yazıldı. Bu mailin devamındaki ayrı kayıtlar aynı işlerin teknik ayrıntısıdır; merak ederseniz bakın, bilmeniz gereken her şey burada.",
      "GÜVENLİK — ALTI AÇIK KAPATILDI (günün en önemli kısmı): Sistematik bir tarama sırasında dışarıdan herkesin görebildiği altı yer bulundu; hiçbiri plana alınmamıştı. Toplamda yaklaşık 4.350 satır iç bilgi ve kişisel veri dışarıya açıktı: (a) üye bilgilerini ve telefon numaralarını içeren eski bir yedek tablo (938 satır), (b) Komuta Merkezi’ndeki 1.761 kayıt — yalnız okunamıyordu, dışarıdan DEĞİŞTİRİLEBİLİYORDU da, (c) eski pano tablolarındaki yaklaşık 1.650 kayıt, (d) 51 yönetici işleminde gereksiz anonim izin (kapılar zaten vardı, bu ek bir önlem), (e) bir özgeçmiş klasörü, (f) eski pano tablolarının giriş yapmış 173 üyeye açık olması — artık yalnız yöneticiler görüyor. Hepsi kapatıldı ve kapatıldıktan sonra dışarıdan denenip doğrulandı.",
      "GEÇMİŞE BAKILDI — KÖTÜYE KULLANIM İZİ YOK: Kapatılan açıklar daha önce kullanıldı mı diye son 90 günün erişim kayıtları (2 milyondan fazla istek) tarandı. Üye bilgilerinin bulunduğu tabloya giden 39 isteğin hepsinin kaynağı belli çıktı: sizin panelden bakışlarınız, Supabase’in kendi yedekleme servisi, bir envanter taraması ve bugünkü kendi doğrulamamız. Dışarıdan erişim izi yok. Dürüst sınır: kayıtlar 90 gün geriye gidiyor, söz konusu tablo Haziran’da oluşturulduğu için ilk yaklaşık 27 gün incelenemedi ve kayıtlarda kimlik bilgisi yok. Yani “kesinlikle olmadı” denemez, ama bildirim gerektirecek bir bulgu da yok.",
      "📌 SİZE TEK SORU: 26 Eylül akşamı yaklaşık 19:11’de (Berlin) panelde ya da bir araçla sistemin tüm tablolarını sırayla gezen bir tarama çalıştırdınız mı? Üç dakikada 301 istekle her tabloya bakılmış; deseni bir envanter taramasına benziyor ama sizin olup olmadığını yalnız siz bilirsiniz. Hatırlarsanız son belirsizlik de kapanır.",
      "ÖZGEÇMİŞLER: Eski özgeçmiş klasöründeki 3 dosyaya bağlı hiçbir kayıt kalmamıştı, yani kimse kullanmıyordu. Önce güvenli bir yere yedeklendi (depoya konmadı, yerel bir klasörde duruyor), sonra silindi.",
      "KOMUTA MERKEZİ SADELEŞTİ: Panodaki aktif kayıt sayısı 1.635’ten 56’ya indi (sabah 495’e, akşam 56’ya). Hiçbir şey silinmedi; hepsi arşive alındı ve geri getirilebilir. Akşamki aşamada bir şey öğrendik: “üzerinde çalışılmış” görünen 412 kaydın 400’ü aslında Mayıs’taki tek bir toplu aktarmanın damgasıydı. Gerçekten üzerinde çalışılmış 12 kayıt var ve onlar panoda duruyor (aboneliklerle ilgili kararlar, SMS bütçesi, Stripe, Google girişi maliyet sorusu gibi).",
      "GRUPLAR: Herkese açık grup dizini 10 yerine 8 grup gösteriyor. ‘HCD – Bilinç Çözümleme’ ve ‘SHAMAN Koçluk’ gruplarının davet linki hiç girilmemişti, bu yüzden dizinde görünseler de kimse katılamıyordu; geçici olarak yayından alındılar, link gelince geri alınabilir. Bu iki grubun sahiplerine normalde giden otomatik “linkiniz çalışmıyor” maili BİLEREK gönderilmedi — gruplar hiç link almamıştı, mail yanlış bir şey söylerdi. Ayrıca ‘Diğer’ kategorisindeki gruplar gerçek kategorilerine taşındı ve tüm grupların ülke/şehir bilgisi sisteme düzgünce bağlandı (dünya geneli olanlar ‘global’ diye işaretlendi).",
      "TAVSİYE ÖZELLİĞİ (üyenin “bana bir uzman öner” talebi): Cadde akışında tavsiye kartı eklendi; talep açılınca uyan uzmanlara bildirim maili gidiyor; ücretli üyelik için kilitli bir gelen kutusu kartı var. Gerçek mail hattından uçtan uca denendi. Bağımsız bir inceleme turunda, mail konusuna gizli karakterle sahte başlık sokulabilen ciddi bir açık bulundu ve kapatıldı; ayrıca talep sahibi artık kendi talebini yanıtlayamıyor, yanıt göndermiş üye de boş form yerine “yanıtın gönderildi” görüyor.",
      "DOĞRULAMA ROZETİ (bugün erken saatlerde): Yöneticinin onayladığı kurumlar dizinde rozet almıyordu; üstelik 2 kayıtta haksız rozet vardı. Rozet artık onay durumundan türetiliyor, yani ikisi birbirinden ayrışamıyor.",
      "HAFTALIK ŞEHİR ÖZETİ ARTIK AÇIK: Üyelerin takip ettiği şehirlerdeki yeni etkinlik ve tavsiyeleri haftada bir (pazartesi sabahı) özetleyen mail bu akşam AÇILDI. Şu an şehir takip eden üye olmadığı için ilk hafta kimseye mail gitmeyecek; özellik duyuruldukça başlar. Bugünkü ayrı kayıtta “karar sizi bekliyor” yazıyordu — o karar verildi, o kayıt da güncellendi.",
      "TELEFON DOĞRULAMA — HAZIR AMA SMS SAĞLAYICISI YOK: Üyeler profillerinde telefonlarını SMS koduyla doğrulayabilecek; arayüz ve altyapı hazır, telefonla kayıt/giriş yolu ise bilerek kapalı. Ancak gerçek SMS gidebilmesi için Supabase panelinde bir SMS sağlayıcısının (Twilio) kimliklerinin girilmesi gerek. Ölçtük: sağlayıcı adı “Twilio” yazıyor ama kimlik alanlarının hepsi BOŞ — yani “Twilio kurulu” bilgisi doğru değildi. Ayrıca “kullanıcı başına günde 5 SMS” sınırı şu an uygulanmıyor; zorunlu olacaksa ek bir iş gerekiyor (karar sizin).",
      "WHATSAPP BOTU: Mesaj gönderme parçası ortak bir modüle taşındı ve canlıya alındı (davranış aynı, yalnız düzen değişti). Bot henüz otomatik cevap VERMİYOR: Meta’dan alınacak 5 bağlantı bilgisi hâlâ girilmedi (şu an yer tutucu). Sıradaki parçalar kapalı doğacak şekilde yazılacak; bilgiler girilip gerçek bir telefonla denenmeden otomatik yanıt AÇILMAYACAK.",
      "KARARLAR VE ÖDEME PLANI: Bekleyen 16 karar bugün tek turda verildi ve yazıya geçirildi; ayrı bir ajanın baştan sona uygulayabileceği bir talimat dosyası da hazırlandı. Verilenlerden bazıları: web siteleri herkese açık kalsın ama kişisel iletişim bilgileri (13 kayıt: WhatsApp, e-posta, telefon) yalnız giriş yapmış üyelere gösterilsin — ⚠️ bu henüz UYGULANMADI, sırada; SEO/GEO çalışması başlasın ama sitenin kurumsal yapılandırılmış veri kısmına dokunulmasın; ödeme yalnız Euro, AB + Türkiye kapsamında. Ödeme (Stripe) için plan yazıldı; abonelik başlangıcına (1 Ocak 2027) 13 hafta var. Bir düzeltme: önceki notlarda “Kurucu 1000 = 99 €” yazıyordu ama sitenin fiyat sayfası aslında 3 paket × aylık/yıllık gösteriyor (Danışman Pro 25/20 €, Kuruluş Pro 50/40 €, İşletme Pro 75/60 €); planın bu şekilde düzeltilmesi sıradaki ajana verildi. En uzun yol teknik değil: Stripe hesabı ve vergi sorusu sizde (vergi için profesyonel danışman gerekir).",
      "SİZDEN BEKLEYENLER: (1) WhatsApp’ın 5 bağlantı bilgisi, (2) SMS sağlayıcısı kimlikleri, (3) Stripe hesabı ve vergi rejimi, (4) iki gerçek mail denemesi (e-posta doğrulama ve revizyon tamamlanma), (5) 25 Eylül toplantı kaydının son yaklaşık 25 dakikası, (6) yukarıdaki 26 Eylül sorusu, (7) depo dışındaki yaklaşık 50 maddenin toplu teyidi. Bunların dışındaki her iş ajanlarda ilerliyor.",
    ],
  },
  {
    id: "20261004-g04-g05-telefon-otp",
    date: "4 Ekim 2026",
    title: "Telefon doğrulama altyapısı hazır — SMS sağlayıcı bekleniyor (U06)",
    items: [
      "G04 — DOĞRULAMA AYNAKLAMA: Auth.users'daki phone_confirmed_at değişimini user_verifications tablosuna aynalayan trigger kuruldu. Telefon doğrulandığında is_phone_verified() otomatik true döner. Phone-only kayıt (email YOK, phone VAR) reddedilir — telefonla giriş/kayıt yolu kapalı.",
      "G05 — DOĞRULAMA ARAYÜZÜ: Profil sayfasında PhoneVerificationCard eklendi. Kullanıcı telefonunu girer → SMS kodu alır → kodu doğrular. Native Supabase Auth yolu kullanılır (updateUser → verifyOtp).",
      "HIZ SINIRI KARARI: Auth'un yerleşik sınırları (30/gün proje geneli) geçerli. DB'de otp_send_attempts tablosu ile gözlem yapılır ama enforcement YOK. Kullanıcı başına 5/gün, 3/saat politikası ENFORCED değil — bunun için edge function gerekir (KARAR GEREKİR, kullanıcı-adımları dosyasında yazılı).",
      "⚠️ U06 BEKLENİYOR: SMS sağlayıcı kimlikleri (Twilio account_sid, auth_token, message_service_sid) Supabase panelinde girilmeden gerçek SMS gönderilemez. external_phone_enabled=true açılmalı.",
      "KANIT: G04 kabul K1–K9 9/9 (geri alınan işlem) · G05 API 12 test · tam suite 455 dosya / 3772 test · tsc 0 · check:dead 0 · check:migrations 490/490 sapmasız.",
    ],
  },
  {
    id: "20261004-w03-whatsapp-graph-ortak-modul",
    date: "4 Ekim 2026",
    title: "WhatsApp Graph gönderim yolu ortak modüle taşındı — davranış değişmedi",
    items: [
      "ALTYAPI: whatsapp-reply fonksiyonundaki Meta Graph API çağrısı (satır 65–90) ve sürüm doğrulaması (satır 15–16) yeni _shared/whatsapp-graph.ts modülüne taşındı. Davranış birebir aynı; W05'te yazılacak whatsapp-autoreply aynı yolu kullanacak, ikinci Graph istemcisi yazılmayacak.",
      "TEST BOŞLUĞU KAPATILDI: Graph yanıtını ayrıştıran 26 satır bugün HİÇ test edilmiyordu (whatsapp-reply.test.ts dört testi sendMessage'i sahte vi.fn() ile değiştiriyordu). Artık 12 karakterizasyon testiyle kilitli: URL biçimi, phoneNumberId kodlaması, wamid öneki, HTTP/hata kodları, sürüm çözümü, sır sızıntısı yokluğu ve tek-istemci kilidi.",
      "⚠️ Meta'ya gerçek gönderim sırlar girilene dek doğrulanamadı (U09 bekliyor). Fonksiyon açılıyor ve handler'a ulaşıyor; deploy sonrası iki smoke çağrısıyla (400 + 409) kanıtlanabilir.",
      "KANIT: 12 test yeşil · 6 mutasyon 6/6 yakalandı · tam test takımı 454 dosya / 3760 test yeşil · TypeScript temiz · check:dead 0 · verify:text 1998 dosya.",
    ],
  },
  {
    id: "20261004-grup-verisi-tamamlandi",
    date: "4 Ekim 2026",
    title: "Grup dizini verisi tamamlandı — iki grup geçici olarak dizinden çıktı (davet linkleri boş)",
    items: [
      "DİZİNDE NE DEĞİŞTİ: Herkese açık grup dizini 10 yerine 8 grup gösteriyor. 'HCD - Bilinç Çözümleme' ve 'SHAMAN Koçluk' gizlendi: ikisinin de davet linki hiç girilmemişti, yani dizinde görünseler de kimse katılamıyordu.",
      "BU BİR SİLME DEĞİL: Gruplar sistemde duruyor, yalnız yayından alındı. Davet linki girilince yeniden yayına alınabilirler. Sahiplerinden link istemek ayrı bir iş ve insan eliyle yapılacak.",
      "GÖNDERENLERE OTOMATİK MAİL GİTMEDİ — bilerek: Normalde bir grup 'link ölü' sebebiyle gizlenince gönderene bildirim maili gider. Bunu ölçtük: kapatmasaydık bu iki kişiye 'linkiniz çalışmıyor' maili gidecekti. Oysa bu gruplar hiç link almamıştı, yani mail yanlış bir şey söylerdi ve gerçek kişilere otomatik mail atmak kararlaştırılmamıştı. Geri alınan bir deneyle doğrulandı: koruma olmadan 1 mail kuyruğa düşüyor, koruma ile 0.",
      "DİĞER İKİ KARAR UYGULANDI: 'AI Legion' artık 'Meslek & Kariyer' kategorisinde. 'TED InnoVenture' Türkiye (ülke geneli) olarak işaretlendi; Ankara Koleji/TED mezun tabanı Türkiye merkezli kabul edildi.",
      "KALAN DURUM: 10 grubun hiçbiri artık 'Diğer' kategorisinde değil; 4 grup bilerek ülkesiz (gerçekten global). Eski ülke/şehir metin alanlarına dokunulmadı. Kabul testi 10/10 yeşil; testin boş olmadığı da uygulamadan önce 9 maddenin kırmızı düşmesiyle kanıtlandı.",
    ],
  },
  {
    id: "20261004-tavsiye-inceleme-borcu-kapatildi",
    date: "4 Ekim 2026",
    title: "Tavsiye incelemesinin ertelenen 7 önerisi aynı gün kapatıldı — “borç satırı” kalmadı",
    items: [
      "DÜZELTME: Bir önceki kayıtta incelemenin 7 düşük öncelikli önerisinin borç olarak ertelendiği yazıyordu — tamamı bu turda KAPATILDI, KALANLAR’daki borç satırı boşaltıldı.",
      "KULLANICIYA GÖRÜNEN: (1) Yanıtını göndermiş üye artık boş form görmüyor — “Yanıtın gönderildi” durumu çiziliyor; ikinci yanıt denemesi teknik hata yerine tek Türkçe mesajla reddediliyor (“Bu talebe yanıtını zaten gönderdin”). (2) Bildirim maillerinin düz-metin sürümünde paragraf araları geri geldi (tek blok yazı düzeldi).",
      "ALTYAPI: Mail kuyruğu artık TANIMADIĞI olay tipinde satırı yakmıyor — işleme almayı bırakıp beklemeye alıyor ve gönderim kodu güncellenince satır KENDİLİĞİNDEN gidiyor (geçmişte yaşanan “sessizce hiç gitmedi” sınıfına karşı oto-onarım). Kalıcı kural kayda geçti: yeni olay tipinde önce gönderim kodu dağıtılır, sonra veritabanı değişikliği.",
      "TEMİZLİK: Ölçüsüz yeniden-yenileme yapan sorgulara açık önbellek pencereleri kondu (sekme odağında gereksiz veritabanı taraması kesildi); hiç kullanılmayan dışa-aktarımlar ve çağıransız filtre dalları budandı; önbellek anahtarındaki çıplak sayı tek sabite bağlandı (kayma testiyle kilitli).",
      "KANIT: SQL kabulü 14/14 (ikinci yanıt artık TEK kodla) · 6 mutasyon 6/6 yakalandı · tam test takımı 453 dosya / 3748 test yeşil · mail kuyruğu dağıtımı canlıya yenilendi.",
    ],
  },
  {
    id: "20261004-erisim-logu-incelemesi",
    date: "4 Ekim 2026",
    title: "Kapatılan güvenlik açıkları kötüye kullanılmış mı? 90 günlük erişim logu tarandı — kanıt YOK",
    items: [
      "SONUÇ: 90 günde (6 Temmuz – 4 Ekim) 2.167.303 isteğin tamamı tarandı. Sızdırılan üye verisi tablosuna giden 39 isteğin HEPSİNİN hesabı çıktı ve hiçbiri dışarıdan değil. Anonim erişim izi YOK.",
      "39 İSTEĞİN DÖKÜMÜ: 25'i Supabase panelinden tabloya bakılması (beş ayrı seferde, her biri birebir aynı imza — önce satır sayımı, sonra 50'şerlik dört sayfa, hepsi bir saniye içinde) · 1'i Supabase'in kendi yedekleme servisi (kimliği user-agent'ında yazıyor) · 1'i bir envanter taraması · 12'si 3 Ekim'deki kendi güvenlik doğrulamamız.",
      "ÜRKÜTÜCÜ GÖRÜNÜP AYDINLANAN BULGU: 26 Eylül'deki tek istek ilk bakışta hedefli bir okuma gibi duruyordu. Çevresine bakılınca üç dakikada 301 istekle veritabanındaki HER tabloyu ve HER fonksiyonu alfabetik sırayla gezen bir tarama olduğu görüldü — sızan tablo hedeflenmemiş, sıradaki kalem olarak bir kez okunmuş. İçinde harita eklentisinin iç fonksiyonları bile var; bir saldırgan bunları taramaz. Ayrıca istekler ayrıcalıklı değildi (10 tanesi reddedildi), yani 'neye erişilebiliyor' diye bakan bir denetim profili.",
      "ÖZGEÇMİŞLER: Aynı taramada özgeçmiş/kariyer deseni de sayıldı — 114 isteğin tamamı 1 ve 3 Ekim'de, yani kariyer modülünün geliştirildiği günlerde. Dışarıdan erişim izi çıkmadı.",
      "⚠️ BU İNCELEMENİN SINIRI (abartmamak için): Loglar en fazla 90 gün geriye gidiyor. Söz konusu tablo 9 Haziran'da yaratıldı, yani ilk ~27 gün kapsam DIŞINDA ve o dönem hakkında hiçbir şey söylenemez. Ayrıca log satırları IP veya anahtar kimliği taşımıyor; teşhisler desen kanıtına dayanıyor. Yani 'kesinlikle sızmadı' denemez — ama bildirim gerektiren bir ihlal bulgusu da YOKTUR.",
      "📌 TEK AÇIK SORU: 26 Eylül akşamı 19:11 (Berlin) civarında bir envanter/şema taraması çalıştırdınız mı, ya da Supabase panelinde API dokümanları sayfasını açtınız mı? Hatırlarsanız son belirsizlik de kapanır. Ayrıntılı rapor: docs/operations/2026-10-04-erisim-logu-incelemesi.md",
    ],
  },
  {
    id: "20261004-tavsiye-inceleme-duzeltmeleri",
    date: "4 Ekim 2026",
    title: "Tavsiye modülünde bağımsız inceleme turu: 1 kritik güvenlik kusuru + 8 mantık kusuru kapatıldı",
    items: [
      "GÜVENLİK (kritik, kapatıldı): Tavsiye eşleşme mailinin konusu, talep başlığını HAM taşıyordu — başlığa gizli satır-sonu karakterleri gömen bir kullanıcı, profesyonellere giden maile sahte “Yanıtla:” adresi gibi başlıklar enjekte edebilirdi (oltalama vektörü). İki katmanlı kilit kondu: şablon ve mail altyapısı kontrol karakterlerini tek noktadan siliyor; saldırı senaryolu test eklendi. Düzeltme canlıya deploy edildi.",
      "KURAL NETLEŞTİ: Talep SAHİBİ kendi talebini artık yanıtlayamaz (veritabanı kuralı + form sahibiye hiç çizilmiyor). Sebep: sahibin kendi “yanıtı” talebi ‘yanıtlanmış’a çevirip listeden düşürüyordu — kimse gerçekten yanıtlamadan. Yeni hata kodu tek Türkçe mesajla eşleşiyor.",
      "ROZET DÜRÜSTLÜĞÜ: Yanıtlardaki “Profesyonel” rozeti artık dizin-görünürlük kurallarıyla birebir aynı süzgeçten geçiyor — dizin dışında kalmış (ör. özel görünürlüklü veya yönetici/test) hesaplar herkese açık rozet ALAMIYOR. Canlı kabul, ayırt edici fixture ile ölçüldü (14/14).",
      "FORM DÜZELTMELERİ: Tavsiye formuna Kategori alanı eklendi (eşleştirmenin en güçlü sinyali formdan toplanmıyordu — ölüydü) ve Ülke alanı serbest metinden kod seçiciye çevrildi (“Almanya” yazısı eşleştirmede asla tutmuyordu; artık Almanya=DE). Hata mesajları kullanıcının dilinde kalıyor (teknik katmanda kaybolup genel mesaja düşme kusuru giderildi).",
      "PERFORMANS/GÜRÜLTÜ: Eşleşen profesyoneller sorgusu anonim ziyaretçide hiç açılmıyor (üyelere özel fonksiyon için garantili hata + gereksiz tekrar denemeleri üretiliyordu).",
      "KANIT: Bağımsız inceleme 4 commit’i taradı (güvenlik/performans/iş mantığı/dağıtım/kopya/ölü kod — 6 uzman geçişi); düzeltmeler sonrası 6 mutasyon 6/6 yakalandı, canlı SQL kabulü 14/14, tam test takımı 453 dosya / 3741 test yeşil. İncelemenin 7 düşük öncelikli önerisi KALANLAR’a borç satırı olarak işlendi (bilinçli erteleme).",
    ],
  },
  {
    id: "20261004-ozgecmis-dosyalari-silindi",
    date: "4 Ekim 2026",
    title: "Üç özgeçmiş dosyası yedeklenip kalıcı olarak silindi — hiçbir kayıt onlara işaret etmiyordu",
    items: [
      "NE YAPILDI: Eski özgeçmiş alanındaki 3 PDF önce güvenli bir yere indirildi (3/3 doğrulandı: dosya boyutları ve PDF imzaları birebir eşleşti), sonra depolamadan kalıcı olarak silindi. Alan artık tamamen boş.",
      "NEDEN SİLME, NEDEN SADECE AD DEĞİŞTİRME DEĞİL: Ölçüm teşhisi değiştirdi. Bu dosyalara işaret eden CANLI hiçbir kayıt yok — kaynak listesindeki 221 kaydın tamamı 'Link' türünde ve hiçbirinde depolama yolu yazmıyor. Yani dosyalar öksüzdü: kimse açamıyor, hiçbir ekran kullanmıyordu. Adını değiştirmek eski bağlantıyı öldürürdü ama üç gerçek kişinin özgeçmişi depoda kalmaya devam ederdi.",
      "RİSK NEYDİ: Bu alan bir süre herkese açık işaretliydi ve 2026-09'da raporlanmış ama kapatılmamıştı. Bugün erken saatte kapatıldı; ancak hızlandırma katmanındaki kopyalar süresi dolana kadar erişilebilir kalıyordu ve bağlantı dışarıyla paylaşıldıysa çalışmaya devam edebilirdi. Dosya silinince o kopyaların da bir değeri kalmadı.",
      "HİÇBİR ŞEY BOZULMADI: Dosyaları gösteren ekran yok, indirme yolu yok, referans veren kayıt yok — ölçülerek doğrulandı. Silme sonrası üç adresin üçü de erişilemez döndü (önbellek atlatılarak kontrol edildi).",
      "YEDEK NEREDE: Dosyalar repo DIŞINDA, yerel bir klasörde duruyor. Repoya veya buluta konmadı; kişisel veri taşıdıkları için bilerek böyle yapıldı. Gerekirse geri yüklenebilir.",
    ],
  },
  {
    id: "20261004-haftalik-sehir-ozeti-canli-dogrulama",
    date: "4 Ekim 2026",
    title: "Haftalık şehir özeti canlıda kanıtlandı — gerçek mail gitti; gönderim anahtarı bu akşam AÇILDI",
    items: [
      "BUGÜN GELEN MAIL: “Haftalık şehir özeti (2026-W40): Dortmund — 1 yeni içerik” konulu mail bu doğrulamanın GERÇEK gönderimidir (test kutusuna plus-adresle düştü). Kuyruk satırı ölçüldü: status=sent + dolu sent_at + boş hata + alıcı 1. Test verisi (üye/takip/talep/satır) ölçümden sonra silindi, kalıntı 0 doğrulandı.",
      "BULUNAN GERÇEK KUSUR (kapatıldı): İlk denemede mail GİTMEDİ — satır “alıcı yok” diye atlandı. Sebep ölçüldü: gönderim işlevi alıcı adresini kullanıcı yönetim API’sinden çözmeye çalışıyordu ve ortamdaki yeni tip gizli anahtar o API’de reddediliyor (401). Kanıtlı grup bildirimi desenine geçildi: adres artık kuyruğa yazım anında veritabanından çözülüyor; adresi olmayana satır hiç açılmıyor. İşlev yeniden deploy edildi ve mail ikinci denemede gitti. Bu, canlı doğrulama turlarının neden “kod yazıldı” ile yetinmediğinin ders kitabı örneği: birim testler yeşilken hat gerçek gönderimde ortaya çıktı.",
      "✅ KARAR VERİLDİ (bu akşam): Haftalık özetin genel gönderim anahtarı AÇILDI. Her pazartesi 05:00’te, yalnız takip ettiği şehirde o hafta yeni etkinlik/tavsiye olan üyelere tek özet maili gider (içeriği olmayana mail YOK, boş özet YOK, hafta başına kullanıcı başına en fazla 1). Şu an takip eden gerçek üye 0 — ilk hafta kimse mail almaz; özellik duyuruldukça özetler başlar.",
      "KANIT: elle tetikleme → 1 satır (ikinci çağrı 0 — hafta dedupe’si) · gerçek drenaj → sent:1 · yeni kabul K1–K6 6/6 (adres çözümü, adressize satır yok, dedupe, anahtar kapalıyken 0, içeriksiz şehre 0) · M25 kabulü temiz canlıda 10/10 (geriye dönük bozulma yok) · 6 mutasyon 6/6 yakalandı · tam test takımı 452 dosya / 3731 test yeşil.",
      "FAZ 4 BÖYLECE TAMAM: takip tablosu + kuyruk tipi (M24) · kuyruğa yazma + haftalık cron (M25) · takip yönetimi ekranı + mail şablonu + gönderim kablolaması (M26) · uçtan uca canlı kanıt (M27). Sırada blokeli işler var: WhatsApp (U09 sırları), SMS (U06 sağlayıcı), grup içe aktarma (U07 CSV) — hepsi kullanıcı girdisi bekliyor.",
    ],
  },
  {
    id: "20261004-eski-pano-yalniz-yoneticiye",
    date: "4 Ekim 2026",
    title: "Eski pano tabloları artık yalnız yöneticilere açık (173 üyenin erişimi kaldırıldı)",
    items: [
      "NE DEĞİŞTİ: Bugün erken saatte bu tablolar anonim erişime kapatılmıştı, ama GİRİŞLİ HERKES hâlâ görebiliyordu. Artık yalnız yöneticiler görüyor.",
      "ÖLÇÜM: Sistemde 175 kullanıcı var, bunların 2’si yönetici. Yani 173 sıradan üye, arayüzde göremedikleri hâlde teknik yoldan ~1.650 kayda (toplantı notları, yol haritası, kişi adları, özgeçmiş kayıtları) erişebiliyordu.",
      "NEDEN GÜVENLİ: Bu sayfalara arayüzden zaten yalnız yönetici girebiliyordu. Yapılan şey, veritabanı kuralını arayüz kapısıyla aynı yere getirmek — davranış değişmedi, yalnız arka kapı kapandı.",
      "DOĞRULAMA: Sıradan bir üye kimliğiyle ölçüldü, toplantı notlarında ve özgeçmiş kayıtlarında 0 satır görüyor. Yönetici kimliğiyle 470 toplantı notunun tamamı görünüyor.",
      "TUTARLILIK: Komuta Merkezi zaten bu seviyedeydi; eski pano tabloları da onunla aynı hizaya getirildi. Artık “hangi tablo hangi seviyede” diye sormak gerekmiyor.",
    ],
  },
  {
    id: "20261004-eski-pano-tablolari-kapatildi",
    date: "4 Ekim 2026",
    title: "Güvenlik: eski pano tablolarının tamamı dışarıya kapatıldı (~1.650 kayıt, 15 tablo)",
    items: [
      "NE OLDU: Komuta Merkezi kapatıldıktan sonra aynı desen tarandı ve Komuta Merkezi ÖNCESİ “eski pano” tablolarının tamamının aynı durumda olduğu görüldü — her birinde doğru çalışan kuralın yanında, herkese okuma veren eski bir kural duruyordu.",
      "KAPSAM: ~1.650 kayıt, 15 tablo. Toplantı notları (470), eski eşleme kayıtları (592), kaynak girdileri (221 — kişi adları, LinkedIn adresleri, dosya yolları), iç yol haritası (188), görevler (122+9), özgeçmiş kayıtları (3 — ad, soyad, rol, dosya yolu).",
      "⚠️ İKİSİNDE YAZMA DA AÇIKMIŞ: Görevler ve eski eşleme tablosuna anonim olarak kayıt eklenebiliyor, değiştirilebiliyordu. Bunlardan birinin kural adı “sadece girişli kullanıcı” anlamına geliyordu ama kapsamı anonimi de içeriyordu — ad yanıltıcıydı.",
      "DOĞRULAMA: Kapatmadan önce 17 açık kural vardı. Sonrasında anonim okuma altı tabloda da 0 kayıt döndürüyor, yazma denemesi “erişim kuralı ihlali” hatası veriyor.",
      "HİÇBİR ŞEY BOZULMADI: 15 tablonun tamamının tek kullanıcısı yönetici panelidir. Girişli kullanıcı davranışı aynen korundu (ölçüldü) ve beş genel sayfa kontrol edildi, hepsi normal açılıyor.",
      "AÇIK KALAN: Bu tabloları girişli HERKES görebiliyor — yalnız yöneticiler değil. Bunu daraltmak ayrı bir karar: hangi yönetici sayfalarının yönetici olmayan ekip üyelerince kullanıldığı ölçülmeden daraltmak paneli düşürebilir.",
    ],
  },
  {
    id: "20261004-haftalik-sehir-ozeti-takip-yonetimi",
    date: "4 Ekim 2026",
    title: "Haftalık şehir özeti hazırlığı: şehir takibi yönetimi Bildirim Tercihleri'nde (gönderim şimdilik KAPALI)",
    items: [
      "NE GELDİ: /settings/notifications sayfasına “Haftalık şehir özeti” kartı eklendi. Üye, geo kataloğundan şehir seçip takip eder (ülke → şehir arama, Türkçe duyarsız filtre); takiplerini çip olarak görür ve tek tıkla kaldırır. Tavan üye başına 10 şehir (eşik veritabanı ayarından gelir, koda sabit gömülü değil; ayna testi kilitliyor).",
      "DÜRÜST AÇ/KAPA: Kartta ÇALIŞMAYAN bir aç/kapa düğmesi YOK — özetin kullanıcının gözündeki anahtarı takip listesinin kendisi: takip varsa özet var, takip yoksa özet yok (içeriği olmayana mail zaten gönderilmiyor). Platform geneli gönderim anahtarı şu an KAPALI ve kart bunu AÇIKÇA yazıyor; canlı uçtan uca kanıt (M27) tamamlandığında İNSAN kararıyla açılacak — otomatik hat kapalı doğar kuralı.",
      "MAIL ŞABLONU HAZIR: Özet maili hafta + şehirler + yeni etkinlik/tavsiye bağlantılarını taşır; YALNIZ başlık ve link çizer, payload’a sızabilecek iletişim alanları bilinçli olarak çizilmez (sızıntı testiyle kilitli). Eşleşmeyen şehirler mailde görünür kalır (Münih↔München gibi sözlük farkları sessizce yutulmaz, görünür ki veri onarılsın).",
      "GÖNDERİM HATTI: Alıcı adresi kuyruğa YAZILMAZ — gönderim anında kullanıcı kimliğinden çözülür (kuyrukta bayat adres riski yok). Hat beş parça (kuyruk kısıtı · ayar anahtarı · eşleme · şablon · alıcı çözümü) ve beşi de aynı işte kuruldu; edge function DEPLOY EDİLDİ (dünkü ders: commit ≠ canlı). Pazartesi 05:00 UTC cron işi M25’te kurulmuştu, anahtar kapalı olduğu için etkisiz.",
      "KANIT: 22 yeni test (7 api sözleşme + 5 kart + 9 şablon/kablolama + 1 entegrasyon); kod 6 yerden bilerek bozuldu (mutasyon: tavan sırası, kimlik kaynağı, eşik aynası, tavan kapısı, şablon sızıntısı, ayar eşlemesi) ve testler her seferinde yakaladı. Tam test takımı 452 dosya / 3731 test yeşil.",
      "KALAN: M27 canlı uçtan uca kanıt — takip + taze içerik tohumlanır, özet elle tetiklenir, kuyruk satırında status='sent' + dolu sent_at ölçülür (“cron yeşil” kanıt sayılmaz); kanıttan sonra gönderim anahtarının açılması kullanıcı kararına sunulur.",
    ],
  },
  {
    id: "20261004-komuta-merkezi-disariya-kapatildi",
    date: "4 Ekim 2026",
    title: "Güvenlik: Komuta Merkezi’nin tamamı dışarıya açıkmış — kapatıldı (1.761 kayıt)",
    items: [
      "NE OLDU: Komuta Merkezi tablosunda, herkese tam yetki veren iki eski erişim kuralı kalmış. Sonuç: iç yol haritamız, toplantı notlarımız, görev detaylarımız ve sorumluları GİRİŞ YAPMADAN okunabiliyordu — ve aynı kural yüzünden değiştirilebilir, silinebilir durumdaydı.",
      "KAPSAM: 1.761 kaydın tamamı (495 aktif + 1.158 arşiv). Başlık, açıklama metni ve atanan kişi dahil.",
      "DOĞRULAMA — ÖNCE: Gerçek anonim istek 1.761 kaydın tamamını listeledi ve örnek bir kaydın başlığını, açıklamasını, sorumlusunu döndürdü. Yazma denemesi de reddedilmedi.",
      "DOĞRULAMA — SONRA: Aynı okuma isteği artık 0 kayıt döndürüyor. Yazma denemesi “erişim kuralı ihlali” hatası veriyor ve hiçbir kayıt oluşmuyor. Özet görünümü de dışarıya kapandı.",
      "NEDEN AÇIK KALMIŞ: Tabloda hem doğru yönetici kuralları hem de eski “herkese açık” kuralları bir arada duruyordu. Bu kurallar birbirini TAMAMLAR, kısıtlamaz — yani açık olan kural, yönetici kurallarını tamamen anlamsız kılıyordu.",
      "PANEL BOZULMADI: Yönetici hesabıyla ölçüldü, 1.761 kaydın tamamı görünmeye devam ediyor. Sıradan bir üye ise hiçbir kayıt göremiyor.",
    ],
  },
  {
    id: "20261004-tavsiye-faz2-canli-dogrulama",
    date: "4 Ekim 2026",
    title: "Tavsiye modülü canlıda doğrulandı — gönderilen “M23 doğrulama talebi” maili gerçek bir testtir",
    items: [
      "NE YAPILDI: Faz 2’nin uçtan uca canlı doğrulaması tamamlandı. (1) Anonim ziyaretçi tavsiye listesini iletişim bilgisi OLMADAN okuyabiliyor (HTTP 200, sıfır iletişim kolonu ölçüldü). (2) Test üyesi canlıda talep açtı — talep BİLEREK hiçbir üyeyle eşleşmeyen konumla açıldı, gerçek üyelere bildirim GİTMEDİ (yan etki 0 ölçüldü). (3) Eşleşme bildirimi GERÇEK gönderim hattından geçti: mail Burak’ın adresine ulaştı, kuyruk satırı status=sent + dolu sent_at + boş hata ile ölçüldü. (4) Kilitli Pro iletişim kartının ilgi kaydı canlıda satır üretti.",
      "BUGÜN GELEN MAIL: “Sana uyan bir tavsiye talebi: M23 doğrulama talebi” konulu mail bu doğrulamanın TEST gönderimidir — gerçek bir talep değildir, ölçümden sonra tüm test verisi silindi (kalıntı 0 doğrulandı).",
      "BULUNAN EKSİK (kapatıldı): İlk gönderim denemesi düştü — canlıdaki edge function ESKİ sürümdü (dünkü kod commit’lenmiş ama deploy edilmemişti). `supabase functions deploy` koşuldu, ikinci denemede mail gitti. Ders: “commit ≠ canlı”; bildirim hattı artık gerçek gönderimle kanıtlı.",
      "KANIT: 4/4 ölçüm + temizlik 6/6 kalıntı sıfır. Kuyruk satırında attempts=2 dürüst tarihi durur (1. deneme deploy öncesi düştü, 2. deneme sent). Faz 2 (M17–M23) bu turla TAMAM.",
      "KALAN: Ön yüz (liste/talep/yanıt sayfaları + Cadde kartı + kilitli kart) frontend deploy’uyla canlıya çıkar; bildirim hattı ÇALIŞIYOR (deploy edildi). Sırada Faz 4: haftalık şehir özeti (M24–M27).",
    ],
  },
  {
    id: "20261004-ozgecmis-kovalari-kapatildi",
    date: "4 Ekim 2026",
    title: "Özgeçmiş dosyaları artık herkese açık değil (Eylül’de raporlanan risk kapatıldı)",
    items: [
      "NE DEĞİŞTİ: İçinde 3 özgeçmiş bulunan eski dosya alanı “herkese açık” işaretliydi. Bağlantısı eline geçen herkes, giriş yapmadan özgeçmiş indirebiliyordu. Kapatıldı.",
      "⚠️ BU RİSK EYLÜL AYINDA RAPORLANMIŞTI ama kapatılmamıştı (“taşımadan önce kapatılmalı” notuyla). Bugün kapatıldı.",
      "SIZINTI DEĞİLDİ: Dosya listesi dışarıya kapalıydı, yani dosya adları tahmin edilemiyordu. Risk, bağlantının bir şekilde paylaşılması durumundaydı — tarayıcı geçmişi, sunucu kaydı, ekran paylaşımı.",
      "DOĞRULAMA: Kapatmadan önce gerçek anonim istek 1,5 MB’lık PDF’i indirdi. Kapattıktan sonra üç dosyanın üçü de “hatalı istek” veriyor.",
      "HİÇBİR EKRAN BOZULMADI: Uygulama bu dosyaları zaten süreli imzalı bağlantıyla açıyordu; o yöntem kapalı alanlarda da çalışır. Boş olan iki alan (özgeçmiş ve ARGE) da şimdiden kapatıldı ki ileride yüklenen ilk dosya açıkta kalmasın.",
      "⚠️ AÇIK KALAN TEK NOKTA: Daha önce indirilmiş veya önbelleğe alınmış kopyalar, dağıtım ağının saklama süresi dolana kadar erişilebilir kalabilir. Bu bağlantılar dışarıyla paylaşıldıysa dosyaların yeni adla yeniden yüklenmesi gerekir.",
      "DOKUNULMAYANLAR: Profil fotoğrafları, Cadde görselleri, haber görselleri gibi gerçekten herkese açık olması gereken alanlar aynen kaldı.",
    ],
  },
  {
    id: "20261004-veri-sizintisi-kapatildi",
    date: "4 Ekim 2026",
    title: "Güvenlik: anonim erişime açık kalmış bir tablo kapatıldı (938 kayıt)",
    items: [
      "NE OLDU: Haziran ayındaki üye veri taşımasından kalan bir denetim günlüğü tablosu, satır güvenliği açılmadan ve dışarıya kapatılmadan kalmış. Sonuç: 938 kaydın tamamı, sitenin herkese açık anahtarıyla GİRİŞ YAPMADAN okunabiliyordu.",
      "SIZAN VERİ: Üye kimlik numaraları ve kayıt e-postaları. ⚠️ Bu e-postaların bir kısmı WhatsApp kayıtlarından geliyor ve biçimleri gereği TELEFON NUMARASI içeriyor. Ayrıca anonim kullanıcı bu tabloya yazabiliyor ve kayıt silebiliyordu.",
      "DOĞRULAMA: Varsayım değil, ölçüm. Kapatmadan önce gerçek bir anonim istek atıldı: 938 satırın tamamı döndü. Kapattıktan sonra aynı istek “yetki yok” hatası veriyor; yazma denemesi de reddediliyor.",
      "YAPILAN: Tablo SİLİNMEDİ (bir göçün denetim izi, neden-niçin sorusunun cevabı orada). Erişim yalnız sunucu tarafına indirildi: satır güvenliği açıldı, hiçbir erişim kuralı tanımlanmadı, dışarıya verilen yetkiler geri alındı. Uygulamada bu tabloyu kullanan hiçbir kod yok, yani hiçbir şey bozulmadı.",
      "NEDEN GÖZDEN KAÇMIŞ: Tablo tek seferlik, geçici bir iş ürünü olarak açılmış. Geçici tabloların da dışarıdan görünür olduğu düşünülmemiş.",
      "TEKRARLAMAMASI İÇİN: Artık kalıcı bir tarama betiği var. Veritabanındaki 285 tablodan 284’ü korumalı; geriye kalan tek tablo harita koordinat sistemleri referansı (hassas veri yok, 0 satır). Benzer bir tablo açılırsa bu tarama onu gösterir.",
    ],
  },
  {
    id: "20261004-tavsiye-eslesme-bildirimi-ve-kilitli-pro-karti",
    date: "4 Ekim 2026",
    title: "Tavsiyede eşleşme bildirimi çalışıyor + kilitli “Pro” iletişim kartı (deploy kuyruğunda)",
    items: [
      "NE GELDİ (bildirim): Üye bir tavsiye talebi açtığında, uzmanlık alanı/konumu taleple EŞLEŞEN profesyonellere (en iyi 5) otomatik e-posta bildirimi gidiyor: “Sana uyan bir tavsiye talebi var” + talebin adı, şehri ve bağlantısı. Bildirim hattının beş parçası da (kuyruk kısıtı, ayar anahtarı, gönderim eşlemesi, şablon, alıcı çözümü) tek işte kuruldu — parça eksikliği yüzünden sessizce mail gitmeme riski kapatıldı.",
      "KİME GİTMEZ: Talebi açanın kendisine, erişimi kısıtlanmış (banlı) kullanıcılara ve taleple HİÇ eşleşmeyen (skor 0) üyelere bildirim gitmez — eşleşmeyeni spamlemiyoruz. Ölçüldü: canlı kabul 13/13 (geri alınan işlem).",
      "GİZLİLİK: Bildirim maili talep sahibinin iletişim bilgisini TAŞIMAZ — mail yalnız talebin kimliğini taşır. Doğrudan iletişim, talebin sayfasındaki KİLİTLİ kartın arkasında: “Talep sahibine doğrudan ulaş — ücretli yüzey yakında”.",
      "NE GELDİ (kilitli kart): Tavsiye detayında, giriş yapmış ve talebin sahibi olmayan kullanıcı kilitli iletişim kartını görür. “İlgileniyorum” deyince ilgi kaydı düşer (feature_interest ‘pro.inbox’). FİYAT/ÖDEME UYDURULMADI (Stripe işi parkta) — hangi ücretli özelliğin önce yapılacağına bu ilgi birikimi karar verecek; aynı kişi iki kez sayılmaz, kanıt satırı silinmez.",
      "KANIT: Canlı kabul 13/13 + M17 geri-dönüş kontrolü 11/11 (talep açma davranışı bozulmadı) · 6 mutasyon (bildirim dışlamaları, beyaz liste, kart anahtarı, yerleşim) testlerce yakalandı · tam test takımı 449 dosya / 3709 test yeşil. Bir mutasyon kabul betiğinin çökme zafiyetini ortaya çıkardı: “betik patladı” ile “iddia düştü” ayrıştırıldı, kabul çökme-dayanımlı hale getirildi.",
      "KALAN: M23 — Faz 2 uçtan uca canlı doğrulama (anonim liste → talep → bildirim GERÇEKTEN gönderildi: outbox satırında status='sent' + dolu sent_at ölçülecek, “kuyruğa yazıldı” kanıt sayılmayacak). Kart ve bildirim bir sonraki deploy’da canlıda.",
    ],
  },
  {
    id: "20261004-cadde-akisinda-tavsiye-karti",
    date: "4 Ekim 2026",
    title: "Cadde akışında “Tavsiye İste” kartı — topluluk tavsiyeleri artık akışta görünür (deploy kuyruğunda)",
    items: [
      "NE GELDİ: Cadde akışının üstünde (kapsam şeridi ile paylaşımların arasında) yeni bir “Tavsiye İste” kartı var. En yeni 3 açık tavsiye talebini başlık + şehirle listeler, tıklayınca talep detayına (/tavsiye/:id) gider; “Tüm tavsiyelere git” düğmesi /tavsiye listesini açar. Kart giriş yapmamış ziyaretçiye de görünür.",
      "GİZLİLİK: Kartta talebin GÖVDE metni BİLEREK gösterilmez — yalnız başlık ve şehir. Sebep: gövde serbest metin olduğundan kullanıcı yanlışlıkla telefon/e-posta yazabilir; akışta bu metin çizilseydi iletişim sızıntı yüzeyi açılırdı. Test kilidi var: gövdeye yazılmış telefon/e-posta DOM’a sızarsa test düşer.",
      "CADDE SIRALAMASI DEĞİŞMEDİ (ölçüldü): Kart yalnız görünürlük sağlar — Cadde’nin bant/skor sıralamasına ve hedefleme kurallarına dokunmaz. Sıralama/kompozisyon dosyaları bu işte DEĞİŞMEDİ; kart akış listesinin dışında sabit konumda durur ve bunu kaynak kilidi testleri doğruluyor. Cadde karakterizasyon testlerinin tamamı değişmeden yeşil.",
      "DAYANIKLILIK: Kart kendi verisini kendi çeker; tavsiye servisi hata verse ya da yavaşlasa bile Cadde akışını BLOKLAMAZ — bu durumda kart yalnız “Tüm tavsiyelere git” bağlantısına düşer.",
      "KANIT: 8 yeni test (4 davranış + 4 bulaşmazlık kilidi); kod 6 yerden bilerek bozuldu (mutasyon) — gövde sızıntısı, hata çökmesi, kartın akış listesine taşınması/silinmesi, link bozma, liste gizleme — testler her seferinde yakaladı. Tam test takımı 447 dosya / 3698 test yeşil.",
      "KALAN: Kilitli profesyonel gelen kutusu (M22) ve Faz 2 canlı doğrulama (M23) sırada. Kart bir sonraki frontend deploy’unda canlıya çıkar.",
    ],
  },
  {
    id: "20261004-dogrulama-rozeti-tek-kaynaga-baglandi",
    date: "4 Ekim 2026",
    title: "Doğrulama rozeti tek kaynağa bağlandı — kurumsal onaylar artık dizine gerçekten yansıyor",
    items: [
      "BULUNAN KUSUR: Kayıtlarda doğrulama bilgisi İKİ ayrı alanda tutuluyordu. Yönetici ekranları ve yeni kurumsal doğrulama akışı birini yazıyordu, herkese açık dizin rozetini ise ÖTEKİ alan çiziyordu. Sonuç: bir yönetici kurumsal doğrulamayı onayladığında dizinde HİÇBİR ŞEY değişmiyordu — hata da vermiyordu, sadece olmuyordu.",
      "İKİNCİ KUSUR: İki grup kaydı dizinde “doğrulanmış” rozetiyle görünüyordu ama aslında kimse onları doğrulamamıştı; değer eski içe aktarmadan kalmıştı. Rozetleri kaldırıldı. Gerçekten doğrulanmış 7 kayıt aynen korundu.",
      "KÖK NEDEN: Rozeti besleyen alanı sistemde YAZAN kimse yoktu (ne bir ekran, ne bir fonksiyon). Yani içe aktarma gününden donmuş bir değerdi ve herkese açık dizin ona güveniyordu.",
      "ÇÖZÜM: O alan artık türetiliyor — doğrulama durumu neyse rozet de odur, elle değiştirilemez. Bir daha ayrışması yapısal olarak mümkün değil.",
      "ETKİ: Bundan sonra yönetici bir kurumsal doğrulamayı onayladığında rozet dizinde anında görünür. Ayrışan kayıt sayısı: 0.",
    ],
  },
  {
    id: "20261004-komuta-merkezi-arsiv-dalgasi",
    date: "4 Ekim 2026",
    title: "Komuta Merkezi temizlendi — 1.635 kayıt 495’e indi (hiçbir şey silinmedi)",
    items: [
      "NE DEĞİŞTİ: Komuta Merkezi’nde 1.635 aktif kayıt vardı ve içinde bir şey bulmak pratik olarak imkânsızdı. Başlanmamış toplantı notları ve tamamlanmış işler arşive alındı; panoda artık 495 kayıt var.",
      "SİLME DEĞİL, ARŞİV: Hiçbir satır silinmedi. Arşivlenenler kendi listesinde duruyor ve tek tek geri alınabilir. Toplam arşiv 1.158 kayda çıktı.",
      "DOKUNULMAYANLAR: “Devam ediyor” durumundaki her kayıt ve ACİL işaretli her kayıt yerinde bırakıldı — bunlar açık iş. Ölçüldü: bu turda yanlışlıkla arşivlenen acil/devam eden kayıt sayısı SIFIR.",
      "PANODA KALAN: 451 bekleyen toplantı notu · 19 bekleyen/başlanmamış todo · 14 devam eden iş.",
      "SIRADAKİ KARAR: Kalan 451 bekleyen toplantı notunun ne olacağı ayrı bir karar. Planda “~150-200 kayıt kalsın” yazıyordu ama ölçüm bunun mümkün olmadığını gösterdi: kayıtların tamamı eski (en yenisi 27 Eylül, en eskisi 17 Nisan), yani “son şu kadar günü koru” diye bir ayar noktası yok. Ya hepsi arşivlenir (33 kalır) ya da olduğu gibi durur.",
      "GÜVENLİK: Arşivden önce yerel denetim notlarının (313 adet) yedeği alındı ve doğrulandı — bu notlar depoya dâhil değil ve yeniden üretim sırasında kaybolabilirdi.",
    ],
  },
  {
    id: "20261003-tavsiye-iste-modulu",
    date: "3 Ekim 2026",
    title: "“Tavsiye İste” modülü geldi — topluluktan güvenilir esnaf/sağlık/danışman tavsiyesi (deploy kuyruğunda)",
    items: [
      "NE GELDİ: Yeni ücretsiz topluluk işlevi — /tavsiye. Üyeler tavsiye talebi açar (ör. “Dortmund’da güvenilir terzi”), topluluk ve eşleşen profesyoneller yanıtlar. Talep listesi ANONİM ziyaretçiye de açık (giriş yapmadan okunur); talep açmak ve yanıtlamak giriş ister.",
      "NEREDE: Üye panelindeki hızlı eylemlere “Tavsiye iste” eklendi (Etkinlik oluştur · Grup ekle · Davet et’in yanında, 4. eylem). Ayrıca /tavsiye adresinden doğrudan erişilir. Talep detayında (/tavsiye/:id) yanıtlar ve kategori+şehir/ülkeye göre SIRALANMIŞ eşleşen profesyoneller görünür.",
      "EŞLEŞME NASIL: Bir talep için profesyoneller kategori + şehir + ülkeye göre skorla sıralanır (en alakalı önce). Eşleşme ELEMEZ, SIRALAR — kısmi eşleşen (ör. sadece aynı şehir) de listede kalır, alt sırada. Türkçe duyarsız katlama kullanılır (İstanbul/ISTANBUL aynı).",
      "GÜVENLİ/GİZLİLİK: 🔴 Eşleşen profesyoneller listesinde İLETİŞİM BİLGİSİ GÖSTERİLMEZ (e-posta/telefon sızdıran arama alanı bilinçli olarak OKUNMAZ) — yalnız herkese açık dizin adı/şehir. Kilitli profesyonel gelen kutusu (iletişim + ilgi kaydı) ayrı bir adım (M22). Yazma yalnız sunucu tarafı fonksiyonlarla (doğrudan kayıt yok); banlı kullanıcı tek noktadan (Cadde ban sistemi) otomatik reddedilir.",
      "KANIT: SQL kabul M17 11/11 + M18 9/9 (canlı, geri alınan işlem) · 25 kod testi · mutasyon 8/8 · tam test takımı 446 dosya / 3690 test yeşil. Tam suite bir gerçek kusuru yakaladı (detay sayfası SEO başlığı veri gelince güncellenmiyordu) — düzeltildi.",
      "KALAN: M21 (Cadde akışında tavsiye kartı + bileşenler) · M22 (kilitli profesyonel gelen kutusu + ilgi kaydı) · M23 (Faz 2 canlı doğrulama). Liste/talep/yanıt bu deploy’da canlıya çıkar.",
    ],
  },
  {
    id: "20261003-kurumsal-dogrulama-inceleme-ekrani",
    date: "3 Ekim 2026",
    title: "Kurumsal doğrulama inceleme ekranı geldi — belgeyi önizle, onayla/reddet (deploy kuyruğunda)",
    items: [
      "NE GELDİ: Yönetici menüsüne “Kurumsal Doğrulama” maddesi eklendi (Üyeler ve Dizin grubu, Approval Queue’nun hemen altında, madde #6). Ekranda bekleyen Seviye 2 doğrulama talepleri listeleniyor: kayıt adı, talep eden, notu ve yüklediği belgeler.",
      "NASIL ÇALIŞIR: Yönetici belgeyi imzalı (süreli) bağlantıyla önizler, sonra “Onayla” ya da “Reddet” der. Onayda kayıt doğrulanmış (verified) olur — kimin, ne zaman onayladığı kayda işlenir. Reddin sebebi ZORUNLUDUR (talep sahibi neden reddedildiğini görür); sebepsiz Ret düğmesi pasiftir.",
      "GÜVENLİK: İnceleme ekranı ve karar fonksiyonları yalnız yöneticiye açıktır (sunucu tarafı is_admin kontrolü). Belgeler dışarıya kapalı kovada durur; önizleme yalnız süreli imzalı bağlantıyla, herkese açık bağlantı üretilmez. Karar verisi (claim tipi/durumu) istemciden alınmaz, sunucuda zorlanır.",
      "KAPSAM NOTU: Bu ekran yalnız inceleme + karar verir. Doğrulama rozetinin üye arama/dizin tarafına yayılması (filtre, “doğrulanmış” etiketi) BİLEREK bu işe KONMADI — ayrı bir adım olarak planlanıyor (katalog/arama belgesine dokunulmadı).",
      "MENÜ NUMARALARI KAYDI: Yeni madde eklendiği için sonraki maddelerin numaraları birer kaydı (Feature Override 6→7, Audit Logs 7→8, …). Bot korpusu aynı turda güncellendi (92 belge, 87 gömme) — asistan bayat numara söylemez.",
      "KANIT: Canlı kabul 9/9 (geri alınan işlem — onay kaydı gerçekten verified yapıyor, ret sebebi kaydediliyor, yetkisiz/olmayan/zaten-incelenmiş talepler doğru tek hatayla reddediliyor). 17 test (10 veri katmanı + 7 ekran) yeşil; kod 6 yerden bilerek bozuldu (mutasyon) ve testler her seferinde yakaladı. Tam takım 442 dosya / 3665 test yeşil.",
      "KALAN: Doğrulama rozetinin üye tarafına yayılımı (arama filtresi + “doğrulanmış” etiketi) ayrı iş. Ekran bir sonraki frontend deploy’ında canlıya çıkar.",
    ],
  },
  {
    id: "20261003-traction-buyume-metrikleri-paneli",
    date: "3 Ekim 2026",
    title: "Admin paneline “Traction” panosu geldi — 5 büyüme metriği tek ekranda (deploy kuyruğunda)",
    items: [
      "NE GELDİ: Yönetici menüsüne yeni bir “Traction” maddesi eklendi (Genel Bakış grubu, madde #2). Panel beş büyüme metriğini gösteriyor: haftalık aktif kullanıcı · üretilen toplam içerik (tür kırılımıyla) · tavsiye yanıt oranı · davetle gelen kayıt · 30 gün geri dönüş oranı.",
      "VERİ CANLIDAN, UYDURMA YOK: Sayılar canlı veritabanındaki türetilmiş görünümlerden okunur (dün kurulan metrik altyapısı). Tavsiye yanıt oranı, tavsiye modülü (M17) gelene dek boş görünür — bu normaldir, yerine sahte bir sayı konmadı. Geri dönüş oranı da cohort boşsa “—” gösterir.",
      "GÜVENLİK: Metrik görünümleri yalnız yöneticiye açıktır (sunucu tarafı yönetici kontrolü). Anonim ve yönetici-olmayan kullanıcı hiçbir sayı görmez — panel zaten yönetici kabuğunun (AdminLayout) içinde, çift katman.",
      "MENÜ NUMARALARI KAYDI: Yönetici menüsüne yeni madde eklendiği için sonraki maddelerin sıra numaraları otomatik olarak birer kaydı (ör. “Kayıt Veritabanı” 2→3). Bot korpusu da aynı turda güncellendi (91 belge, 90 gömme) — asistan artık bayat numara söylemez.",
      "KANIT: 12 test (7 veri katmanı + 5 bileşen) yeşil; kod 6 yerden bilerek bozuldu (mutasyon) ve testler her seferinde yakaladı. Tam test takımı 440 dosya / 3648 test yeşil.",
      "KALAN: Her metriğin SQL çıktısıyla panel rakamının elle karşılaştırılması (M16 canlı doğrulama) sırada. Panel bir sonraki frontend deploy’ında canlıya çıkar.",
    ],
  },
  {
    id: "20261003-kurumsal-dogrulama-basvuru-formu",
    date: "3 Ekim 2026",
    title: "Kurumsal doğrulama başvurusu artık ekranda — kuruluş kaydını belgeyle doğrulat (deploy kuyruğunda)",
    items: [
      "NE GELDİ: Dün kurulan kurumsal doğrulama altyapısının (belge kovası + talep kuyruğu) üye tarafındaki ekranı hazır. Bir dernek/okul/kuruluş kaydının temsilcisi, kayıt sayfasında tüzük veya yetki belgesini yükleyip doğrulama talebi açabiliyor; talep yönetici kuyruğuna düşüyor.",
      "ÖNCE KAYDI SAHİPLEN (iki adım): 262 kurumsal kaydın 249'unda kaydı temsil eden hiçbir kişi bağı yok (sahipsiz içe aktarılmış kayıtlar). Bu yüzden bağı olmayan kullanıcıya belge formu GÖSTERİLMİYOR — bunun yerine 'önce kaydı sahiplen' (düzenleme yetkisi) yolu gösteriliyor. Yalnız temsil yetkisi olan başvuru yapabiliyor. Bu bilinçli: sahipsiz bir kaydı doğrulatmak, o kurumu temsil etmekle aynı şey değil.",
      "BELGE GÜVENLİĞİ: Belgeler dışarıya kapalı özel alanda duruyor; yalnız yükleyen kişi ve yöneticiler, o da süreli bağlantıyla açabiliyor (herkese açık bağlantı üretilmiyor). Dosyanın ham adı depolama anahtarına girmiyor (dizin dışına çıkma denemeleri kapatılıyor). Tür, dosyanın içeriğinden değil uzantısından belirleniyor — dar liste: PDF/JPG/PNG/WebP, dosya başına en çok 15 MB, en çok 5 belge.",
      "KANIT: 26 test (17 sözleşme + 9 bileşen) yeşil; kod 6 yerden bilerek bozuldu (mutasyon) ve testler her seferinde yakaladı. Canlı kova ölçüldü: özel · 15 MB · 4 tür · 'her şeyi kabul et' türü YOK · başvuru fonksiyonu anonime kapalı, üyeye açık.",
      "KALAN: Yönetici inceleme ekranı (kuyruk + belge önizleme + onayla/reddet) sırada. Bu form üye tarafıdır ve bir sonraki frontend deploy'ında canlıya çıkar.",
    ],
  },
  {
    id: "20261003-kurumsal-dogrulama-altyapisi",
    date: "3 Ekim 2026",
    title: "Kurumsal doğrulama altyapısı kuruldu — dernek/okul/kuruluş kayıtları için belgeli başvuru",
    items: [
      "NE GELDİ: Bir kuruluş kaydının “doğrulanmış” sayılabilmesi için belgeli başvuru altyapısı canlıda. Başvuran tüzük/yetki belgesini yüklüyor, kayıt yönetici kuyruğuna düşüyor. Onay kimin, ne zaman verdiği artık kayıt altında tutuluyor — eskiden bu iz hiç yoktu.",
      "YENİ BİR “SEVİYE” ALANI AÇILMADI: Kayıtta zaten iki doğrulama alanı vardı; üçüncüsünü eklemek aynı bilginin birbirini tutmayan üç kopyasını üretirdi. “Seviye 2” artık mevcut doğrulama durumundan türetiliyor, ayrıca saklanmıyor.",
      "ÖNEMLİ ÖLÇÜM — AKIŞ BUNA GÖRE KURGULANDI: 262 kurumsal kaydın 249’unda kaydı temsil eden hiçbir kişi bağı yok (bunlar toplu aktarılmış sahipsiz kayıtlar). Bu yüzden doğrulama başvurusu için önce kaydı sahiplenmek gerekiyor; sahipsiz bir kaydı doğrulatmak o kurumu temsil etmekle aynı şey değil.",
      "BELGE GÜVENLİĞİ: Belgeler dışarıya tamamen kapalı özel bir alanda duruyor; yalnız belgeyi yükleyen kişi ve yöneticiler, o da süreli bağlantıyla açabiliyor. Başkasının klasörüne yazma ve başkasının belgesini kendi başvurusuna iliştirme yolları ayrı ayrı kapatıldı.",
      "KANIT: 15 kabul kontrolü canlı veritabanında, geri alınan bir işlem içinde ölçüldü (başvuru açma, mükerrer başvurunun reddi, zaten doğrulanmış kayıt, kurumsal olmayan kayıt, yetkisiz klasör, belgesiz başvuru, oturumsuz erişim). Canlıda hiçbir iz bırakılmadı.",
      "KALAN: Üyenin göreceği başvuru formu ve yöneticinin kullanacağı inceleme ekranı sırada. Bugün kurulan kısım altyapı — ekran gelmeden kullanıcıya görünmez.",
    ],
  },
  {
    id: "20261003-grup-sahipligi-rol-yukseltme",
    date: "3 Ekim 2026",
    title: "Grup sahipliğini doğrulayan üyeye artık rolü gerçekten veriliyor (sessiz kusur kapandı)",
    items: [
      "SORUN NEYDİ: Bir üye grubunun sahipliğini doğruladığında kendisine “WhatsApp/Telegram/Discord Yöneticisi” rolü verilmesi gerekiyordu. Ama sistem kimseye veremiyordu: kayıt olan herkese otomatik olarak varsayılan üye rolü atanıyor ve sistem “mevcut rolü ezme” kuralı yüzünden her seferinde atlıyordu. Hata vermiyordu — sadece olmuyordu.",
      "ÇÖZÜM: Artık YALNIZ varsayılan üye rolü yükseltiliyor. Süper Admin, danışman, kuruluş ve özel roller eskisi gibi korunuyor — bir Süper Admin grubunu doğrulayınca Süper Adminliğini kaybetmiyor.",
      "ÖLÇÜM: Sistemdeki 175 üyenin tamamının tek rolü var. 148’i varsayılan rolde (yükseltmeye açık), 27’si başka rollerde (korunuyor).",
      "KANIT: 10 kontrolün tamamı canlıda, geri alınan işlem içinde ölçüldü — varsayılan rol yükseldi, Süper Admin ve danışman rolleri ezilmedi, rolü olmayan kullanıcıya rol atandı, kullanıcı başına tek rol kuralı korundu.",
    ],
  },
  {
    id: "20261003-cadde-kimlik-isareti",
    date: "3 Ekim 2026",
    title: "Cadde’ye kimlik işareti (logo) eklendi — deploy kuyruğunda",
    items: [
      "NE GELDİ: Burak’ın verdiği Cadde logosu, akışın filtre şeridinin sol ucuna küçük bir kimlik işareti olarak yerleşti.",
      "SAYFADAN YER ÇALMIYOR: İşaret kendi şeridini açmıyor, var olan filtre satırının içinde duruyor ve satırın yüksekliğini değiştirmiyor. Akışın üstüne blok eklenmedi — paylaşım kutusunu aşağı iten eski düzen sorunu geri getirilmedi.",
      "DOSYA DÜZELTİLDİ: Gelen görselin arka planı şeffaf değildi; olduğu gibi konsaydı koyu temada beyaz bir kutu olarak görünecekti. Arka plan gerçekten saydamlaştırıldı, kenar boşlukları kırpıldı ve dosya 3 MB’tan 220 KB’a indi (sayfa açılış hızı için önemli).",
      "DEĞİŞMEYEN: Cadde’nin bronz kurumsal rengi aynen duruyor; logo renkli, arayüz rengi bronz — ikisi ayrı iştir.",
      "NE ZAMAN GÖRÜNÜR: Bir sonraki frontend deploy’unda.",
    ],
  },
  {
    id: "20261003-davet-liderligi",
    date: "3 Ekim 2026",
    title: "Davet sistemi açıldı — /liderlik sayfası, davet kodu ve QR (deploy kuyruğunda)",
    items: [
      "LİDERLİK TABLOSU: Yeni herkese açık sayfa /liderlik — topluluğa en çok arkadaşını davet eden üyeler sıralanıyor. Giriş yapmadan da gezilebilir; liste dizinin görünürlük kurallarıyla aynıdır (yönetici, test ve yer tutucu kayıtlar SQL seviyesinde elenir — ekranda da doğrulandı).",
      "DAVET KARTI: Girişli üye profilindeki hızlı işlemlerden veya /liderlik sayfasından davet kodunu alır: kod + paylaşılabilir link + QR kodu + tek tıkla kopyalama. Kod kişi başına tektir ve aynı kalır.",
      "ROZETLER: Davet sayısıyla kazanılır (3+ · 10+ · 25+). Eşikler ayar tablosundan yönetiliyor — değiştirmek kod işi değil. Bir üye yalnız bir kez sayılır; kendi kodunu kullanmak reddedilir.",
      "KANIT: Gerçek veriyle uçtan uca ölçüldü: davet kodu üretildi → ikinci üye kullandı → liste HTTP üzerinden anonim okundu (doğru üye göründü, YÖNETİCİ hesabı kullanımına rağmen görünmedi, yer tutucu başlık düşürüldü) → ölçüm satırları temizlendi, canlı başlangıç durumunda.",
      "SIRADAKİ: Davet linkiyle gelen ziyaretçinin kayıt akışında otomatik sayılması (M13) — davet bonusu kaydı asla bloklamayacak şekilde bağlanıyor.",
    ],
  },
  {
    id: "20261003-profil-baslangic-kartlari",
    date: "3 Ekim 2026",
    title: "Profilin ilk ekranına üç yeni kart geldi — hızlı işlemler, başlangıç adımları ve “yakında” vitrini (deploy kuyruğunda)",
    items: [
      "HIZLI İŞLEMLER: Profilin ilk ekranında (tüm rollerde) kısayol kartı: “Etkinlik oluştur” ve “Grup ekle”. Listeye “Davet et” ve “Tavsiye iste” kendi modülleri geldiğinde eklenecek — çalışan rotası olmayan düğme konmuyor.",
      "BAŞLANGIÇ ADIMLARI: Dört satırlık ilerleme kartı — profilini tamamla (zorunlu alan sayın gerçek kayıtlardan), ilk hizmet/ürününü ekle (Çarşı ilanların), ilk etkinliğini oluştur, 3 arkadaşını davet et. Tamamlanma GERÇEK veriden okunuyor; davet satırı sistem gelene kadar “yakında” diye PASİF duruyor — sahte tik yok.",
      "YAKINDA · ÜCRETLİ ÖZELLİKLER: “Öne çıkar” ve “Bilet sat” KİLİTLİ kart olarak duruyor (ödeme kapsam dışı, ayrı plan). “İlgileniyorum” diyenin kaydı alınıyor — hangi ücretli özelliğin önce yapılacağına bu ilgi birikimi karar verecek. İlgi kaydı silinemez ve aynı kişi iki kez sayılmaz.",
      "KANIT: İlgi kaydı canlıda ölçüldü (geri alınan işlem): kayıt satırı oluştu · ikinci tık “zaten kayıtlı” dedi, tek satır kaldı · listede olmayan anahtar reddedildi · giriş yapmamış kullanıcı hiç kayıt açamadı · işlem geri alınca canlıda iz kalmadı. Ekranlar bir sonraki frontend deploy’unda görünür.",
    ],
  },
  {
    id: "20261003-etkinlik-motoru-faz1",
    date: "3 Ekim 2026",
    title: "Etkinlik motoru Faz 1 hazır — ilk-onay kuralı, kontenjan ve katılım düğmesi (arayüz deploy kuyruğunda)",
    items: [
      "İLK-ONAY KURALI ARTIK VERİTABANINDA: Bir üyenin İLK etkinliği yönetici onayına düşer; onaydan sonraki etkinlikleri otomatik yayınlanır. Bu kural eskiden yalnız ekran kodundaydı — isteyen teknik yoldan atlayabilirdi. Artık kural sunucuda: doğrudan “yayınlandı” yazmayı deneyen istek reddediliyor (ölçüldü), durum değişikliğini yalnız moderatör yapabiliyor.",
      "KONTENJAN SINIRI: Etkinlik sahibi “maks. katılımcı” verdiyse kontenjan dolduğunda katılım SUNUCUDA kapanır — iki kişi aynı anda basarsa bile kontenjan aşılamaz (yarış kilidi veritabanında).",
      "KATILIM DÜĞMESİ: Etkinlik detayına “Etkinliğe katıl / Katılımdan ayrıl” düğmesi geldi; kaç kişinin katıldığı ve kapasite yanında görünür. Kontenjan dolunca düğme “Kontenjan dolu” diye pasifleşir. Giriş yapmamış ziyaretçi önce girişe yönlendirilir. Katılanların listesi kimseye gösterilmez — yalnız sayı.",
      "AKTİF ETKİNLİK LİMİTİ: Aynı anda en fazla 2 aktif (gelecek tarihli, yayında) etkinlik — geçmiş etkinlikler sayılmaz. Limit ayar tablosundan yönetiliyor.",
      "ETKİNLİKLERİM PANELİ: Kural artık kullanıcıya açıkça anlatılıyor: “İlk etkinliğin onaydan geçer, sonrakiler otomatik yayınlanır; en fazla 2 aktif etkinliğin olabilir (şu an N).”",
      "KANIT: Tam zincir canlıda geri alınan işlemle ölçüldü (8/8): ilk etkinlik onay kuyruğuna düştü → moderatör yayınladı → ikincisi otomatik yayın → üçüncüde limit reddi → doğrudan “yayınlandı” yazma denemeleri İKİ katmanda da reddedildi → katılım/ayrılma/kontenjan zinciri doğru → ziyaretçiye yalnız sayı göründü. İşlem geri alındığı için canlıda iz bırakmadı.",
      "NOT: Veritabanı tarafı şu an bile geçerli (eski ekran da yeni kurallara uyuyor); katılım düğmesi ve yeni metinler bir sonraki frontend deploy'unda görünür olacak.",
    ],
  },
  {
    id: "20261003-cadde-gonderi-duzenleme",
    date: "3 Ekim 2026",
    title: "Cadde'de paylaşım düzenleme açıldı — artık silmek zorunda değilsin",
    items: [
      "DÜZENLE MENÜDE: Kendi paylaşımının üç nokta menüsünde “Düzenle” var. Composer aynı kutuda düzenleme moduna geçer: metin, medya ve konum ön dolu gelir; “Kaydet” ile güncellenir, “Vazgeç” ile hiçbir şey değişmez.",
      "NE DEĞİŞİR, NE DEĞİŞMEZ: Metin, görsel/video ve ülke-şehir hedefi düzenlenebilir. @anmaların KORUNUR (metinden silsen bile anma kayıtları durur), #etiketler yeni metinden otomatik tazelenir. Paylaşımın tipi ve kafe bağlantısı değişmez.",
      "SINIRLAR: Aynı kurallar düzenlemede de geçerli — metin 4000 karakter, en fazla 4 görsel + 1 video, tek hedef (birden fazla hedef premium kapsamında ve şimdilik kapalı). Boş paylaşım kaydedilemez (metin silinecekse medya da silinmeli).",
      "GÜVENLİK: Düzenleme yetkisinin gerçek denetimi veritabanında — yalnız paylaşım sahibi (veya admin/moderatör) kaydedebilir; başkasının paylaşımında menü hiç görünmez, görünse bile sunucu reddeder. Canlıda 10 senaryoyla ölçüldü (hepsi geri alınan işlemde): sahip düzenledi · anmalar korundu · etiket tazelendi · medya temizlendi · hedef değişti · ikinci hedef premium kapısına takıldı · sahip olmayan reddedildi · gizli paylaşım 'yok' sayıldı · kafe paylaşımında hedef yok sayıldı · 4001 karakter reddedildi.",
      "NOT: Bu ekran da bir sonraki frontend deploy'unda canlıya çıkar (veritabanı tarafı zaten çalışıyordu, şimdi arayüzü bağlandı).",
    ],
  },
  {
    id: "20261003-deploy-sonrasi-guvenlik-ve-skorlar",
    date: "3 Ekim 2026",
    title: "Deploy tamam: yeni grup ekranları canlıda, link sızıntısı KAPANDI, grup skorları görünür oldu",
    items: [
      "YENİ EKRANLAR CANLIDA: Grup ekleme formu, yeni dizin dili (Sahibi doğruladı / Üye önerisi / Yeni / Onaylı Grup rozetleri), grup detayı + “Bu grup sizin mi?” sahiplenme akışı, sahip paneli ve moderatör paneli (/admin/gruplar) artık sitede çalışıyor. Deploy sonrası ziyaretçi turu doğrulandı: dizin 10 grubu yeni kolonlarla dönüyor.",
      "🔒 GÜVENLİK KUSURU KAPANDI: Grup davet linkleri ve yönetici iletişim bilgileri, eski tablo yetkisi yüzünden giriş yapmamış ziyaretçilere teknik olarak okunabiliyordu (ekranda gösterilmese bile). Deploy doğrulanır doğrulanmaz tablo yetkisi daraltıldı: giriş yapmayana tablo artık tamamen kapalı — linkler yalnız girişli kullanıcıya, grup sayfasında, tek kapıdan veriliyor. Dört yolun dördü de yeniden ölçüldü (4/4 temiz). Ek önlem: giriş yapmamış rolün tablo üzerindeki silme/biçme yetkileri de kaldırıldı.",
      "SKORLAR GÖRÜNÜR OLDU: Günlük skor hesabının anahtarı (deploy bekliyordu) açıldı ve ilk hesap koştu: 10 grubun skoru yazıldı. Bugünkü taban 35/100 (çalışan link + şikayetsizlik kalemleri); profil, kurallar ve sahiplik doğrulandıkça skor ve “Onaylı Grup” rozeti kendiliğinden yükselecek. Kartlar artık doğru ölçekle “35 / 100” çiziyor.",
      "ESKİ SİSTEM BOZULMADI: Admin moderasyon ekranı ve editör akışları aynen çalışıyor (yetki daraltması yalnız giriş yapmamış rolü etkiledi).",
    ],
  },
  {
    id: "20261002-grup-motoru-kabul-testleri",
    date: "2 Ekim 2026",
    title: "Grup motorunun 13 kabul testi tek betikte — QA turu bir gerçek kusuru daha yakaladı",
    items: [
      "QA BETİĞİ: Motorun 13 kabul testinin 12'si tek komutla yeniden koşulan, KENDİNİ DOĞRUAYAN bir canlı betiğe bağlandı (her senaryo veritabanı üzerinde iddialı; hepsi geri alınan işlemde — canlıya dokunmaz). Anonim ziyaretçinin link/panel/kuyruk göremediği bölüm gerçek rollerle ayrıca ölçülüyor.",
      "KUSUR YAKALANDI VE ONARILDI: “Grup için bir ihlal kaydı oluştu” uyarı maili hiçbir zaman gitmeyecekti — bildirim, ihlalin log satırına bağlanmıştı ama ilk ihlal (uyarı) log üretmiyor. Uyarı artık doğrudan ihlal kaydı tablosuna bağlı: her ihlal = tek mail; askı/kaldırma sonucu da mailin sebep alanına işleniyor. Çift mail riski de kapatıldı.",
      "MUTASYON SINAVI: Testlerin gerçekten test olduğu kanıtlandı — “bilinmeyen link sonucu sayacı bozmasın” kuralı, “Aile & Çocuk kilidi” ve “anonime link sızmaz” kuralı canlıda bilerek BOZULDU; betik üçünde de kızardı, kurallar geri yüklendi ve canlı yeniden ölçüldü.",
      "ŞİKAYET TESTİ BİLİNÇLİ BEKLEMEDE: Şikayet eşiği kabulü (#6) telefon doğrulamasına bağlı altyapıyı bekliyor. Betikte tripwire var: şikayet tablosu ortaya çıktığı an QA kızarır ve o kabul testi yazılmak zorunda kalır — unutulamaz.",
      "RAPOR: 13 kabulün tamamı, kanıt değerleri ve mutasyon sonuçları docs/dijital-gruplar/2026-10-02-g25-kabul-raporu.md dosyasında. Tam test takımı 417 dosya / 3440 test yeşil.",
    ],
  },
  {
    id: "20261002-grup-moderator-paneli",
    date: "2 Ekim 2026",
    title: "Grup moderatör paneli hazır — dört kuyruk tek ekranda (/admin/gruplar, deploy kuyruğunda)",
    items: [
      "TEK EKRAN DÖRT KUYRUK: Yeni gruplar · sahiplik talepleri (ekran görüntüsü yöntemi) · şikayetler · platform gönderi kuyruğu. Klavye kısayolları: J/K gez, A onayla, R reddet (hazır sebep listesi + not). Reddin sebebi üyeye giden bildirim mailine yazılıyor.",
      "ÜST ŞERİT: Kuyruk sayaçları · moderasyondan geçen grup sayacı (x/100 — eşik dolunca “hızlı şeridi aç” önerisi görünür, karar insanın) · hızlı şerit anahtarı (ayar tablosuna yazar; anahtar listesi DAR: panelden yalnız bu tek ayar değişebilir, eşikler ürün kararı olarak kalır) · 6 zamanlanmış görevin son koşu durumları.",
      "TEK TIK KARARLAR: Grup yayınla/reddet · uyarı ver (ihlal merdiveni otomatik: 1. uyarı → 2.’de 30 gün askı → 3.’te kaldırma+yasak; kırmızı çizgi seçilirse ilk ihlalde kaldırır) · sahipliği onayla/reddet (onay, sahipliği doğrulanmış yapar) · gönderi onayla/reddet. Ekran görüntüsü kanıtları 5 dakikalık imzalı bağlantıyla açılır (kova private kalır).",
      "ŞİKAYET KUYRUĞU BİLİNÇLİ BOŞ: Altyapısı telefon doğrulamasına bağlı (G14) — o güne dek sekme boş durumu açıklıyor, sayaç 0 dönüyor. Uydurma veri yok.",
      "KANIT: Sunucu kapıları canlıda ölçüldü (geri alınan işlem): üye ve anonim özeti OKUYAMIYOR · anahtarı yalnız admin yazıyor (iz: updated_by) · beyaz liste dışı anahtar ve tip reddi · kuyruk sayacı gerçek gönderiyle 0→1 hareket etti · görev koşuları gerçek cron verisinden (claim-expiry 22:30’da succeeded). Ekran deploy kuyruğunda (form/dizin/detay ile aynı).",
    ],
  },
  {
    id: "20261002-grup-bildirimleri",
    date: "2 Ekim 2026",
    title: "Grup bildirimleri canlıda — 8 olayda üyeler artık otomatik e-posta alıyor",
    items: [
      "8 BİLDİRİM: “Grubun alındı” (inceleme genelde 24 saat) · “{Grup} yayında — sayfanı paylaş” · “Yayınlanamadı + sebep + Grup Sözü linki” · “Sahiplik doğrulandı — kodu grup adından silebilirsin” · “Onay bekleyen {n} gönderi var, 48 saatte bakmazsan ekip devralır” · “Davet linkin çalışmıyor, grup geçici gizlendi” · “Tebrikler, Onaylı Grup oldun — rozet görselin hazır” · “İhlal kaydı oluştu: {sebep}”. Metinler tasarım dokümanındaki tabloyla birebir (testle kilitli).",
      "NASIL ÇALIŞIYOR: Bildirimler veritabanı tetikleyicilerinden kuyruğa düşüyor ve anında gönderiliyor (akşam özeti beklenmiyor — bunlar işlemsel bildirimler). Kimse kimsenin adresini görmüyor; her mail tek alıcıya gidiyor.",
      "SPAM KORUMASI: “Onay bekleyen gönderi” maili grup başına GÜNDE BİR kez gelir (içinde güncel sayıyla). Hızlı şeritle yayına çıkan grup hem “alındı” hem “yayında” maili ÜRETMEZ — yalnız “yayında”.",
      "GÜVENLİK: Mail içeriğine davet linki ASLA konmuyor (kural 8) — {link} alanları site sayfası; davet linki yalnız girişli kullanıcıya grup sayfasında. Test satırları dahil hiçbir kuyruk kaydına link yazılmadı (canlıda tarandı: 0 sızıntı).",
      "KANIT: 8 olayın 8’i de canlıda uçtan uca doğrulandı — tetikleyiciler geri alınan işlemde ölçüldü (8/8 olay tipi üretildi, gün-dedupe çalıştı, toplu-işlem bayrağı susturdu), ardından 8 gerçek mail yönetici adresine gönderildi: 8/8 “sent”, alıcı sayısı 1, hata yok. Test satırları silindi. Her bildirim tipi admin panelindeki Bildirim Ayarları anahtarlarıyla kapatılabilir.",
    ],
  },
  {
    id: "20261002-grup-motoru-zamanlanmis-gorevler",
    date: "2 Ekim 2026",
    title: "Grup motorunun 6 zamanlanmış görevi canlıda — link sağlığı çalışmaya başladı",
    items: [
      "LİNK SAĞLIĞI (çalışıyor): Her grubun davet linki haftada bir, günlere/saatlere YAYILMIŞ biçimde sunucu tarafında kontrol ediliyor. Sonuç üç değerli: çalışıyor / ölü / okunamadı. Üst üste 2 ölü kontrol grubu gizler (sebep: link_dead) ve admin kuyruğuna düşürür; 1 başarılı kontrol gizli grubu GERİ AÇAR. “Okunamadı” sonucu gruba asla mal edilmez — sayaç artmaz (ağ hatası yüzünden kimse gizlenmez). İlk gerçek tur koştu: 1 grup kontrol edildi, sonuç “okunamadı” (sayaç 0 kaldı).",
      "KUYRUK ESKALASYONU (saatlik): Grup admininin 48 saat içinde bakmadığı gönderiler otomatik olarak platform ekibinin kuyruğuna geçiyor.",
      "ASKI BIRAKMA (günlük): 30 günlük askı süresi dolan gruplar otomatik yayına dönüyor.",
      "SAHİPLİK YENİLEME (günlük): Doğrulanmış sahipler yılda bir kısa onay veriyor (panelde “Yenileme onayını ver” düğmesi). 30 gün yanıt gelmezse sahiplik düşer ve grup yeniden “üye önerisi” durumuna geçer.",
      "KOD SÜRESİ (10 dakikada bir): Sahiplik doğrulama kodlarının süresi dolunca kayıtları otomatik kapanıyor — “grup başına tek aktif kod” kuralı boşa işgal edilmiyor.",
      "⚠️ SKOR HESABI BİLEREK KAPALI: Günlük sağlık skoru görevi kuruldu ama ANAHTARI KAPALI. Sebep: canlı site hâlâ eski kartı çiziyor ve yeni 0-100 skorları “35 / 10” gibi bozuk gösterirdi. Yeni ekranlar deploy edildikten sonra anahtarı insan kararıyla açacağız (tek ayar satırı).",
      "KANIT: Görevlerin tamamı canlı veritabanında geri alınan bir işlemde 8 senaryoyla ölçüldü (2 ölü link → gizledi → başarılı kontrol → geri açtı dahil); görev fonksiyonları üyelere kapalı, yalnız sistem rolü çağırabiliyor. Zamanlayıcıya 6 yeni iş kaydedildi.",
    ],
  },
  {
    id: "20261002-grup-sahip-paneli",
    date: "2 Ekim 2026",
    title: "Grup sahibi paneli hazır — skor rehberi, onay kuyruğu, düzenleme, listeden kaldırma (deploy kuyruğunda)",
    items: [
      "SAHİP PANELİ: Grubun doğrulanmış sahibi grup sayfasında kendi panelini görüyor: sağlık skoru kalem kalem + eksik adım rehberi (“Kurallarını ekle, +15” gibi), onay bekleyen gönderiler, bilgi düzenleme ve “Grubu listeden kaldır”. Sahip olmayan ziyaretçiye panel HİÇ çizilmiyor — sunucu da panel verisini yalnız sahibe veriyor (başkasına tek alan dönüyor: “sahip değil”).",
      "ONAY KUYRUĞU SAHİPTE: Gruba düşen gönderiler önce sahibin onayına düşüyor (48 saat içinde bakmazsa ekibimizin kuyruğuna geçiyor — uyarı panelde yazılı). Sahip tek tıkla onaylıyor ya da reddediyor.",
      "LİSTEDEN KALDIRMA ANINDA: Doğrulanmış sahip “Grubu listeden kaldır”a basınca grup ANINDA gizleniyor — gerekçe SORMUYORUZ (politika: sahip istemezse 24 saat). 24 saat içinde moderatör kalıcı kaldırmaya çeviriyor. İki adımlı onay var, yanlışlıkla basılamıyor.",
      "DÜZENLEME SKORU BESLİYOR: Sahip kısa açıklamayı, kuralları, kategoriyi, şehri/ülkeyi, vurgu cümlesini ve görseli değiştirebiliyor; skor ertesi günkü günlük hesapta güncelleniyor. “Aile & Çocuk” kategorisi burada da doğrulama altyapısına kadar kilitli.",
      "ROZET GÖRSELİ: “Onaylı Grup” rozetini kazanan gruplar, Instagram’da paylaşılabilir 1080x1080 rozet görselini panelden indirebiliyor (grup adı + skor yazılı).",
      "⚠️ EKRAN DEPLOY BEKLİYOR: Sunucu tarafı canlıda ve doğrulandı (kaldırma isteği canlı ölçümde grubu anında dizinden düşürdü, sonra geri alındı); panel ekranı form + dizin + detay ile aynı deploy kuyruğunda.",
    ],
  },
  {
    id: "20261002-grup-sahipligi-ekrani",
    date: "2 Ekim 2026",
    title: "“Bu grup sizin mi?” — grup sahiplenme ekranı hazır (deploy kuyruğunda)",
    items: [
      "SAHİPLENME EKRANI: Her grup sayfasının altında “Bu grubun admini misin?” bölümü açıldı. İki yol var: (1) KOD — sistem 10 dakikalık tek kullanımlık bir kod üretir (CQ+4 hane), kodu grup adının sonuna eklersin, “Kontrol et”e basınca sistem grup adını SUNUCUDA okur ve kodu bulursa sayfa sana bağlanır; (2) EKRAN GÖRÜNTÜSÜ — kodla olmuyorsa admin panelinin ekran görüntüsünü yüklersin, talep moderatör kuyruğuna düşer.",
      "GÜVENLİK: Doğrulamada 3 deneme hakkı var; linki ölü ya da okunamayan gruplarda deneme YANMAZ (sistem hatası kullanıcıya mal edilmez). Ekran görüntüleri yalnızca kişinin kendi özel klasörüne yazılır — başkasının kanıtını kimse göremez, silmeyi yalnız admin yapabilir. Günlük talep sınırı ayar tablosundan yönetiliyor.",
      "GRUP ZATEN SAHİPLENİLMİŞSE: Otomatik devir YOK. Ekran görüntüsüyle itiraz edilebilir, kararı moderatör verir; mevcut sahibe haber gider (bildirim altyapısı M4’te bağlanacak).",
      "ANONİM ZİYARETÇİ GÜVENCESİ (kabul testi): Giriş yapmamış ziyaretçi için davet linki sayfa kaynağı dahil HİÇBİR YERDE görünmüyor — “Katıl” düğmesi önce giriş istiyor. Bu davranış otomatik testlerle kilitlendi.",
      "EKSİK BÖLÜM DÜZELTİLDİ: “Grup koşulları” bölümü boşken artık hiç çizilmiyor (boş başlık görünmüyor).",
      "⚠️ “ŞİKAYET ET” BİLEREK YOK: Şikayet altyapısı telefon doğrulamasına bağlı (K09/U06 kararı bekleniyor). Arkasında sistem olmayan bir buton koymak yerine hiç konmadı — altyapı gelince eklenecek.",
      "⚠️ EKRAN DEPLOY BEKLİYOR: Veritabanı tarafı zaten canlıydı ve yeniden doğrulandı; ekran, form + dizin ile aynı deploy kuyruğunda.",
    ],
  },
  {
    id: "20261002-grup-dizini-yeni-dil",
    date: "2 Ekim 2026",
    title: "Grup dizininin yeni dili hazır — sahiplik rozetleri, “Yeni” etiketi, 0-100 skor (deploy kuyruğunda)",
    items: [
      "ROZET DİLİ DEĞİŞTİ: Kartlardaki “Admin onaylı!” / “Üye onaylı!” rozetleri kalktı. Yerine politikanın dili geldi: “Sahibi doğruladı” (gerçek admin ekledi ve kanıtladı), “Üye önerisi” (admin olmayan biri önerdi, sahiplenilmedi), “Yeni” (ilk 72 saat) ve “Onaylı Grup” (sağlık skoru 70+).",
      "“SKOR BEKLENİYOR” KUTUSU KALKTI: Skor hesaplanana kadar kartta skor alanı hiç gösterilmiyor (politika kuralı). Skor gelince 0-100 ölçeğinde “Grup Sağlık Skoru” olarak görünüyor — eski “X / 10” dili bitti.",
      "GİZLİ BİR KUSUR KAPATILDI: Yeni moderasyon motoru bir grubu gizlediğinde/askıya aldığında, dizinin okuduğu eski görünüm yalnızca eski onay alanına baktığı için grup SİTEDE GÖRÜNMEYE DEVAM EDERDİ. Dizin artık her iki sisteme de bakıyor: motor “gizli/askıda/kaldırıldı” dediyse grup anında dizinden düşüyor (canlıda ölçüldü).",
      "SIRALAMA SKORA BAĞLANDI: Gruplar sağlık skoruna göre diziliyor (skoru yüksek olan üste); skoru henüz hesaplanmamış gruplar sonda kalıyor. “Yeni” etiketinin 72 saat eşiği ayar tablosundan yönetiliyor, koda gömülü değil.",
      "FİLTRE VE KARTLAR ARTIK AYNI LİSTE: Kategori filtreleri ile kart rozetleri tek kaynaktan besleniyor — eskiden iki ayrı liste vardı ve birbirinden sessizce kayabilirdi.",
      "⚠️ EKRAN DEPLOY BEKLİYOR: Veritabanı tarafı canlıda ve doğrulandı; yeni kart/filtre görünümü frontend deploy kuyruğunda (form ile aynı). Eski paket deploy’a kadar mevcut diliyle çalışmaya devam eder — hiçbir sayfa kırılmaz (canlı dizin içeriği bugün birebir aynı kaldı, 10 grup).",
    ],
  },
  {
    id: "20261002-grup-ekleme-formu-yenilendi",
    date: "2 Ekim 2026",
    title: "Grup ekleme formu baştan yazıldı — link yapıştır, gerisi otomatik (deploy kuyruğunda)",
    items: [
      "YENİ FORM: Kullanıcı fiilen üç şey yazıyor: link, kısa açıklama (en fazla 160 karakter), şehir. Linki yapıştırınca sistem davet sayfasını SUNUCU tarafında okuyor — grup adı ve görseli otomatik doluyor, platform (WhatsApp/Telegram/Discord) linkten tanınıyor. Platform seçimi ve serbest metin ülke/şehir alanları KALDIRILDI; konum artık coğrafi katalogdan seçiliyor (Global gruplar için hedef ülke + 'Genel').",
      "AYNI GRUP İKİ KEZ EKLENEMEZ: Davet linkinin kodu tekilleştirme anahtarı. Link zaten listedeyse form 'Bu grup zaten listede — sahibi misin?' uyarısı veriyor. Eskiden aynı linkle onlarca kayıt açılabiliyordu.",
      "KARA LİSTE ÖN TARAMASI: 'Vize, oturum, garanti, sinyal, yatırım getirisi, kredi' gibi kelimeler geçen gönderimler OTOMATİK REDDEDİLMİYOR — yalnızca işaretleniyor ve hızlı şeritten geçemiyor. Karar moderatörün (liste ayar tablosunda, kodda sabit değil).",
      "HIZLI ŞERİT HAZIR (ŞU AN KAPALI): Yönetici, kendi grubunu eklerken 'adminiyim' derse ve şerit açıksa grup anında yayına çıkar — karar moderasyon kayıt defterine 'fast_lane' olarak düşer. Normal üyelerde 'adminiyim' beyanı grubu yayına çıkarmaz; sahiplik doğrulama kuyruğu açılır. Şeridi açma kararı insanındır (100 grup önerisi).",
      "GÜNDE 5 GÖNDERİM SINIRI + GRUP SÖZÜ: Spam koruması olarak kullanıcı başına 24 saatte en fazla 5 gönderim (ayarlardan değiştirilebilir). Form, politika metnindeki 'Grup Sözü' onay kutusu işaretlenmeden gönderilemiyor. Yasaklı kullanıcı (ihlal sistemi) formu açtığında uyarıyı görüyor.",
      "⚠️ EKRAN DEPLOY BEKLİYOR: Yeni form, dizin/detay sayfalarıyla aynı kuyrukta — Coolify deploy'undan sonra canlıya çıkar. Eski form deploy'a kadar çalışmaya devam eder (sunucu tarafı kapılar her iki yolu da koruyor). 'Aile & Çocuk' kategorisi doğrulama altyapısı (kurumsal seviye) gelene dek kilitli.",
    ],
  },
  {
    id: "20261002-grup-saglik-skoru",
    date: "2 Ekim 2026",
    title: "Grup sağlık skoru motoru kuruldu — “Onaylı Grup” rozeti otomatik hesaplanacak (ekranlar henüz yok)",
    items: [
      "SKOR NEDİR: Her grup için 0-100 arası bir sağlık skoru hesaplayan motor kuruldu. Kalem kalem: profil bilgileri dolu mu (15), grup kuralları yazılı mı (15), sahibi doğrulanmış mı ve onay kuyruğunu 48 saat içinde eritiyor mu (15), davet linki çalışıyor mu (15), kaç üye “bu gruptayım, tavsiye ederim” dedi (20’ye kadar), son 90 günde onaylanmış şikayet var mı (20).",
      "ROZET KURALI — GİDİP GELMESİN DİYE: Skor 70’e ulaşan grup “Onaylı Grup” rozetini kazanır; rozet ancak skor 65’İN ALTINA düşünce geri alınır. Aradaki bantta rozet yerinde kalır — grup bir gün var bir gün yok diye titremez.",
      "İLK 7 GÜN SKOR YOK: Yeni bir grup yayına çıkınca ilk 7 gün skor hesaplanmaz (boş kalır) — yeni grup “puanı düşük” diye cezalı görünmesin.",
      "TAVSİYE SİSTEMİ: Üyeler bir grup için “tavsiye ederim” diyebilecek; aynı kişi aynı grubu iki kez sayılmaz, tavsiyesini geri çekebilir. İlk 10 tavsiye skora puan olarak yansır, sonrası yansımaz (skor şişirilmesin).",
      "⚠️ EKRANLAR HENÜZ YOK: Bu da altyapı işi — skor kartlarda G19 (dizin), sahip panelinde G21, günlük otomatik hesap ise G22’de bağlanacak. Bugün canlıda hiçbir grubun skoru değişmedi; motorun bütün davranışı canlı veritabanında GERİ ALINAN bir işlemde 16 senaryoyla ölçüldü.",
      "SESSİZ BİR HATA BULUNDU VE KAPATILDI: Eski yönetici ekranı, bir grup kaydını her düzenleyip kaydettiğinde skor alanını sessizce SIFIRLIYORDU (kimse fark etmiyordu çünkü skorlar henüz boştu). Skor sistemi devreye girmeden önce bu davranış ölçüldü ve kapatıldı: skor artık yalnızca motorun kendisi tarafından yazılır; grup sahibi kendi skorunu elle yükseltemez.",
    ],
  },
  {
    id: "20261002-kariyer-sayfasi-ve-basvuru-sistemi",
    date: "2 Ekim 2026",
    title: "Kariyer sayfası baştan yazıldı — 17 ilan, başvuru formu ve yönetici ekranı artık çalışıyor",
    items: [
      "ÖZET: /kariyer sayfası eskiden yalnızca bir ilgi formuydu. Artık gerçek bir işe alım sayfası: 17 açık pozisyon, staj programı, kurucu mektupları ve dosya yükleyebilen bir başvuru formu var.",
      "ZİYARETÇİ NE GÖRÜYOR: İlanlar 5 alana göre süzülebiliyor (çiplere tıklayarak). Bir ilanda “Bu pozisyona başvur” denince seçim otomatik olarak alttaki forma taşınıyor ve sayfa oraya kayıyor. Her ilanın kendi bağlantısı var, yani tek bir ilanı doğrudan paylaşabilirsiniz.",
      "BAŞVURU FORMU: Ad, iletişim, pozisyon seçimi ve üç dosya — CV (zorunlu, en çok 10 MB), ön yazı ve sunum (en çok 25 MB). Dosyalar sürükle-bırak ile de yüklenebiliyor. KVKK onay kutusu BOŞ geliyor; kullanıcı işaretlemeden başvuru gönderilemiyor.",
      "ESKİ İLANLAR SİLİNMEDİ: Önceki dönemin 4 ilanı sayfanın altında “önceki dönem ilanı” rozetiyle duruyor ve onlardan gelen başvurular da aynı yeni sisteme düşüyor. Ne zaman kaldırılacağına ekip karar verecek — yeni ilanlar üzerinden en az bir tam başvuru dönemi geçtikten sonra.",
      "➡️ SİZDEN NE GEREKİYOR — BAŞVURULARI BURADAN OKUYUN: /admin/kadro → “Başvurular”. Yeni bir yönetici grubu açılmadı; mevcut kadro konsoluna 5. madde olarak eklendi. Adayın CV’si ve diğer dosyaları buradan açılıyor.",
      "E-POSTA BİLDİRİMİ AÇIK: Yeni başvuru geldiğinde kurucu ekibe anında mail gidiyor. Bu bildirim TÜM yöneticilere gider — ayrıca abone olmanıza gerek yok, istemeyen kapatır. Canlıda uçtan uca denendi: başvuru girildi, mail 3 saniyede gönderildi, deneme kaydı sonra silindi.",
      "⚠️ GÜVENLİK NOTU — CV’LER MAİLE KONMUYOR: Mailde yalnızca “yeni başvuru var” bilgisi ve adayın adı var; dosya bağlantısı YOK. Sebebi şu: maile gömülen bağlantı posta kutusunda süresiz durur ve o maili ilettiğiniz herkes adayın CV’sini açabilir. Dosyalar yalnızca panelden, 5 dakika geçerli özel bağlantıyla açılıyor.",
      "GELEN HAZIR PAKETTEKİ 3 HATA DÜZELTİLDİ: Dışarıdan gelen kurulum dosyası olduğu gibi çalıştırılsaydı sistem hiç kurulamayacaktı. Ayrıca yüklenen dosyanın adı hiç denetlenmiyordu ve “her türü kabul et” ayarı yüzünden depoya çalıştırılabilir dosya bile konabiliyordu. Üçü de kapatıldı ve canlıda 10 çağrıyla sınandı: izinsiz dosya türü, kural dışı dosya adı ve girişsiz okuma denemelerinin üçü de reddedildi.",
    ],
  },
  {
    id: "20261002-dijital-gruplar-motoru",
    date: "2 Ekim 2026",
    title: "Dijital Gruplar motoru kuruldu — doğrulama, moderasyon ve uyarı sistemi (ekranlar henüz yok)",
    items: [
      "NEDEN: Fikir şu — “Linkini saklama, kapını paylaş.” Ham WhatsApp davet linki ortalıkta dolaşmak yerine CorteQS grup sayfası paylaşılacak; katılmak isteyen kimliğini doğrulayacak, grup sahibi onaylayacak, spam kapıda kalacak.",
      "⚠️ EN ÖNEMLİ UYARI — PANELDE HENÜZ YENİ BİR EKRAN YOK: Bu hafta kurulan her şey arka plandadır. Grup onay kuyruğu, moderasyon ekranı ve bildirimler ayrı işler olarak sırada bekliyor. Yani panele girip “nerede bu?” diye aramayın; kurulan şey altyapı, henüz arayüz değil.",
      "SAHİPLİK DOĞRULAMA: Bir grubun gerçekten sizin olduğunuzu iki yoldan kanıtlayabileceğiniz sistem kuruldu — ya grup açıklamasına size verilen kodu yapıştırırsınız (sistem sayfayı kendisi okuyup kontrol eder) ya da ekran görüntüsü yüklersiniz. Kodlar tek kullanımlık; bir kişinin aynı anda tek açık talebi olabiliyor.",
      "DURUM MAKİNESİ VE KAYIT DEFTERİ: Bir grubun durumu (beklemede / yayında / askıda / kaldırıldı) artık rastgele değiştirilemiyor; yalnızca tanımlı geçişlere izin veriliyor ve her değişiklik kim-ne zaman-neden bilgisiyle kayda geçiyor. “Kaldırıldı” kalıcıdır, geri dönüşü yoktur.",
      "UYARI (STRIKE) SİSTEMİ: Kural ihlalinde kademeli ceza — 1. uyarı yalnızca uyarıdır, 2.’sinde grup 30 gün askıya alınır, 3.’sünde kaldırılır ve grubu EKLEYEN kişi yeni grup ekleyemez. Ağır ihlallerde (kırmızı çizgi) ilk seferde doğrudan kaldırma + yasak uygulanır. Yasaklı kişi hangi yoldan denerse denesin grup ekleyemiyor; yöneticiler bu kuraldan muaf.",
      "EŞİKLER KODDA DEĞİL AYARDA: Kaç uyarıda askı, kaç günlük askı, hangi ihlal kırmızı çizgi — hepsi bir ayar tablosunda duruyor. Yani bu kararları değiştirmek için yazılım güncellemesi gerekmiyor, ayar değişiyor. (Cadde’de aynı deseni kullanıyoruz.)",
      "GRUP SAYFASI GÖNDERİLERİ: Grup sayfalarına gönderi atılabilmesi için altyapı yazıldı. Doğrulanmış grup yöneticisinin ve güvenilir üyenin gönderisi doğrudan yayınlanıyor; diğerleri önce grup sahibinin onayına düşüyor. Sahip 48 saat içinde bakmazsa gönderi otomatik olarak platform kuyruğuna taşınıyor — yani onay beklerken sonsuza kadar asılı kalmıyor.",
      "TASARIM BELGESİNİN 5 VARSAYIMI ÖLÇÜLDÜ VE ÇÜRÜDÜ: Belge, var olduğunu sandığı 5 şeyin üzerine kuruluydu (yorum/beğeni tabloları, telefon doğrulama servisi, kurumsal güven seviyesi gibi). Canlıda ölçtük: hiçbiri yoktu. Varsayımla devam edilseydi çalışmayan bir sistem kurulacaktı; hepsi sıfırdan yazıldı.",
      "⛔ BLOKE OLAN İŞ — KARAR SİZDE: “Kurumsal doğrulama” adımı durduruldu. Sebep: katalog kayıtlarında ZATEN iki ayrı doğrulama alanı var ve ikisi de canlıda kullanılıyor; gelen tasarım üçüncü bir tane istiyor. Üçüncüsünü eklemek “doğrulanmış mı?” sorusunun üç ayrı cevabı olması demek. Hangisinin tek doğru kaynak olacağına karar verilmeden devam edilmeyecek.",
    ],
  },
  {
    id: "20261001-whatsapp-gruplari-guvenlik-acigi",
    date: "1 Ekim 2026",
    title: "⚠️ GÜVENLİK: WhatsApp grup sayfalarında iki açık bulundu ve kapatıldı",
    items: [
      "BİRİNCİ AÇIK — HERKES SINIRSIZ GRUP EKLEYEBİLİYORDU: Hesabı olmayan, giriş bile yapmamış biri sisteme istediği kadar grup kaydı ekleyebiliyordu. Dahası, kaydı BAŞKA BİR KULLANICININ üzerine yazabiliyordu. Günlük sınır da yoktu. Bu, kendiliğinden açık duran bir spam kapısıdır.",
      "DÜZELTİLDİ VE CANLIDA KANITLANDI: Girişsiz ekleme denemesi artık reddediliyor. Kendi adınıza ekleme çalışmaya devam ediyor (form bozulmadı), başkasının adına ekleme reddediliyor. Ayrıca aynı işi iki kez yapan 3 gereksiz kural temizlendi.",
      "İKİNCİ AÇIK — GRUP YÖNETİCİLERİNİN KİŞİSEL BİLGİLERİ HERKESE AÇIKTI: Beklenen sorun yalnızca davet linkiydi. Ölçünce daha ağırı çıktı: 10 grubun 10’unda da grup yöneticisinin ADI, E-POSTASI VE TELEFON NUMARASI giriş yapmamış herkese görünüyordu. Bu, planda yazılı değildi — ölçerek bulundu.",
      "DÜZELTİLDİ: Dizin ve grup detay sayfası artık kişisel bilgi taşımayan ayrı bir kaynaktan okuyor. Davet linki de kayıtla birlikte gelmiyor; yalnızca giriş yapmış kullanıcı istediğinde ayrıca veriliyor.",
      "KULLANICI NE GÖRÜYOR: “Katıl” düğmesi kaybolmuyor. Dört durumun dördünün de karşılığı var — link hazırsa gerçek bağlantı, giriş yoksa “Giriş yap ve katıl”, yükleniyorsa bekleme düğmesi, link yoksa sebebini yazan bir mesaj. (Eski kodda link gelmeyince düğme sessizce hiç çizilmiyordu; o tuzağa düşülmedi.)",
      "NOT: Bu iki açık canlıda uzun süredir açıktı. Kötüye kullanıldığına dair bir iz yok — ama kullanılabilirdi. İkisi de artık kapalı ve canlıda tek tek denenerek doğrulandı.",
    ],
  },
  {
    id: "20261001-yonetici-menusu-numaralari-ve-asistan",
    date: "1 Ekim 2026",
    title: "Yönetici menüsüne sıra numaraları geldi, asistan artık menüyü biliyor",
    items: [
      "NUMARALAR: Yönetici menüsündeki her maddenin artık sabit bir sıra numarası var (toplam 88 madde: 75 ana başlık, 13 alt madde). Amaç konuşmayı kolaylaştırmak — “şu ekrandaki üstten üçüncü” yerine numara söylenebiliyor. Numara tek bir yerden üretiliyor; kenar menü, komut paleti ve asistan aynı listeyi kullanıyor.",
      "ASİSTAN MENÜYÜ ÖĞRENDİ: Site asistanına menünün tamamı öğretildi (madde başına bir kayıt). Artık “X ekranı nerede?” diye sorabilirsiniz.",
      "⚠️ BU BİLGİ YALNIZCA YÖNETİCİYE AÇIK: Menü bilgisi, asistanın yönetici olduğunuzu doğruladığı durumda veriliyor; normal üye sorarsa erişemiyor. Ayrıca asistanın numara UYDURMASINI engelleyen bir fren kondu — bilmediği bir madde için numara icat edemiyor.",
      "SOHBETTEKİ BAĞLANTILAR ARTIK TIKLANABİLİR: Botun yanıtındaki site içi bağlantılar normal link gibi çalışıyor, dış bağlantılar yeni sekmede açılıyor. Zararlı olabilecek bağlantı türleri bilerek tıklanamaz hâlde (düz yazı olarak) gösteriliyor.",
      "SESSİZ BİR HATA DA YAKALANDI: Belgeler asistanın hafızasına yüklenirken, içinde emoji geçen bir belge parçası tam yanlış yerden bölünüyor ve kayıt sessizce düşüyordu (her 93 parçada 1). Onarıldı; ardından 93 parçanın 93’ü de sorunsuz yüklendi.",
    ],
  },
  {
    id: "20261001-tasinma-araclari-sirali-liste-gorseli",
    date: "1 Ekim 2026",
    title: "Taşınma araçlarında sıralı sonuç listesi okunur hâle getirildi",
    items: [
      "NE DEĞİŞTİ: Sonuç listesindeki her madde artık kendi renkli başlık şeridi olan bir kutu. Puan barları kalınlaştırıldı ve sayılar da bandın rengini aldı — hangi seçeneğin önde olduğu bir bakışta görünüyor.",
      "TALEP TEK ARAÇ İÇİN AÇILMIŞTI, DÖRDÜ BİRDEN GÜNCELLENDİ: Ölçtük — bu liste 4 aktif araçta kullanılıyor (ülke eşleştirme, şehir eşleştirme, Almanya banka seçimi, Almanya sigorta seçimi). Yalnızca birini değiştirmek, aynı listenin iki farklı görünüme sahip olması demekti.",
      "RENK TEK BAŞINA BİLGİ TAŞIMIYOR: Bandın Türkçe etiketi her zaman yazılı duruyor ve sayı her zaman görünüyor — renk göremeyen kullanıcı da sıralamayı okuyabiliyor. Puanı olmayan madde renk ALMIYOR; yoksa “0 puan” zayıf bir sonuç sanılırdı.",
    ],
  },
];
