// Ürün güncellemeleri — Ekim 2026 kayıtları (en yeniden eskiye).
// Tek kaynak barrel: ../admin-updates.ts — ekranlar oradan okur, buradan DEĞİL.

import type { AdminUpdateEntry } from "./types.ts";

export const ADMIN_UPDATES_2026_10: AdminUpdateEntry[] = [
  {
    id: "20261003-kurumsal-dogrulama-basvuru-formu",
    date: "3 Ekim 2026",
    title: "Kurumsal doğrulama başvurusu artık ekranda — kuruluş kaydını belgeyle doğrulat (deploy kuyruğunda)",
    items: [
      "NE GELDİ: Dün kurulan kurumsal doğrulama altyapısının (belge kovası + talep kuyruğu) üye tarafındaki ekranı hazır. Bir dernek/okul/kuruluş kaydının temsilcisi, kayıt sayfasında tüzük veya yetki belgesini yükleyip doğrulama talebi açabiliyor; talep yönetici kuyruğuna düşüyor.",
      "ÖNCE KAYDI SAHİPLEN (iki adım): 262 kurumsal kaydın 249'unda kaydı temsil eden hiçbir kişi bağı yok (sahipsiz içe aktarılmış kayıtlar). Bu yüzden bağı olmayan kullanıcıya belge formu GÖSTERİLMİYOR — bunun yerine 'önce kaydı sahiplen' (düzenleme yetkisi) yolu gösteriliyor. Yalnız temsil yetkisi olan başvuru yapabiliyor. Bu bilinçli: sahipsiz bir kaydı doğrulatmak, o kurumu temsil etmekle aynı şey değil.",
      "BELGE GÜVENLİĞİ: Belgeler dışarıya kapalı özel alanda duruyor; yalnız yükleyen kişi ve yöneticiler, o da süreli bağlantıyla açabiliyor (herkese açık bağlantı üretilmiyor). Dosyanın ham adı depolama anahtarına girmiyor (dizin dışına çıkma denemeleri kapatılıyor). Tür, dosyanın içeriğinden değil uzantısından belirleniyor — dar liste: PDF/JPG/PNG/WebP, dosya başına en çok 15 MB, en çok 5 belge.",
      "KANIT: 26 test (17 sözleşme + 9 bileşen) yeşil; kod 6 yerden bilerek bozuldu (mutasyon) ve testler her seferinde yakaladı. Canlı kova ölçüldü: özel · 15 MB · 4 tür · 'her şeyi kabul et' türü YOK · başvuru fonksiyonu anonime kapalı, üyeye açık.",
      "KALAN: Yönetici inceleme ekranı (kuyruk + belge önizleme + onayla/reddet) sırada. Bu form üye tarafıdır ve bir sonraki frontend deploy'ında canlıya çıkar.",
    ],
  },
  {
    id: "20261003-kurumsal-dogrulama-altyapisi",
    date: "3 Ekim 2026",
    title: "Kurumsal doğrulama altyapısı kuruldu — dernek/okul/kuruluş kayıtları için belgeli başvuru",
    items: [
      "NE GELDİ: Bir kuruluş kaydının “doğrulanmış” sayılabilmesi için belgeli başvuru altyapısı canlıda. Başvuran tüzük/yetki belgesini yüklüyor, kayıt yönetici kuyruğuna düşüyor. Onay kimin, ne zaman verdiği artık kayıt altında tutuluyor — eskiden bu iz hiç yoktu.",
      "YENİ BİR “SEVİYE” ALANI AÇILMADI: Kayıtta zaten iki doğrulama alanı vardı; üçüncüsünü eklemek aynı bilginin birbirini tutmayan üç kopyasını üretirdi. “Seviye 2” artık mevcut doğrulama durumundan türetiliyor, ayrıca saklanmıyor.",
      "ÖNEMLİ ÖLÇÜM — AKIŞ BUNA GÖRE KURGULANDI: 262 kurumsal kaydın 249’unda kaydı temsil eden hiçbir kişi bağı yok (bunlar toplu aktarılmış sahipsiz kayıtlar). Bu yüzden doğrulama başvurusu için önce kaydı sahiplenmek gerekiyor; sahipsiz bir kaydı doğrulatmak o kurumu temsil etmekle aynı şey değil.",
      "BELGE GÜVENLİĞİ: Belgeler dışarıya tamamen kapalı özel bir alanda duruyor; yalnız belgeyi yükleyen kişi ve yöneticiler, o da süreli bağlantıyla açabiliyor. Başkasının klasörüne yazma ve başkasının belgesini kendi başvurusuna iliştirme yolları ayrı ayrı kapatıldı.",
      "KANIT: 15 kabul kontrolü canlı veritabanında, geri alınan bir işlem içinde ölçüldü (başvuru açma, mükerrer başvurunun reddi, zaten doğrulanmış kayıt, kurumsal olmayan kayıt, yetkisiz klasör, belgesiz başvuru, oturumsuz erişim). Canlıda hiçbir iz bırakılmadı.",
      "KALAN: Üyenin göreceği başvuru formu ve yöneticinin kullanacağı inceleme ekranı sırada. Bugün kurulan kısım altyapı — ekran gelmeden kullanıcıya görünmez.",
    ],
  },
  {
    id: "20261003-grup-sahipligi-rol-yukseltme",
    date: "3 Ekim 2026",
    title: "Grup sahipliğini doğrulayan üyeye artık rolü gerçekten veriliyor (sessiz kusur kapandı)",
    items: [
      "SORUN NEYDİ: Bir üye grubunun sahipliğini doğruladığında kendisine “WhatsApp/Telegram/Discord Yöneticisi” rolü verilmesi gerekiyordu. Ama sistem kimseye veremiyordu: kayıt olan herkese otomatik olarak varsayılan üye rolü atanıyor ve sistem “mevcut rolü ezme” kuralı yüzünden her seferinde atlıyordu. Hata vermiyordu — sadece olmuyordu.",
      "ÇÖZÜM: Artık YALNIZ varsayılan üye rolü yükseltiliyor. Süper Admin, danışman, kuruluş ve özel roller eskisi gibi korunuyor — bir Süper Admin grubunu doğrulayınca Süper Adminliğini kaybetmiyor.",
      "ÖLÇÜM: Sistemdeki 175 üyenin tamamının tek rolü var. 148’i varsayılan rolde (yükseltmeye açık), 27’si başka rollerde (korunuyor).",
      "KANIT: 10 kontrolün tamamı canlıda, geri alınan işlem içinde ölçüldü — varsayılan rol yükseldi, Süper Admin ve danışman rolleri ezilmedi, rolü olmayan kullanıcıya rol atandı, kullanıcı başına tek rol kuralı korundu.",
    ],
  },
  {
    id: "20261003-cadde-kimlik-isareti",
    date: "3 Ekim 2026",
    title: "Cadde’ye kimlik işareti (logo) eklendi — deploy kuyruğunda",
    items: [
      "NE GELDİ: Burak’ın verdiği Cadde logosu, akışın filtre şeridinin sol ucuna küçük bir kimlik işareti olarak yerleşti.",
      "SAYFADAN YER ÇALMIYOR: İşaret kendi şeridini açmıyor, var olan filtre satırının içinde duruyor ve satırın yüksekliğini değiştirmiyor. Akışın üstüne blok eklenmedi — paylaşım kutusunu aşağı iten eski düzen sorunu geri getirilmedi.",
      "DOSYA DÜZELTİLDİ: Gelen görselin arka planı şeffaf değildi; olduğu gibi konsaydı koyu temada beyaz bir kutu olarak görünecekti. Arka plan gerçekten saydamlaştırıldı, kenar boşlukları kırpıldı ve dosya 3 MB’tan 220 KB’a indi (sayfa açılış hızı için önemli).",
      "DEĞİŞMEYEN: Cadde’nin bronz kurumsal rengi aynen duruyor; logo renkli, arayüz rengi bronz — ikisi ayrı iştir.",
      "NE ZAMAN GÖRÜNÜR: Bir sonraki frontend deploy’unda.",
    ],
  },
  {
    id: "20261003-davet-liderligi",
    date: "3 Ekim 2026",
    title: "Davet sistemi açıldı — /liderlik sayfası, davet kodu ve QR (deploy kuyruğunda)",
    items: [
      "LİDERLİK TABLOSU: Yeni herkese açık sayfa /liderlik — topluluğa en çok arkadaşını davet eden üyeler sıralanıyor. Giriş yapmadan da gezilebilir; liste dizinin görünürlük kurallarıyla aynıdır (yönetici, test ve yer tutucu kayıtlar SQL seviyesinde elenir — ekranda da doğrulandı).",
      "DAVET KARTI: Girişli üye profilindeki hızlı işlemlerden veya /liderlik sayfasından davet kodunu alır: kod + paylaşılabilir link + QR kodu + tek tıkla kopyalama. Kod kişi başına tektir ve aynı kalır.",
      "ROZETLER: Davet sayısıyla kazanılır (3+ · 10+ · 25+). Eşikler ayar tablosundan yönetiliyor — değiştirmek kod işi değil. Bir üye yalnız bir kez sayılır; kendi kodunu kullanmak reddedilir.",
      "KANIT: Gerçek veriyle uçtan uca ölçüldü: davet kodu üretildi → ikinci üye kullandı → liste HTTP üzerinden anonim okundu (doğru üye göründü, YÖNETİCİ hesabı kullanımına rağmen görünmedi, yer tutucu başlık düşürüldü) → ölçüm satırları temizlendi, canlı başlangıç durumunda.",
      "SIRADAKİ: Davet linkiyle gelen ziyaretçinin kayıt akışında otomatik sayılması (M13) — davet bonusu kaydı asla bloklamayacak şekilde bağlanıyor.",
    ],
  },
  {
    id: "20261003-profil-baslangic-kartlari",
    date: "3 Ekim 2026",
    title: "Profilin ilk ekranına üç yeni kart geldi — hızlı işlemler, başlangıç adımları ve “yakında” vitrini (deploy kuyruğunda)",
    items: [
      "HIZLI İŞLEMLER: Profilin ilk ekranında (tüm rollerde) kısayol kartı: “Etkinlik oluştur” ve “Grup ekle”. Listeye “Davet et” ve “Tavsiye iste” kendi modülleri geldiğinde eklenecek — çalışan rotası olmayan düğme konmuyor.",
      "BAŞLANGIÇ ADIMLARI: Dört satırlık ilerleme kartı — profilini tamamla (zorunlu alan sayın gerçek kayıtlardan), ilk hizmet/ürününü ekle (Çarşı ilanların), ilk etkinliğini oluştur, 3 arkadaşını davet et. Tamamlanma GERÇEK veriden okunuyor; davet satırı sistem gelene kadar “yakında” diye PASİF duruyor — sahte tik yok.",
      "YAKINDA · ÜCRETLİ ÖZELLİKLER: “Öne çıkar” ve “Bilet sat” KİLİTLİ kart olarak duruyor (ödeme kapsam dışı, ayrı plan). “İlgileniyorum” diyenin kaydı alınıyor — hangi ücretli özelliğin önce yapılacağına bu ilgi birikimi karar verecek. İlgi kaydı silinemez ve aynı kişi iki kez sayılmaz.",
      "KANIT: İlgi kaydı canlıda ölçüldü (geri alınan işlem): kayıt satırı oluştu · ikinci tık “zaten kayıtlı” dedi, tek satır kaldı · listede olmayan anahtar reddedildi · giriş yapmamış kullanıcı hiç kayıt açamadı · işlem geri alınca canlıda iz kalmadı. Ekranlar bir sonraki frontend deploy’unda görünür.",
    ],
  },
  {
    id: "20261003-etkinlik-motoru-faz1",
    date: "3 Ekim 2026",
    title: "Etkinlik motoru Faz 1 hazır — ilk-onay kuralı, kontenjan ve katılım düğmesi (arayüz deploy kuyruğunda)",
    items: [
      "İLK-ONAY KURALI ARTIK VERİTABANINDA: Bir üyenin İLK etkinliği yönetici onayına düşer; onaydan sonraki etkinlikleri otomatik yayınlanır. Bu kural eskiden yalnız ekran kodundaydı — isteyen teknik yoldan atlayabilirdi. Artık kural sunucuda: doğrudan “yayınlandı” yazmayı deneyen istek reddediliyor (ölçüldü), durum değişikliğini yalnız moderatör yapabiliyor.",
      "KONTENJAN SINIRI: Etkinlik sahibi “maks. katılımcı” verdiyse kontenjan dolduğunda katılım SUNUCUDA kapanır — iki kişi aynı anda basarsa bile kontenjan aşılamaz (yarış kilidi veritabanında).",
      "KATILIM DÜĞMESİ: Etkinlik detayına “Etkinliğe katıl / Katılımdan ayrıl” düğmesi geldi; kaç kişinin katıldığı ve kapasite yanında görünür. Kontenjan dolunca düğme “Kontenjan dolu” diye pasifleşir. Giriş yapmamış ziyaretçi önce girişe yönlendirilir. Katılanların listesi kimseye gösterilmez — yalnız sayı.",
      "AKTİF ETKİNLİK LİMİTİ: Aynı anda en fazla 2 aktif (gelecek tarihli, yayında) etkinlik — geçmiş etkinlikler sayılmaz. Limit ayar tablosundan yönetiliyor.",
      "ETKİNLİKLERİM PANELİ: Kural artık kullanıcıya açıkça anlatılıyor: “İlk etkinliğin onaydan geçer, sonrakiler otomatik yayınlanır; en fazla 2 aktif etkinliğin olabilir (şu an N).”",
      "KANIT: Tam zincir canlıda geri alınan işlemle ölçüldü (8/8): ilk etkinlik onay kuyruğuna düştü → moderatör yayınladı → ikincisi otomatik yayın → üçüncüde limit reddi → doğrudan “yayınlandı” yazma denemeleri İKİ katmanda da reddedildi → katılım/ayrılma/kontenjan zinciri doğru → ziyaretçiye yalnız sayı göründü. İşlem geri alındığı için canlıda iz bırakmadı.",
      "NOT: Veritabanı tarafı şu an bile geçerli (eski ekran da yeni kurallara uyuyor); katılım düğmesi ve yeni metinler bir sonraki frontend deploy'unda görünür olacak.",
    ],
  },
  {
    id: "20261003-cadde-gonderi-duzenleme",
    date: "3 Ekim 2026",
    title: "Cadde'de paylaşım düzenleme açıldı — artık silmek zorunda değilsin",
    items: [
      "DÜZENLE MENÜDE: Kendi paylaşımının üç nokta menüsünde “Düzenle” var. Composer aynı kutuda düzenleme moduna geçer: metin, medya ve konum ön dolu gelir; “Kaydet” ile güncellenir, “Vazgeç” ile hiçbir şey değişmez.",
      "NE DEĞİŞİR, NE DEĞİŞMEZ: Metin, görsel/video ve ülke-şehir hedefi düzenlenebilir. @anmaların KORUNUR (metinden silsen bile anma kayıtları durur), #etiketler yeni metinden otomatik tazelenir. Paylaşımın tipi ve kafe bağlantısı değişmez.",
      "SINIRLAR: Aynı kurallar düzenlemede de geçerli — metin 4000 karakter, en fazla 4 görsel + 1 video, tek hedef (birden fazla hedef premium kapsamında ve şimdilik kapalı). Boş paylaşım kaydedilemez (metin silinecekse medya da silinmeli).",
      "GÜVENLİK: Düzenleme yetkisinin gerçek denetimi veritabanında — yalnız paylaşım sahibi (veya admin/moderatör) kaydedebilir; başkasının paylaşımında menü hiç görünmez, görünse bile sunucu reddeder. Canlıda 10 senaryoyla ölçüldü (hepsi geri alınan işlemde): sahip düzenledi · anmalar korundu · etiket tazelendi · medya temizlendi · hedef değişti · ikinci hedef premium kapısına takıldı · sahip olmayan reddedildi · gizli paylaşım 'yok' sayıldı · kafe paylaşımında hedef yok sayıldı · 4001 karakter reddedildi.",
      "NOT: Bu ekran da bir sonraki frontend deploy'unda canlıya çıkar (veritabanı tarafı zaten çalışıyordu, şimdi arayüzü bağlandı).",
    ],
  },
  {
    id: "20261003-deploy-sonrasi-guvenlik-ve-skorlar",
    date: "3 Ekim 2026",
    title: "Deploy tamam: yeni grup ekranları canlıda, link sızıntısı KAPANDI, grup skorları görünür oldu",
    items: [
      "YENİ EKRANLAR CANLIDA: Grup ekleme formu, yeni dizin dili (Sahibi doğruladı / Üye önerisi / Yeni / Onaylı Grup rozetleri), grup detayı + “Bu grup sizin mi?” sahiplenme akışı, sahip paneli ve moderatör paneli (/admin/gruplar) artık sitede çalışıyor. Deploy sonrası ziyaretçi turu doğrulandı: dizin 10 grubu yeni kolonlarla dönüyor.",
      "🔒 GÜVENLİK KUSURU KAPANDI: Grup davet linkleri ve yönetici iletişim bilgileri, eski tablo yetkisi yüzünden giriş yapmamış ziyaretçilere teknik olarak okunabiliyordu (ekranda gösterilmese bile). Deploy doğrulanır doğrulanmaz tablo yetkisi daraltıldı: giriş yapmayana tablo artık tamamen kapalı — linkler yalnız girişli kullanıcıya, grup sayfasında, tek kapıdan veriliyor. Dört yolun dördü de yeniden ölçüldü (4/4 temiz). Ek önlem: giriş yapmamış rolün tablo üzerindeki silme/biçme yetkileri de kaldırıldı.",
      "SKORLAR GÖRÜNÜR OLDU: Günlük skor hesabının anahtarı (deploy bekliyordu) açıldı ve ilk hesap koştu: 10 grubun skoru yazıldı. Bugünkü taban 35/100 (çalışan link + şikayetsizlik kalemleri); profil, kurallar ve sahiplik doğrulandıkça skor ve “Onaylı Grup” rozeti kendiliğinden yükselecek. Kartlar artık doğru ölçekle “35 / 100” çiziyor.",
      "ESKİ SİSTEM BOZULMADI: Admin moderasyon ekranı ve editör akışları aynen çalışıyor (yetki daraltması yalnız giriş yapmamış rolü etkiledi).",
    ],
  },
  {
    id: "20261002-grup-motoru-kabul-testleri",
    date: "2 Ekim 2026",
    title: "Grup motorunun 13 kabul testi tek betikte — QA turu bir gerçek kusuru daha yakaladı",
    items: [
      "QA BETİĞİ: Motorun 13 kabul testinin 12'si tek komutla yeniden koşulan, KENDİNİ DOĞRUAYAN bir canlı betiğe bağlandı (her senaryo veritabanı üzerinde iddialı; hepsi geri alınan işlemde — canlıya dokunmaz). Anonim ziyaretçinin link/panel/kuyruk göremediği bölüm gerçek rollerle ayrıca ölçülüyor.",
      "KUSUR YAKALANDI VE ONARILDI: “Grup için bir ihlal kaydı oluştu” uyarı maili hiçbir zaman gitmeyecekti — bildirim, ihlalin log satırına bağlanmıştı ama ilk ihlal (uyarı) log üretmiyor. Uyarı artık doğrudan ihlal kaydı tablosuna bağlı: her ihlal = tek mail; askı/kaldırma sonucu da mailin sebep alanına işleniyor. Çift mail riski de kapatıldı.",
      "MUTASYON SINAVI: Testlerin gerçekten test olduğu kanıtlandı — “bilinmeyen link sonucu sayacı bozmasın” kuralı, “Aile & Çocuk kilidi” ve “anonime link sızmaz” kuralı canlıda bilerek BOZULDU; betik üçünde de kızardı, kurallar geri yüklendi ve canlı yeniden ölçüldü.",
      "ŞİKAYET TESTİ BİLİNÇLİ BEKLEMEDE: Şikayet eşiği kabulü (#6) telefon doğrulamasına bağlı altyapıyı bekliyor. Betikte tripwire var: şikayet tablosu ortaya çıktığı an QA kızarır ve o kabul testi yazılmak zorunda kalır — unutulamaz.",
      "RAPOR: 13 kabulün tamamı, kanıt değerleri ve mutasyon sonuçları docs/dijital-gruplar/2026-10-02-g25-kabul-raporu.md dosyasında. Tam test takımı 417 dosya / 3440 test yeşil.",
    ],
  },
  {
    id: "20261002-grup-moderator-paneli",
    date: "2 Ekim 2026",
    title: "Grup moderatör paneli hazır — dört kuyruk tek ekranda (/admin/gruplar, deploy kuyruğunda)",
    items: [
      "TEK EKRAN DÖRT KUYRUK: Yeni gruplar · sahiplik talepleri (ekran görüntüsü yöntemi) · şikayetler · platform gönderi kuyruğu. Klavye kısayolları: J/K gez, A onayla, R reddet (hazır sebep listesi + not). Reddin sebebi üyeye giden bildirim mailine yazılıyor.",
      "ÜST ŞERİT: Kuyruk sayaçları · moderasyondan geçen grup sayacı (x/100 — eşik dolunca “hızlı şeridi aç” önerisi görünür, karar insanın) · hızlı şerit anahtarı (ayar tablosuna yazar; anahtar listesi DAR: panelden yalnız bu tek ayar değişebilir, eşikler ürün kararı olarak kalır) · 6 zamanlanmış görevin son koşu durumları.",
      "TEK TIK KARARLAR: Grup yayınla/reddet · uyarı ver (ihlal merdiveni otomatik: 1. uyarı → 2.’de 30 gün askı → 3.’te kaldırma+yasak; kırmızı çizgi seçilirse ilk ihlalde kaldırır) · sahipliği onayla/reddet (onay, sahipliği doğrulanmış yapar) · gönderi onayla/reddet. Ekran görüntüsü kanıtları 5 dakikalık imzalı bağlantıyla açılır (kova private kalır).",
      "ŞİKAYET KUYRUĞU BİLİNÇLİ BOŞ: Altyapısı telefon doğrulamasına bağlı (G14) — o güne dek sekme boş durumu açıklıyor, sayaç 0 dönüyor. Uydurma veri yok.",
      "KANIT: Sunucu kapıları canlıda ölçüldü (geri alınan işlem): üye ve anonim özeti OKUYAMIYOR · anahtarı yalnız admin yazıyor (iz: updated_by) · beyaz liste dışı anahtar ve tip reddi · kuyruk sayacı gerçek gönderiyle 0→1 hareket etti · görev koşuları gerçek cron verisinden (claim-expiry 22:30’da succeeded). Ekran deploy kuyruğunda (form/dizin/detay ile aynı).",
    ],
  },
  {
    id: "20261002-grup-bildirimleri",
    date: "2 Ekim 2026",
    title: "Grup bildirimleri canlıda — 8 olayda üyeler artık otomatik e-posta alıyor",
    items: [
      "8 BİLDİRİM: “Grubun alındı” (inceleme genelde 24 saat) · “{Grup} yayında — sayfanı paylaş” · “Yayınlanamadı + sebep + Grup Sözü linki” · “Sahiplik doğrulandı — kodu grup adından silebilirsin” · “Onay bekleyen {n} gönderi var, 48 saatte bakmazsan ekip devralır” · “Davet linkin çalışmıyor, grup geçici gizlendi” · “Tebrikler, Onaylı Grup oldun — rozet görselin hazır” · “İhlal kaydı oluştu: {sebep}”. Metinler tasarım dokümanındaki tabloyla birebir (testle kilitli).",
      "NASIL ÇALIŞIYOR: Bildirimler veritabanı tetikleyicilerinden kuyruğa düşüyor ve anında gönderiliyor (akşam özeti beklenmiyor — bunlar işlemsel bildirimler). Kimse kimsenin adresini görmüyor; her mail tek alıcıya gidiyor.",
      "SPAM KORUMASI: “Onay bekleyen gönderi” maili grup başına GÜNDE BİR kez gelir (içinde güncel sayıyla). Hızlı şeritle yayına çıkan grup hem “alındı” hem “yayında” maili ÜRETMEZ — yalnız “yayında”.",
      "GÜVENLİK: Mail içeriğine davet linki ASLA konmuyor (kural 8) — {link} alanları site sayfası; davet linki yalnız girişli kullanıcıya grup sayfasında. Test satırları dahil hiçbir kuyruk kaydına link yazılmadı (canlıda tarandı: 0 sızıntı).",
      "KANIT: 8 olayın 8’i de canlıda uçtan uca doğrulandı — tetikleyiciler geri alınan işlemde ölçüldü (8/8 olay tipi üretildi, gün-dedupe çalıştı, toplu-işlem bayrağı susturdu), ardından 8 gerçek mail yönetici adresine gönderildi: 8/8 “sent”, alıcı sayısı 1, hata yok. Test satırları silindi. Her bildirim tipi admin panelindeki Bildirim Ayarları anahtarlarıyla kapatılabilir.",
    ],
  },
  {
    id: "20261002-grup-motoru-zamanlanmis-gorevler",
    date: "2 Ekim 2026",
    title: "Grup motorunun 6 zamanlanmış görevi canlıda — link sağlığı çalışmaya başladı",
    items: [
      "LİNK SAĞLIĞI (çalışıyor): Her grubun davet linki haftada bir, günlere/saatlere YAYILMIŞ biçimde sunucu tarafında kontrol ediliyor. Sonuç üç değerli: çalışıyor / ölü / okunamadı. Üst üste 2 ölü kontrol grubu gizler (sebep: link_dead) ve admin kuyruğuna düşürür; 1 başarılı kontrol gizli grubu GERİ AÇAR. “Okunamadı” sonucu gruba asla mal edilmez — sayaç artmaz (ağ hatası yüzünden kimse gizlenmez). İlk gerçek tur koştu: 1 grup kontrol edildi, sonuç “okunamadı” (sayaç 0 kaldı).",
      "KUYRUK ESKALASYONU (saatlik): Grup admininin 48 saat içinde bakmadığı gönderiler otomatik olarak platform ekibinin kuyruğuna geçiyor.",
      "ASKI BIRAKMA (günlük): 30 günlük askı süresi dolan gruplar otomatik yayına dönüyor.",
      "SAHİPLİK YENİLEME (günlük): Doğrulanmış sahipler yılda bir kısa onay veriyor (panelde “Yenileme onayını ver” düğmesi). 30 gün yanıt gelmezse sahiplik düşer ve grup yeniden “üye önerisi” durumuna geçer.",
      "KOD SÜRESİ (10 dakikada bir): Sahiplik doğrulama kodlarının süresi dolunca kayıtları otomatik kapanıyor — “grup başına tek aktif kod” kuralı boşa işgal edilmiyor.",
      "⚠️ SKOR HESABI BİLEREK KAPALI: Günlük sağlık skoru görevi kuruldu ama ANAHTARI KAPALI. Sebep: canlı site hâlâ eski kartı çiziyor ve yeni 0-100 skorları “35 / 10” gibi bozuk gösterirdi. Yeni ekranlar deploy edildikten sonra anahtarı insan kararıyla açacağız (tek ayar satırı).",
      "KANIT: Görevlerin tamamı canlı veritabanında geri alınan bir işlemde 8 senaryoyla ölçüldü (2 ölü link → gizledi → başarılı kontrol → geri açtı dahil); görev fonksiyonları üyelere kapalı, yalnız sistem rolü çağırabiliyor. Zamanlayıcıya 6 yeni iş kaydedildi.",
    ],
  },
  {
    id: "20261002-grup-sahip-paneli",
    date: "2 Ekim 2026",
    title: "Grup sahibi paneli hazır — skor rehberi, onay kuyruğu, düzenleme, listeden kaldırma (deploy kuyruğunda)",
    items: [
      "SAHİP PANELİ: Grubun doğrulanmış sahibi grup sayfasında kendi panelini görüyor: sağlık skoru kalem kalem + eksik adım rehberi (“Kurallarını ekle, +15” gibi), onay bekleyen gönderiler, bilgi düzenleme ve “Grubu listeden kaldır”. Sahip olmayan ziyaretçiye panel HİÇ çizilmiyor — sunucu da panel verisini yalnız sahibe veriyor (başkasına tek alan dönüyor: “sahip değil”).",
      "ONAY KUYRUĞU SAHİPTE: Gruba düşen gönderiler önce sahibin onayına düşüyor (48 saat içinde bakmazsa ekibimizin kuyruğuna geçiyor — uyarı panelde yazılı). Sahip tek tıkla onaylıyor ya da reddediyor.",
      "LİSTEDEN KALDIRMA ANINDA: Doğrulanmış sahip “Grubu listeden kaldır”a basınca grup ANINDA gizleniyor — gerekçe SORMUYORUZ (politika: sahip istemezse 24 saat). 24 saat içinde moderatör kalıcı kaldırmaya çeviriyor. İki adımlı onay var, yanlışlıkla basılamıyor.",
      "DÜZENLEME SKORU BESLİYOR: Sahip kısa açıklamayı, kuralları, kategoriyi, şehri/ülkeyi, vurgu cümlesini ve görseli değiştirebiliyor; skor ertesi günkü günlük hesapta güncelleniyor. “Aile & Çocuk” kategorisi burada da doğrulama altyapısına kadar kilitli.",
      "ROZET GÖRSELİ: “Onaylı Grup” rozetini kazanan gruplar, Instagram’da paylaşılabilir 1080x1080 rozet görselini panelden indirebiliyor (grup adı + skor yazılı).",
      "⚠️ EKRAN DEPLOY BEKLİYOR: Sunucu tarafı canlıda ve doğrulandı (kaldırma isteği canlı ölçümde grubu anında dizinden düşürdü, sonra geri alındı); panel ekranı form + dizin + detay ile aynı deploy kuyruğunda.",
    ],
  },
  {
    id: "20261002-grup-sahipligi-ekrani",
    date: "2 Ekim 2026",
    title: "“Bu grup sizin mi?” — grup sahiplenme ekranı hazır (deploy kuyruğunda)",
    items: [
      "SAHİPLENME EKRANI: Her grup sayfasının altında “Bu grubun admini misin?” bölümü açıldı. İki yol var: (1) KOD — sistem 10 dakikalık tek kullanımlık bir kod üretir (CQ+4 hane), kodu grup adının sonuna eklersin, “Kontrol et”e basınca sistem grup adını SUNUCUDA okur ve kodu bulursa sayfa sana bağlanır; (2) EKRAN GÖRÜNTÜSÜ — kodla olmuyorsa admin panelinin ekran görüntüsünü yüklersin, talep moderatör kuyruğuna düşer.",
      "GÜVENLİK: Doğrulamada 3 deneme hakkı var; linki ölü ya da okunamayan gruplarda deneme YANMAZ (sistem hatası kullanıcıya mal edilmez). Ekran görüntüleri yalnızca kişinin kendi özel klasörüne yazılır — başkasının kanıtını kimse göremez, silmeyi yalnız admin yapabilir. Günlük talep sınırı ayar tablosundan yönetiliyor.",
      "GRUP ZATEN SAHİPLENİLMİŞSE: Otomatik devir YOK. Ekran görüntüsüyle itiraz edilebilir, kararı moderatör verir; mevcut sahibe haber gider (bildirim altyapısı M4’te bağlanacak).",
      "ANONİM ZİYARETÇİ GÜVENCESİ (kabul testi): Giriş yapmamış ziyaretçi için davet linki sayfa kaynağı dahil HİÇBİR YERDE görünmüyor — “Katıl” düğmesi önce giriş istiyor. Bu davranış otomatik testlerle kilitlendi.",
      "EKSİK BÖLÜM DÜZELTİLDİ: “Grup koşulları” bölümü boşken artık hiç çizilmiyor (boş başlık görünmüyor).",
      "⚠️ “ŞİKAYET ET” BİLEREK YOK: Şikayet altyapısı telefon doğrulamasına bağlı (K09/U06 kararı bekleniyor). Arkasında sistem olmayan bir buton koymak yerine hiç konmadı — altyapı gelince eklenecek.",
      "⚠️ EKRAN DEPLOY BEKLİYOR: Veritabanı tarafı zaten canlıydı ve yeniden doğrulandı; ekran, form + dizin ile aynı deploy kuyruğunda.",
    ],
  },
  {
    id: "20261002-grup-dizini-yeni-dil",
    date: "2 Ekim 2026",
    title: "Grup dizininin yeni dili hazır — sahiplik rozetleri, “Yeni” etiketi, 0-100 skor (deploy kuyruğunda)",
    items: [
      "ROZET DİLİ DEĞİŞTİ: Kartlardaki “Admin onaylı!” / “Üye onaylı!” rozetleri kalktı. Yerine politikanın dili geldi: “Sahibi doğruladı” (gerçek admin ekledi ve kanıtladı), “Üye önerisi” (admin olmayan biri önerdi, sahiplenilmedi), “Yeni” (ilk 72 saat) ve “Onaylı Grup” (sağlık skoru 70+).",
      "“SKOR BEKLENİYOR” KUTUSU KALKTI: Skor hesaplanana kadar kartta skor alanı hiç gösterilmiyor (politika kuralı). Skor gelince 0-100 ölçeğinde “Grup Sağlık Skoru” olarak görünüyor — eski “X / 10” dili bitti.",
      "GİZLİ BİR KUSUR KAPATILDI: Yeni moderasyon motoru bir grubu gizlediğinde/askıya aldığında, dizinin okuduğu eski görünüm yalnızca eski onay alanına baktığı için grup SİTEDE GÖRÜNMEYE DEVAM EDERDİ. Dizin artık her iki sisteme de bakıyor: motor “gizli/askıda/kaldırıldı” dediyse grup anında dizinden düşüyor (canlıda ölçüldü).",
      "SIRALAMA SKORA BAĞLANDI: Gruplar sağlık skoruna göre diziliyor (skoru yüksek olan üste); skoru henüz hesaplanmamış gruplar sonda kalıyor. “Yeni” etiketinin 72 saat eşiği ayar tablosundan yönetiliyor, koda gömülü değil.",
      "FİLTRE VE KARTLAR ARTIK AYNI LİSTE: Kategori filtreleri ile kart rozetleri tek kaynaktan besleniyor — eskiden iki ayrı liste vardı ve birbirinden sessizce kayabilirdi.",
      "⚠️ EKRAN DEPLOY BEKLİYOR: Veritabanı tarafı canlıda ve doğrulandı; yeni kart/filtre görünümü frontend deploy kuyruğunda (form ile aynı). Eski paket deploy’a kadar mevcut diliyle çalışmaya devam eder — hiçbir sayfa kırılmaz (canlı dizin içeriği bugün birebir aynı kaldı, 10 grup).",
    ],
  },
  {
    id: "20261002-grup-ekleme-formu-yenilendi",
    date: "2 Ekim 2026",
    title: "Grup ekleme formu baştan yazıldı — link yapıştır, gerisi otomatik (deploy kuyruğunda)",
    items: [
      "YENİ FORM: Kullanıcı fiilen üç şey yazıyor: link, kısa açıklama (en fazla 160 karakter), şehir. Linki yapıştırınca sistem davet sayfasını SUNUCU tarafında okuyor — grup adı ve görseli otomatik doluyor, platform (WhatsApp/Telegram/Discord) linkten tanınıyor. Platform seçimi ve serbest metin ülke/şehir alanları KALDIRILDI; konum artık coğrafi katalogdan seçiliyor (Global gruplar için hedef ülke + 'Genel').",
      "AYNI GRUP İKİ KEZ EKLENEMEZ: Davet linkinin kodu tekilleştirme anahtarı. Link zaten listedeyse form 'Bu grup zaten listede — sahibi misin?' uyarısı veriyor. Eskiden aynı linkle onlarca kayıt açılabiliyordu.",
      "KARA LİSTE ÖN TARAMASI: 'Vize, oturum, garanti, sinyal, yatırım getirisi, kredi' gibi kelimeler geçen gönderimler OTOMATİK REDDEDİLMİYOR — yalnızca işaretleniyor ve hızlı şeritten geçemiyor. Karar moderatörün (liste ayar tablosunda, kodda sabit değil).",
      "HIZLI ŞERİT HAZIR (ŞU AN KAPALI): Yönetici, kendi grubunu eklerken 'adminiyim' derse ve şerit açıksa grup anında yayına çıkar — karar moderasyon kayıt defterine 'fast_lane' olarak düşer. Normal üyelerde 'adminiyim' beyanı grubu yayına çıkarmaz; sahiplik doğrulama kuyruğu açılır. Şeridi açma kararı insanındır (100 grup önerisi).",
      "GÜNDE 5 GÖNDERİM SINIRI + GRUP SÖZÜ: Spam koruması olarak kullanıcı başına 24 saatte en fazla 5 gönderim (ayarlardan değiştirilebilir). Form, politika metnindeki 'Grup Sözü' onay kutusu işaretlenmeden gönderilemiyor. Yasaklı kullanıcı (ihlal sistemi) formu açtığında uyarıyı görüyor.",
      "⚠️ EKRAN DEPLOY BEKLİYOR: Yeni form, dizin/detay sayfalarıyla aynı kuyrukta — Coolify deploy'undan sonra canlıya çıkar. Eski form deploy'a kadar çalışmaya devam eder (sunucu tarafı kapılar her iki yolu da koruyor). 'Aile & Çocuk' kategorisi doğrulama altyapısı (kurumsal seviye) gelene dek kilitli.",
    ],
  },
  {
    id: "20261002-grup-saglik-skoru",
    date: "2 Ekim 2026",
    title: "Grup sağlık skoru motoru kuruldu — “Onaylı Grup” rozeti otomatik hesaplanacak (ekranlar henüz yok)",
    items: [
      "SKOR NEDİR: Her grup için 0-100 arası bir sağlık skoru hesaplayan motor kuruldu. Kalem kalem: profil bilgileri dolu mu (15), grup kuralları yazılı mı (15), sahibi doğrulanmış mı ve onay kuyruğunu 48 saat içinde eritiyor mu (15), davet linki çalışıyor mu (15), kaç üye “bu gruptayım, tavsiye ederim” dedi (20’ye kadar), son 90 günde onaylanmış şikayet var mı (20).",
      "ROZET KURALI — GİDİP GELMESİN DİYE: Skor 70’e ulaşan grup “Onaylı Grup” rozetini kazanır; rozet ancak skor 65’İN ALTINA düşünce geri alınır. Aradaki bantta rozet yerinde kalır — grup bir gün var bir gün yok diye titremez.",
      "İLK 7 GÜN SKOR YOK: Yeni bir grup yayına çıkınca ilk 7 gün skor hesaplanmaz (boş kalır) — yeni grup “puanı düşük” diye cezalı görünmesin.",
      "TAVSİYE SİSTEMİ: Üyeler bir grup için “tavsiye ederim” diyebilecek; aynı kişi aynı grubu iki kez sayılmaz, tavsiyesini geri çekebilir. İlk 10 tavsiye skora puan olarak yansır, sonrası yansımaz (skor şişirilmesin).",
      "⚠️ EKRANLAR HENÜZ YOK: Bu da altyapı işi — skor kartlarda G19 (dizin), sahip panelinde G21, günlük otomatik hesap ise G22’de bağlanacak. Bugün canlıda hiçbir grubun skoru değişmedi; motorun bütün davranışı canlı veritabanında GERİ ALINAN bir işlemde 16 senaryoyla ölçüldü.",
      "SESSİZ BİR HATA BULUNDU VE KAPATILDI: Eski yönetici ekranı, bir grup kaydını her düzenleyip kaydettiğinde skor alanını sessizce SIFIRLIYORDU (kimse fark etmiyordu çünkü skorlar henüz boştu). Skor sistemi devreye girmeden önce bu davranış ölçüldü ve kapatıldı: skor artık yalnızca motorun kendisi tarafından yazılır; grup sahibi kendi skorunu elle yükseltemez.",
    ],
  },
  {
    id: "20261002-kariyer-sayfasi-ve-basvuru-sistemi",
    date: "2 Ekim 2026",
    title: "Kariyer sayfası baştan yazıldı — 17 ilan, başvuru formu ve yönetici ekranı artık çalışıyor",
    items: [
      "ÖZET: /kariyer sayfası eskiden yalnızca bir ilgi formuydu. Artık gerçek bir işe alım sayfası: 17 açık pozisyon, staj programı, kurucu mektupları ve dosya yükleyebilen bir başvuru formu var.",
      "ZİYARETÇİ NE GÖRÜYOR: İlanlar 5 alana göre süzülebiliyor (çiplere tıklayarak). Bir ilanda “Bu pozisyona başvur” denince seçim otomatik olarak alttaki forma taşınıyor ve sayfa oraya kayıyor. Her ilanın kendi bağlantısı var, yani tek bir ilanı doğrudan paylaşabilirsiniz.",
      "BAŞVURU FORMU: Ad, iletişim, pozisyon seçimi ve üç dosya — CV (zorunlu, en çok 10 MB), ön yazı ve sunum (en çok 25 MB). Dosyalar sürükle-bırak ile de yüklenebiliyor. KVKK onay kutusu BOŞ geliyor; kullanıcı işaretlemeden başvuru gönderilemiyor.",
      "ESKİ İLANLAR SİLİNMEDİ: Önceki dönemin 4 ilanı sayfanın altında “önceki dönem ilanı” rozetiyle duruyor ve onlardan gelen başvurular da aynı yeni sisteme düşüyor. Ne zaman kaldırılacağına ekip karar verecek — yeni ilanlar üzerinden en az bir tam başvuru dönemi geçtikten sonra.",
      "➡️ SİZDEN NE GEREKİYOR — BAŞVURULARI BURADAN OKUYUN: /admin/kadro → “Başvurular”. Yeni bir yönetici grubu açılmadı; mevcut kadro konsoluna 5. madde olarak eklendi. Adayın CV’si ve diğer dosyaları buradan açılıyor.",
      "E-POSTA BİLDİRİMİ AÇIK: Yeni başvuru geldiğinde kurucu ekibe anında mail gidiyor. Bu bildirim TÜM yöneticilere gider — ayrıca abone olmanıza gerek yok, istemeyen kapatır. Canlıda uçtan uca denendi: başvuru girildi, mail 3 saniyede gönderildi, deneme kaydı sonra silindi.",
      "⚠️ GÜVENLİK NOTU — CV’LER MAİLE KONMUYOR: Mailde yalnızca “yeni başvuru var” bilgisi ve adayın adı var; dosya bağlantısı YOK. Sebebi şu: maile gömülen bağlantı posta kutusunda süresiz durur ve o maili ilettiğiniz herkes adayın CV’sini açabilir. Dosyalar yalnızca panelden, 5 dakika geçerli özel bağlantıyla açılıyor.",
      "GELEN HAZIR PAKETTEKİ 3 HATA DÜZELTİLDİ: Dışarıdan gelen kurulum dosyası olduğu gibi çalıştırılsaydı sistem hiç kurulamayacaktı. Ayrıca yüklenen dosyanın adı hiç denetlenmiyordu ve “her türü kabul et” ayarı yüzünden depoya çalıştırılabilir dosya bile konabiliyordu. Üçü de kapatıldı ve canlıda 10 çağrıyla sınandı: izinsiz dosya türü, kural dışı dosya adı ve girişsiz okuma denemelerinin üçü de reddedildi.",
    ],
  },
  {
    id: "20261002-dijital-gruplar-motoru",
    date: "2 Ekim 2026",
    title: "Dijital Gruplar motoru kuruldu — doğrulama, moderasyon ve uyarı sistemi (ekranlar henüz yok)",
    items: [
      "NEDEN: Fikir şu — “Linkini saklama, kapını paylaş.” Ham WhatsApp davet linki ortalıkta dolaşmak yerine CorteQS grup sayfası paylaşılacak; katılmak isteyen kimliğini doğrulayacak, grup sahibi onaylayacak, spam kapıda kalacak.",
      "⚠️ EN ÖNEMLİ UYARI — PANELDE HENÜZ YENİ BİR EKRAN YOK: Bu hafta kurulan her şey arka plandadır. Grup onay kuyruğu, moderasyon ekranı ve bildirimler ayrı işler olarak sırada bekliyor. Yani panele girip “nerede bu?” diye aramayın; kurulan şey altyapı, henüz arayüz değil.",
      "SAHİPLİK DOĞRULAMA: Bir grubun gerçekten sizin olduğunuzu iki yoldan kanıtlayabileceğiniz sistem kuruldu — ya grup açıklamasına size verilen kodu yapıştırırsınız (sistem sayfayı kendisi okuyup kontrol eder) ya da ekran görüntüsü yüklersiniz. Kodlar tek kullanımlık; bir kişinin aynı anda tek açık talebi olabiliyor.",
      "DURUM MAKİNESİ VE KAYIT DEFTERİ: Bir grubun durumu (beklemede / yayında / askıda / kaldırıldı) artık rastgele değiştirilemiyor; yalnızca tanımlı geçişlere izin veriliyor ve her değişiklik kim-ne zaman-neden bilgisiyle kayda geçiyor. “Kaldırıldı” kalıcıdır, geri dönüşü yoktur.",
      "UYARI (STRIKE) SİSTEMİ: Kural ihlalinde kademeli ceza — 1. uyarı yalnızca uyarıdır, 2.’sinde grup 30 gün askıya alınır, 3.’sünde kaldırılır ve grubu EKLEYEN kişi yeni grup ekleyemez. Ağır ihlallerde (kırmızı çizgi) ilk seferde doğrudan kaldırma + yasak uygulanır. Yasaklı kişi hangi yoldan denerse denesin grup ekleyemiyor; yöneticiler bu kuraldan muaf.",
      "EŞİKLER KODDA DEĞİL AYARDA: Kaç uyarıda askı, kaç günlük askı, hangi ihlal kırmızı çizgi — hepsi bir ayar tablosunda duruyor. Yani bu kararları değiştirmek için yazılım güncellemesi gerekmiyor, ayar değişiyor. (Cadde’de aynı deseni kullanıyoruz.)",
      "GRUP SAYFASI GÖNDERİLERİ: Grup sayfalarına gönderi atılabilmesi için altyapı yazıldı. Doğrulanmış grup yöneticisinin ve güvenilir üyenin gönderisi doğrudan yayınlanıyor; diğerleri önce grup sahibinin onayına düşüyor. Sahip 48 saat içinde bakmazsa gönderi otomatik olarak platform kuyruğuna taşınıyor — yani onay beklerken sonsuza kadar asılı kalmıyor.",
      "TASARIM BELGESİNİN 5 VARSAYIMI ÖLÇÜLDÜ VE ÇÜRÜDÜ: Belge, var olduğunu sandığı 5 şeyin üzerine kuruluydu (yorum/beğeni tabloları, telefon doğrulama servisi, kurumsal güven seviyesi gibi). Canlıda ölçtük: hiçbiri yoktu. Varsayımla devam edilseydi çalışmayan bir sistem kurulacaktı; hepsi sıfırdan yazıldı.",
      "⛔ BLOKE OLAN İŞ — KARAR SİZDE: “Kurumsal doğrulama” adımı durduruldu. Sebep: katalog kayıtlarında ZATEN iki ayrı doğrulama alanı var ve ikisi de canlıda kullanılıyor; gelen tasarım üçüncü bir tane istiyor. Üçüncüsünü eklemek “doğrulanmış mı?” sorusunun üç ayrı cevabı olması demek. Hangisinin tek doğru kaynak olacağına karar verilmeden devam edilmeyecek.",
    ],
  },
  {
    id: "20261001-whatsapp-gruplari-guvenlik-acigi",
    date: "1 Ekim 2026",
    title: "⚠️ GÜVENLİK: WhatsApp grup sayfalarında iki açık bulundu ve kapatıldı",
    items: [
      "BİRİNCİ AÇIK — HERKES SINIRSIZ GRUP EKLEYEBİLİYORDU: Hesabı olmayan, giriş bile yapmamış biri sisteme istediği kadar grup kaydı ekleyebiliyordu. Dahası, kaydı BAŞKA BİR KULLANICININ üzerine yazabiliyordu. Günlük sınır da yoktu. Bu, kendiliğinden açık duran bir spam kapısıdır.",
      "DÜZELTİLDİ VE CANLIDA KANITLANDI: Girişsiz ekleme denemesi artık reddediliyor. Kendi adınıza ekleme çalışmaya devam ediyor (form bozulmadı), başkasının adına ekleme reddediliyor. Ayrıca aynı işi iki kez yapan 3 gereksiz kural temizlendi.",
      "İKİNCİ AÇIK — GRUP YÖNETİCİLERİNİN KİŞİSEL BİLGİLERİ HERKESE AÇIKTI: Beklenen sorun yalnızca davet linkiydi. Ölçünce daha ağırı çıktı: 10 grubun 10’unda da grup yöneticisinin ADI, E-POSTASI VE TELEFON NUMARASI giriş yapmamış herkese görünüyordu. Bu, planda yazılı değildi — ölçerek bulundu.",
      "DÜZELTİLDİ: Dizin ve grup detay sayfası artık kişisel bilgi taşımayan ayrı bir kaynaktan okuyor. Davet linki de kayıtla birlikte gelmiyor; yalnızca giriş yapmış kullanıcı istediğinde ayrıca veriliyor.",
      "KULLANICI NE GÖRÜYOR: “Katıl” düğmesi kaybolmuyor. Dört durumun dördünün de karşılığı var — link hazırsa gerçek bağlantı, giriş yoksa “Giriş yap ve katıl”, yükleniyorsa bekleme düğmesi, link yoksa sebebini yazan bir mesaj. (Eski kodda link gelmeyince düğme sessizce hiç çizilmiyordu; o tuzağa düşülmedi.)",
      "NOT: Bu iki açık canlıda uzun süredir açıktı. Kötüye kullanıldığına dair bir iz yok — ama kullanılabilirdi. İkisi de artık kapalı ve canlıda tek tek denenerek doğrulandı.",
    ],
  },
  {
    id: "20261001-yonetici-menusu-numaralari-ve-asistan",
    date: "1 Ekim 2026",
    title: "Yönetici menüsüne sıra numaraları geldi, asistan artık menüyü biliyor",
    items: [
      "NUMARALAR: Yönetici menüsündeki her maddenin artık sabit bir sıra numarası var (toplam 88 madde: 75 ana başlık, 13 alt madde). Amaç konuşmayı kolaylaştırmak — “şu ekrandaki üstten üçüncü” yerine numara söylenebiliyor. Numara tek bir yerden üretiliyor; kenar menü, komut paleti ve asistan aynı listeyi kullanıyor.",
      "ASİSTAN MENÜYÜ ÖĞRENDİ: Site asistanına menünün tamamı öğretildi (madde başına bir kayıt). Artık “X ekranı nerede?” diye sorabilirsiniz.",
      "⚠️ BU BİLGİ YALNIZCA YÖNETİCİYE AÇIK: Menü bilgisi, asistanın yönetici olduğunuzu doğruladığı durumda veriliyor; normal üye sorarsa erişemiyor. Ayrıca asistanın numara UYDURMASINI engelleyen bir fren kondu — bilmediği bir madde için numara icat edemiyor.",
      "SOHBETTEKİ BAĞLANTILAR ARTIK TIKLANABİLİR: Botun yanıtındaki site içi bağlantılar normal link gibi çalışıyor, dış bağlantılar yeni sekmede açılıyor. Zararlı olabilecek bağlantı türleri bilerek tıklanamaz hâlde (düz yazı olarak) gösteriliyor.",
      "SESSİZ BİR HATA DA YAKALANDI: Belgeler asistanın hafızasına yüklenirken, içinde emoji geçen bir belge parçası tam yanlış yerden bölünüyor ve kayıt sessizce düşüyordu (her 93 parçada 1). Onarıldı; ardından 93 parçanın 93’ü de sorunsuz yüklendi.",
    ],
  },
  {
    id: "20261001-tasinma-araclari-sirali-liste-gorseli",
    date: "1 Ekim 2026",
    title: "Taşınma araçlarında sıralı sonuç listesi okunur hâle getirildi",
    items: [
      "NE DEĞİŞTİ: Sonuç listesindeki her madde artık kendi renkli başlık şeridi olan bir kutu. Puan barları kalınlaştırıldı ve sayılar da bandın rengini aldı — hangi seçeneğin önde olduğu bir bakışta görünüyor.",
      "TALEP TEK ARAÇ İÇİN AÇILMIŞTI, DÖRDÜ BİRDEN GÜNCELLENDİ: Ölçtük — bu liste 4 aktif araçta kullanılıyor (ülke eşleştirme, şehir eşleştirme, Almanya banka seçimi, Almanya sigorta seçimi). Yalnızca birini değiştirmek, aynı listenin iki farklı görünüme sahip olması demekti.",
      "RENK TEK BAŞINA BİLGİ TAŞIMIYOR: Bandın Türkçe etiketi her zaman yazılı duruyor ve sayı her zaman görünüyor — renk göremeyen kullanıcı da sıralamayı okuyabiliyor. Puanı olmayan madde renk ALMIYOR; yoksa “0 puan” zayıf bir sonuç sanılırdı.",
    ],
  },
];
