-- Seed: 25 Eylül 2026 toplantısı -> command_center_items (item_type=meeting_note)
-- Kaynak toplantı: T21 (25 Eylül 2026). T20 = 21 Eylül zaten kullanımda.
-- ⚠️ Numara kronolojik değildir: 17 Eylül toplantısı henüz eklenmedi; gelirse T22 olur.
-- ⚠️ Kaynak transkript 80 dakikanın yaklaşık ilk 55 dakikasını kapsar (yapıştırılan
--    metin kesildi). Son 25 dakikanın maddeleri gelirse AYRI bir ek migration ile
--    eklenir — bu dosya değiştirilmez.
-- Assignee eşlemesi: UBT -> UBT, Burak -> Burak, ortak kararlar -> B+B.
-- Toplantıda "workshop kalan maddeler sorular" MD'si üzerinden M91, M93, M94, M95,
-- M101, M135, M12 ve çoklu rol soruları cevaplandı.
-- 13 UBT + 4 Burak + 2 fikir + 9 karar = 28 satır.
-- Idempotent guard: legacy_source_date_label = '25 Eylül 2026'.

do $$
begin
  if exists (
    select 1 from public.command_center_items
    where item_type = 'meeting_note'
      and legacy_source_date_label = '25 Eylül 2026'
  ) then
    raise notice 'T21 (25 Eylül 2026) seed already present, skipping.';
    return;
  end if;

  insert into public.command_center_items
    (item_type, title, detail, category_label, assignee, status, priority, due_date, urgent,
     legacy_source_type, legacy_source_code, legacy_source_date_label, legacy_source_category, legacy_source_title, sort_order)
  values
    -- ── UBT — Cadde workshop cevapları ──────────────────────────────────────────
    ('meeting_note', 'M91: kafe ev sahibine kafe ekranında "Yeni katılım talebi var" bildirimi', 'Karar seçenek A: kafeye katılım talebi gelince kafeyi açan kişiye uygulama içi (kafe ekranında) bildirim gidecek. Durum: commit 838e9db, migration 20260925140000 canlıda.', '25 Eylül 2026', 'UBT', 'Tamamlandi', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'topluluk-yonetimi', 'M91: kafe ev sahibine kafe ekranında "Yeni katılım talebi var" bildirimi', 10),
    ('meeting_note', 'M93: talep kabul/red edilince talep sahibine bildirim gitmesin', 'Karar seçenek C: hiç bildirim yok, kullanıcı durumu kafeye girince görür. Durum: migration 20260925170000 yazıldı (daha önceki "X kafeye girdi" bildirimini de kaldırıyor), henüz canlıya uygulanmadı.', '25 Eylül 2026', 'UBT', 'Devam ediyor', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'topluluk-yonetimi', 'M93: talep kabul/red edilince talep sahibine bildirim gitmesin', 20),
    ('meeting_note', 'M94: Cadde videosu en fazla 10 MB ve 30 saniye', 'Video yükleme açık kalacak ama sınır 10 MB / 30 sn''ye iner. Durum: migration 20260925180000 ve istemci sınırı yazıldı, henüz canlıya uygulanmadı.', '25 Eylül 2026', 'UBT', 'Devam ediyor', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'mvp-hedefleri', 'M94: Cadde videosu en fazla 10 MB ve 30 saniye', 30),
    ('meeting_note', 'M135: Cadde logosunu Cadde sayfa başlığına yerleştir', 'Burak: "Cadde''deyiz ama Cadde''de olduğumuzu bilmiyoruz" — Cadde sayfasının başlığında logo olmalı (site başlığında Cadde bölgesinin yanı da seçenek). Logo dosyası Burak''tan geliyor. Not: 838e9db''deki "m135" işi KAFE logosu yüklemeydi; bu madde Cadde''nin kendi logosu.', '25 Eylül 2026', 'UBT', 'Baslanmadi', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'mvp-hedefleri', 'M135: Cadde logosunu Cadde sayfa başlığına yerleştir', 40),
    ('meeting_note', '"Yetki yükleniyor" yazısını "Yükleniyor" yap', 'Sayfa geçişlerinde görünen "Yetki yükleniyor..." yazısı kullanıcıya bekçi çağrıştırıyor; yalnız "Yükleniyor" yazacak. Durum: RequireFeature.tsx''te değişiklik yapıldı, commit/deploy yok.', '25 Eylül 2026', 'UBT', 'Devam ediyor', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'mvp-hedefleri', '"Yetki yükleniyor" yazısını "Yükleniyor" yap', 50),
    ('meeting_note', 'Toplantıda Cadde akışı ve revizyon sayfası yüklenmedi — kök nedeni bul', 'Toplantı sırasında Cadde akışı boş geldi ("Tümü / Şehrim / Ülkem" dolmadı) ve revizyon sayfası yüklenmedi; UBT canlıda incelemeye aldı. Olası neden (doğrulanmadı): canlı veritabanının küçük compute + sürekli swap kullanması ve periyodik 504''ler.', '25 Eylül 2026', 'UBT', 'Devam ediyor', 5, null, true, 'meeting_notes', 'T21', '25 Eylül 2026', 'veritabani-tasarimi', 'Toplantıda Cadde akışı ve revizyon sayfası yüklenmedi — kök nedeni bul', 60),
    ('meeting_note', 'M95: SMS ile telefon doğrulamasını aç', 'Bütçe onaylandı, açılış işlemleri başlayabilir. Kod 6 haneli, geçerlilik 5 dakika. SMS başına 0,05–0,10 € (100 kişi ≈ 10 €). Harcama tavanı konuldu ki bot saldırısı bütçeyi tüketemesin — transkriptte hem "20 €" hem "25 lira" geçiyor, tavan tutarı ve para birimi netleştirilmeli.', '25 Eylül 2026', 'UBT', 'Baslanmadi', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'kullanici-kisitlamalari', 'M95: SMS ile telefon doğrulamasını aç', 70),
    ('meeting_note', 'Supabase kapasite ve maliyet dokümanı hazırla, Burak''a panel erişimi ver', 'Burak''ın isteği: veritabanı nasıl çalışıyor, kapasite ve ücretsiz kota ne, fiyatlama nasıl — kısa bir doküman. Ayrıca Burak''a Supabase paneline erişim verilecek ki aylık harcamayı kendisi görebilsin ve öneride bulunabilsin.', '25 Eylül 2026', 'UBT', 'Baslanmadi', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'veritabani-tasarimi', 'Supabase kapasite ve maliyet dokümanı hazırla, Burak''a panel erişimi ver', 80),
    ('meeting_note', 'AI Search: sonucu özetlesin, netleştirici soru sorsun, ilgili makaleleri önersin', 'Arama Google AI gibi çalışacak: "4 işletme, 18 kişi buldum" gibi özet verecek, "ne arıyorsun?" diye netleştirici sorular soracak, veritabanı + RAG''den ilgili makaleleri önerecek. T20''deki konuşmalı AI Search maddesinin ayrıntısı.', '25 Eylül 2026', 'UBT', 'Baslanmadi', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'mvp-hedefleri', 'AI Search: sonucu özetlesin, netleştirici soru sorsun, ilgili makaleleri önersin', 90),
    ('meeting_note', 'WhatsApp botunu menü tabanlı (1-2-3) yap, takılınca siteye yönlendirsin', 'WhatsApp botu RAG kullanmayacak: veritabanındaki seçeneklerden numaralı menüyle cevap verecek; cevap veremezse kullanıcıyı sitedeki AI Search''e veya ekibe yönlendirecek. Not: whatsapp-reply / whatsapp-webhook fonksiyonları repoda var ama canlıya deploy edilmedi.', '25 Eylül 2026', 'UBT', 'Baslanmadi', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'topluluk-yonetimi', 'WhatsApp botunu menü tabanlı (1-2-3) yap, takılınca siteye yönlendirsin', 100),
    ('meeting_note', 'Profil ön kartı ve detay kartı envanteri + çalışma planı', 'Burak: panellerimizi görüyoruz ama başkasının gördüğü ön kartı ve detay kartını göremiyoruz. Ön kartın kaç yerde (arama, dizin, Cadde…) göründüğü çıkarılacak ve kartlar için çalışma planı yapılacak.', '25 Eylül 2026', 'UBT', 'Baslanmadi', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'mvp-hedefleri', 'Profil ön kartı ve detay kartı envanteri + çalışma planı', 110),
    ('meeting_note', '82 rolün mevcut yapısını 8-10 örnekle belgele, ortak/tekil alan matrisi çıkar', 'Burak''ın isteği: mevcut rol yapısını anlatan doküman — 8-10 örnek rol üzerinden. UBT buna ek olarak ortak ve role özgü alanların (attribute) matrisini çıkaracak; Burak hangisinin herkese, hangisinin role özel olacağını işaretleyecek.', '25 Eylül 2026', 'UBT', 'Baslanmadi', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'veritabani-tasarimi', '82 rolün mevcut yapısını 8-10 örnekle belgele, ortak/tekil alan matrisi çıkar', 120),
    ('meeting_note', '17 Eylül toplantısının yapılacaklarını Komuta Merkezi''ne ekle', 'Burak: son toplantıların yapılacakları transkriptten çekilip kuyruğa eklensin. 21 ve 25 Eylül eklendi; 17 Eylül toplantısı henüz yok.', '25 Eylül 2026', 'UBT', 'Baslanmadi', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'ekip-ve-isbirligi', '17 Eylül toplantısının yapılacaklarını Komuta Merkezi''ne ekle', 130),

    -- ── Burak Akcakanat ─────────────────────────────────────────────────────────
    ('meeting_note', '"Workshop kalan maddeler — sorular" MD''sini cevapla', 'UBT''nin gönderdiği soru dokümanındaki kararlar cevaplanacak. Toplantıda M91, M93, M94, M95, M101, M135, M12 ve çoklu rol cevaplandı; kalan sorular birkaç gün sonraki oturumda.', '25 Eylül 2026', 'Burak', 'Devam ediyor', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'ekip-ve-isbirligi', '"Workshop kalan maddeler — sorular" MD''sini cevapla', 140),
    ('meeting_note', 'Cadde logosunu UBT''ye gönder', 'M135 için Cadde logo dosyası UBT''ye iletilecek.', '25 Eylül 2026', 'Burak', 'Baslanmadi', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'mvp-hedefleri', 'Cadde logosunu UBT''ye gönder', 150),
    ('meeting_note', 'Test MD''sini gezip bulguları revizyona gir', 'UBT''nin hazırladığı test dokümanı üzerinden site gezilecek; hata ve düzeltmeler revizyon olarak girilecek.', '25 Eylül 2026', 'Burak', 'Devam ediyor', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'ekip-ve-isbirligi', 'Test MD''sini gezip bulguları revizyona gir', 160),
    ('meeting_note', 'Rol / alan matrisini işaretle: herkese ortak mı, role özel mi', 'UBT''nin çıkaracağı matriste her alan için karar verilecek (ör. etkinlik ve WhatsApp numarası herkeste; emlakçıya ek fotoğraf alanı gibi role özel alanlar).', '25 Eylül 2026', 'Burak', 'Baslanmadi', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'veritabani-tasarimi', 'Rol / alan matrisini işaretle: herkese ortak mı, role özel mi', 170),
    ('meeting_note', 'FİKİR: 82 rolü kategorilere etiketle, menüde grupla, sayıyı sadeleştir', 'Burak''ın fikri: 82 rol "Profesyoneller / İşletmeler / Kuruluşlar" gibi kategorilere etiketlensin ve menüde bu başlıklar altında toplansın; UBT sayının belki ~50''ye inebileceğini söyledi. Kategori rol olarak değil etiket/attribute olarak eklenebilir. UBT düşünecek; karar yok.', '25 Eylül 2026', 'Burak', 'Beklemede', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'veritabani-tasarimi', 'FİKİR: 82 rolü kategorilere etiketle, menüde grupla, sayıyı sadeleştir', 180),
    ('meeting_note', 'FİKİR: profil tamamlama için puan / oyunlaştırma', 'Burak''ın fikri: kullanıcıyı teşvik eden puan veya küçük ödül mekanizması. Soru dokümanında zaten var; karar bekliyor.', '25 Eylül 2026', 'Burak', 'Beklemede', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'topluluk-yonetimi', 'FİKİR: profil tamamlama için puan / oyunlaştırma', 190),

    -- ── Ortak kararlar (B+B) ────────────────────────────────────────────────────
    ('meeting_note', 'KARAR: mevcut site artık ürün; MVP layout ve harita iteratif taşınacak', 'mvp.corteqs.net''ten bugünkü siteye evrildik; bu artık MVP değil ürün. Eski MVP''nin menü düzeni, sayfa görünümleri ve haritası frontend işi olarak (birkaç günlük iş) iteratif taşınacak; mimaride kendimize kilit koymuyoruz. Backend''in %75-80''i hazır, kalan kısım ağırlıkla görünüm.', '25 Eylül 2026', 'B+B', 'Beklemede', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'mvp-hedefleri', 'KARAR: mevcut site artık ürün; MVP layout ve harita iteratif taşınacak', 200),
    ('meeting_note', 'KARAR: WhatsApp botu ile site AI Search ayrı tutulacak', 'WhatsApp menü tabanlı çalışacak, RAG/LLM kullanmayacak — hem kredi tüketir hem kullanıcının ne yazdığı görülemez hem de sitedeki etkileşimi azaltır. Konuşmalı AI Search sitede olacak; WhatsApp takılan kullanıcıyı oraya yönlendirecek.', '25 Eylül 2026', 'B+B', 'Beklemede', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'mvp-hedefleri', 'KARAR: WhatsApp botu ile site AI Search ayrı tutulacak', 210),
    ('meeting_note', 'KARAR: kafe bildirimleri — M91 seçenek A, M93 seçenek C', 'M91: katılım talebinde kafe ev sahibine kafe ekranında uygulama içi bildirim. M93: talep kabul/red edilince talep sahibine hiç bildirim yok.', '25 Eylül 2026', 'B+B', 'Beklemede', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'topluluk-yonetimi', 'KARAR: kafe bildirimleri — M91 seçenek A, M93 seçenek C', 220),
    ('meeting_note', 'KARAR: video 10 MB / 30 sn; kota aşılırsa aylık 25 $ plan, ileride kendi sunucu', 'Her yüklenen video depolama maliyeti yazar (ücretsiz kota birkaç yüz MB – 1 GB). Video açık kalacak ama 10 MB / 30 sn ile sınırlanacak; kota aşılırsa aylık 25 $''lık plana bakılacak, ileride kendi sunucumuza (VPS) taşınacak.', '25 Eylül 2026', 'B+B', 'Beklemede', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'veritabani-tasarimi', 'KARAR: video 10 MB / 30 sn; kota aşılırsa aylık 25 $ plan, ileride kendi sunucu', 230),
    ('meeting_note', 'KARAR: kullanıcının kendi profil akışı olmayacak (Reddit modeli)', 'Cadde ortak bir alan; paylaşımlar kişinin kendi sayfasına değil ortama (kafe, akış) yapılır. Kullanıcı kendi paylaşımlarına geri dönüp bakabilir ama Instagram gibi profil ızgarası olmayacak.', '25 Eylül 2026', 'B+B', 'Beklemede', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'topluluk-yonetimi', 'KARAR: kullanıcının kendi profil akışı olmayacak (Reddit modeli)', 240),
    ('meeting_note', 'KARAR: SMS telefon doğrulama bütçesi onaylandı', 'M95 açılış işlemleri başlayabilir: 6 haneli kod, 5 dakika geçerlilik, harcama tavanıyla. Tavan tutarı netleştirilecek (transkriptte "20 €" ve "25 lira" geçiyor).', '25 Eylül 2026', 'B+B', 'Beklemede', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'kullanici-kisitlamalari', 'KARAR: SMS telefon doğrulama bütçesi onaylandı', 250),
    ('meeting_note', 'KARAR: eski üyelere "profilini tamamla" maili şimdi GÖNDERİLMEYECEK (M12)', 'Burak: önce bot ve profil tamamlansın, sonra kullanıcı profilini tamamlasın; mail şimdilik iptal. Kayıt en az sürtünmeyle olacak, ek özellikler için belge/bilgi sonradan istenecek. Hatırlatma sistemi daha sonra konuşulacak.', '25 Eylül 2026', 'B+B', 'Beklemede', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'kullanici-kisitlamalari', 'KARAR: eski üyelere "profilini tamamla" maili şimdi GÖNDERİLMEYECEK (M12)', 260),
    ('meeting_note', 'KARAR: çoklu rol ertelendi — 1-2 ay tek rol, talebe göre genişlet', 'Çoklu rol şema değişikliği ve yüksek kırılma riski taşıyor. 1-2 ay tek rol sistemiyle kullanıcı toplanacak, yeni roller gelen talebe göre değerlendirilecek; altyapı (backbone) hazır tutulacak. Önce bireysel kullanıcılar, sonra onların ihtiyacına göre role özel ekranlar.', '25 Eylül 2026', 'B+B', 'Beklemede', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'veritabani-tasarimi', 'KARAR: çoklu rol ertelendi — 1-2 ay tek rol, talebe göre genişlet', 270),
    ('meeting_note', 'KARAR: M101 ("şok panosu formatı") geçildi', 'Madde iki taraf için de anlaşılmadı; acil durum panosu zaten toplu hâlde olduğu için geçildi.', '25 Eylül 2026', 'B+B', 'Beklemede', 5, null, false, 'meeting_notes', 'T21', '25 Eylül 2026', 'mvp-hedefleri', 'KARAR: M101 ("şok panosu formatı") geçildi', 280);

  -- Seed sayısını doğrula: eksik/fazla satır sessizce geçmesin (WS2 seed dersi).
  if (
    select count(*) from public.command_center_items
    where item_type = 'meeting_note' and legacy_source_date_label = '25 Eylül 2026'
  ) <> 28 then
    raise exception 'T21 seed 28 satır eklemeliydi.';
  end if;
end
$$;
