// Admin Panel V2 — tek kaynaklı navigasyon registry'si.
// Desktop sidebar, mobil drawer, command palette, breadcrumb ve dashboard
// hızlı navigasyonu BU dosyadan beslenir; başka yerde link listesi tutulmaz.
// URL path'leri App.tsx'teki mevcut route ağacıyla birebir aynıdır ve
// değiştirilemez (masterplan §4.3). Görünür isim ve gruplama değişebilir.

import {
  ArrowLeftRight,
  BookOpen,
  Briefcase,
  Calculator,
  ClipboardList,
  Database,
  ExternalLink,
  FileText,
  FolderKanban,
  Globe,
  Heart,
  LayoutDashboard,
  Layers,
  Lightbulb,
  Link2,
  ListChecks,
  Megaphone,
  MessageSquare,
  Newspaper,
  Radio,
  Rocket,
  ScrollText,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Store,
  Table2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Users,
} from "lucide-react";

import { advisorProfileSections } from "@/lib/resource-links";
import { workspaceDocPages } from "@/lib/dashboard/workspace-doc-pages";
import type { AdminNavGroup, AdminNavItem } from "./admin-shell-types";

const advisorProfileItems: AdminNavItem[] = advisorProfileSections.map((section) => ({
  id: `advisors-${section.key}`,
  label: section.label,
  to: `/admin/advisors/${section.key}`,
  icon: Link2,
  accent: "amber",
}));

const workspaceDocItems: AdminNavItem[] = workspaceDocPages.map((page) => ({
  id: `workspace-doc-${page.slug}`,
  label: page.title,
  description: page.description,
  to: `/admin/workspace/docs/${page.slug}`,
  icon: ScrollText,
  accent: "slate",
}));

export const adminNavGroups: AdminNavGroup[] = [
  {
    id: "overview",
    label: "Genel Bakış",
    accent: "indigo",
    defaultOpen: true,
    items: [
      {
        id: "dashboard",
        label: "Genel Bakış",
        description: "Operasyon merkezi: KPI'lar, dikkat isteyenler ve hızlı işlemler.",
        to: "/admin",
        icon: LayoutDashboard,
        accent: "indigo",
        aliases: ["dashboard", "ana sayfa", "home", "özet"],
      },
    ],
  },
  {
    id: "members",
    label: "Üyeler ve Dizin",
    accent: "sky",
    defaultOpen: true,
    items: [
      {
        id: "catalog-database",
        label: "Kayıt Veritabanı",
        shortLabel: "Veritabanı",
        description: "Tüm katalog ve profil kayıtları; kullanıcı rol atama buradan yapılır.",
        to: "/admin/data",
        // İkinci URL backward compatibility için korunur (masterplan §6.1.B notu).
        match: ["/admin/new-member/profile-role-assignment", "/admin/data"],
        icon: Database,
        accent: "sky",
        aliases: ["kayıt", "katalog", "veritabanı", "üyeler", "kullanıcı rol atama", "profil"],
      },
      {
        id: "approvals",
        label: "Approval Queue",
        description: "Bekleyen talepleri incele, onayla veya reddet.",
        to: "/admin/approvals",
        icon: ClipboardList,
        accent: "sky",
        badge: "approval-count",
        aliases: ["onay", "approval", "claim", "bekleyen talepler"],
      },
      {
        id: "feature-overrides",
        label: "Feature Override",
        description: "Kullanıcı bazlı feature istisnaları.",
        to: "/admin/new-member/overrides",
        icon: SlidersHorizontal,
        accent: "sky",
        aliases: ["override", "feature", "istisna", "yetki"],
      },
      {
        id: "audit-logs",
        label: "Audit Logs",
        description: "Kritik admin işlem geçmişi.",
        to: "/admin/audit-logs",
        icon: ScrollText,
        accent: "sky",
        aliases: ["audit", "log", "denetim", "geçmiş"],
      },
      {
        id: "referral",
        label: "Referans Kodları",
        shortLabel: "Ref Kod",
        description: "Referans kodu kaynakları, grupları ve tipleri.",
        to: "/admin/referral",
        match: ["/admin/referral"],
        icon: Sparkles,
        accent: "sky",
        aliases: ["ref kod", "referans", "davet", "referral"],
      },
    ],
  },
  {
    id: "roles-afs",
    label: "Roller ve AFS",
    accent: "emerald",
    items: [
      {
        id: "afs-overview",
        label: "AFS Genel Bakış",
        description: "Roller ve entity genel bakış.",
        to: "/admin/new-member/roles-overview",
        icon: Layers,
        accent: "emerald",
        aliases: ["afs", "rol", "roller", "rolesgo", "genel bakış"],
      },
      {
        id: "role-matrix",
        label: "Roller AFS Matrisi",
        description: "Rol başına attribute / feature / section kuralları.",
        to: "/admin/new-member/role-matrix",
        icon: Shield,
        accent: "emerald",
        aliases: ["matris", "attribute", "feature", "section", "rol kuralları"],
      },
      {
        id: "durum-raporu",
        label: "Durum Raporu",
        description: "Canlı rebuild sağlığı ve sistem metrikleri.",
        to: "/admin/new-member/durum-raporu",
        icon: ShieldCheck,
        accent: "emerald",
        aliases: ["durum", "sağlık", "health", "rapor"],
      },
      {
        id: "database-tables",
        label: "Veritabanı Tabloları",
        description: "Teknik tablo görünümü.",
        to: "/admin/veritabani-tablolari",
        icon: Table2,
        accent: "emerald",
        aliases: ["tablo", "şema", "teknik", "database"],
      },
      {
        id: "system-guide",
        label: "Sistem Kullanım Kılavuzu",
        shortLabel: "Kılavuz",
        description: "Admin rehberi.",
        to: "/admin/new-member/guide",
        icon: BookOpen,
        accent: "emerald",
        aliases: ["kılavuz", "klavuz", "rehber", "guide", "yardım"],
      },
      {
        id: "roles-draft",
        label: "Roller Taslak",
        description: "Taslak rol çalışma ekranı.",
        to: "/admin/roller-taslak",
        icon: FileText,
        accent: "emerald",
        isInactive: true,
        aliases: ["taslak", "draft"],
      },
    ],
  },
  {
    id: "communities",
    label: "Topluluklar",
    accent: "rose",
    items: [
      {
        id: "community-landings",
        label: "Topluluk Landingleri",
        description: "Topluluk kayıtları ve landing yönetimi.",
        to: "/admin/whatsapp-landings",
        icon: MessageSquare,
        accent: "rose",
        aliases: ["topluluk", "whatsapp", "landing"],
      },
      {
        id: "community-editors",
        label: "Topluluk Editörleri",
        description: "Landing editor atamaları.",
        to: "/admin/whatsapp-landings/editors",
        icon: Users,
        accent: "rose",
        aliases: ["editör", "editor"],
      },
      {
        id: "community-guide",
        label: "Topluluk Kılavuzu",
        description: "Topluluk akış rehberi.",
        to: "/admin/whatsapp-landings/guide",
        icon: BookOpen,
        accent: "rose",
        aliases: ["topluluk kılavuzu", "rehber"],
      },
      {
        id: "consulates",
        label: "Diplomatik Profiller",
        description: "Konsolosluk ve diplomatik temsilcilik profilleri.",
        to: "/admin/consulates",
        icon: Globe,
        accent: "rose",
        aliases: ["diplomatik", "konsolosluk", "consulate"],
      },
    ],
  },
  {
    id: "content",
    label: "İçerik ve Kampanyalar",
    accent: "amber",
    items: [
      {
        id: "cadde",
        label: "Cadde",
        description: "Cadde yönetimi.",
        to: "/admin/cadde",
        icon: Store,
        accent: "amber",
        aliases: ["cadde", "marketplace"],
      },
      {
        id: "surveys",
        label: "Anketler",
        description: "Survey CRUD ve cevaplar.",
        to: "/admin/surveys",
        match: ["/admin/surveys"],
        icon: ClipboardList,
        accent: "amber",
        aliases: ["anket", "survey"],
      },
      {
        id: "marquee",
        label: "Haber Bandı",
        description: "Marquee yönetimi.",
        to: "/admin/marquee",
        icon: Radio,
        accent: "amber",
        aliases: ["haber bandı", "marquee"],
      },
      {
        id: "social-media",
        label: "Sosyal Medya",
        description: "Sosyal medya bağlantıları.",
        to: "/admin/social-media",
        icon: Megaphone,
        accent: "amber",
        aliases: ["sosyal medya", "social"],
      },
      {
        id: "advisor-profiles",
        label: "Sosyal Link Profilleri",
        description: "Profil bazlı sosyal link içerikleri.",
        match: ["/admin/advisors"],
        icon: Link2,
        accent: "amber",
        aliases: ["advisor", "consultant", "influencer", "contributor"],
        children: advisorProfileItems,
      },
      {
        id: "dunya-kupasi",
        label: "Dünya Kupası",
        description: "Maç yayını yapan işletme başvuruları ve onayları.",
        to: "/admin/dunya-kupasi",
        icon: Trophy,
        accent: "amber",
        aliases: ["dünya kupası", "işletme kampanyası", "world cup", "maç yayını"],
      },
      {
        id: "may19-kelime",
        label: "19 Mayıs Kelime",
        description: "Kampanya kelime kayıtları.",
        to: "/admin/may19/kelime",
        icon: Lightbulb,
        accent: "amber",
        isInactive: true,
        aliases: ["19 mayıs", "kelime", "fikir"],
      },
      {
        id: "may19-ani",
        label: "19 Mayıs Anı",
        description: "Kampanya anı kayıtları.",
        to: "/admin/may19/ani",
        icon: Heart,
        accent: "amber",
        isInactive: true,
        aliases: ["19 mayıs", "anı"],
      },
    ],
  },
  {
    id: "workspace",
    label: "Operasyon Workspace",
    accent: "slate",
    items: [
      {
        id: "workspace-home",
        label: "Workspace",
        description: "Workspace ana sayfası.",
        to: "/admin/workspace",
        icon: Briefcase,
        accent: "slate",
        aliases: ["workspace", "dashboard merkezi"],
      },
      {
        id: "command-center",
        label: "Command Center",
        shortLabel: "CC",
        description: "Todo ve koordinasyon merkezi.",
        to: "/admin/workspace/command-center",
        icon: ListChecks,
        accent: "slate",
        aliases: ["cc", "todo", "komuta", "command"],
      },
      {
        id: "workspace-resources",
        label: "Dosyalar ve Linkler",
        description: "Kaynak merkezi.",
        to: "/admin/workspace/resources",
        icon: FolderKanban,
        accent: "slate",
        aliases: ["dosya", "link", "kaynak", "resources"],
      },
      {
        id: "workspace-mvp",
        label: "MVP Listesi",
        description: "MVP takip listesi.",
        to: "/admin/workspace/mvp",
        icon: Rocket,
        accent: "slate",
        aliases: ["mvp"],
      },
      {
        id: "workspace-docs",
        label: "Dokümanlar",
        description: "Workspace doküman sayfaları.",
        match: ["/admin/workspace/docs"],
        icon: FileText,
        accent: "slate",
        aliases: ["doküman", "docs"],
        children: workspaceDocItems,
      },
    ],
  },
  {
    id: "muhasebe",
    label: "Muhasebe",
    accent: "green",
    items: [
      {
        id: "muhasebe-dashboard",
        label: "Muhasebe Dashboard",
        shortLabel: "Muhasebe",
        description: "KPI özet ekranı.",
        to: "/admin/muhasebe",
        icon: Calculator,
        accent: "green",
        aliases: ["muhasebe", "finans"],
      },
      {
        id: "muhasebe-giderler",
        label: "Giderler",
        description: "Gider kayıtları CRUD.",
        to: "/admin/muhasebe/giderler",
        icon: TrendingDown,
        accent: "green",
        aliases: ["gider", "masraf"],
      },
      {
        id: "muhasebe-gelirler",
        label: "Gelirler",
        description: "Gelir kayıtları CRUD.",
        to: "/admin/muhasebe/gelirler",
        icon: TrendingUp,
        accent: "green",
        aliases: ["gelir"],
      },
      {
        id: "muhasebe-nakit-akisi",
        label: "Nakit Akışı",
        description: "Finansal akış görünümü.",
        to: "/admin/muhasebe/nakit-akisi",
        icon: ArrowLeftRight,
        accent: "green",
        aliases: ["nakit", "cash flow", "akış"],
      },
    ],
  },
  {
    id: "system",
    label: "Sistem",
    accent: "red",
    items: [
      {
        id: "about",
        label: "Ürün Güncellemeleri",
        description: "Sürüm notları ve güncellemeler.",
        to: "/admin/about",
        icon: Newspaper,
        accent: "red",
        aliases: ["güncelleme", "sürüm", "release", "about"],
      },
      {
        id: "admin-guide",
        label: "Admin Kullanım Kılavuzu",
        shortLabel: "Kılavuz",
        description: "Tüm admin fonksiyonlarının kullanım rehberi.",
        to: "/admin/guide",
        icon: BookOpen,
        accent: "red",
        aliases: ["yardım", "kılavuz", "klavuz", "guide", "help", "rehber"],
      },
      {
        id: "external-engine",
        label: "Engine",
        href: "https://eng.corteqs.net",
        icon: ExternalLink,
        accent: "red",
        isExternal: true,
        aliases: ["engine"],
      },
      {
        id: "external-globe",
        label: "Globe",
        href: "https://globe.corteqs.net",
        icon: ExternalLink,
        accent: "red",
        isExternal: true,
        aliases: ["globe"],
      },
      {
        id: "external-founders",
        label: "Founders",
        href: "https://mvp.corteqs.net/founders",
        icon: ExternalLink,
        accent: "red",
        isExternal: true,
        aliases: ["founders", "kurucular"],
      },
    ],
  },
];
