// Admin Panel V2 — tek kaynaklı navigasyon registry'si.
// Desktop sidebar, mobil drawer, command palette, breadcrumb ve dashboard
// hızlı navigasyonu BU dosyadan beslenir; başka yerde link listesi tutulmaz.
// URL path'leri App.tsx'teki mevcut route ağacıyla birebir aynıdır ve
// değiştirilemez (masterplan §4.3). Görünür isim ve gruplama değişebilir.

import {
  ArrowLeftRight,
  BarChart3,
  BellRing,
  BookOpen,
  Boxes,
  Briefcase,
  Calculator,
  ClipboardList,
  Crown,
  Database,
  ExternalLink,
  FileText,
  FolderKanban,
  FolderOpen,
  Globe,
  Hammer,
  Heart,
  Inbox,
  LayoutDashboard,
  Layers,
  Lightbulb,
  Link2,
  ListChecks,
  Megaphone,
  MessageSquare,
  MessageSquarePlus,
  Newspaper,
  Radio,
  Rocket,
  ScrollText,
  Bug,
  Share2,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Store,
  Table2,
  TrendingDown,
  TrendingUp,
  Upload,
  Users,
  Wallet,
} from "lucide-react";

import { advisorProfileSections } from "@/lib/resource-links";
import { workspaceDocPages } from "@/lib/dashboard/workspace-doc-pages";
import type { AdminNavGroup, AdminNavItem } from "./admin-shell-types";

const advisorProfileItems: AdminNavItem[] = advisorProfileSections.map((section) => ({
  id: `advisors-${section.key}`,
  label: section.label,
  to: `/admin/advisors/${section.key}`,
  icon: Link2,
  accent: "amber",
}));

const workspaceDocItems: AdminNavItem[] = workspaceDocPages.map((page) => ({
  id: `workspace-doc-${page.slug}`,
  label: page.title,
  description: page.description,
  to: `/admin/workspace/docs/${page.slug}`,
  icon: ScrollText,
  accent: "slate",
}));

export const adminNavGroups: AdminNavGroup[] = [
  {
    id: "overview",
    label: "Genel Bakış",
    accent: "indigo",
    defaultOpen: true,
    items: [
      {
        id: "dashboard",
        label: "Genel Bakış",
        description: "Operasyon merkezi: KPI'lar, dikkat isteyenler ve hızlı işlemler.",
        to: "/admin",
        icon: LayoutDashboard,
        accent: "indigo",
        aliases: ["dashboard", "ana sayfa", "home", "özet"],
      },
    ],
  },
  {
    id: "members",
    label: "Üyeler ve Dizin",
    accent: "sky",
    defaultOpen: true,
    items: [
      {
        id: "catalog-database",
        label: "Kayıt Veritabanı",
        shortLabel: "Veritabanı",
        description: "Tüm katalog ve profil kayıtları; kullanıcı rol atama buradan yapılır.",
        to: "/admin/data",
        // İkinci URL backward compatibility için korunur (masterplan §6.1.B notu).
        match: ["/admin/new-member/profile-role-assignment", "/admin/data"],
        icon: Database,
        accent: "sky",
        aliases: ["kayıt", "katalog", "veritabanı", "üyeler", "kullanıcı rol atama", "profil"],
      },
      {
        id: "bulk-import",
        label: "Toplu İçe Aktarma",
        shortLabel: "İçe Aktar",
        description: "CSV/JSON profesyonel listelerini beklemeye al; Kayıt Veritabanı'ndan onayla.",
        to: "/admin/bulk-import",
        icon: Upload,
        accent: "sky",
        aliases: ["içe aktar", "ice aktar", "import", "toplu", "csv", "json", "profil yükle", "deep research"],
      },
      {
        id: "submissions",
        label: "Üye Takibi",
        shortLabel: "Başvurular",
        description: "Kayıt açıklamalarını, ihtiyaçları, referral bilgisini ve güvenli ekleri incele.",
        to: "/admin/submissions",
        icon: FileText,
        accent: "sky",
        aliases: ["başvuru", "kayıt formu", "üye takibi", "ek dosya", "iş arıyorum"],
      },
      {
        id: "approvals",
        label: "Approval Queue",
        description: "Bekleyen talepleri incele, onayla veya reddet.",
        to: "/admin/approvals",
        icon: ClipboardList,
        accent: "sky",
        badge: "approval-count",
        aliases: ["onay", "approval", "claim", "bekleyen talepler"],
      },
      {
        id: "feature-overrides",
        label: "Feature Override",
        description: "Kullanıcı bazlı feature istisnaları.",
        to: "/admin/new-member/overrides",
        icon: SlidersHorizontal,
        accent: "sky",
        aliases: ["override", "feature", "istisna", "yetki"],
      },
      {
        id: "audit-logs",
        label: "Audit Logs",
        description: "Kritik admin işlem geçmişi.",
        to: "/admin/audit-logs",
        icon: ScrollText,
        accent: "sky",
        aliases: ["audit", "log", "denetim", "geçmiş"],
      },
      {
        id: "client-errors",
        label: "İstemci Hataları",
        shortLabel: "Hatalar",
        description: "Tarayıcıda yakalanan Cadde yazma/okuma ve render hataları (m134 tanısı).",
        to: "/admin/client-errors",
        icon: Bug,
        accent: "sky",
        aliases: ["hata", "istemci", "client error", "m134", "tarayıcı hatası", "console"],
      },
      {
        id: "referral",
        label: "Referans Kodları",
        shortLabel: "Ref Kod",
        description: "Referans kodu kaynakları, grupları ve tipleri.",
        to: "/admin/referral",
        match: ["/admin/referral"],
        icon: Sparkles,
        accent: "sky",
        aliases: ["ref kod", "referans", "davet", "referral"],
      },
    ],
  },
  {
    id: "roles-afs",
    label: "Roller ve AFS",
    accent: "emerald",
    items: [
      {
        id: "afs-overview",
        label: "AFS Genel Bakış",
        description: "Roller ve entity genel bakış.",
        to: "/admin/new-member/roles-overview",
        icon: Layers,
        accent: "emerald",
        aliases: ["afs", "rol", "roller", "rolesgo", "genel bakış"],
      },
      {
        id: "role-matrix",
        label: "Roller AFS Matrisi",
        description: "Rol başına attribute / feature / section kuralları.",
        to: "/admin/new-member/role-matrix",
        icon: Shield,
        accent: "emerald",
        aliases: ["matris", "attribute", "feature", "section", "rol kuralları"],
      },
      {
        id: "durum-raporu",
        label: "Durum Raporu",
        description: "Canlı rebuild sağlığı ve sistem metrikleri.",
        to: "/admin/new-member/durum-raporu",
        icon: ShieldCheck,
        accent: "emerald",
        aliases: ["durum", "sağlık", "health", "rapor"],
      },
      {
        id: "database-tables",
        label: "Veritabanı Tabloları",
        description: "Teknik tablo görünümü.",
        to: "/admin/veritabani-tablolari",
        icon: Table2,
        accent: "emerald",
        aliases: ["tablo", "şema", "teknik", "database"],
      },
      {
        id: "system-guide",
        label: "Sistem Kullanım Kılavuzu",
        shortLabel: "Kılavuz",
        description: "Admin rehberi.",
        to: "/admin/new-member/guide",
        icon: BookOpen,
        accent: "emerald",
        aliases: ["kılavuz", "klavuz", "rehber", "guide", "yardım"],
      },
      {
        id: "roles-draft",
        label: "Roller Taslak",
        description: "Taslak rol çalışma ekranı.",
        to: "/admin/roller-taslak",
        icon: FileText,
        accent: "emerald",
        isInactive: true,
        aliases: ["taslak", "draft"],
      },
      {
        id: "brainstorming",
        label: "Brainstorming",
        description: "Cadde 3.0 & Premium Panel durum ve karar raporu — düzenlenebilir.",
        to: "/admin/brainstorming",
        icon: Lightbulb,
        accent: "emerald",
        aliases: ["brainstorming", "durum raporu", "karar", "statusreport", "3006"],
      },
    ],
  },
  {
    id: "communities",
    label: "Topluluklar",
    accent: "rose",
    items: [
      {
        id: "community-landings",
        label: "Topluluk Landingleri",
        description: "Topluluk kayıtları ve landing yönetimi.",
        to: "/admin/whatsapp-landings",
        icon: MessageSquare,
        accent: "rose",
        aliases: ["topluluk", "whatsapp", "landing"],
      },
      {
        id: "community-editors",
        label: "Topluluk Editörleri",
        description: "Landing editor atamaları.",
        to: "/admin/whatsapp-landings/editors",
        icon: Users,
        accent: "rose",
        aliases: ["editör", "editor"],
      },
      {
        id: "community-guide",
        label: "Topluluk Kılavuzu",
        description: "Topluluk akış rehberi.",
        to: "/admin/whatsapp-landings/guide",
        icon: BookOpen,
        accent: "rose",
        aliases: ["topluluk kılavuzu", "rehber"],
      },
      {
        id: "consulates",
        label: "Diplomatik Profiller",
        description: "Konsolosluk ve diplomatik temsilcilik profilleri.",
        to: "/admin/consulates",
        icon: Globe,
        accent: "rose",
        aliases: ["diplomatik", "konsolosluk", "consulate"],
      },
    ],
  },
  {
    id: "content",
    label: "İçerik ve Kampanyalar",
    accent: "amber",
    items: [
      {
        id: "cadde",
        label: "Cadde",
        description: "Cadde yönetimi.",
        to: "/admin/cadde",
        icon: Store,
        accent: "amber",
        aliases: ["cadde", "marketplace"],
      },
      {
        id: "cadde-guide",
        label: "Cadde Kural Kitabı",
        description: "Cadde'nin üye ve admin tarafı rehberi.",
        to: "/admin/cadde/rehber",
        icon: BookOpen,
        accent: "amber",
        aliases: ["cadde rehber", "cadde kılavuz", "kural kitabı"],
      },
      {
        id: "surveys",
        label: "Anketler",
        description: "Survey CRUD ve cevaplar.",
        to: "/admin/surveys",
        match: ["/admin/surveys"],
        icon: ClipboardList,
        accent: "amber",
        aliases: ["anket", "survey"],
      },
      {
        id: "marquee",
        label: "Haber Bandı",
        description: "Marquee yönetimi.",
        to: "/admin/marquee",
        icon: Radio,
        accent: "amber",
        aliases: ["haber bandı", "marquee"],
      },
      {
        id: "blog",
        label: "Blog",
        description: "Ülke rehberi yazıları — oluştur, düzenle, yayınla.",
        to: "/admin/blog",
        icon: FileText,
        accent: "amber",
        aliases: ["blog", "yazı", "makale", "rehber", "ülke rehberi"],
      },
      {
        id: "social-media",
        label: "Sosyal Medya",
        description: "Sosyal medya bağlantıları.",
        to: "/admin/social-media",
        icon: Megaphone,
        accent: "amber",
        aliases: ["sosyal medya", "social"],
      },
      {
        id: "social-share-vault",
        label: "Sosyal Medya Paylaşım Deposu",
        shortLabel: "Paylaşım Deposu",
        description: "Hazır Canva görsel promptları ve LinkedIn postları — araç tanıtımları, diaspora postları ve test araçları için kopyala-paylaş.",
        to: "/admin/social-share-vault",
        icon: Share2,
        accent: "amber",
        aliases: ["sosyal medya deposu", "paylaşım", "canva", "linkedin", "prompt", "içerik paketi", "post", "diaspora", "gurbet", "test aracı", "varyant"],
      },
      {
        id: "vip-invitations",
        label: "VIP Davetleri",
        description: "Tek kullanımlık kişisel VIP davetlerini oluştur ve iptal et.",
        to: "/admin/vip-invitations",
        icon: Crown,
        accent: "amber",
        aliases: ["vip", "davet", "invitation", "özel bağlantı"],
      },
      {
        id: "customer-requests",
        label: "Müşteri Talepleri",
        description: "WhatsApp taleplerini ata, durumunu yönet ve denetimli yanıtla.",
        to: "/admin/customer-requests",
        icon: Inbox,
        accent: "emerald",
        aliases: ["müşteri", "talep", "whatsapp", "destek", "inbox", "cevap"],
      },
      {
        id: "advisor-profiles",
        label: "Sosyal Link Profilleri",
        description: "Profil bazlı sosyal link içerikleri.",
        match: ["/admin/advisors"],
        icon: Link2,
        accent: "amber",
        aliases: ["advisor", "consultant", "influencer", "contributor"],
        children: advisorProfileItems,
      },
      {
        id: "may19-kelime",
        label: "19 Mayıs Kelime",
        description: "Kampanya kelime kayıtları.",
        to: "/admin/may19/kelime",
        icon: Lightbulb,
        accent: "amber",
        isInactive: true,
        aliases: ["19 mayıs", "kelime", "fikir"],
      },
      {
        id: "may19-ani",
        label: "19 Mayıs Anı",
        description: "Kampanya anı kayıtları.",
        to: "/admin/may19/ani",
        icon: Heart,
        accent: "amber",
        isInactive: true,
        aliases: ["19 mayıs", "anı"],
      },
    ],
  },
  {
    id: "workspace",
    label: "Operasyon Workspace",
    accent: "slate",
    items: [
      {
        id: "workspace-home",
        label: "Workspace",
        description: "Workspace ana sayfası.",
        to: "/admin/workspace",
        icon: Briefcase,
        accent: "slate",
        aliases: ["workspace", "dashboard merkezi"],
      },
      {
        id: "command-center",
        label: "Command Center",
        shortLabel: "CC",
        description: "Todo ve koordinasyon merkezi.",
        to: "/admin/workspace/command-center",
        icon: ListChecks,
        accent: "slate",
        aliases: ["cc", "todo", "komuta", "command"],
      },
      {
        id: "revision-requests",
        label: "Revizyon İstekleri",
        shortLabel: "Revizyon",
        description: "Site/ürün revizyon talepleri ve yorum thread'leri — tüm adminler ortak.",
        to: "/admin/revision-requests",
        icon: MessageSquarePlus,
        accent: "slate",
        aliases: ["revizyon", "istek", "talep", "yorum", "comment", "revision"],
      },
      {
        id: "member-feedback",
        label: "Üye Geri Bildirimleri",
        shortLabel: "Feedback",
        description: "Üyelerin 'Feedback Ver' formundan gelen geri bildirimler — durum + arşiv.",
        to: "/admin/feedback",
        icon: Inbox,
        accent: "slate",
        aliases: ["feedback", "geri bildirim", "üye görüşü", "öneri", "şikayet"],
      },
      {
        id: "workspace-resources",
        label: "Dosyalar ve Linkler",
        description: "Kaynak merkezi.",
        to: "/admin/workspace/resources",
        icon: FolderKanban,
        accent: "slate",
        aliases: ["dosya", "link", "kaynak", "resources"],
      },
      {
        id: "contributor-resources",
        label: "Contributor Kaynakları",
        shortLabel: "Contributor",
        description: "Yerel kaynak gönderimlerini incele, eksik bilgi iste veya kabul et.",
        to: "/admin/contributor-resources",
        icon: FolderOpen,
        accent: "emerald",
        aliases: ["contributor", "katkı", "kaynak kuyruğu", "yerel kaynak"],
      },
      {
        id: "workspace-mvp",
        label: "MVP Listesi",
        description: "MVP takip listesi.",
        to: "/admin/workspace/mvp",
        icon: Rocket,
        accent: "slate",
        aliases: ["mvp"],
      },
      {
        id: "workspace-docs",
        label: "Dokümanlar",
        description: "Workspace doküman sayfaları.",
        match: ["/admin/workspace/docs"],
        icon: FileText,
        accent: "slate",
        aliases: ["doküman", "docs"],
        children: workspaceDocItems,
      },
    ],
  },
  {
    // Workshop panoları: her workshop kendi madde listesi + UBT/Burak onay kutuları.
    // Veri kaynağı: workshop_items tablosu (mig 20260730190000).
    id: "workshop",
    label: "Workshop",
    icon: Hammer,
    accent: "emerald",
    items: [
      {
        id: "workshop-cadde",
        label: "Cadde",
        shortLabel: "Cadde WS",
        description: "30.07.2026 Cadde workshop maddeleri; UBT + Burak onay kutuları.",
        to: "/admin/workshop/cadde",
        icon: ClipboardList,
        accent: "emerald",
        aliases: ["workshop", "cadde workshop", "atölye", "madde", "checklist", "ubt", "burak"],
      },
      {
        id: "workshop-profil",
        label: "Profil",
        shortLabel: "Profil WS",
        description: "03.09.2026 Profiller toplantısı maddeleri; UBT + Burak onay kutuları.",
        to: "/admin/workshop/profil",
        icon: ClipboardList,
        accent: "emerald",
        aliases: ["profil workshop", "profiller", "rol etiketi", "doğrulama", "referans", "paket"],
      },
    ],
  },
  {
    id: "muhasebe",
    label: "Muhasebe",
    accent: "green",
    items: [
      {
        id: "muhasebe-dashboard",
        label: "Muhasebe Dashboard",
        shortLabel: "Muhasebe",
        description: "KPI özet ekranı.",
        to: "/admin/muhasebe",
        icon: Calculator,
        accent: "green",
        aliases: ["muhasebe", "finans"],
      },
      {
        id: "muhasebe-giderler",
        label: "Giderler",
        description: "Gider kayıtları CRUD.",
        to: "/admin/muhasebe/giderler",
        icon: TrendingDown,
        accent: "green",
        aliases: ["gider", "masraf"],
      },
      {
        id: "muhasebe-gelirler",
        label: "Gelirler",
        description: "Gelir kayıtları CRUD.",
        to: "/admin/muhasebe/gelirler",
        icon: TrendingUp,
        accent: "green",
        aliases: ["gelir"],
      },
      {
        id: "muhasebe-nakit-akisi",
        label: "Nakit Akışı",
        description: "Finansal akış görünümü.",
        to: "/admin/muhasebe/nakit-akisi",
        icon: ArrowLeftRight,
        accent: "green",
        aliases: ["nakit", "cash flow", "akış"],
      },
      {
        id: "muhasebe-butce",
        label: "Bütçe",
        description: "Yıllık departman bütçesi, gelir beklentisi ve runway.",
        to: "/admin/muhasebe/butce",
        icon: Wallet,
        accent: "green",
        aliases: ["bütçe", "butce", "budget", "runway"],
      },
    ],
  },
  {
    id: "service-finder",
    label: "Hizmet Bulucu",
    accent: "sky",
    items: [
      {
        id: "service-finder-dashboard",
        label: "Hizmet Bulucu",
        shortLabel: "Bulucu",
        description: "AI destekli hizmet sağlayıcı keşfi — özet ve hızlı iş oluşturma.",
        to: "/admin/service-finder",
        icon: Sparkles,
        accent: "sky",
        aliases: ["service finder", "bulucu", "tarama", "scraper", "keşif"],
      },
      {
        id: "service-finder-jobs",
        label: "Tarama İşleri",
        description: "İş kuyruğu, durum ve aday incelemesi.",
        to: "/admin/service-finder/jobs",
        icon: ListChecks,
        accent: "sky",
        aliases: ["tarama işi", "job", "kuyruk"],
        match: ["/admin/service-finder/jobs"],
      },
      {
        id: "service-finder-providers",
        label: "Sağlayıcılar",
        description: "Tavily / SerpAPI / Gemini ayarları ve bütçe tavanları.",
        to: "/admin/service-finder/providers",
        icon: SlidersHorizontal,
        accent: "sky",
        aliases: ["tavily", "serpapi", "gemini", "sağlayıcı", "provider"],
      },
      {
        id: "service-finder-templates",
        label: "Meslek Şablonları",
        description: "Sorgu üretimi için meslek/dil terimi şablonları.",
        to: "/admin/service-finder/templates",
        icon: ClipboardList,
        accent: "sky",
        aliases: ["şablon", "template", "meslek"],
      },
      {
        id: "service-finder-costs",
        label: "Maliyetler",
        description: "Sağlayıcı bazında maliyet defteri toplamları.",
        to: "/admin/service-finder/costs",
        icon: TrendingUp,
        accent: "sky",
        aliases: ["maliyet", "cost", "harcama", "bütçe"],
      },
      {
        id: "service-finder-guide",
        label: "Hizmet Bulucu Kılavuzu",
        shortLabel: "Kılavuz",
        description: "İş oluşturma, aday inceleme ve sağlayıcı ayarları rehberi.",
        to: "/admin/service-finder/guide",
        icon: BookOpen,
        accent: "sky",
        aliases: ["hizmet bulucu kılavuz", "scrapper rehber", "tarama rehber", "bulucu kılavuz"],
      },
    ],
  },
  {
    id: "relocation-ingestion",
    label: "Kullanıcı Araçları",
    accent: "sky",
    items: [
      {
        id: "relocation-ingestion-jobs",
        label: "Toplama İşleri",
        shortLabel: "İşler",
        description: "Taşınma kaynak toplama işleri ve worker durumu.",
        to: "/admin/relocation-ingestion",
        icon: ListChecks,
        accent: "sky",
        aliases: ["relocation", "taşınma toplama", "ingestion", "relokasyon iş"],
      },
      {
        id: "relocation-ingestion-candidates",
        label: "Aday İnceleme",
        description: "Toplanan servis/bürokrasi/acil adaylarını onayla ve yayınla.",
        to: "/admin/relocation-ingestion/candidates",
        icon: ClipboardList,
        accent: "sky",
        aliases: ["taşınma aday", "relocation candidate", "aday onay"],
        match: ["/admin/relocation-ingestion/candidates"],
      },
      {
        id: "relocation-tools-question-counts",
        label: "Araç Soru Sayıları",
        shortLabel: "Soru Sayıları",
        description: "Her relocation aracında hızlı/normal modda kaç soru/alan var, canlı DB'den.",
        to: "/admin/relocation-tools/soru-sayilari",
        icon: Table2,
        accent: "sky",
        aliases: ["soru sayısı", "relocation tool questions", "araç soru", "quiz sayısı"],
      },
    ],
  },
  {
    id: "radar",
    label: "Radar Haber Pipeline",
    accent: "violet",
    items: [
      {
        id: "radar-queue",
        label: "Moderasyon Kuyruğu",
        shortLabel: "Kuyruk",
        description: "Bekleyen haber adaylarını incele, onayla veya reddet.",
        to: "/admin/radar/queue",
        icon: Radio,
        accent: "violet",
        aliases: ["radar", "haber kuyruğu", "moderasyon", "aday haber"],
      },
      {
        id: "radar-sources",
        label: "Haber Kaynakları",
        shortLabel: "Kaynaklar",
        description: "RSS, Atom ve GDELT kaynaklarını yönet.",
        to: "/admin/radar/sources",
        icon: Newspaper,
        accent: "violet",
        aliases: ["kaynak", "rss", "atom", "gdelt", "feed"],
      },
      {
        id: "radar-runs",
        label: "Tarama Geçmişi",
        shortLabel: "Taramalar",
        description: "Günlük cron ve manuel tarama sonuçlarını izle.",
        to: "/admin/radar/runs",
        icon: ListChecks,
        accent: "violet",
        aliases: ["tarama geçmişi", "cron", "scan runs"],
      },
      {
        id: "radar-guide",
        label: "Radar Kural Kitabı",
        shortLabel: "Rehber",
        description: "Radar'ın nasıl çalıştığını ve nasıl yönetildiğini anlatan rehber.",
        to: "/admin/radar/rehber",
        icon: BookOpen,
        accent: "violet",
        aliases: ["radar rehber", "haber rehber", "radar kılavuz", "haber otomasyonu rehber"],
      },
    ],
  },
  {
    id: "links",
    label: "Linkler",
    accent: "indigo",
    items: [
      {
        id: "links-overview",
        label: "Linkler",
        description: "Admin panelinden hızlı erişilen dış araçlar ve panolar.",
        to: "/admin/links",
        icon: Link2,
        accent: "indigo",
        aliases: ["link", "linkler", "dış bağlantı", "araçlar", "kısayol"],
      },
      {
        id: "external-site-traffic",
        label: "Site Trafik Durumu",
        description: "Microsoft Clarity — site trafik ve davranış panosu.",
        href: "https://clarity.microsoft.com/projects/view/wdkgdje6rb/",
        icon: BarChart3,
        accent: "indigo",
        isExternal: true,
        aliases: ["trafik", "clarity", "site trafik", "analytics", "ziyaretçi", "istatistik"],
      },
    ],
  },
  {
    id: "system",
    label: "Sistem",
    accent: "red",
    items: [
      {
        id: "about",
        label: "Ürün Güncellemeleri",
        description: "Sürüm notları ve güncellemeler.",
        to: "/admin/about",
        icon: Newspaper,
        accent: "red",
        aliases: ["güncelleme", "sürüm", "release", "about"],
      },
      {
        id: "notification-settings",
        label: "Bildirim Ayarları",
        shortLabel: "Bildirimler",
        description: "Yeni üye ve güncelleme e-postalarını aç/kapa; kendi aboneliğini yönet.",
        to: "/admin/notifications",
        icon: BellRing,
        accent: "red",
        aliases: ["bildirim", "mail", "e-posta", "eposta", "abonelik", "notification", "yeni üye"],
      },
      {
        id: "tools",
        label: "Araç Kataloğu",
        shortLabel: "Araçlar",
        description: "Platformun tüm edge function, worker, modül ve script'leri — koddan otomatik üretilen liste.",
        to: "/admin/tools",
        icon: Boxes,
        accent: "red",
        aliases: ["araç", "arac", "tool", "registry", "katalog", "edge", "worker"],
      },
      {
        id: "agent-analytics",
        label: "Agent Analitik",
        shortLabel: "Analitik",
        description: "Araç sağlığı, yönlendirme skorları ve gizlilik özeti.",
        to: "/admin/agent-analytics",
        icon: BarChart3,
        accent: "red",
        aliases: ["analitik", "skor", "score", "routing", "agent", "metrik", "saglik"],
      },
      {
        id: "admin-guide",
        label: "Admin Kullanım Kılavuzu",
        shortLabel: "Kılavuz",
        description: "Tüm admin fonksiyonlarının kullanım rehberi.",
        to: "/admin/guide",
        icon: BookOpen,
        accent: "red",
        aliases: ["yardım", "kılavuz", "klavuz", "guide", "help", "rehber"],
      },
      {
        id: "external-engine",
        label: "Engine",
        href: "https://eng.corteqs.net",
        icon: ExternalLink,
        accent: "red",
        isExternal: true,
        aliases: ["engine"],
      },
      {
        id: "external-globe",
        label: "Globe",
        href: "https://globe.corteqs.net",
        icon: ExternalLink,
        accent: "red",
        isExternal: true,
        aliases: ["globe"],
      },
      {
        id: "external-founders",
        label: "Founders",
        href: "https://corteqs.net/founders",
        icon: ExternalLink,
        accent: "red",
        isExternal: true,
        aliases: ["founders", "kurucular"],
      },
      {
        id: "external-drive",
        label: "Drive Klasörü",
        href: "https://drive.google.com/drive/u/3/folders/1TYFEdjDPOLOMWAf_MScs6XJXRW9FHh-r",
        icon: FolderOpen,
        accent: "red",
        isExternal: true,
        aliases: ["drive", "google drive", "klasör", "klasor", "dosyalar", "drive klasörü"],
      },
    ],
  },
];
