/**
 * Kariyer sayfasının ilan verisi — 17 ilan + staj programı (KR01).
 *
 * ⚠️ BU VERİ `src/lib/kadro/` İLE BİRLEŞTİRİLMEZ — kopya değildir, ayrı iştir.
 * `kadro` iç işe alım konsoludur: canlı DB tablolarını okur
 * (`kadro_role_states`, `kadro_candidates`, `kadro_role_events`), 52 iç rolü
 * durum/aday/dalga ekseninde izler ve yalnız yöneticiye görünür. Buradaki veri
 * ise **herkese açık ilan metnidir**: statiktir, çeviri ve pazarlama diline
 * sahiptir, sürümü git'tedir ve değişince deploy gerekir. İkisinin yaşam döngüsü,
 * kitlesi ve alanları farklıdır; tek tabloya indirmek ilan metnini DB'ye,
 * iç kadro durumunu da herkese açık sayfaya taşır. Gerekçe kaynak planda:
 * `docs/plans/2026-09-30-kariyer-sayfasi-yenileme-plani.md` → "Onaylanan kararlar" md. 2.
 *
 * Kaynak: ekipten gelen `kariyer (1).html` (28 Eylül 2026 sürümü), satır 404–406.
 * Veri **makineyle** çıkarıldı; elle kopyalanmadı.
 */
import type { CareerArea, CareerInternship, CareerJob } from "./careers-types";

export const CAREER_AREAS: CareerArea[] = [
  { id: "ops", label: "Operasyon ve ağ" },
  { id: "biz", label: "İş ortaklıkları" },
  { id: "mkt", label: "Pazarlama, içerik ve topluluk" },
  { id: "prd", label: "Ürün" },
  { id: "tech", label: "Teknoloji" },
];

export const CAREER_JOBS: CareerJob[] = [
  {
    id: "coo",
    area: "ops",
    tr: "Operasyon Direktörü",
    en: "COO (Chief Operating Officer)",
    badges: [
      "Kurucu ortak adayı",
      "Yatırımcı-Ortak Modeli'ne açık",
    ],
    intro: "CorteQS'in operasyon motorunu kuracak, departmanları bir makine gibi birlikte çalıştıracak COO'yu arıyoruz. 19 ülkede pre-launch, 29 Ekim'de tam açılış ve ardından şehir şehir büyüme var; bu ritmi tasarlayıp sürdürecek kişi sensin.",
    tasks: [
      "Tüm departmanların makro ve mikro operasyonel süreçlerini kurar, ölçer ve sürekli iyileştirirsin",
      "Ülke contributor ağı ve Şehir Elçileri katmanının operasyonunu (açılış, seçim, ritim, kalite) yönetirsin",
      "Haftalık operasyon ritmini, hedef ve KPI sistemini kurarsın; darboğazları erkenden görürsün",
      "Destek, moderasyon ve ileride finans-hukuk operasyonunun temellerini atarsın",
      "Kurucularla birlikte işe alım, ekip yapısı ve ölçeklenme kararlarında masada olursun",
    ],
    profile: [
      "10+ yıl operasyon, genel müdürlük veya ölçeklenen bir şirkette C-level/direktör deneyimi",
      "Platform, marketplace veya çok ülkeli bir organizasyonda operasyon kurmuş olmak",
      "Süreç, veri ve otomasyonla düşünen; AI araçlarını günlük işine sokmuş biri",
      "Belirsizlikte bile yapı kurabilen, sakin ama hızlı karar alan liderlik tarzı",
    ],
    plus: "Uber, Airbnb, Getir gibi şehir bazlı açılış yapan bir şirkette deneyim; diaspora topluluklarını tanımak.",
    report: "Kuruculara raporlar. Giriş seviyesi COO'dur; kurucu ortaklık yoludur.",
    model: "Kurucu Ekip Modeli (ertelenmiş ücret + 4 yıl vesting, hedef bazlı hızlandırma) veya Yatırımcı-Ortak Modeli.",
  },
  {
    id: "network",
    area: "ops",
    tr: "Global Ağ Yöneticisi",
    en: "Global Network Manager (Country Contributors)",
    badges: [
      "Vesting'li ortaklık payı",
    ],
    intro: "Her ülkede CorteQS'in yerel sesi olacak contributor katmanını kuracak ve Şehir Elçileri ile birlikte tek bir büyüme ağına dönüştürecek birini arıyoruz. Dağınık bir gönüllü listesi değil; görevleri, ritmi ve yükselme yolu belli, yaşayan bir ağ kuracaksın.",
    tasks: [
      "19 ülkelik pre-launch sürecinde her ülkede contributor ağını kurar ve büyütürsün",
      "Contributor seçimi, görev tanımları, motivasyon ve ödül modelini tasarlarsın",
      "Local Contributor → Şehir Elçisi → Country Lead → Regional Lead yükselme yolunu işletirsin",
      "Merkezden gelen içerik ve kampanyaların yerelde yayılmasını, yerelden gelen geri bildirimlerin merkeze ulaşmasını sağlarsın",
      "Ülke bazlı ağ sağlığı metriklerini (aktif contributor, kazanılan kullanıcı ve işletme) takip edersin",
    ],
    profile: [
      "4+ yıl topluluk yönetimi, ambassador programı veya çok ülkeli saha ekibi yönetimi deneyimi",
      "Gönüllü ve performans bazlı ağları motive etmeyi bilen, uzaktan ekip yönetebilen biri",
      "Diaspora dinamiklerini yaşamış ya da yakından tanıyan",
    ],
    plus: "Google Local Guides, Couchsurfing, Meetup veya öğrenci ağı gibi programlarda organizatörlük.",
    report: "COO'ya raporlar (başlangıçta kuruculara). Global Network Manager → Head of Global Network → Director of Expansion.",
    model: "Kurucu Ekip Modeli (ertelenmiş ücret + 4 yıl vesting).",
  },
  {
    id: "partnerships",
    area: "biz",
    tr: "İş Ortaklıkları ve Ayrıcalıklar Lideri",
    en: "Head of Partnerships & Perks",
    badges: [
      "Kurucu ortak adayı",
      "Yatırımcı-Ortak Modeli'ne açık",
    ],
    intro: "Diaspora çapındaki tüm Türk işletmeleriyle affiliate ve indirim katmanını kuracak, CorteQS'in ticari tarafını sahiplenecek birini arıyoruz. Berlin'deki bir restorandan Dubai'deki bir klinik zincirine kadar işletmeleri, kullanıcılara değer veren kampanyalarla platforma bağlayacaksın.",
    tasks: [
      "Diaspora işletmeleri ve profesyonellerle affiliate, indirim ve sadakat kuponu anlaşmaları kurarsın",
      "Kupon ve indirim katmanının ticari modelini, kurallarını ve fiyatlamasını belirlersin",
      "İşletme ve profesyonellerle ortak kampanyalar tasarlar, Kurucu 1000 satışını büyütürsün",
      "Ülke kümeleri bazlı iş geliştirme ekibini kurar ve yönetirsin",
      "Birim gelirini, dönüşümü ve partner memnuniyetini ölçüp raporlarsın",
    ],
    profile: [
      "7+ yıl partnerships, iş geliştirme veya ticari yönetim deneyimi",
      "Sadakat programları, affiliate ağları veya B2B2C kampanya kurgusunda somut başarılar",
      "Ekip kurmuş, hedef koymuş ve gelir sorumluluğu taşımış olmak",
      "Birden fazla ülkede işletmelerle çalışabilecek ilişki gücü ve dil yetkinliği",
    ],
    plus: "Havayolu, banka veya kart sadakat programı deneyimi; diaspora işletme ağlarını tanımak.",
    report: "Kuruculara raporlar. Head of Partnerships & Perks → BU Director (birim kendi gelir-gider tablosunu oluşturduğunda) → CCO.",
    model: "Kurucu Ekip Modeli (ertelenmiş ücret + 4 yıl vesting + birim geliri primi) veya Yatırımcı-Ortak Modeli.",
  },
  {
    id: "bd",
    area: "biz",
    tr: "İş Geliştirme Sorumlusu",
    en: "Business Development Responsible",
    badges: [
      "Birden fazla kişi",
      "Ülke veya şehir kümesi bazlı",
      "Komisyon ağırlıklı",
    ],
    intro: "Yaşadığın bölgedeki Türk işletmelerini ve profesyonellerini CorteQS'e kazandıracak, onlarla kampanya ve indirim anlaşmaları kapatacak iş geliştirme sorumluları arıyoruz. Her kişi bir ülke veya şehir kümesinden (örneğin DACH, Benelüks, Körfez, Kuzey Amerika) sorumlu olacak.",
    tasks: [
      "Bölgendeki işletme ve profesyonellere ulaşır, CorteQS'i ve Kurucu 1000 programını anlatırsın",
      "Affiliate, indirim ve kampanya anlaşmalarını kapatır, sonrasını takip edersin",
      "Kendi satış hattını CRM üzerinde düzenli tutarsın",
      "Sahadan gelen ihtiyaç ve geri bildirimleri İş Ortaklıkları Lideri'ne taşırsın",
    ],
    profile: [
      "Satış, iş geliştirme veya hesap yönetiminde 2+ yıl deneyim (güçlü bir çevre, deneyim eksiğini telafi eder)",
      "Bölgendeki Türk işletme çevresini tanıyan, telefonu açmaktan çekinmeyen biri",
      "Hedef odaklı, kendi takvimini yönetebilen, sonuçla ölçülmekten keyif alan",
    ],
    plus: "Birden fazla dil; restoran, sağlık, emlak veya hukuk sektörlerinde çevre.",
    report: "Head of Partnerships & Perks'e raporlar. BD Responsible → BD Manager (3–5 kişilik ekip yönetmeye başladığında) → Senior BD Manager → Regional BD Lead → Head of BD.",
    model: "Kapattığın anlaşmalardan komisyon + küçük sabit destek; yüksek performans gösterenler için vesting'li ortaklık payı.",
  },
  {
    id: "sponsorship",
    area: "biz",
    tr: "Sponsorluk Yöneticisi",
    en: "Sponsorship Manager",
    badges: [
      "Vesting'li ortaklık payı",
      "Başarı primi",
    ],
    intro: "Diasporanın yarışmalarına, oyunlarına ve milli gün kampanyalarına ulusal ve global sponsorlar bağlayacak birini arıyoruz. Ülke ülke sponsor haritasını çıkaracak, platformdaki işletme ve kuruluşları da sponsorluk ekosistemine dahil edeceksin.",
    tasks: [
      "Ülke bazlı potansiyel sponsor haritası ve satış hattı kurarsın",
      "Platformdaki işletme, profesyonel ve kuruluşlardan kademeli sponsorluk programları tasarlarsın",
      "Blogger ve vlogger yarışmaları, Diaspora Olimpiyatları, liderlik ödülleri ve milli gün kampanyalarına sponsor bağlarsın",
      "Kampanya ve içerik ekipleriyle sponsor aktivasyonlarını planlar, sonuçları sponsorlara raporlarsın",
      "Sponsor ilişkilerini yıllık yenileme ve büyütme odağıyla yönetirsin",
    ],
    profile: [
      "5+ yıl sponsorluk, marka ortaklıkları veya ajans tarafında deneyim",
      "Kurumsal markalarla müzakere etmiş, sponsorluk paketi kurgulayıp satmış olmak",
      "Sponsor yatırımının geri dönüşünü ölçüp anlatabilen analitik bir bakış",
    ],
    plus: "Havayolu, banka, telekom veya Türk ihracat markalarıyla mevcut ilişkiler.",
    report: "Head of Partnerships & Perks'e raporlar (hedef: CCO). Sponsorship Manager → Head of Sponsorships → Director of Strategic Partnerships.",
    model: "Kurucu Ekip Modeli (ertelenmiş ücret + 4 yıl vesting) ve sponsorluk başarı primi.",
  },
  {
    id: "marketing",
    area: "mkt",
    tr: "Pazarlama Lideri",
    en: "Head of Marketing",
    badges: [
      "Kurucu ortak adayı",
      "Yatırımcı-Ortak Modeli'ne açık",
    ],
    intro: "CorteQS'i dünyanın her yerindeki Türkler için ilk akla gelen adres yapacak pazarlama liderini arıyoruz. İçerik, kanallar, içerik üreticileri ve kampanyalardan oluşan güçlü bir ekibi tek bir marka hikâyesi etrafında toplayacaksın.",
    tasks: [
      "Çok ülkeli bir diaspora markası olarak CorteQS'in konumlandırmasını ve marka dilini kurarsın",
      "İçerik, kanal, creator ve kampanya ekiplerini tek bir stratejide birleştirir ve yönetirsin",
      "Büyüme ve performans pazarlamasını (kullanıcı, işletme ve profesyonel kazanımı) kurgularsın",
      "Cadde hedefli reklam ürünü ve iş ortaklıkları ekipleriyle ticari pazarlamayı koordine edersin",
      "Pazarlama bütçesini, hedeflerini ve ölçüm sistemini sahiplenirsin",
    ],
    profile: [
      "10+ yıl marka ve büyüme pazarlaması; ekip yönetmiş bir lider",
      "Topluluk odaklı bir platform veya tüketici markasını birden fazla pazarda büyütmüş olmak",
      "Hem hikâye anlatan hem de veriyle yöneten, dengeli bir pazarlama anlayışı",
    ],
    plus: "Diaspora pazarlarını tanımak; platform ya da pazar yeri pazarlaması deneyimi.",
    report: "Kuruculara raporlar. Head of Marketing → VP Marketing → CMO.",
    model: "Kurucu Ekip Modeli (ertelenmiş ücret + 4 yıl vesting, hedef bazlı hızlandırma) veya Yatırımcı-Ortak Modeli.",
  },
  {
    id: "content",
    area: "mkt",
    tr: "İçerik Sorumlusu",
    en: "Content Responsible",
    badges: [
      "Vesting'li ortaklık payı",
      "Kıdemli adaylar Head of Content seviyesinden girebilir",
    ],
    intro: "CorteQS'in Instagram'ını bir \"CorteQS TV kanalı\" gibi yayına sokacak, tüm sosyal kanalları besleyen içerik motorunu çalıştıracak birini arıyoruz. Instagram'ı avucunun içi gibi bilen, hem strateji kuran hem de gerektiğinde üretime inen biri olmalısın.",
    tasks: [
      "Instagram'ın bütününü sahiplenirsin: grid tasarımı, yayın takvimi, formatlar, büyüme",
      "Sponsorlu, manuel, otomasyon ve collab içeriklerini bir arada yürütürsün",
      "Her hafta ana içerikleri üretir, AI destekli akışla bunları Meta, video, topluluk kanalları ve LinkedIn formatlarına dönüştürürsün",
      "B2B (işletme, sponsor) ve B2C (diaspora kullanıcısı) için içerik, kampanya ve işbirliği kurgularsın",
      "Story Editörü'nü ve ileride kanal sorumlularını yönetirsin; performansı ölçüp optimize edersin",
    ],
    profile: [
      "4+ yıl sosyal medya, içerik veya marka iletişimi deneyimi; büyüttüğün hesaplar ve kampanyalar",
      "Meta ekosistemine (Instagram, Facebook, reklam yöneticisi, collab ve creator araçları) derin hakimiyet",
      "AI içerik araçları ve otomasyon sistemleriyle günlük çalışan biri",
      "Creator ve marka ilişkilerini yürütebilecek iletişim gücü",
    ],
    plus: "Bir medya markasında \"kanal\" mantığıyla yayın akışı kurmuş olmak; diaspora yaşamı.",
    report: "Head of Marketing'e raporlar (başlangıçta kuruculara). Content Responsible → Content Manager → Head of Content → Director of Content & Media → CMO.",
    model: "Kurucu Ekip Modeli (ertelenmiş ücret + 4 yıl vesting).",
  },
  {
    id: "story",
    area: "mkt",
    tr: "Story Editörü",
    en: "Story Editor",
    badges: [
      "Performans ve prim",
    ],
    intro: "Dünyanın dört bir yanındaki diaspora hikâyelerini Instagram story ve reels'te, her gün merakla takip edilen editöryel bir yayın kuşağına dönüştürecek bir editör arıyoruz. Diasporada kimin ne ürettiğini herkesten önce gören, doğru içerik üreticisini doğru hikâyeyle buluşturan ve her story'yi platforma açılan bir kapıya çeviren biri.",
    tasks: [
      "Diaspora ekosistemini sürekli tararsın: kim, hangi ülkeden, ne tür reels paylaşıyor ve nasıl bir etkileşim alıyor. Bunu düzenli bir izleme listesine ve içgörü raporuna dönüştürürsün.",
      "Her içerik üreticisi için doğru işbirliği modelini belirlersin: paylaşım, ortak yayın, seri, hesap devri (takeover) ya da kampanya.",
      "CorteQS story'lerinde yer almak isteyen kişi, işletme ve kuruluşlar için yaratıcı başvuru kampanyaları ve dönüşüm odaklı akışlar tasarlarsın.",
      "Tüm içerikleri ülke, şehir, tema ve format bazında kategorize ederek yeniden kullanılabilir bir içerik arşivi kurarsın.",
      "Platform ekipleriyle (Cadde, Çarşı, Etkinlikler, Kampanyalar) koordineli işbirlikleri oluşturur, story'lerden platforma uzanan trafik akışını kurarsın.",
      "Günlük story ve reels kuşağını planlar; kapakları, CTA'ları ve seri formatlarını (örneğin \"Bir Şehir, Bir Hikâye\") tasarlarsın.",
      "29 Ekim geri sayımı gibi kampanya dönemlerinde yayın akışını yönetir; izlenme, tıklama, yanıt ve dönüşüm verileriyle formatları sürekli iyileştirirsin.",
    ],
    profile: [
      "Story ve reels formatlarında güçlü bir portföy; kurgu ve tasarım araçlarında ustalık",
      "Editöryel bir göz: neyin hikâye olduğunu ve neyin tutacağını hızla sezen biri",
      "Etkileşim verilerini okuyup içerik kararına çevirebilen, veriyle çalışan bir yaklaşım",
      "İçerik üreticileriyle rahat iletişim kuran, işbirliğini karşılıklı kazanca dönüştürebilen biri",
      "Günlük yayın ritmini aksatmadan sürdürebilecek disiplin",
    ],
    plus: "Bir medya markası ya da içerik üreticisi için yayın kuşağı yönetmiş olmak; diaspora yaşamını yakından tanımak.",
    report: "İçerik Sorumlusu'na raporlar. Story Editor → Senior Story Editor → Managing Editor → Head of Social Programming.",
    model: "Küçük sabit destek ve performans primi; ilerleyen dönemde opsiyon havuzundan pay.",
  },
  {
    id: "campaigns",
    area: "mkt",
    tr: "Kampanya ve Yarışmalar Sorumlusu",
    en: "Campaigns & Competitions Responsible",
    badges: [
      "Performans ve etkinlik primi",
    ],
    intro: "Diasporayı şehirler ve ülkeler arasında yarıştıracak, milli günlerde tüm dünyada aynı anda \"köpürecek\" kampanyaları kuracak birini arıyoruz. İlk büyük sınavın: 29 Ekim 2026 tam açılışı.",
    tasks: [
      "Blogger ve vlogger yarışmalarını (başvuru, jüri, ödül, duyuru) uçtan uca yürütürsün",
      "Şehirler ve ülkeler arası oyunlar, challenge'lar ve Diaspora Olimpiyatları gibi formatları tasarlarsın",
      "19 Mayıs, 23 Nisan, 29 Ekim gibi günlerde global diaspora kampanyaları kurgularsın",
      "İçerik, oyunlaştırma ve sponsorluk ekipleriyle birlikte yıllık kampanya takvimini oluşturursun",
      "Katılım, erişim ve kazanılan kullanıcı metrikleriyle her kampanyayı raporlarsın",
    ],
    profile: [
      "3+ yıl kampanya, etkinlik veya topluluk aktivasyonu deneyimi",
      "Dijital yarışma, kullanıcı içeriği (UGC) kampanyası veya challenge formatı yürütmüş olmak",
      "Yaratıcı fikirleri takvime, bütçeye ve sonuca bağlayabilen biri",
    ],
    plus: "Diaspora dernekleri veya öğrenci kulüpleriyle etkinlik deneyimi; oyun ve e-spor formatlarına ilgi.",
    report: "Head of Marketing'e raporlar (başlangıçta kuruculara). Campaigns & Competitions Responsible → Manager → Head of Events & Campaigns → Director of Community Experiences.",
    model: "Küçük sabit destek + kampanya ve sponsor primi; ilerleyen dönemde opsiyon havuzundan pay.",
  },
  {
    id: "creators",
    area: "mkt",
    tr: "İçerik Üretici ve Influencer İşbirlikleri Sorumlusu",
    en: "Creator & Influencer Partnerships Responsible",
    badges: [
      "Vesting'li ortaklık payı",
    ],
    intro: "Diasporanın en etkili içerik üreticilerini CorteQS'in yol arkadaşlarına dönüştürecek birini arıyoruz. Influencer'lar için özel bir karşılama deneyimi, kendi topluluklarını yönetebilecekleri bir panel ve CorteQS ile birlikte büyüyebilecekleri işbirlikleri kuracaksın.",
    tasks: [
      "Ülke ülke diaspora influencer'larını tespit eder, onlara özel bir karşılama (onboarding) akışı yürütürsün",
      "Influencer'lara özel kontrol ve topluluk yönetimi panelinin ihtiyaçlarını teknik ekiple birlikte tanımlar, paneli işletirsin",
      "CorteQS ile ortak seriler, etkinlikler, affiliate ve marka işbirlikleri tasarlarsın",
      "Creator topluluğunu (iletişim kanalları, buluşmalar, ödül ve tanınırlık) yönetirsin",
      "Story Editörü ve kampanya ekibiyle birlikte creator takvimini koordine edersin",
    ],
    profile: [
      "3+ yıl influencer marketing, creator ilişkileri veya yetenek yönetimi deneyimi",
      "Creator ekonomisini, anlaşma modellerini ve performans ölçümünü bilen biri",
      "Güven veren, uzun soluklu ilişki kurabilen iletişim tarzı",
    ],
    plus: "Diaspora içerik üreticileriyle mevcut bağlar; bir creator ajansında çalışmış olmak.",
    report: "Head of Marketing'e raporlar (başlangıçta kuruculara). Responsible → Manager → Head of Creator Partnerships → Director of Creator Economy.",
    model: "Kurucu Ekip Modeli (ertelenmiş ücret + 4 yıl vesting).",
  },
  {
    id: "community",
    area: "mkt",
    tr: "Topluluk Kanalları Sorumlusu",
    en: "Community Channels Responsible",
    badges: [
      "Performans ve prim",
    ],
    intro: "X, Reddit, Telegram ve Discord'da CorteQS'in sesi olacak birini arıyoruz. Bu kanallar birer yayın panosu değil, sohbet meydanı; gündemi yakalayan, soruya hızla cevap veren ve tartışmayı topluluğa dönüştüren birine ihtiyacımız var.",
    tasks: [
      "X hesabımızı diaspora gündeminin nabzını tutan, hızlı ve esprili bir sese dönüştürürsün",
      "r/diasporaturks topluluğunu büyütür, moderasyonunu ve AMA gibi etkinliklerini yürütürsün",
      "Telegram ve Discord topluluklarını kurar, kurallarını ve ritmini belirlersin",
      "Kanallardaki sohbetleri CorteQS'teki içerik, etkinlik ve hizmetlere yönlendirirsin",
      "Topluluk duyarlılığını izler, olası krizleri erken fark edip yönetirsin",
    ],
    profile: [
      "2+ yıl topluluk yönetimi veya sosyal medya deneyimi",
      "Reddit ve X kültürünü içeriden bilen, doğal ve samimi yazan biri",
      "Sakin kalabilen, moderasyon ve kriz anlarında dengeli davranan bir yaklaşım",
    ],
    plus: "Diaspora forumlarında ya da öğrenci topluluklarında moderatörlük.",
    report: "İçerik Sorumlusu'na raporlar. Responsible → Community Channels Manager → Head of Community Channels.",
    model: "Küçük sabit destek ve performans primi; ilerleyen dönemde opsiyon havuzundan pay.",
  },
  {
    id: "video",
    area: "mkt",
    tr: "Video Kanal Sorumlusu",
    en: "Video Channel Responsible",
    badges: [
      "Performans primi veya proje bazlı",
    ],
    intro: "CorteQS'in YouTube kanalını gerçek bir \"CorteQS TV\"ye dönüştürecek video sorumlusunu arıyoruz. Diaspora belgeselleri, şehir rehberleri ve ilham veren röportajlarla uzun formatı kuracak; aynı içeriklerden kısa videolar üretip TikTok ve Shorts'ta yayacaksın.",
    tasks: [
      "YouTube kanalının yayın takvimini ve seri formatlarını (belgesel, röportaj, şehir rehberi) kurarsın",
      "Uzun içeriklerden Shorts ve TikTok için kısa kesimler üretirsin",
      "Vlogger yarışması ve kampanyalarla koordineli video içerikleri planlarsın",
      "Kapak görselleri, başlıklar ve arama optimizasyonuyla kanal büyümesini yönetirsin",
      "İzlenme süresi, abone ve etkileşim verileriyle formatları iyileştirirsin",
    ],
    profile: [
      "3+ yıl video prodüksiyon veya YouTube kanal yönetimi deneyimi",
      "Çekim, kurgu ve hikâye anlatımında güçlü bir portföy",
      "Platform algoritmalarını ve kısa video trendlerini yakından takip eden biri",
    ],
    plus: "Belgesel veya seyahat içeriği üretmiş olmak; diaspora vlogger'larıyla bağlar.",
    report: "İçerik Sorumlusu'na raporlar. Responsible → Video Manager → Head of Video (CorteQS TV).",
    model: "Performans primi veya proje bazlı ödeme; ilerleyen dönemde opsiyon havuzundan pay.",
  },
  {
    id: "carsi",
    area: "prd",
    tr: "Çarşı Sorumlusu",
    en: "Marketplace Responsible",
    badges: [
      "Vesting'li ortaklık payı",
    ],
    intro: "Diasporanın ikinci el eşyadan oda kiralamaya, özel dersten hizmet ilanlarına uzanan pazar yeri Çarşı'yı açacak ve büyütecek birini arıyoruz. Yurt dışına yeni taşınan birinin ilk mobilyasını, ilk odasını bulduğu yer burası olacak.",
    tasks: [
      "Çarşı'nın açılışını planlar ve yürütürsün; kategori yapısını ve ilan kurallarını belirlersin",
      "İlk satıcıları ve ilanları kazanarak arzı, şehir bazlı kampanyalarla talebi büyütürsün",
      "Güven, doğrulama ve moderasyon süreçlerini kurar, dolandırıcılığa karşı önlemleri belirlersin",
      "Çarşı ilanlarının Cadde akışında ve profillerde görünürlüğünü ürün ekibiyle birlikte geliştirirsin",
      "Premium ilan ve öne çıkarma (boost) gelirini büyütür; ilan, iletişim ve satış dönüşümlerini takip edersin",
    ],
    profile: [
      "3+ yıl pazar yeri, e-ticaret veya ilan platformu deneyimi",
      "İki taraflı pazarların (alıcı-satıcı) dinamiklerini ve büyüme mekaniklerini bilen biri",
      "Veriyle karar veren, operasyon ile ürünü birlikte düşünebilen bir yaklaşım",
    ],
    plus: "İlan veya ikinci el platformlarında çalışmış olmak; yurt dışına taşınma sürecini yaşamış olmak.",
    report: "Başlangıçta Umut Barış Terzioğlu'na raporlar (hedef: Head of Product). Responsible → Marketplace Manager → Head of Çarşı → GM Çarşı.",
    model: "Kurucu Ekip Modeli (ertelenmiş ücret + 4 yıl vesting).",
  },
  {
    id: "gamification",
    area: "prd",
    tr: "Oyunlaştırma Ürün Sorumlusu",
    en: "Gamification Product Responsible",
    badges: [
      "Vesting'li ortaklık payı",
    ],
    intro: "CorteQS'teki her etkileşimi anlamlı bir oyuna dönüştürecek birini arıyoruz. CQ Puan ekonomisinden şehirler arası turnuvalara kadar, insanları platforma her gün geri getiren mekanikleri sen tasarlayacaksın.",
    tasks: [
      "CQ Puan ekonomisini (sadakat, etkileşim ve davet puanları) uçtan uca tasarlar ve dengelersin",
      "Yolcu → Gezgin → Kaşif → Elçi → Efsane seviye sistemini ve ödül mekaniğini geliştirirsin",
      "Kişi, şehir ve ülke liderlik tablolarını ve ödül kurgusunu yönetirsin",
      "Oyunlaştırmayı Cadde, Çarşı, etkinlikler ve kampanyalara yayarsın",
      "Diaspora Olimpiyatları, Memleket Quiz ve Cadde Savaşları'nın ürün tarafını sahiplenirsin",
      "Deneylerle (A/B testleri) bağlılık ve geri dönüş metriklerini iyileştirirsin",
    ],
    profile: [
      "3+ yıl ürün yönetimi, oyun tasarımı veya oyunlaştırma deneyimi",
      "Davranış tasarımı ve motivasyon psikolojisine ilgi duyan biri",
      "Puan ekonomisini hem eğlenceli hem sürdürülebilir kurgulayabilen analitik bir bakış",
    ],
    plus: "Mobil oyun, sadakat programı ya da topluluk oyunları deneyimi.",
    report: "Başlangıçta Umut Barış Terzioğlu'na raporlar (hedef: Head of Product). Responsible → Manager → Head of Gamification → Head of Gaming.",
    model: "Kurucu Ekip Modeli (ertelenmiş ücret + 4 yıl vesting).",
  },
  {
    id: "socialapp",
    area: "prd",
    tr: "Sosyal Uygulama Ürün Sorumlusu",
    en: "Social App Product Responsible",
    badges: [
      "Vesting'li ortaklık payı",
    ],
    intro: "CorteQS'in sosyal uygulamasını, diasporanın her gün açtığı bir alışkanlığa dönüştürecek ürün sorumlusunu arıyoruz. Kullanıcıyı dinleyecek, mühendislikle omuz omuza çalışacak ve uygulamanın yol haritasını sahipleneceksin.",
    tasks: [
      "Sosyal uygulamanın ürün vizyonunu ve yol haritasını belirlersin",
      "Kullanıcı araştırmaları yapar, ihtiyaçları önceliklendirilmiş özelliklere çevirirsin",
      "Mühendislik ekibiyle birlikte geliştirme döngüsünü yönetirsin",
      "Aktivasyon, günlük kullanım ve geri dönüş metriklerini takip edip iyileştirirsin",
      "Uygulama mağazalarındaki varlığı ve kullanıcı geri bildirimlerini sahiplenirsin",
    ],
    profile: [
      "3+ yıl ürün yönetimi; tercihen mobil ve sosyal tüketici uygulamaları",
      "Veriyle karar veren, kullanıcıya empatiyle yaklaşan biri",
      "Tasarım ve mühendislikle aynı dili konuşabilen iletişim gücü",
    ],
    plus: "Sosyal akış, mesajlaşma veya topluluk uygulaması deneyimi.",
    report: "Başlangıçta Umut Barış Terzioğlu'na raporlar (hedef: Head of Product). Responsible → Product Manager → Senior PM → Head of Product → CPO.",
    model: "Kurucu Ekip Modeli (ertelenmiş ücret + 4 yıl vesting).",
  },
  {
    id: "founding-eng",
    area: "tech",
    tr: "Kurucu Mühendis (Kıdemli)",
    en: "Founding Engineer (Senior)",
    badges: [
      "Vesting'li ortaklık payı",
    ],
    intro: "Kurucu ortağımız ve CTO'muz Umut Barış Terzioğlu'nun yanında CorteQS'in teknik çekirdeğini kuracak kıdemli mühendisler arıyoruz. Global ölçeğe hazır bir platformu, açılış temposunda ayağa kaldıracaksın.",
    tasks: [
      "React + TypeScript ön yüz ve Supabase (Postgres, RLS, Edge Functions) arka yüz üzerinde kritik modülleri geliştirirsin",
      "Stripe ödeme, AI arama, relocation chat ve AI Twin gibi entegrasyonları üretim kalitesine taşırsın",
      "Mimari, güvenlik ve ölçeklenebilirlik kararlarında Barış'la birlikte karar verirsin",
      "Test, kod inceleme ve dağıtım süreçlerini kurar, junior mühendislere mentorluk edersin",
    ],
    profile: [
      "6+ yıl yazılım geliştirme; en az bir ürünü sıfırdan canlıya taşımış olmak",
      "React, TypeScript ve Postgres'te derin deneyim; Supabase veya benzeri BaaS deneyimi",
      "AI destekli geliştirme araçlarını ve LLM entegrasyonlarını günlük kullanan biri",
      "Hız ile kaliteyi dengeleyebilen, ürün ve iş modeli perspektifiyle düşünen",
    ],
    plus: "Mobil uygulama, marketplace veya sosyal akış deneyimi; DevOps ve güvenlik yetkinliği.",
    report: "CTO Umut Barış Terzioğlu'na raporlar. Senior Engineer → Staff / Tech Lead → Head of Engineering.",
    model: "Kurucu Ekip Modeli (ertelenmiş ücret + 4 yıl vesting).",
  },
  {
    id: "junior-eng",
    area: "tech",
    tr: "Yazılım Mühendisi",
    en: "Junior Engineer",
    badges: [
      "Birden fazla kişi",
    ],
    intro: "Kariyerinin başında, yapay zekâ çağının geliştirme pratiklerini gerçek bir üründe öğrenmek isteyen mühendisler arıyoruz. Kıdemli ekip arkadaşlarının yanında, milyonlarca kullanıcıya ulaşacak bir platformda ilk günden üretime katkı vereceksin.",
    tasks: [
      "Kurucu mühendislerle birlikte yeni özellikler geliştirirsin (React, TypeScript, Supabase)",
      "Hata ayıklama, test ve kod inceleme süreçlerine katılırsın",
      "AI destekli geliştirme araçlarını günlük işinde kullanarak hızla öğrenirsin",
      "Küçük modüllerin sahipliğini zamanla tamamen üstlenirsin",
    ],
    profile: [
      "0–2 yıl deneyim; son sınıf öğrencileri ve yeni mezunlar da başvurabilir",
      "JavaScript/TypeScript ve React temelleri; GitHub'da gösterebileceğin projeler",
      "Öğrenme iştahı yüksek, soru sormaktan çekinmeyen, sorumluluk alan biri",
    ],
    plus: "Kendi yaptığın bir web ya da mobil uygulama; açık kaynak katkıları.",
    report: "Kurucu Mühendis'e raporlar. Junior Engineer → Engineer → Senior Engineer.",
    model: "Nakit ağırlıklı ücret; ilerleyen dönemde opsiyon havuzundan pay.",
  },
];

export const CAREER_INTERNSHIP: CareerInternship = {
  id: "intern",
  tr: "Geleceğin Liderleri Stajyer Programı",
  en: "Future Leaders Internship Program",
  intro: "Yarının girişimcilerini ve liderlerini bugünden aramıza katmak istiyoruz. Geleceğin Liderleri programı, dünyanın her yerindeki üniversite öğrencileri ve yeni mezunlar için; özellikle yurt dışında okuyan Türk öğrencilere kapımız sonuna kadar açık. Burada fotokopi çekmeyeceksin: gerçek bir projenin, gerçek bir sorumluluğun sahibi olacaksın.",
  tasks: [
    "Pazarlama, içerik, iş ortaklıkları, ürün, teknoloji veya operasyon birimlerinden birine yerleşirsin",
    "Sana bir mentor eşlik eder; dönem boyunca kendi projeni sahiplenirsin",
    "Dönem sonunda projeni ekibe sunarsın",
    "Başarılı stajyerler, ilgili birimde Responsible basamağından ekibe katılma fırsatı yakalar",
  ],
  profile: [
    "Üniversite öğrencisi veya son iki yılda mezun olmuş, bölüm fark etmeksizin",
    "Merakı yüksek, öğrenmeye aç, sorumluluk almaktan keyif alan biri",
    "Kendi projesini kurmadan önce bir girişimin mutfağını görmek isteyenler için ideal",
  ],
  model: "Staj belgesi, referans mektubu ve performansa bağlı prim; başarılı stajyerler için ekibe geçiş yolu.",
};
