// Katalogtaki edge function'lardan OpenAPI 3.1 sözleşmesi üretir.
// Bir ajan/istemci kaynak kod okumadan endpoint'leri, girdi alanlarını ve
// HTTP status kodlarını bu spec'ten anlar. Bağımlılıksız, deterministik YAML.
//
// Çıktı: docs/agent/openapi.yaml
// input_schema.fields'tan request body, http_statuses'tan response'lar türetilir.

const STATUS_DESCR = {
  200: "Başarılı",
  201: "Oluşturuldu",
  400: "Geçersiz istek (payload doğrulama hatası)",
  403: "Origin'e izin verilmedi",
  404: "Bulunamadı",
  405: "Yöntem desteklenmiyor",
  410: "Kullanımdan kaldırıldı (deprecated)",
  413: "Payload çok büyük",
  429: "Çok fazla istek (rate limit)",
  500: "Sunucu hatası",
};

// find-matches gibi bilinen alanların tip/kısıt bilgisi (katalog sadece adları tutar).
const FIELD_HINTS = {
  offers_needs: { type: "string", minLength: 5, maxLength: 2000 },
  sourceSubmissionId: { type: "string", format: "uuid" },
  submissionId: { type: "string", format: "uuid" },
  field: { type: "string" },
  city: { type: "string" },
  country: { type: "string" },
  category: { type: "string" },
  persist: { type: "boolean" },
  surveySlug: { type: "string" },
};

const REQUIRED_HINTS = {
  "edge.find_matches": ["offers_needs"],
  "edge.send_submission_email": ["submissionId"],
  "edge.submit_survey_response": ["surveySlug"],
};

function indent(n) {
  return "  ".repeat(n);
}

function yamlScalar(value) {
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (/[:#{}[\],&*?|<>=!%@`"]|^\s|\s$/.test(value)) {
    return `"${String(value).replace(/"/g, '\\"')}"`;
  }
  return String(value);
}

function buildPropertyLines(field, depth) {
  const hint = FIELD_HINTS[field] ?? { type: "string" };
  const lines = [`${indent(depth)}${field}:`];
  for (const [k, v] of Object.entries(hint)) {
    lines.push(`${indent(depth + 1)}${k}: ${yamlScalar(v)}`);
  }
  return lines;
}

function buildPathItem(tool) {
  const opId = `execute_${tool.tool_name.replace(/-/g, "_")}`;
  const path = `/functions/v1/${tool.tool_name}`;
  const fields = tool.input_schema?.fields ?? [];
  const required = REQUIRED_HINTS[tool.tool_key] ?? [];
  const statuses = tool.http_statuses?.length
    ? tool.http_statuses
    : [200, 400, 429, 500];

  const lines = [];
  lines.push(`${indent(1)}${path}:`);
  lines.push(`${indent(2)}post:`);
  lines.push(
    `${indent(3)}summary: ${yamlScalar(`${tool.tool_name} aracını çalıştır`)}`,
  );
  lines.push(`${indent(3)}operationId: ${opId}`);
  if (tool.status === "deprecated") {
    lines.push(`${indent(3)}deprecated: true`);
  }
  lines.push(`${indent(3)}x-tool-key: ${tool.tool_key}`);
  lines.push(`${indent(3)}x-status: ${tool.status}`);
  if (tool.tables_read_write?.length) {
    lines.push(
      `${indent(3)}x-tables: [${tool.tables_read_write.map(yamlScalar).join(", ")}]`,
    );
  }

  // Request body (varsa alanlar)
  if (fields.length) {
    lines.push(`${indent(3)}requestBody:`);
    lines.push(`${indent(4)}required: true`);
    lines.push(`${indent(4)}content:`);
    lines.push(`${indent(5)}application/json:`);
    lines.push(`${indent(6)}schema:`);
    lines.push(`${indent(7)}type: object`);
    if (required.length) {
      lines.push(`${indent(7)}required: [${required.map(yamlScalar).join(", ")}]`);
    }
    lines.push(`${indent(7)}properties:`);
    for (const f of fields) {
      lines.push(...buildPropertyLines(f, 8));
    }
  }

  // Responses
  lines.push(`${indent(3)}responses:`);
  for (const code of statuses) {
    lines.push(`${indent(4)}"${code}":`);
    lines.push(
      `${indent(5)}description: ${yamlScalar(STATUS_DESCR[code] ?? "Yanıt")}`,
    );
  }
  return lines.join("\n");
}

/**
 * Katalogtan OpenAPI 3.1 YAML üretir (yalnız edge_function ailesi).
 * @param {{ tools: object[] }} catalog
 * @returns {string}
 */
export function buildOpenApi(catalog) {
  const edges = catalog.tools
    .filter((t) => t.family === "edge_function")
    .sort((a, b) => a.tool_key.localeCompare(b.tool_key));

  const header = [
    "# AUTO-GENERATED by scripts/ingest-tools.mjs --openapi — DÜZENLEME.",
    "# Kaynak doğruluk: docs/agent/tools.json",
    "openapi: 3.1.0",
    "info:",
    "  title: CorteQS Agent Tool Gateway",
    "  version: 0.1.0",
    "  description: >-",
    "    Katalogtan otomatik üretilen edge function HTTP sözleşmeleri.",
    "    Bir ajan bu spec ile araçları kaynak kod okumadan çağırabilir.",
    "servers:",
    "  - url: https://injprdrsklkxgnaiixzh.supabase.co",
    "    description: Supabase Edge Functions",
    "paths:",
  ].join("\n");

  const paths = edges.map(buildPathItem).join("\n");
  return `${header}\n${paths}\n`;
}
