// Admin Panel V2 navigasyon registry'si — "İçerik ve Kampanyalar" grubu.
// URL path'leri App.tsx route ağacıyla birebir aynıdır ve değiştirilemez
// (masterplan §4.3). Grup sırası ../admin-navigation-registry.ts'te belirlenir.

import {
  BookOpen,
  ClipboardList,
  Crown,
  FileText,
  Heart,
  Inbox,
  Lightbulb,
  Link2,
  Megaphone,
  Radio,
  Share2,
  Store,
} from "lucide-react";

import { advisorProfileSections } from "@/lib/resource-links";
import type { AdminNavGroup, AdminNavItem } from "../admin-shell-types";

const advisorProfileItems: AdminNavItem[] = advisorProfileSections.map((section) => ({
  id: `advisors-${section.key}`,
  label: section.label,
  to: `/admin/advisors/${section.key}`,
  icon: Link2,
  accent: "amber",
}));

export const contentNavGroup: AdminNavGroup = {
  id: "content",
  label: "İçerik ve Kampanyalar",
  accent: "amber",
  items: [
    {
      id: "cadde",
      label: "Cadde",
      description: "Cadde yönetimi.",
      to: "/admin/cadde",
      icon: Store,
      accent: "amber",
      aliases: ["cadde", "marketplace"],
    },
    {
      id: "cadde-guide",
      label: "Cadde Kural Kitabı",
      description: "Cadde'nin üye ve admin tarafı rehberi.",
      to: "/admin/cadde/rehber",
      icon: BookOpen,
      accent: "amber",
      aliases: ["cadde rehber", "cadde kılavuz", "kural kitabı"],
    },
    {
      id: "surveys",
      label: "Anketler",
      description: "Survey CRUD ve cevaplar.",
      to: "/admin/surveys",
      match: ["/admin/surveys"],
      icon: ClipboardList,
      accent: "amber",
      aliases: ["anket", "survey"],
    },
    {
      id: "marquee",
      label: "Haber Bandı",
      description: "Marquee yönetimi.",
      to: "/admin/marquee",
      icon: Radio,
      accent: "amber",
      aliases: ["haber bandı", "marquee"],
    },
    {
      id: "blog",
      label: "Blog",
      description: "Ülke rehberi yazıları — oluştur, düzenle, yayınla.",
      to: "/admin/blog",
      icon: FileText,
      accent: "amber",
      aliases: ["blog", "yazı", "makale", "rehber", "ülke rehberi"],
    },
    {
      id: "social-media",
      label: "Sosyal Medya",
      description: "Sosyal medya bağlantıları.",
      to: "/admin/social-media",
      icon: Megaphone,
      accent: "amber",
      aliases: ["sosyal medya", "social"],
    },
    {
      id: "social-share-vault",
      label: "Sosyal Medya Paylaşım Deposu",
      shortLabel: "Paylaşım Deposu",
      description: "Hazır Canva görsel promptları ve LinkedIn postları — araç tanıtımları, diaspora postları ve test araçları için kopyala-paylaş.",
      to: "/admin/social-share-vault",
      icon: Share2,
      accent: "amber",
      aliases: ["sosyal medya deposu", "paylaşım", "canva", "linkedin", "prompt", "içerik paketi", "post", "diaspora", "gurbet", "test aracı", "varyant"],
    },
    {
      id: "vip-invitations",
      label: "VIP Davetleri",
      description: "Tek kullanımlık kişisel VIP davetlerini oluştur ve iptal et.",
      to: "/admin/vip-invitations",
      icon: Crown,
      accent: "amber",
      aliases: ["vip", "davet", "invitation", "özel bağlantı"],
    },
    {
      id: "yenilik-rehberi",
      label: "Yenilikler ve Test Rehberi",
      description: "Son yeniliklerin nasil calistigi ve nasil test edilecegi; HTML olarak indirilir.",
      to: "/admin/yenilik-rehberi",
      icon: FileText,
      accent: "sky",
      aliases: ["rehber", "test", "yenilik", "kilavuz", "surum notu", "burak"],
    },
    {
      id: "customer-requests",
      label: "Müşteri Talepleri",
      description: "WhatsApp taleplerini ata, durumunu yönet ve denetimli yanıtla.",
      to: "/admin/customer-requests",
      icon: Inbox,
      accent: "emerald",
      aliases: ["müşteri", "talep", "whatsapp", "destek", "inbox", "cevap"],
    },
    {
      id: "advisor-profiles",
      label: "Sosyal Link Profilleri",
      description: "Profil bazlı sosyal link içerikleri.",
      match: ["/admin/advisors"],
      icon: Link2,
      accent: "amber",
      aliases: ["advisor", "consultant", "influencer", "contributor"],
      children: advisorProfileItems,
    },
    {
      id: "may19-kelime",
      label: "19 Mayıs Kelime",
      description: "Kampanya kelime kayıtları.",
      to: "/admin/may19/kelime",
      icon: Lightbulb,
      accent: "amber",
      isInactive: true,
      aliases: ["19 mayıs", "kelime", "fikir"],
    },
    {
      id: "may19-ani",
      label: "19 Mayıs Anı",
      description: "Kampanya anı kayıtları.",
      to: "/admin/may19/ani",
      icon: Heart,
      accent: "amber",
      isInactive: true,
      aliases: ["19 mayıs", "anı"],
    },
  ],
};
