import type { KadroRole } from "../kadro-types";

export const GELIR_ROLES: KadroRole[] = [
  {
    id: "gl-b2b",
    dept: "gelir",
    axis: "merkez",
    title: "B2B Satış Yöneticisi",
    type: "core",
    wave: 2,
    pri: "yuksek",
    status: "acik",
    owner: "",
    reports: "CEO",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP + prim",
    esop: "%0.5–1.5 vesting 4y/1y cliff",
    kpi: ["Aylık pipeline değeri", "Kapanan anlaşma adedi", "Ortalama anlaşma boyutu"],
    cadence: "Günlük outreach · haftalık pipeline review · aylık gelir raporu",
    tools: "LinkedIn, Notion CRM, Google Workspace, DocuSign",
    trigger: "İlk gelir sinyali doğrulandığında",
    exit: "Gelir hattı oturduktan sonra Head of Sales rolüne evrilir",
    jd: "CorteQS'in B2B satış hattını kurar ve yönetir. Marka ve kurum müşterileri için pipeline oluşturur, teklif hazırlar, müzakereleri yürütür ve anlaşmaları kapatır. Erken aşamada ilk gelir sinyallerini toplamak bu rolün birincil görevidir.",
    ad: {
      sum: "CorteQS'in B2B satış hattını kuracak, pipeline oluşturacak ve ilk gelir sinyallerini toplayacak bir B2B satış yöneticisi arıyoruz. Early-stage start-up'ta sıfırdan satış süreci kurma deneyimi bekleniyor.",
      does: [
        "B2B pipeline oluşturmak ve haftalık review ile takip etmek",
        "Teklif dosyalarını hazırlamak ve sunmak",
        "Müzakereleri yürütmek ve anlaşmaları kapatmak",
        "İlk gelir sinyallerini toplamak ve raporlamak",
        "Aylık gelir raporunu CEO ile paylaşmak",
      ],
      profile: [
        "En az 3 yıl B2B satış deneyimi",
        "Pipeline yönetimi ve teklif hazırlama yetkinliği",
        "Start-up veya ajans ortamında çalışmış olmak",
        "Sonuç odaklı ve hedef takip alışkanlığı",
      ],
      test: "Görev testi: CorteQS için 5 hedef müşteri belirle. Her biri için bir cümlelik değer önerisi ve outreach mesajı yaz.",
    },
  },
  {
    id: "gl-sponsor",
    dept: "gelir",
    axis: "merkez",
    title: "Sponsorluk & Etkinlik Satışı",
    type: "proje",
    wave: 2,
    pri: "orta",
    status: "acik",
    owner: "",
    reports: "CEO / B2B Satış (gl-b2b)",
    hours: "Proje bazlı — aylık 30–40 saat",
    pay: "Proje başına ücret + komisyon",
    esop: "—",
    kpi: ["Aylık sponsorluk geliri", "Sponsor memnuniyet puanı", "Etkinlik bazlı dönüşüm"],
    cadence: "Haftalık sponsor pipeline · etkinlik öncesi yoğunlaşma",
    tools: "LinkedIn, Notion CRM, Canva, Google Workspace",
    trigger: "İlk topluluk etkinliği planlandığında",
    exit: "Sponsorluk programı oturduktan sonra B2B ekibine entegre olur",
    jd: "CorteQS'in etkinlik ve içerik sponsorluklarını satar. Sponsorluk paketleri oluşturur, marka tekliflerini hazırlar, etkinlik bazlı görünürlük fırsatlarını yönetir ve sponsor memnuniyetini takip eder. Proje bazlı çalışır.",
    ad: {
      sum: "CorteQS'in etkinlik ve içerik sponsorluklarını satacak, sponsorluk paketleri oluşturacak bir sponsorluk satış yöneticisi arıyoruz. Marka ilişkileri ve etkinlik sponsorluğu konusunda deneyimli bir profil bekleniyor. Proje bazlı.",
      does: [
        "Sponsorluk paketleri oluşturmak ve fiyatlandırmak",
        "Marka tekliflerini hazırlamak ve sunmak",
        "Etkinlik bazlı görünürlük fırsatlarını yönetmek",
        "Sponsor memnuniyetini takip etmek",
        "Haftalık sponsor pipeline raporunu sunmak",
      ],
      profile: [
        "Sponsorluk satışı veya etkinlik pazarlaması deneyimi",
        "Teklif dosyası hazırlama ve sunum becerisi",
        "Marka ilişkileri ve network",
        "Sonuç odaklı çalışma alışkanlığı",
      ],
      test: "Görev testi: CorteQS etkinliği için 3 sponsorluk paketi oluştur (bronze, silver, gold). Her paket için fiyat, görünürlük ve faydaları belirt.",
    },
  },
  {
    id: "gl-account",
    dept: "gelir",
    axis: "merkez",
    title: "Hesap Yöneticisi — Mevcut Müşteri İlişkileri",
    type: "core",
    wave: 3,
    pri: "orta",
    status: "beklemede",
    owner: "",
    reports: "B2B Satış (gl-b2b)",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%0.5–1 vesting 4y/1y cliff",
    kpi: ["Müşteri elde tutma oranı", "Upsell/cross-sell geliri", "NPS puanı"],
    cadence: "Haftalık müşteri check-in · çeyreklik iş planı review",
    tools: "Notion CRM, Google Workspace, Slack, Zoom",
    trigger: "Aktif B2B müşteri sayısı 5'e ulaştığında",
    exit: "Müşteri portföyü oturduktan sonra senior hesap yöneticisine evrilir",
    jd: "CorteQS'in mevcut B2B müşterilerinin ilişkilerini yönetir. Müşteri memnuniyetini takip eder, upsell ve cross-sell fırsatlarını değerlendirir, çeyreklik iş planı review'lerini yürütür ve müşterinin CorteQS'ten maksimum değer almasını sağlar. Dalga 3 rolü.",
    ad: {
      sum: "CorteQS'in mevcut B2B müşterilerinin ilişkilerini yönetecek, upsell fırsatlarını değerlendirecek bir hesap yöneticisi arıyoruz. Müşteri ilişkileri ve büyüme odaklı bir profil bekleniyor. Dalga 3 rolü.",
      does: [
        "Mevcut müşteri ilişkilerini yönetmek",
        "Upsell ve cross-sell fırsatlarını değerlendirmek",
        "Çeyreklik iş planı review'lerini yürütmek",
        "Müşteri memnuniyetini takip etmek ve raporlamak",
        "Müşteri geri bildirimlerini iç ekibe iletmek",
      ],
      profile: [
        "En az 2 yıl hesap yönetimi deneyimi",
        "Müşteri ilişkileri ve büyüme odaklı yaklaşım",
        "Notion CRM ve Google Workspace'de yetkin",
        "İletişim ve koordinasyon becerisi yüksek",
      ],
      test: "Görev testi: Mevcut bir müşteri için çeyreklik iş planı review ajandası oluştur. 3 başlık ve her biri için 2 soru belirt.",
    },
  },
];
