import type { KadroRole } from "../kadro-types";

export const KURUMSAL_ROLES: KadroRole[] = [
  {
    id: "ld-cfo",
    dept: "kurumsal",
    axis: "merkez",
    title: "Finans & Muhasebe Danışmanı",
    type: "danisman",
    wave: 1,
    pri: "yuksek",
    status: "acik",
    owner: "",
    reports: "CEO",
    hours: "Aylık 16–20 saat",
    pay: "Danışman ücreti",
    esop: "—",
    kpi: ["Aylık kapanış süresi", "Nakit akışı tahmin doğruluğu", "Vergi uyumu"],
    cadence: "Aylık finansal kapanış · çeyreklik bütçe revizyonu",
    tools: "Google Sheets, Logo Muhasebe, Stripe dashboard",
    trigger: "İlk gider kalemi düzenli hale geldiğinde",
    exit: "Tam zamanlı CFO ihtiyacı doğana kadar dış danışman olarak devam",
    jd: "CorteQS'in erken dönem finansal yapısını kurar: muhasebe altyapısı, nakit akışı takibi, bütçe planlaması ve vergi uyumu. Aylık kapanışları yürütür, çeyreklik bütçe revizyonlarını CEO ile birlikte yapar. Early-stage'de tam zamanlı CFO gerekmez; danışman modeli bilinçli tercihtir.",
    ad: {
      sum: "CorteQS'in erken dönem finansal altyapısını kuracak, aylık kapanışları yürütecek ve nakit akışı planlamasını yapacak bir finans danışmanı arıyoruz. Start-up muhasebesinde deneyimli, lean yapıya uygun bir yaklaşım bekleniyor.",
      does: [
        "Muhasebe altyapısını kurmak ve aylık kapanışları yürütmek",
        "Nakit akışı tahminlerini tutmak ve haftalık CEO'ya raporlamak",
        "Çeyreklik bütçe revizyonlarını CEO ile birlikte yapmak",
        "Vergi uyumunu sağlamak ve SGK bildirimlerini takip etmek",
        "Yatırımcı due diligence için finansal dosyayı hazır tutmak",
      ],
      profile: [
        "En az 5 yıl finans/muhasebe deneyimi, tercihen start-up ortamında",
        "Türkiye vergi mevzuatına hakim",
        "Google Sheets ve muhasebe yazılımında ileri düzey",
        "Erken aşama belirsizliğinde lean çalışma alışkanlığı",
      ],
      test: "Görev testi: CorteQS'in basit bir 3 aylık nakit akışı şablonu oluştur. 5 gelir ve 8 gider kalemi varsay. Her kalem için bir cümlelik gerekçe yaz.",
    },
  },
  {
    id: "ld-legal",
    dept: "kurumsal",
    axis: "merkez",
    title: "Hukuk Danışmanı — Start-up & Ticari",
    type: "danisman",
    wave: 1,
    pri: "orta",
    status: "acik",
    owner: "",
    reports: "CEO",
    hours: "Aylık 8–12 saat",
    pay: "Saat başı danışman ücreti",
    esop: "—",
    kpi: ["Sözleşme dönüş süresi", "Reserved Matters uyumu", "Risk taraması adedi"],
    cadence: "Ad hoc çağrı · aylık hukuki gözden geçirme",
    tools: "Google Workspace, DocuSign, Notion",
    trigger: "İlk marka ortaklığı sözleşmesi hazırlandığında",
    exit: "Hukuki altyapı oturduktan sonra çeyreklik review'ye geçer",
    jd: "CorteQS'in ticari sözleşmelerini, marka ortaklığı anlaşmalarını, ESOP planını ve Reserved Matters çerçevesini yönetir. Start-up hukukuna hakim, erken aşama dinamiklerini anlayan bir yaklaşım beklenir. Aylık 8-12 saatlik taahhüt, ad hoc çağrılarla desteklenir.",
    ad: {
      sum: "CorteQS'in ticari sözleşmelerini, ortaklık anlaşmalarını ve kurumsal hukuk altyapısını yönetecek bir start-up hukuk danışmanı arıyoruz. Erken aşama belirsizliğinde hızlı ve pratik çözümler üretebilen bir profil bekleniyor.",
      does: [
        "Ticari sözleşmeleri ve marka ortaklığı anlaşmalarını hazırlamak",
        "ESOP planını ve Reserved Matters çerçevesini yapılandırmak",
        "Fikri mülkiyet korumasını sağlamak",
        "Aylık hukuki gözden geçirmeyle riskleri raporlamak",
        "Yatırımcı term sheet ve SHA review'lerinde destek vermek",
      ],
      profile: [
        "En az 5 yıl ticari hukuk deneyimi, start-up odaklı",
        "ESOP, SHA ve term sheet konusunda çalışmış olmak",
        "Türkiye ticaret hukuku ve fikri mülkiyet mevzuatına hakim",
        "Hızlı dönüş ve pratik çözüm odaklı çalışma alışkanlığı",
      ],
      test: "Görev testi: CorteQS için basit bir NDA taslağı hazırla. Tek taraflı, 2 sayfa, Türkçe. Kritik 3 maddeyi bir cümleyle gerekçelendir.",
    },
  },
  {
    id: "ku-finans",
    dept: "kurumsal",
    axis: "merkez",
    title: "Muhasebe & İdari İşler Sorumlusu",
    type: "part",
    wave: 2,
    pri: "orta",
    status: "acik",
    owner: "",
    reports: "Finans Danışmanı (ld-cfo)",
    hours: "Haftalık 20 saat",
    pay: "Aylık sabit ücret",
    esop: "—",
    kpi: ["Fatura işleme süresi", "Gider takibi doğruluğu", "Ay sonu kapanış günü"],
    cadence: "Günlük fatura takibi · haftalık gider raporu · aylık kapanış",
    tools: "Logo Muhasebe, Google Sheets, Stripe dashboard, banka portalları",
    trigger: "Aylık işlem hacmi 50'yi geçtiğinde",
    exit: "İşlem hacmi arttığında tam zamanlıya evrilir",
    jd: "CorteQS'in günlük muhasebe işlemlerini, fatura takibini, gider kayıtlarını ve idari işlerini yürütür. Finans danışmanına rapor eder. Erken aşamada lean yapı: tek kişi, geniş sorumluluk. Muhasebe yazılımı, banka portalları ve Stripe dashboard'u günlük kullanır.",
    ad: {
      sum: "CorteQS'in günlük muhasebe işlemlerini ve idari işlerini yürütecek, erken aşama start-up ortamında lean çalışabilecek bir muhasebe sorumlusu arıyoruz. Haftalık 20 saatlik part-time bir rol.",
      does: [
        "Günlük fatura ve gider kayıtlarını işlemek",
        "Banka mutabakatlarını haftalık olarak yapmak",
        "Stripe ödemelerini takip etmek ve raporlamak",
        "Ay sonu kapanışını finans danışmanıyla birlikte tamamlamak",
        "İdari dosyalama ve evrak takibini yürütmek",
      ],
      profile: [
        "En az 2 yıl muhasebe deneyimi",
        "Türkiye vergi mevzuatına temel düzeyde hakim",
        "Google Sheets ve muhasebe yazılımında yetkin",
        "Detaylı ve düzenli çalışma alışkanlığı",
      ],
      test: "Görev testi: 10 adet örnek fatura verisi al (tutar, tarih, kategori). Bunları basit bir Google Sheets şablonuna işle ve aylık gider özet tablosu oluştur.",
    },
  },
];
