import type { KadroRole } from "../kadro-types";

export const LIDERLIK_ROLES: KadroRole[] = [
  {
    id: "ld-ceo",
    dept: "kurucu",
    axis: "merkez",
    title: "Kurucu Ortak / CEO — Ürün & Büyüme",
    type: "core",
    wave: 1,
    pri: "kritik",
    status: "dolu",
    owner: "Burak Akçakanat",
    reports: "—",
    hours: "Tam zamanlı",
    pay: "Kurucu",
    esop: "Kurucu payı (50/50)",
    kpi: ["Aylık aktif şehir sayısı", "İlk gelir sinyali ve dönüşüm oranı"],
    cadence: "Haftalık kanal sağlık oturumu · aylık yol haritası revizyonu",
    tools: "Lovable, Notion/Drive, LinkedIn, yatırımcı CRM",
    trigger: "Mevcut",
    exit: "—",
    jd: "CorteQS'in vizyonunu, ürün yönünü, konumlandırmasını ve gelir modelini taşır. Yatırımcı ve mentor ilişkilerini yönetir, şehir lansman stratejisini belirler, haftalık kanal sağlık oturumlarıyla tüm bölüm başlarının hizalanmasını sağlar. İlk 6 ayın önceliği ürün-müşteri uyumunu doğrulamak ve ilk gelir sinyalini almaktır.",
    ad: null,
  },
  {
    id: "ld-cto",
    dept: "kurucu",
    axis: "merkez",
    title: "Kurucu Ortak / CTO — Teknoloji & Mimari",
    type: "core",
    wave: 1,
    pri: "kritik",
    status: "dolu",
    owner: "UBT",
    reports: "—",
    hours: "Tam zamanlı",
    pay: "Kurucu",
    esop: "Kurucu payı (50/50)",
    kpi: ["Sprint teslim oranı", "Lovable üzerinde deployment sıklığı", "Kritik bug çözüm süresi"],
    cadence: "Günlük standup · haftalık sprint planlama · aylık teknik yol haritası",
    tools: "Lovable, GitHub, Supabase, Vercel, Figma",
    trigger: "Mevcut",
    exit: "—",
    jd: "CorteQS'in teknoloji mimarisini, Lovable tabanlı ürün geliştirme hattını ve DevOps süreçlerini yönetir. Fullstack, frontend, backend, mobil, QA, AI, veri ve DevOps rollerinin teknik yönünü belirler. Sprint planlamasını kendi yapar, kod incelemelerini yürütür ve güvenlik açıklarına karşı son karar merciidir.",
    ad: null,
  },
  {
    id: "ld-cmo",
    dept: "kurucu",
    axis: "merkez",
    title: "Head of Marketing & Growth",
    type: "core",
    wave: 1,
    pri: "kritik",
    status: "acik",
    owner: "",
    reports: "CEO",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%2–5 vesting 4y/1y cliff",
    kpi: ["Haftalık içerik üretim adedi", "Takipçi büyüme hızı", "Şehir lansman conversion oranı"],
    cadence: "Günlük story dizilimi · haftalık pazarlama standup'ı · aylık büyüme raporu",
    tools: "Instagram Creator Studio, Notion, Canva, Meta Business Suite, Google Analytics",
    trigger: "İlk 3 şehir aktif olduğunda",
    exit: "Büyüme kanalları oturduktan sonra VP seviyesine evrilir",
    jd: "Pazarlamanın 27 kişilik ekibini üç eksende (ürün, işlev, coğrafya) koordine eder. Instagram yayın stratejisini belirler, şehir lansman takvimini yönetir, performans reklamlarının bütçe ve hedeflerini koyar. CEO ile birlikte büyüme modelini şekillendirir ve haftalık pazarlama standup'ıyla tüm ekip hizalanmasını sağlar.",
    ad: {
      sum: "CorteQS'in 27 kişilik pazarlama ekibini üç eksende yönetecek, Instagram yayın stratejisini belirleyecek ve şehir lansman takvimini koordine edecek bir Head of Marketing arıyoruz. Erken aşama start-up belirsizliğinde, sonuç odaklı ve elini taşın altına sokmaya hazır bir lider arıyoruz.",
      does: [
        "27 kişilik pazarlama ekibini ürün, işlev ve coğrafya eksenlerinde koordine etmek",
        "Instagram yayın stratejisini belirlemek ve haftalık story dizilimini onaylamak",
        "Şehir lansman takvimini CEO ile birlikte yönetmek",
        "Performans reklamlarının bütçe, hedef ve dönüşüm oranlarını takip etmek",
        "Haftalık pazarlama standup'ını yürütmek ve aylık büyüme raporunu yazmak",
      ],
      profile: [
        "En az 5 yıl performans pazarlaması veya büyüme liderliği deneyimi",
        "Instagram ve sosyal medya yayın stratejisi konusunda kanıtlanmış sonuç",
        "Erken aşama start-up ortamında çalışmış olmak",
        "Veri odaklı karar alma ve hızlı prototipleme alışkanlığı",
        "Türkçe ana dil seviyesinde, İngilizce profesyonel düzeyde",
      ],
      test: "Görev testi: CorteQS'in mevcut Instagram hesabını 30 dakika incele. Bir hafta sonrasının story dizilimini (7 gün × 3-5 kart/gün) tema günlerine göre planla ve hangi kartın neden ikinci sırada olması gerektiğini iki cümleyle açıkla.",
    },
  },
  {
    id: "ld-partner",
    dept: "kurucu",
    axis: "merkez",
    title: "Kurucu Ortak — İş Geliştirme & Ortaklıklar",
    type: "core",
    wave: 2,
    pri: "yuksek",
    status: "acik",
    owner: "",
    reports: "CEO",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%1–3 vesting 4y/1y cliff",
    kpi: ["Aylık marka ortaklığı adedi", "Sponsorluk gelir dönüşümü", "Stratejik ortaklık pipeline değeri"],
    cadence: "Haftalık partner pipeline review · aylık stratejik gözden geçirme",
    tools: "LinkedIn, Notion CRM, Google Workspace, DocuSign",
    trigger: "İlk gelir sinyali doğrulandığında",
    exit: "Ortaklık hattı oturduktan sonra Head of Partnerships'e evrilir",
    jd: "CorteQS'in marka ortaklıklarını, sponsorluk anlaşmalarını ve stratejik iş birliklerini yönetir. B2B satış hattıyla birlikte çalışarak marka pipeline'ını doldurur, pilot anlaşmaları yapılandırır ve uzun vadeli ortaklık modellerini tasarlar. CEO ile Reserved Matters çerçevesinde hareket eder.",
    ad: {
      sum: "CorteQS'in marka ortaklıklarını ve sponsorluk anlaşmalarını yapılandıracak, erken dönem start-up belirsizliğinde pipeline oluşturacak bir iş geliştirme kurucu ortağı arıyoruz. İlk 6 ayda en az 3 pilot ortaklık hedefleniyor.",
      does: [
        "Marka ortaklığı pipeline'ını oluşturmak ve haftalık review ile takip etmek",
        "Sponsorluk anlaşmalarını yapılandırmak ve pilot dönemlerini yönetmek",
        "Stratejik iş birlikleri için teklif dosyalarını hazırlamak",
        "B2B satış hattıyla koordinasyonu sağlamak",
        "Aylık stratejik gözden geçirmede ortaklık performansını raporlamak",
      ],
      profile: [
        "En az 4 yıl iş geliştirme veya marka ortaklıkları deneyimi",
        "Start-up veya ajans ortamında pipeline yönetimi yapmış olmak",
        "Teklif dosyası hazırlama ve müzakere konusunda kendine güvenen",
        "Veri odaklı yaklaşım ve sonuç takip alışkanlığı",
        "Türkçe ana dil seviyesinde, İngilizce profesyonel düzeyde",
      ],
      test: "Görev testi: CorteQS'in hedef kitlesine uygun 3 marka belirle. Her biri için bir cümlelik ortaklık önerisi yaz ve neden bu markanın CorteQS ile çalışmak isteyeceğini iki cümleyle açıkla.",
    },
  },
  {
    id: "ld-advisor",
    dept: "kurucu",
    axis: "merkez",
    title: "Dış Danışman — Strateji & Yatırım",
    type: "danisman",
    wave: 1,
    pri: "orta",
    status: "acik",
    owner: "",
    reports: "CEO",
    hours: "Aylık 8–12 saat",
    pay: "Danışman ücreti + advisory ESOP",
    esop: "%0.5–1 advisory vesting 2y",
    kpi: ["Aylık strateji oturumu adedi", "Yatırımcı referral adedi", "Karar hızı iyileşmesi"],
    cadence: "Aylık strateji oturumu · çeyreklik advisory review",
    tools: "Zoom, Notion, Google Workspace",
    trigger: "İlk yatırımcı görüşmesi planlandığında",
    exit: "Tohum tur kapandıktan sonra gözden geçirilir",
    jd: "CorteQS'in stratejik yönüne dışarıdan perspektif taşır. Yatırımcı ilişkilerinde mentorluk yapar, pitch deck ve finansal model geri bildirimi verir, karar hızını artıracak çerçeveler sunar. Haftalık kurucu oturumlarına katılmaz; aylık strateji oturumları ve ad hoc çağrılarla çalışır.",
    ad: {
      sum: "CorteQS'in stratejik kararlarına dış perspektif taşıyacak, yatırımcı ilişkilerinde mentorluk yapacak ve erken aşama start-up dinamiklerinde rehberlik edecek bir dış danışman arıyoruz. Aylık 8-12 saatlik bir taahhüt bekleniyor.",
      does: [
        "Aylık strateji oturumlarıyla kurucu ortaklara çerçeve sağlamak",
        "Pitch deck ve finansal model geri bildirimi vermek",
        "Yatırımcı ağından referral yapmak",
        "Karar hızını artıracak önceliklendirme çerçeveleri sunmak",
        "Çeyreklik advisory review'de ilerlemeyi değerlendirmek",
      ],
      profile: [
        "En az bir erken aşama start-up'ı Series A'ya taşımış olmak",
        "Türkiye ve MENA pazarında network sahibi olmak",
        "Stratejik önceliklendirme ve karar çerçevelerinde deneyimli",
        "Haftada 2-3 saat ayırabilme taahhüdü",
      ],
      test: "Görev testi: CorteQS'in mevcut konumlandırmasını ve hedef kitlesini 20 dakika incele. İlk 3 ay için en kritik 3 stratejik soruyu yaz ve her biri için neden bu sorunun önemli olduğunu bir cümleyle açıkla.",
    },
  },
];
