import type { KadroRole } from "../kadro-types";

export const OPERASYON_ROLES: KadroRole[] = [
  {
    id: "op-partner",
    dept: "operasyon",
    axis: "merkez",
    title: "Partner İlişkileri Yöneticisi",
    type: "core",
    wave: 2,
    pri: "yuksek",
    status: "acik",
    owner: "",
    reports: "CEO",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%0.5–1 vesting 4y/1y cliff",
    kpi: ["Aktif partner sayısı", "Partner memnuniyet puanı", "Partner kaynak kullanım oranı"],
    cadence: "Haftalık partner check-in · aylık partner raporu",
    tools: "Notion CRM, Google Workspace, Slack, Zoom",
    trigger: "İlk 3 partner anlaşması imzalandığında",
    exit: "Partner ağı oturduktan sonra iş geliştirme ekibine evrilir",
    jd: "CorteQS'in marka ve kurum partnerleriyle olan ilişkilerini yönetir. Partner onboarding sürecini yürütür, haftalık check-in'leri koordine eder, partner kaynaklarının etkin kullanımını takip eder ve aylık partner raporunu hazırlar.",
    ad: {
      sum: "CorteQS'in marka ve kurum partnerleriyle olan ilişkilerini yönetecek, partner onboarding sürecini yürütecek bir partner ilişkileri yöneticisi arıyoruz. İlişki yönetimi ve koordinasyon konusunda deneyimli bir profil bekleniyor.",
      does: [
        "Partner onboarding sürecini yürütmek",
        "Haftalık partner check-in'lerini koordine etmek",
        "Partner kaynaklarının etkin kullanımını takip etmek",
        "Aylık partner raporunu hazırlamak",
        "Partner geri bildirimlerini iç ekibe iletmek",
      ],
      profile: [
        "En az 3 yıl partner veya hesap yönetimi deneyimi",
        "İlişki yönetimi ve koordinasyon becerisi yüksek",
        "Notion CRM ve Google Workspace'de yetkin",
        "Erken aşama start-up ortamında çalışabilme",
      ],
      test: "Görev testi: Yeni bir partner için 4 haftalık onboarding planı oluştur. Her hafta için 3 aksiyon ve 1 başarı ölçütü belirt.",
    },
  },
  {
    id: "op-platform",
    dept: "operasyon",
    axis: "merkez",
    title: "Platform Operasyon Sorumlusu",
    type: "core",
    wave: 1,
    pri: "kritik",
    status: "acik",
    owner: "",
    reports: "CTO",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%0.5–1 vesting 4y/1y cliff",
    kpi: ["Platform uptime oranı", "Kullanıcı rapor yanıt süresi", "Bug çözüm süresi"],
    cadence: "Günlük platform kontrolü · haftalık operasyon raporu",
    tools: "Supabase dashboard, Vercel analytics, Notion, Slack",
    trigger: "MVP yayına alındığında",
    exit: "Platform stabilitesi sağlandıktan sonra QA ekibine devredilir",
    jd: "CorteQS'in platform operasyonunun günlük sağlığını takip eder. Supabase dashboard ve Vercel analytics üzerinden sistem performansını izler, kullanıcı raporlarını yanıtlar, kritik bug'ları tespit eder ve teknik ekibe iletir.",
    ad: {
      sum: "CorteQS'in platform operasyonunun günlük sağlığını takip edecek, kullanıcı raporlarını yanıtlayacak bir platform operasyon sorumlusu arıyoruz. Teknik takip becerisi ve kullanıcı odaklı bir profil bekleniyor.",
      does: [
        "Günlük platform sağlığını kontrol etmek",
        "Kullanıcı raporlarını yanıtlamak ve sınıflandırmak",
        "Kritik bug'ları tespit etmek ve teknik ekibe iletmek",
        "Supabase dashboard ve Vercel analytics'i izlemek",
        "Haftalık operasyon raporunu hazırlamak",
      ],
      profile: [
        "Teknik destek veya operasyon deneyimi",
        "Supabase veya benzeri dashboard'larda yetkin",
        "Kullanıcı odaklı yaklaşım ve sabır",
        "Problem tespit ve sınıflandırma alışkanlığı",
      ],
      test: "Görev testi: 5 örnek kullanıcı raporu al (bug, özellik isteği, erişim sorunu, performans, genel soru). Her birini öncelik ve kategoriye göre sınıflandır.",
    },
  },
  {
    id: "op-trust",
    dept: "operasyon",
    axis: "merkez",
    title: "Güven & Güvenlik Sorumlusu",
    type: "core",
    wave: 2,
    pri: "yuksek",
    status: "acik",
    owner: "",
    reports: "CTO",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%0.5–1 vesting 4y/1y cliff",
    kpi: ["Güvenlik incident sayısı", "Rapor yanıt süresi", "Kural ihlali tespit oranı"],
    cadence: "Günlük güvenlik taraması · haftalık güvenlik raporu",
    tools: "Supabase RLS, admin panel, Notion, Slack",
    trigger: "Kullanıcı hacmi moderasyon gerektirdiğinde",
    exit: "Güvenlik altyapısı oturduktan sonra otomasyona evrilir",
    jd: "CorteQS'in platform güvenliği ve kullanıcı güvenliğinden sorumludur. RLS politikalarını denetler, güvenlik açıklarını takip eder, kullanıcı ihlallerini inceler ve aksiyon alır. CTO ile birlikte güvenlik stratejisini belirler.",
    ad: {
      sum: "CorteQS'in platform güvenliğini yönetecek, RLS politikalarını denetleyecek ve kullanıcı ihlallerini inceleyecek bir güven sorumlusu arıyoruz. Güvenlik ve moderasyon konusunda dikkatli bir profil bekleniyor.",
      does: [
        "RLS politikalarını denetlemek ve test etmek",
        "Güvenlik açıklarını takip etmek ve raporlamak",
        "Kullanıcı ihlallerini incelemek ve aksiyon almak",
        "Güvenlik stratejisini CTO ile belirlemek",
        "Haftalık güvenlik raporunu hazırlamak",
      ],
      profile: [
        "Güvenlik veya trust & safety deneyimi",
        "Supabase RLS ve veritabanı güvenliği anlayışı",
        "Dikkatli ve titiz çalışma alışkanlığı",
        "Incident response ve karar alma yeteneği",
      ],
      test: "Görev testi: 5 örnek kullanıcı ihlali raporu al. Her biri için aksiyon kararını (uyarı, askı, ban) ve gerekçesini yaz.",
    },
  },
  {
    id: "op-moderasyon",
    dept: "operasyon",
    axis: "merkez",
    title: "İçerik Moderatörü",
    type: "part",
    wave: 1,
    pri: "yuksek",
    status: "acik",
    owner: "",
    reports: "Güven Sorumlusu (op-trust)",
    hours: "Haftalık 20 saat",
    pay: "Aylık sabit ücret",
    esop: "—",
    kpi: ["Günlük moderasyon adedi", "Yanıt süresi", "Hatalı karar oranı"],
    cadence: "Günlük içerik taraması · haftalık moderasyon raporu",
    tools: "Admin panel, Instagram, Notion, Slack",
    trigger: "İçerik hacmi manuel takibi zorlaştırdığında",
    exit: "Moderasyon otomasyonu kurulduktan sonra azalır",
    jd: "CorteQS'in platform içeriğini günlük olarak moderasyon yapar. Kullanıcı raporlarını inceler, topluluk kurallarını uygular, hatalı içeriği kaldırır ve moderasyon kararlarını belgeler. Part-time çalışır.",
    ad: {
      sum: "CorteQS'in platform içeriğini günlük olarak moderasyon yapacak, kullanıcı raporlarını inceleyecek bir içerik moderatörü arıyoruz. Dikkatli, adil ve tutarlı bir profil bekleniyor. Part-time, haftalık 20 saat.",
      does: [
        "Günlük içerik taraması yapmak",
        "Kullanıcı raporlarını incelemek",
        "Topluluk kurallarını uygulamak",
        "Hatalı içeriği kaldırmak ve belgelemek",
        "Haftalık moderasyon raporunu hazırlamak",
      ],
      profile: [
        "İçerik moderasyonu veya topluluk yönetimi deneyimi",
        "Dikkatli ve tutarlı karar alma",
        "Türkçe yazılı iletişim becerisi yüksek",
        "Hassas içerikle çalışma olgunluğu",
      ],
      test: "Görev testi: 5 örnek içerik raporu al. Her biri için kararını (kalsın, kaldırılsın, uyarı) ve gerekçesini yaz.",
    },
  },
  {
    id: "op-success",
    dept: "operasyon",
    axis: "merkez",
    title: "Kullanıcı Başarısı Sorumlusu",
    type: "core",
    wave: 2,
    pri: "orta",
    status: "acik",
    owner: "",
    reports: "CEO",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%0.5–1 vesting 4y/1y cliff",
    kpi: ["Kullanıcı aktivasyon oranı", "Destek talebi yanıt süresi", "NPS puanı"],
    cadence: "Günlük destek talepleri · haftalık kullanıcı başarısı raporu",
    tools: "Intercom/Crisp, Notion, Google Forms, Slack",
    trigger: "İlk 500 aktif kullanıcıya ulaşıldığında",
    exit: "Kullanıcı başarısı altyapısı oturduktan sonra otomasyona evrilir",
    jd: "CorteQS'in kullanıcılarının platformdan maksimum değer almasını sağlar. Onboarding süreçlerini iyileştirir, destek taleplerini yanıtlar, kullanıcı geri bildirimlerini toplar ve ürün ekibine iletir. Kullanıcı memnuniyetini artırma odaklı çalışır.",
    ad: {
      sum: "CorteQS'in kullanıcılarının platformdan maksimum değer almasını sağlayacak, onboarding süreçlerini iyileştirecek bir kullanıcı başarısı sorumlusu arıyoruz. Kullanıcı odaklı ve empatik bir profil bekleniyor.",
      does: [
        "Onboarding süreçlerini iyileştirmek",
        "Destek taleplerini zamanında yanıtlamak",
        "Kullanıcı geri bildirimlerini toplamak ve analiz etmek",
        "Geri bildirimleri ürün ekibine iletmek",
        "Haftalık kullanıcı başarısı raporunu hazırlamak",
      ],
      profile: [
        "Kullanıcı başarısı veya müşteri deneyimi deneyimi",
        "Empatik iletişim ve problem çözme",
        "Onboarding ve eğitim materyali oluşturma deneyimi",
        "Veri odaklı yaklaşım alışkanlığı",
      ],
      test: "Görev testi: Yeni bir kullanıcı için 5 adımlı onboarding akışı tasarla. Her adım için beklenen süreyi ve başarı ölçütünü belirt.",
    },
  },
];
