import type { KadroRole } from "../kadro-types";

export const PAZARLAMA_ISLEV_ROLES: KadroRole[] = [
  {
    id: "pz-ig",
    dept: "pazarlama",
    axis: "islev",
    title: "Instagram Kanal Yöneticisi",
    type: "core",
    wave: 1,
    pri: "kritik",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%0.5–1.5 vesting 4y/1y cliff",
    kpi: ["Günlük story yayın adedi", "Takipçi büyüme hızı", "Etkileşim oranı"],
    cadence: "Günlük story + haftalık 3 feed post · aylık kanal raporu",
    tools: "Instagram Creator Studio, Canva, Later/Planoly, Google Analytics",
    trigger: "MVP yayında ve günlük yayın başladığında",
    exit: "Kanal oturduktan sonra içerik müdürü rolüne evrilir",
    jd: "CorteQS'in Instagram kanalının günlük operasyonunu yönetir. Story dizilimi, feed post planlaması, yorum moderasyonu ve DM yanıtlarını yürütür. Kanal sağlığını haftalık raporlar, büyüme stratejisini Head of Marketing ile birlikte belirler.",
    ad: {
      sum: "CorteQS'in Instagram kanalının günlük operasyonunu yönetecek, story ve feed planlamasını yapacak bir kanal yöneticisi arıyoruz. Instagram'da günlük yayın disiplini olan, topluluk etkileşimine önem veren bir profil bekleniyor.",
      does: [
        "Günlük story dizilimini planlamak ve yayınlamak",
        "Haftalık 3 feed post planlamak ve yayınlamak",
        "Yorum moderasyonu ve DM yanıtlarını yürütmek",
        "Kanal sağlığını izlemek ve haftalık rapor sunmak",
        "Büyüme stratejisini Head of Marketing ile belirlemek",
      ],
      profile: [
        "Instagram kanal yönetimi deneyimi",
        "Günlük yayın disiplini ve story tasarımı yetkinliği",
        "Topluluk etkileşimi ve moderasyon alışkanlığı",
        "Canva ve planlama araçlarında yetkin",
      ],
      test: "Görev testi: CorteQS'in Instagram hesabını incele. Bir haftalık içerik planı oluştur (7 story + 3 feed post). Her post için başlık, görsel fikri ve açıklama metnini yaz.",
    },
  },
  {
    id: "pz-li",
    dept: "pazarlama",
    axis: "islev",
    title: "LinkedIn & Profesyonel Kanal Yöneticisi",
    type: "part",
    wave: 2,
    pri: "orta",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Haftalık 15 saat",
    pay: "Aylık sabit ücret",
    esop: "%0.25–0.5 vesting 4y/1y cliff",
    kpi: ["Haftalık LinkedIn post adedi", "Profesyonel network büyümesi", "B2B lead adedi"],
    cadence: "Haftalık 3 LinkedIn post · aylık profesyonel içerik özeti",
    tools: "LinkedIn, Canva, Notion, Google Analytics",
    trigger: "B2B ortaklık pipeline'ı aktif olduğunda",
    exit: "LinkedIn kanalı oturduktan sonra içerik ekibine devredilir",
    jd: "CorteQS'in LinkedIn ve profesyonel kanallarını yönetir. Kurucu ortakların kişisel markalarını destekler, B2B odaklı içerik üretir ve profesyonel network büyümesini takip eder. Part-time çalışır, haftalık 15 saat.",
    ad: {
      sum: "CorteQS'in LinkedIn ve profesyonel kanallarını yönetecek, B2B odaklı içerik üretecek ve kurucu ortakların kişisel markalarını destekleyecek bir kanal yöneticisi arıyoruz. Part-time, haftalık 15 saat.",
      does: [
        "Haftalık 3 LinkedIn post planlamak ve yayınlamak",
        "Kurucu ortakların kişisel marka içeriğini desteklemek",
        "B2B odaklı içerik üretmek",
        "Profesyonel network büyümesini takip etmek",
        "Aylık profesyonel içerik özetini yazmak",
      ],
      profile: [
        "LinkedIn içerik üretimi ve kanal yönetimi deneyimi",
        "B2B pazarlama veya profesyonel iletişim deneyimi",
        "Yazılı iletişim becerisi yüksek",
        "Notion ve Canva'da yetkin",
      ],
      test: "Görev testi: CorteQS için 3 LinkedIn post taslağı yaz. Her biri farklı bir açıdan (ürün vizyonu, ekip hikayesi, sektör içgörüsü) olmalı.",
    },
  },
  {
    id: "pz-yt",
    dept: "pazarlama",
    axis: "islev",
    title: "YouTube & Long-form Video Editörü",
    type: "proje",
    wave: 2,
    pri: "orta",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Proje bazlı — aylık 30–50 saat",
    pay: "Proje başına ücret",
    esop: "—",
    kpi: ["Aylık video yayın adedi", "Ortalama izlenme süresi", "Abone büyüme hızı"],
    cadence: "Haftalık 1 uzun video · aylık YouTube raporu",
    tools: "DaVinci Resolve/Premiere, YouTube Studio, Canva, Notion",
    trigger: "YouTube kanalı açıldığında",
    exit: "YouTube formatı oturduktan sonra tam zamanlıya dönüşüm değerlendirilir",
    jd: "CorteQS'in YouTube ve uzun format video içeriğini yönetir. Haftalık 1 uzun video üretir, thumbnail tasarlar, SEO optimizasyonu yapar ve YouTube Studio metriklerini takip eder. Proje bazlı çalışır.",
    ad: {
      sum: "CorteQS'in YouTube kanalını yönetecek, uzun format video içerikleri üretecek bir video editörü arıyoruz. Video prodüksiyonu ve YouTube SEO konusunda deneyimli bir profil bekleniyor. Proje bazlı, aylık 30-50 saat.",
      does: [
        "Haftalık 1 uzun video üretmek (çekim, kurgu, yayın)",
        "Thumbnail tasarlamak ve SEO optimizasyonu yapmak",
        "YouTube Studio metriklerini takip etmek",
        "Video açıklama ve zaman damgalarını hazırlamak",
        "Aylık YouTube raporunu yazmak",
      ],
      profile: [
        "Video prodüksiyonu ve kurgu deneyimi",
        "YouTube SEO ve kanal yönetimi bilgisi",
        "DaVinci Resolve veya Premiere'de ileri düzey",
        "Hikaye anlatımı ve görsel kompozisyon yeteneği",
      ],
      test: "Görev testi: CorteQS için 5 dakikalık bir YouTube video planı oluştur. Konu, bölüm akışı, thumbnail fikri ve SEO başlığını belirt.",
    },
  },
  {
    id: "pz-short",
    dept: "pazarlama",
    axis: "islev",
    title: "Short-form Video Üreticisi",
    type: "core",
    wave: 1,
    pri: "yuksek",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%0.5–1 vesting 4y/1y cliff",
    kpi: ["Haftalık short video adedi", "Reels izlenme oranı", "Viral video adedi"],
    cadence: "Günlük 1-2 short video · haftalık performans review",
    tools: "CapCut, Canva, Instagram Reels, TikTok, Notion",
    trigger: "Short-form video stratejisi belirlendiğinde",
    exit: "Short-form hattı oturduktan sonra içerik müdürü rolüne evrilir",
    jd: "CorteQS'in kısa format video içeriğini üretir. Instagram Reels, TikTok ve YouTube Shorts için günlük 1-2 video hazırlar. Trend takibi yapar, viral potansiyeli yüksek formatları dener ve haftalık performans review sunar.",
    ad: {
      sum: "CorteQS'in kısa format video içeriğini üretecek, Instagram Reels ve TikTok için günlük video hazırlayacak bir short-form video üreticisi arıyoruz. Trend takibi yapan, hızlı üreten bir profil bekleniyor.",
      does: [
        "Günlük 1-2 short video üretmek (Reels, TikTok, Shorts)",
        "Trend takibi yapmak ve viral formatları denemek",
        "Video kurgusunu CapCut veya benzeri araçlarla yapmak",
        "Haftalık performans review sunmak",
        "Diğer içerik üreticileriyle koordineli çalışmak",
      ],
      profile: [
        "Short-form video prodüksiyonu deneyimi",
        "Trend takibi ve hızlı üretim alışkanlığı",
        "CapCut, Canva veya benzeri araçlarda yetkin",
        "Instagram ve TikTok algoritmalarına aşina",
      ],
      test: "Görev testi: CorteQS için 3 short video fikri üret. Her biri için hook (ilk 3 saniye), gövde ve CTA'yı yaz.",
    },
  },
  {
    id: "pz-creator",
    dept: "pazarlama",
    axis: "islev",
    title: "Creator İlişkileri Yöneticisi",
    type: "core",
    wave: 2,
    pri: "yuksek",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%0.5–1 vesting 4y/1y cliff",
    kpi: ["Aylık creator işbirliği adedi", "Creator içerik performansı", "Creator elde tutma oranı"],
    cadence: "Haftalık creator check-in · aylık creator raporu",
    tools: "Instagram, TikTok, Notion CRM, Google Workspace",
    trigger: "İlk creator işbirliği pilotu başlatıldığında",
    exit: "Creator programı oturduktan sonra ortaklık yöneticisine evrilir",
    jd: "CorteQS'in creator işbirliği programını yönetir. Uygun creator'ları belirler, işbirliği koşullarını görüşür, içerik brief'lerini hazırlar ve performans takibini yapar. Creator ilişkilerini uzun vadeli inşa eder.",
    ad: {
      sum: "CorteQS'in creator işbirliği programını yönetecek, creator ilişkilerini inşa edecek ve içerik brief'lerini hazırlayacak bir creator ilişkileri yöneticisi arıyoruz. Influencer marketing ve ilişki yönetimi konusunda deneyimli bir profil bekleniyor.",
      does: [
        "Uygun creator'ları belirlemek ve outreach yapmak",
        "İşbirliği koşullarını görüşmek ve anlaşmaları yönetmek",
        "İçerik brief'lerini hazırlamak ve creator'lara iletmek",
        "Creator içerik performansını takip etmek",
        "Aylık creator raporunu yazmak",
      ],
      profile: [
        "Influencer marketing veya creator ilişkileri deneyimi",
        "İletişim ve müzakere becerisi yüksek",
        "Instagram ve TikTok creator ekosistemine aşina",
        "Notion CRM ve Google Workspace'de yetkin",
      ],
      test: "Görev testi: CorteQS hedef kitlesine uygun 5 creator belirle. Her biri için bir cümlelik işbirliği önerisi ve brief özeti yaz.",
    },
  },
  {
    id: "pz-tasarim",
    dept: "pazarlama",
    axis: "islev",
    title: "Görsel Tasarım & Brand Guardian",
    type: "core",
    wave: 1,
    pri: "yuksek",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%0.5–1.5 vesting 4y/1y cliff",
    kpi: ["Tasarım teslim süresi", "Marka tutarlılık puanı", "İçerik üretici memnuniyeti"],
    cadence: "Günlük tasarım talepleri · haftalık brand review",
    tools: "Figma, Canva Pro, Adobe Creative Suite, Notion",
    trigger: "Marka kimliği belirlendiğinde",
    exit: "Tasarım sistemi oturduktan sonra art director rolüne evrilir",
    jd: "CorteQS'in görsel kimliğini korur ve geliştirir. Tüm pazarlama materyallerinin marka tutarlılığını sağlar, şablonlar oluşturur ve içerik üreticilerine tasarım desteği verir. Figma'da tasarım sistemini yönetir.",
    ad: {
      sum: "CorteQS'in görsel kimliğini koruyacak, marka tutarlılığını sağlayacak ve içerik üreticilerine tasarım desteği verecek bir görsel tasarımcı arıyoruz. Marka kimliği ve tasarım sistemi konusunda deneyimli bir profil bekleniyor.",
      does: [
        "Marka görsel kimliğini korumak ve geliştirmek",
        "Tüm pazarlama materyallerinin tasarım tutarlılığını sağlamak",
        "Figma'da şablonlar ve tasarım bileşenleri oluşturmak",
        "İçerik üreticilerine günlük tasarım desteği vermek",
        "Haftalık brand review'de tutarlılık raporunu sunmak",
      ],
      profile: [
        "Görsel tasarım ve marka kimliği deneyimi",
        "Figma'da ileri düzey, Adobe Creative Suite'te yetkin",
        "Marka tutarlılığı ve tasarım sistemi anlayışı",
        "Hızlı teslim ve geri bildirim döngüsü alışkanlığı",
      ],
      test: "Görev testi: CorteQS için bir Instagram story şablonu tasarla. 3 varyasyon üret (bilgi duyurusu, alıntı, etkinlik). Marka renk paletini ve tipografi seçimini gerekçelendir.",
    },
  },
  {
    id: "pz-seo",
    dept: "pazarlama",
    axis: "islev",
    title: "SEO & Organik Büyüme Uzmanı",
    type: "part",
    wave: 2,
    pri: "orta",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Haftalık 15 saat",
    pay: "Aylık sabit ücret",
    esop: "%0.25–0.5 vesting 4y/1y cliff",
    kpi: ["Organik trafik büyüme hızı", "Anahtar kelime sıralaması", "Backlink adedi"],
    cadence: "Haftalık SEO raporu · aylık içerik planı",
    tools: "Google Search Console, Ahrefs/Ubersuggest, Google Analytics, Notion",
    trigger: "Web sitesi organic trafiği ölçülmeye başlandığında",
    exit: "SEO stratejisi oturduktan sonra içerik ekibine devredilir",
    jd: "CorteQS'in organik arama stratejisini yönetir. Anahtar kelime araştırması yapar, teknik SEO denetimleri yürütür, içerik planını SEO hedefleriyle hizalar ve backlink stratejisini uygular. Part-time çalışır.",
    ad: {
      sum: "CorteQS'in organik arama stratejisini yönetecek, anahtar kelime araştırması yapacak ve teknik SEO denetimleri yürütecek bir SEO uzmanı arıyoruz. Part-time, haftalık 15 saat.",
      does: [
        "Anahtar kelime araştırması yapmak ve önceliklendirmek",
        "Teknik SEO denetimleri yürütmek",
        "İçerik planını SEO hedefleriyle hizalamak",
        "Backlink stratejisini uygulamak",
        "Haftalık SEO raporu sunmak",
      ],
      profile: [
        "En az 2 yıl SEO deneyimi",
        "Google Search Console ve SEO araçlarında yetkin",
        "Teknik SEO ve içerik SEO'suna hakim",
        "Veri odaklı yaklaşım alışkanlığı",
      ],
      test: "Görev testi: CorteQS için 10 anahtar kelime belirle. Her biri için arama hacmi tahmini, zorluk seviyesi ve hedef sayfa önerisini yaz.",
    },
  },
  {
    id: "pz-perf",
    dept: "pazarlama",
    axis: "islev",
    title: "Performans Analisti — Büyüme Metrikleri",
    type: "part",
    wave: 2,
    pri: "yuksek",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Haftalık 20 saat",
    pay: "Aylık sabit ücret",
    esop: "%0.25–0.5 vesting 4y/1y cliff",
    kpi: ["Raporlama doğruluğu", "İçgörü başına aksiyon adedi", "Dashboard güncelliği"],
    cadence: "Günlük metrik kontrolü · haftalık büyüme raporu · aylık derin analiz",
    tools: "Google Analytics, Meta Business Suite, Google Sheets, Notion",
    trigger: "İlk büyüme metrikleri düzenli ölçülmeye başlandığında",
    exit: "Büyüme altyapısı oturduktan sonra tam zamanlıya dönüşüm değerlendirilir",
    jd: "CorteQS'in büyüme metriklerini takip eder, analiz eder ve içgörüler üretir. Google Analytics, Meta Business Suite ve diğer kanallardan veri toplar, haftalık büyüme raporu hazırlar ve aylık derin analiz sunar. Part-time çalışır.",
    ad: {
      sum: "CorteQS'in büyüme metriklerini takip edecek, analiz edecek ve aksiyon alınabilir içgörüler üretecek bir performans analisti arıyoruz. Veri analizi ve raporlama konusunda güçlü bir profil bekleniyor. Part-time, haftalık 20 saat.",
      does: [
        "Çoklu kanaldan büyüme metriklerini toplamak",
        "Haftalık büyüme raporu hazırlamak",
        "Aylık derin analiz ve içgörü raporu sunmak",
        "Dashboard'ları güncel tutmak",
        "Aksiyon önerilerini pazarlama ekibine iletmek",
      ],
      profile: [
        "Veri analizi ve raporlama deneyimi",
        "Google Analytics ve Meta Business Suite'te ileri düzey",
        "Google Sheets'te ileri düzey (pivot, formül, görselleştirme)",
        "İçgörü üretme ve aksiyon önerme alışkanlığı",
      ],
      test: "Görev testi: 5 günlük örnek Instagram ve web trafiği verisi al. Haftalık büyüme raporu taslağı oluştur: 3 ana metrik, 2 içgörü, 1 aksiyon önerisi.",
    },
  },
  {
    id: "pz-crm",
    dept: "pazarlama",
    axis: "islev",
    title: "CRM & Otomasyon Uzmanı",
    type: "proje",
    wave: 3,
    pri: "orta",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Proje bazlı — aylık 30–40 saat",
    pay: "Proje başına ücret",
    esop: "—",
    kpi: ["E-posta açılma oranı", "Otomasyon akış adedi", "Kullanıcı yaşam döngüsü dönüşümü"],
    cadence: "Haftalık otomasyon bakımı · aylık CRM raporu",
    tools: "Mailchimp/Loops, Zapier/Make, Google Sheets, Notion",
    trigger: "İlk 500 aboneye ulaşıldığında",
    exit: "CRM altyapısı oturduktan sonra operasyon ekibine devredilir",
    jd: "CorteQS'in CRM altyapısını kurar ve otomasyon akışlarını yönetir. E-posta pazarlaması, kullanıcı yaşam döngüsü otomasyonu ve segmentasyon stratejisini tasarlar. Proje bazlı çalışır.",
    ad: {
      sum: "CorteQS'in CRM altyapısını kuracak, e-posta otomasyon akışlarını yönetecek ve segmentasyon stratejisini tasarlayacak bir CRM uzmanı arıyoruz. Proje bazlı, aylık 30-40 saat.",
      does: [
        "CRM altyapısını kurmak ve yapılandırmak",
        "E-posta otomasyon akışlarını tasarlamak",
        "Segmentasyon stratejisini oluşturmak",
        "Haftalık otomasyon bakımı yapmak",
        "Aylık CRM raporunu sunmak",
      ],
      profile: [
        "CRM ve e-posta pazarlaması deneyimi",
        "Mailchimp, Loops veya benzeri araçlarda yetkin",
        "Zapier/Make ile otomasyon kurma deneyimi",
        "Segmentasyon ve kullanıcı yaşam döngüsü anlayışı",
      ],
      test: "Görev testi: Yeni abone için 5 adımlı bir karşılama e-posta akışı tasarla. Her e-posta için konu satırı, gönderim zamanı ve temel içeriği belirt.",
    },
  },
  {
    id: "pz-analitik",
    dept: "pazarlama",
    axis: "islev",
    title: "İçerik Analisti — Veri Odaklı Editörlük",
    type: "part",
    wave: 2,
    pri: "orta",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Haftalık 12 saat",
    pay: "Aylık sabit ücret",
    esop: "—",
    kpi: ["İçgörü başına içerik iyileştirme adedi", "Veri destekli karar oranı", "Raporlama düzenliliği"],
    cadence: "Haftalık içerik performansı raporu · aylık derin analiz",
    tools: "Instagram Insights, Google Analytics, Google Sheets, Notion",
    trigger: "İçerik üretimi düzenli hale geldiğinde",
    exit: "Analitik altyapısı oturduktan sonra performans analistine devredilir",
    jd: "CorteQS'in içerik performansını veri odaklı analiz eder. Hangi içerik tipinin hangi kitlede çalıştığını belirler, içerik ekibine veri destekli öneriler sunar ve haftalık performans raporu hazırlar. Part-time çalışır.",
    ad: {
      sum: "CorteQS'in içerik performansını veri odaklı analiz edecek, içerik ekibine içgörü ve öneri sunacak bir içerik analisti arıyoruz. Veri analizi ve içerik stratejisi kesişiminde çalışan bir profil bekleniyor. Part-time, haftalık 12 saat.",
      does: [
        "İçerik performans verilerini toplamak ve analiz etmek",
        "Haftalık içerik performansı raporu hazırlamak",
        "İçerik ekibine veri destekli öneriler sunmak",
        "Aylık derin içerik analizi yapmak",
        "İçerik tipleri arası karşılaştırma framework'ü oluşturmak",
      ],
      profile: [
        "Veri analizi deneyimi, tercihen içerik veya pazarlama alanında",
        "Instagram Insights ve Google Analytics'te yetkin",
        "Google Sheets'te ileri düzey",
        "İçgörü üretme ve iletişim alışkanlığı",
      ],
      test: "Görev testi: 10 günlük Instagram içerik verisi al. En iyi ve en kötü performans gösteren 3 içeriği belirle. Her biri için bir cümlelik neden analizi yaz.",
    },
  },
  {
    id: "pz-topluluk",
    dept: "pazarlama",
    axis: "islev",
    title: "Topluluk Yöneticisi",
    type: "core",
    wave: 1,
    pri: "yuksek",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%0.5–1 vesting 4y/1y cliff",
    kpi: ["Aktif topluluk üyesi sayısı", "Günlük etkileşim oranı", "Topluluk büyüme hızı"],
    cadence: "Günlük topluluk moderasyonu · haftalık topluluk özeti · aylık rapor",
    tools: "Instagram DM, Discord/Telegram, Notion, Google Forms",
    trigger: "İlk 200 abone alındığında",
    exit: "Topluluk altyapısı oturduktan sonra operasyon ekibine evrilir",
    jd: "CorteQS'in topluluğunu yönetir ve büyütür. Günlük moderasyon yapar, DM ve yorum yanıtlarını yürütür, topluluk etkinliklerini koordine eder ve haftalık topluluk özeti hazırlar. Topluluğun sesini ürün ekibine taşır.",
    ad: {
      sum: "CorteQS'in topluluğunu yönetecek, günlük moderasyonu yapacak ve topluluğun sesini ürüne taşıyacak bir topluluk yöneticisi arıyoruz. İnsan ilişkileri güçlü, sabırlı ve empatik bir profil bekleniyor.",
      does: [
        "Günlük topluluk moderasyonunu yapmak",
        "DM ve yorum yanıtlarını yürütmek",
        "Topluluk etkinliklerini koordine etmek",
        "Haftalık topluluk özeti hazırlamak",
        "Topluluk geri bildirimlerini ürün ekibine iletmek",
      ],
      profile: [
        "Topluluk yönetimi veya müşteri deneyimi deneyimi",
        "Empatik iletişim ve sabır",
        "Instagram DM ve sosyal medya moderasyonu deneyimi",
        "Türkçe yazılı iletişim becerisi yüksek",
      ],
      test: "Görev testi: 5 örnek topluluk mesajı al (olumlu, olumsuz, soru, öneri, şikayet). Her biri için yanıt taslağı yaz.",
    },
  },
];
