import type { KadroRole } from "../kadro-types";

export const PAZARLAMA_URUN_ROLES: KadroRole[] = [
  {
    id: "pz-f1000",
    dept: "pazarlama",
    axis: "urun",
    title: "F1000 — İlk Bin Abone Küratörü",
    type: "core",
    wave: 1,
    pri: "kritik",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%0.5–1.5 vesting 4y/1y cliff",
    kpi: ["Haftalık F1000 abone sayısı", "İlk 30 gün elde tutma oranı", "Story etkileşim oranı"],
    cadence: "Günlük story dizilimi · haftalık abone raporu",
    tools: "Instagram Creator Studio, Canva, Notion, Google Analytics",
    trigger: "MVP yayında ve ilk 100 abone alındığında",
    exit: "F1000 programı oturduktan sonra büyüme rolüne evrilir",
    jd: "CorteQS'in F1000 erken abone programını yönetir. İlk bin aboneyi kazanmak, onları elde tutmak ve story etkileşimini yüksek tutmak bu rolün temel görevidir. Günlük story dizilimini planlar, abone davranışını takip eder ve haftalık rapor sunar.",
    ad: {
      sum: "CorteQS'in F1000 erken abone programını yönetecek, günlük story dizilimini planlayacak ve abone elde tutma oranını yükseltecek bir küratör arıyoruz. Instagram'da içerik üretme konusunda tutkulu, veri odaklı bir profil bekleniyor.",
      does: [
        "Günlük story dizilimini planlamak ve yayına almak",
        "F1000 abone programının büyüme stratejisini yürütmek",
        "Abone davranışını takip etmek ve haftalık rapor sunmak",
        "İlk 30 gün elde tutma oranını izlemek ve iyileştirmek",
        "İçerik takvimini diğer ürün hatlarıyla koordine etmek",
      ],
      profile: [
        "Instagram içerik üretimi ve topluluk yönetimi deneyimi",
        "Veri odaklı yaklaşım ve raporlama alışkanlığı",
        "Erken aşama start-up ortamında çalışabilme",
        "Türkçe ana dil seviyesinde",
      ],
      test: "Görev testi: CorteQS'in Instagram hesabını incele. Bir haftalık story dizilimi (7 gün × 3-5 kart) oluştur ve her günün temasını bir cümleyle açıkla.",
    },
  },
  {
    id: "pz-radar",
    dept: "pazarlama",
    axis: "urun",
    title: "Radar Story Curator",
    type: "core",
    wave: 1,
    pri: "kritik",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%0.5–1.5 vesting 4y/1y cliff",
    kpi: ["Günlük story yayın adedi", "Story tamamlanma oranı", "Sinyal keşif hızı"],
    cadence: "Günlük Radar story dizilimi · haftalık sinyal raporu",
    tools: "Instagram Creator Studio, radar-news-scan pipeline, Notion, Canva",
    trigger: "Radar haber tarama hattı aktif olduğunda",
    exit: "Radar ürünü oturduktan sonra editör rolüne evrilir",
    jd: "Radar haber tarama hattından gelen sinyalleri Instagram story formatına dönüştürür. Tema gününe uygun 7-9 kartlık story dizilimi hazırlar, güçlü sinyali ikinci sıraya koyar, sticker'ı üçüncü karttan sonra yerleştirir ve tek kapanış CTA'sı ile bitirir. radar-news-scan edge function'ı ile entegre çalışır.",
    ad: {
      sum: "CorteQS'in Radar haber tarama hattından gelen sinyalleri Instagram story formatına dönüştürecek, günlük story dizilimini planlayacak bir Story Curator arıyoruz. Haber küratörlüğü ve Instagram story tasarımı konusunda deneyimli bir profil bekleniyor.",
      does: [
        "Radar pipeline'ından gelen sinyalleri günlük story dizilimine dönüştürmek",
        "Tema gününe uygun 7-9 kartlık story planlamak",
        "Güçlü sinyali ikinci sıraya koymak, sticker'ı üçüncü karttan sonra yerleştirmek",
        "Tek kapanış CTA'sı ile story'yi bitirmek",
        "Haftalık sinyal raporunu yazmak",
      ],
      profile: [
        "Haber küratörlüğü veya editörlük deneyimi",
        "Instagram story tasarımı ve dizilimi konusunda yetkin",
        "Canva veya benzeri tasarım araçlarında ileri düzey",
        "Hızlı karar alma ve günlük yayın disiplini",
      ],
      test: "Görev testi: Bugünün teknoloji haberlerinden 3 sinyal seç. Her biri için bir story kartı tasarla (başlık + 1 cümle özet + CTA). Kartların sıralama gerekçesini yaz.",
    },
  },
  {
    id: "pz-defter",
    dept: "pazarlama",
    axis: "urun",
    title: "Defter — Şehir Günlüğü Editörü",
    type: "core",
    wave: 1,
    pri: "yuksek",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%0.5–1.5 vesting 4y/1y cliff",
    kpi: ["Haftalık Defter yayın adedi", "Okuyucu etkileşim oranı", "Şehir kapsama breadth"],
    cadence: "Haftalık 3 Defter yayını · aylık şehir özeti",
    tools: "Instagram Creator Studio, Canva, Notion, Google Analytics",
    trigger: "İlk şehir lansmanı tamamlandığında",
    exit: "Defter formatı oturduktan sonra içerik müdürü rolüne evrilir",
    jd: "CorteQS'in şehir bazlı günlük içerik ürünü Defter'in editörlüğünü yapar. Her şehrin günlük kültürel nabzını tutar, yerel sinyalleri story formatına dönüştürür ve haftalık 3 yayın çıkarır. Şehir küratörleriyle koordineli çalışır.",
    ad: {
      sum: "CorteQS'in şehir bazlı günlük içerik ürünü Defter'in editörlüğünü yapacak, yerel sinyalleri story formatına dönüştürecek bir şehir günlüğü editörü arıyoruz. Şehir kültürüne hakim, hızlı yazan bir profil bekleniyor.",
      does: [
        "Şehir bazlı günlük içerikleri planlamak ve yayınlamak",
        "Yerel sinyalleri story formatına dönüştürmek",
        "Şehir küratörleriyle koordineli çalışmak",
        "Haftalık 3 Defter yayını çıkarmak",
        "Aylık şehir özetini yazmak",
      ],
      profile: [
        "Editörlük veya içerik üretimi deneyimi",
        "Şehir kültürü ve yerel dinamiklere ilgi",
        "Instagram story formatına hakim",
        "Hızlı yazma ve günlük yayın disiplini",
      ],
      test: "Görev testi: Yaşadığın şehirden 3 yerel sinyal seç. Her biri için bir Defter kartı yaz (başlık + 2 cümle özet). Kartların şehir nabzını nasıl yansıttığını açıkla.",
    },
  },
  {
    id: "pz-sehir",
    dept: "pazarlama",
    axis: "urun",
    title: "Şehir Lansman Koordinatörü",
    type: "core",
    wave: 2,
    pri: "yuksek",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%0.5–1.5 vesting 4y/1y cliff",
    kpi: ["Lansman haftası abone sayısı", "Şehir bazlı elde tutma", "Lansman öncesi hazırlık tamamlanma oranı"],
    cadence: "Lansman öncesi 4 haftalık geri sayım · haftalık check-in",
    tools: "Notion, Instagram Creator Studio, Google Workspace, Canva",
    trigger: "İkinci şehir lansmanı planlandığında",
    exit: "Lansman playbooks oturduktan sonra operasyon rolüne evrilir",
    jd: "CorteQS'in şehir lansmanlarını pazarlama açısından koordine eder. Her lansman için 4 haftalık geri sayım takvimi hazırlar, yerel içerik stratejisini belirler, şehir küratörünü işe alım sürecinde destekler ve lansman haftası operasyonunu yürütür.",
    ad: {
      sum: "CorteQS'in şehir lansmanlarını pazarlama açısından koordine edecek, 4 haftalık geri sayım takvimini yönetecek bir lansman koordinatörü arıyoruz. Proje yönetimi ve şehir bazlı pazarlama konusunda deneyimli bir profil bekleniyor.",
      does: [
        "Her lansman için 4 haftalık geri sayım takvimi hazırlamak",
        "Yerel içerik stratejisini belirlemek ve uygulamak",
        "Şehir küratörü işe alım sürecinde destek vermek",
        "Lansman haftası operasyonunu yürütmek",
        "Lansman sonrası elde tutma raporunu yazmak",
      ],
      profile: [
        "Proje yönetimi veya etkinlik koordinasyonu deneyimi",
        "Şehir bazlı pazarlama veya topluluk oluşturma deneyimi",
        "Notion ve Google Workspace'de ileri düzey",
        "Çoklu zaman çizelgesi yönetimi alışkanlığı",
      ],
      test: "Görev testi: Yeni bir şehir lansmanı için 4 haftalık geri sayım takvimi oluştur. Her hafta için 3 anahtar aksiyon ve 1 başarı ölçütü belirle.",
    },
  },
  {
    id: "pz-motor",
    dept: "pazarlama",
    axis: "urun",
    title: "Motor — Performans Reklam Uzmanı",
    type: "core",
    wave: 2,
    pri: "yuksek",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%0.5–1.5 vesting 4y/1y cliff",
    kpi: ["ROAS oranı", "CAC (müşteri edinme maliyeti)", "Reklam spend verimliliği"],
    cadence: "Günlük reklam performansı izleme · haftalık optimizasyon · aylık bütçe raporu",
    tools: "Meta Business Suite, Google Ads, Google Analytics, Notion",
    trigger: "İlk gelir sinyali doğrulandığında",
    exit: "Performans kanalları oturduktan sonra büyüme lideri rolüne evrilir",
    jd: "CorteQS'in performans reklam kanallarını yönetir. Meta ve Google Ads üzerinde kampanya kurar, optimize eder ve bütçe verimliliğini takip eder. ROAS ve CAC metriklerini haftalık raporlar. Erken aşamada sınırlı bütçeyle maksimum etki yaratması beklenir.",
    ad: {
      sum: "CorteQS'in performans reklam kanallarını yönetecek, sınırlı bütçeyle maksimum etki yaratacak bir performans reklam uzmanı arıyoruz. Meta ve Google Ads konusunda kanıtlanmış sonuçları olan bir profil bekleniyor.",
      does: [
        "Meta ve Google Ads kampanyalarını kurmak ve optimize etmek",
        "ROAS ve CAC metriklerini haftalık raporlamak",
        "Bütçe verimliliğini takip etmek ve aylık bütçe raporu sunmak",
        "A/B test planlarını oluşturmak ve sonuçları analiz etmek",
        "Reklam kreatiflerini içerik ekibiyle koordine etmek",
      ],
      profile: [
        "En az 3 yıl performans pazarlaması deneyimi",
        "Meta Business Suite ve Google Ads'de ileri düzey",
        "Veri analizi ve raporlama alışkanlığı",
        "Erken aşama bütçe kısıtlarında çalışma deneyimi",
      ],
      test: "Görev testi: CorteQS için aylık 5.000 TL bütçe ile bir Meta reklam planı oluştur. Hedef kitle, kampanya tipi ve beklenen ROAS'ı belirt.",
    },
  },
  {
    id: "pz-carsi",
    dept: "pazarlama",
    axis: "urun",
    title: "Çarşı — Topluluk Pazar Yeri Editörü",
    type: "core",
    wave: 2,
    pri: "orta",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%0.5–1 vesting 4y/1y cliff",
    kpi: ["Haftalık Çarşı ilan adedi", "İlan-eşleşme oranı", "Kullanıcı memnuniyet puanı"],
    cadence: "Günlük ilan moderasyonu · haftalık Çarşı özeti",
    tools: "Instagram Creator Studio, Notion, Canva, Google Forms",
    trigger: "Çarşı MVP'si yayına alındığında",
    exit: "Çarşı platformu oturduktan sonra ürün editörü rolüne evrilir",
    jd: "CorteQS'in topluluk pazar yeri ürünü Çarşı'nın editörlüğünü yapar. İlan kalitesini takip eder, ilan-eşleşme oranını izler, haftalık Çarşı özetini yayınlar ve topluluk geri bildirimlerini ürün ekibine iletir.",
    ad: {
      sum: "CorteQS'in topluluk pazar yeri Çarşı'nın editörlüğünü yapacak, ilan kalitesini takip edecek ve topluluk geri bildirimlerini ürüne taşıyacak bir pazar yeri editörü arıyoruz. Topluluk yönetimi ve içerik kalitesi konusunda dikkatli bir profil bekleniyor.",
      does: [
        "Günlük ilan moderasyonunu ve kalite kontrolünü yapmak",
        "İlan-eşleşme oranını izlemek ve iyileştirmek",
        "Haftalık Çarşı özetini yayınlamak",
        "Topluluk geri bildirimlerini toplamak ve ürün ekibine iletmek",
        "İlan veren kullanıcılarla iletişim kurmak",
      ],
      profile: [
        "Topluluk yönetimi veya pazar yeri deneyimi",
        "İçerik kalitesi ve moderasyon konusunda dikkatli",
        "İletişim becerisi yüksek",
        "Notion ve Google Workspace'de yetkin",
      ],
      test: "Görev testi: 5 örnek Çarşı ilanı al. Her biri için kalite puanı ver (1-5) ve iyileştirme önerisini bir cümleyle yaz.",
    },
  },
  {
    id: "pz-etkinlik",
    dept: "pazarlama",
    axis: "urun",
    title: "Etkinlik & Buluşma Koordinatörü",
    type: "proje",
    wave: 3,
    pri: "orta",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Proje bazlı — aylık 40–60 saat",
    pay: "Proje başına ücret",
    esop: "—",
    kpi: ["Aylık etkinlik adedi", "Katılımcı memnuniyet puanı", "Etkinlik sonrası dönüşüm oranı"],
    cadence: "Etkinlik öncesi 2 haftalık planlama · etkinlik günü operasyon · sonrası rapor",
    tools: "Eventbrite/Luma, Instagram, Canva, Google Workspace",
    trigger: "İlk topluluk buluşması planlandığında",
    exit: "Etkinlik formatı oturduktan sonra topluluk yöneticisine devredilir",
    jd: "CorteQS'in şehir bazlı topluluk buluşmalarını ve etkinliklerini koordine eder. Mekan ayarlaması, duyuru, kayıt yönetimi, etkinlik günü operasyonu ve sonrası raporlama bu rolün kapsamındadır. Proje bazlı çalışır; etkinlik takvimine göre yoğunluk değişir.",
    ad: {
      sum: "CorteQS'in şehir bazlı topluluk buluşmalarını koordine edecek, etkinlik operasyonunu yönetecek bir etkinlik koordinatörü arıyoruz. Proje bazlı çalışır, etkinlik takvimine göre yoğunluk değişir.",
      does: [
        "Etkinlik öncesi 2 haftalık planlama takvimini oluşturmak",
        "Mekan ayarlaması, duyuru ve kayıt yönetimini yürütmek",
        "Etkinlik günü operasyonunu koordine etmek",
        "Etkinlik sonrası rapor ve memnuniyet anketini hazırlamak",
        "Etkinlik fotoğraflarını ve özetini sosyal medyaya taşımak",
      ],
      profile: [
        "Etkinlik koordinasyonu veya topluluk organizasyonu deneyimi",
        "Proje yönetimi ve çoklu zaman çizelgesi alışkanlığı",
        "İletişim becerisi yüksek, sahada rahat",
        "Şehir bazlı network tercih sebebidir",
      ],
      test: "Görev testi: 50 kişilik bir topluluk buluşması için etkinlik planı oluştur. Mekan kriterleri, duyuru takvimi, kayıt akışı ve etkinlik günü zaman çizelgesini belirt.",
    },
  },
];
