import type { KadroRole } from "../kadro-types";

export const PAZARLAMA_COGRAFYA_ROLES: KadroRole[] = [
  {
    id: "cg-dach",
    dept: "pazarlama",
    axis: "cografya",
    title: "DACH Bölge Küratörü — Almanya, Avusturya, İsviçre",
    type: "core",
    wave: 2,
    pri: "yuksek",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%0.5–1 vesting 4y/1y cliff",
    kpi: ["Bölge abone sayısı", "Haftalık içerik yayın adedi", "Bölgesel etkileşim oranı"],
    cadence: "Günlük story · haftalık bölge raporu",
    tools: "Instagram Creator Studio, Canva, Notion, Google Analytics",
    trigger: "DACH bölgesinde ilk 50 abone alındığında",
    exit: "Bölge oturduktan sonra şehir küratörlerine devredilir",
    jd: "DACH bölgesinin (Almanya, Avusturya, İsviçre) içerik küratörlüğünü yapar. Bölgesel sinyalleri story formatına dönüştürür, yerel etkinlikleri takip eder ve bölge bazlı büyüme stratejisini uygular. Almanca-Türkçe çift dil kapasitesi beklenir.",
    ad: {
      sum: "DACH bölgesinin içerik küratörlüğünü yapacak, bölgesel sinyalleri story formatına dönüştürecek bir bölge küratörü arıyoruz. Almanca-Türkçe çift dil kapasitesi ve bölge kültürüne aşinalık bekleniyor.",
      does: [
        "Bölgesel sinyalleri günlük story formatına dönüştürmek",
        "Yerel etkinlikleri ve fırsatları takip etmek",
        "Bölge bazlı büyüme stratejisini uygulamak",
        "Haftalık bölge raporunu sunmak",
        "Merkez ekip ile bölgesel koordinasyonu sağlamak",
      ],
      profile: [
        "DACH bölgesinde yaşama veya çalışma deneyimi",
        "Almanca-Türkçe çift dil kapasitesi",
        "İçerik üretimi ve sosyal medya deneyimi",
        "Bölge kültürüne ve yerel dinamiklere aşinalık",
      ],
      test: "Görev testi: DACH bölgesinden 3 yerel sinyal seç. Her biri için bir story kartı hazırla (Almanca başlık + Türkçe özet). Bölgesel farklılığı bir cümleyle açıkla.",
    },
  },
  {
    id: "cg-uk",
    dept: "pazarlama",
    axis: "cografya",
    title: "İngiltere Bölge Küratörü",
    type: "core",
    wave: 2,
    pri: "orta",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%0.5–1 vesting 4y/1y cliff",
    kpi: ["Bölge abone sayısı", "Haftalık içerik yayın adedi", "Bölgesel etkileşim oranı"],
    cadence: "Günlük story · haftalık bölge raporu",
    tools: "Instagram Creator Studio, Canva, Notion, Google Analytics",
    trigger: "İngiltere'de ilk 50 abone alındığında",
    exit: "Bölge oturduktan sonra şehir küratörlerine devredilir",
    jd: "İngiltere bölgesinin içerik küratörlüğünü yapar. Londra başta olmak üzere İngiltere'deki Türk diasporası için bölgesel sinyalleri story formatına dönüştürür, yerel etkinlikleri takip eder ve büyüme stratejisini uygular.",
    ad: {
      sum: "İngiltere bölgesinin içerik küratörlüğünü yapacak, Türk diasporası için bölgesel içerik üretecek bir bölge küratörü arıyoruz. İngiltere'de yaşayan, İngilizce-Türkçe çift dil kapasiteli bir profil bekleniyor.",
      does: [
        "Bölgesel sinyalleri günlük story formatına dönüştürmek",
        "Yerel etkinlikleri ve fırsatları takip etmek",
        "Bölge bazlı büyüme stratejisini uygulamak",
        "Haftalık bölge raporunu sunmak",
        "Merkez ekip ile bölgesel koordinasyonu sağlamak",
      ],
      profile: [
        "İngiltere'de yaşama veya çalışma deneyimi",
        "İngilizce-Türkçe çift dil kapasitesi",
        "İçerik üretimi ve sosyal medya deneyimi",
        "Diaspora dinamiklerine aşinalık",
      ],
      test: "Görev testi: İngiltere'den 3 yerel sinyal seç. Her biri için bir story kartı hazırla. Diaspora kitlesine özgü farklılığı bir cümleyle açıkla.",
    },
  },
  {
    id: "cg-benelux",
    dept: "pazarlama",
    axis: "cografya",
    title: "Benelux Bölge Küratörü — Hollanda, Belçika, Lüksemburg",
    type: "part",
    wave: 3,
    pri: "orta",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Haftalık 15 saat",
    pay: "Aylık sabit ücret",
    esop: "%0.25–0.5 vesting 4y/1y cliff",
    kpi: ["Bölge abone sayısı", "Haftalık içerik yayın adedi", "Bölgesel etkileşim oranı"],
    cadence: "Haftalık 3 story · haftalık bölge raporu",
    tools: "Instagram Creator Studio, Canva, Notion",
    trigger: "Benelux'ta ilk 30 abone alındığında",
    exit: "Bölge büyümesi hızlanırsa tam zamanlıya dönüşüm değerlendirilir",
    jd: "Benelux bölgesinin (Hollanda, Belçika, Lüksemburg) içerik küratörlüğünü yapar. Part-time çalışır, haftalık 15 saat. Bölgesel sinyalleri story formatına dönüştürür ve yerel Türk diasporası için içerik üretir.",
    ad: {
      sum: "Benelux bölgesinin içerik küratörlüğünü yapacak, part-time bölgesel içerik üretecek bir bölge küratörü arıyoruz. Benelux'ta yaşayan, bölge kültürüne aşina bir profil bekleniyor. Haftalık 15 saat.",
      does: [
        "Haftalık 3 story formatında bölgesel içerik üretmek",
        "Yerel etkinlikleri ve fırsatları takip etmek",
        "Bölge bazlı büyüme önerilerini iletmek",
        "Haftalık bölge raporunu sunmak",
      ],
      profile: [
        "Benelux'ta yaşama veya çalışma deneyimi",
        "İçerik üretimi ve sosyal medya deneyimi",
        "Bölge kültürüne aşinalık",
        "Hollanda/Flemenkçe tercih sebebidir",
      ],
      test: "Görev testi: Benelux'tan 2 yerel sinyal seç. Her biri için bir story kartı hazırla. Bölgesel farklılığı bir cümleyle açıkla.",
    },
  },
  {
    id: "cg-korfez",
    dept: "pazarlama",
    axis: "cografya",
    title: "Körfez Bölge Küratörü — BAE, Katar, Suudi Arabistan",
    type: "part",
    wave: 3,
    pri: "orta",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Haftalık 12 saat",
    pay: "Aylık sabit ücret",
    esop: "%0.25–0.5 vesting 4y/1y cliff",
    kpi: ["Bölge abone sayısı", "Haftalık içerik yayın adedi", "Bölgesel etkileşim oranı"],
    cadence: "Haftalık 3 story · haftalık bölge raporu",
    tools: "Instagram Creator Studio, Canva, Notion",
    trigger: "Körfez bölgesinde ilk 30 abone alındığında",
    exit: "Bölge büyümesi hızlanırsa tam zamanlıya dönüşüm değerlendirilir",
    jd: "Körfez bölgesinin (BAE, Katar, Suudi Arabistan) içerik küratörlüğünü yapar. Part-time çalışır. Bölgedeki Türk profesyoneller ve girişimciler için bölgesel sinyalleri story formatına dönüştürür.",
    ad: {
      sum: "Körfez bölgesinin içerik küratörlüğünü yapacak, bölgedeki Türk profesyoneller için içerik üretecek bir bölge küratörü arıyoruz. Körfez bölgesinde yaşayan, Arapça tercih sebebidir. Haftalık 12 saat.",
      does: [
        "Haftalık 3 story formatında bölgesel içerik üretmek",
        "Yerel etkinlikleri ve iş fırsatlarını takip etmek",
        "Bölge bazlı büyüme önerilerini iletmek",
        "Haftalık bölge raporunu sunmak",
      ],
      profile: [
        "Körfez bölgesinde yaşama veya çalışma deneyimi",
        "İçerik üretimi ve sosyal medya deneyimi",
        "Bölge kültürüne ve iş dinamiklerine aşinalık",
        "Arapça tercih sebebidir",
      ],
      test: "Görev testi: Körfez bölgesinden 2 yerel sinyal seç. Her biri için bir story kartı hazırla. Bölgedeki Türk profesyonellere özgü farklılığı bir cümleyle açıkla.",
    },
  },
  {
    id: "cg-na",
    dept: "pazarlama",
    axis: "cografya",
    title: "Kuzey Amerika Bölge Küratörü — ABD, Kanada",
    type: "part",
    wave: 3,
    pri: "dusuk",
    status: "beklemede",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Haftalık 10 saat",
    pay: "Aylık sabit ücret",
    esop: "%0.25 vesting 4y/1y cliff",
    kpi: ["Bölge abone sayısı", "Haftalık içerik yayın adedi", "Bölgesel etkileşim oranı"],
    cadence: "Haftalık 2 story · aylık bölge raporu",
    tools: "Instagram Creator Studio, Canva, Notion",
    trigger: "Kuzey Amerika'da ilk 30 abone alındığında",
    exit: "Bölge önceliklendirme kararına göre devam eder veya sonlanır",
    jd: "Kuzey Amerika bölgesinin (ABD, Kanada) içerik küratörlüğünü yapar. Part-time çalışır. Diaspora odaklı bölgesel sinyalleri story formatına dönüştürür. Dalga 3 rolü olarak öncelik düşüktür.",
    ad: {
      sum: "Kuzey Amerika bölgesinin içerik küratörlüğünü yapacak, diaspora odaklı bölgesel içerik üretecek bir bölge küratörü arıyoruz. Kuzey Amerika'da yaşayan, İngilizce-Türkçe çift dil kapasiteli bir profil bekleniyor. Haftalık 10 saat.",
      does: [
        "Haftalık 2 story formatında bölgesel içerik üretmek",
        "Diaspora etkinliklerini ve fırsatlarını takip etmek",
        "Bölge bazlı büyüme önerilerini iletmek",
        "Aylık bölge raporunu sunmak",
      ],
      profile: [
        "Kuzey Amerika'da yaşama veya çalışma deneyimi",
        "İngilizce-Türkçe çift dil kapasitesi",
        "İçerik üretimi ve sosyal medya deneyimi",
        "Diaspora dinamiklerine aşinalık",
      ],
      test: "Görev testi: Kuzey Amerika'dan 2 yerel sinyal seç. Her biri için bir story kartı hazırla. Diaspora kitlesine özgü farklılığı bir cümleyle açıkla.",
    },
  },
  {
    id: "cg-ulke",
    dept: "pazarlama",
    axis: "cografya",
    title: "Türkiye Şehir Küratörleri Koordinatörü",
    type: "core",
    wave: 1,
    pri: "kritik",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%0.5–1.5 vesting 4y/1y cliff",
    kpi: ["Aktif şehir sayısı", "Şehir bazlı içerik kalite puanı", "Küratör elde tutma oranı"],
    cadence: "Günlük şehir koordinasyonu · haftalık küratör toplantısı",
    tools: "Instagram Creator Studio, Notion, Canva, Google Workspace",
    trigger: "İkinci şehir aktif olduğunda",
    exit: "Şehir ağı oturduktan sonra operasyon ekibine evrilir",
    jd: "Türkiye'deki şehir küratörlerini koordine eder. Her şehrin içerik kalitesini takip eder, küratör işe alımını destekler, haftalık küratör toplantısını yürütür ve şehir bazlı büyüme stratejisini uygular. İstanbul dışındaki şehirler için kritik roldür.",
    ad: {
      sum: "Türkiye'deki şehir küratörlerini koordine edecek, şehir bazlı içerik kalitesini takip edecek bir şehir koordinatörü arıyoruz. Türkiye'nin farklı şehirlerine aşina, koordinasyon becerisi yüksek bir profil bekleniyor.",
      does: [
        "Şehir küratörlerini koordine etmek ve yönetmek",
        "Şehir bazlı içerik kalitesini takip etmek",
        "Küratör işe alım sürecini desteklemek",
        "Haftalık küratör toplantısını yürütmek",
        "Şehir bazlı büyüme stratejisini uygulamak",
      ],
      profile: [
        "Türkiye'nin farklı şehirlerine aşinalık",
        "Koordinasyon ve ekip yönetimi deneyimi",
        "İçerik kalitesi ve moderasyon anlayışı",
        "Notion ve Google Workspace'de yetkin",
      ],
      test: "Görev testi: 3 farklı şehir için küratör iş ilanı taslağı yaz. Her şehir için farklı bir vurgu belirle ve neden bu vurgunun o şehre uygun olduğunu açıkla.",
    },
  },
  {
    id: "cg-elci",
    dept: "pazarlama",
    axis: "cografya",
    title: "Elçi Programı Yöneticisi — Kampüs Temsilcileri",
    type: "topluluk",
    wave: 2,
    pri: "orta",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Haftalık 10 saat + etkinlik bazlı",
    pay: "Gönüllü + ESOP adaylığı",
    esop: "Performansa göre %0.1–0.25 advisory",
    kpi: ["Aktif elçi sayısı", "Elçi başına referral adedi", "Kampüs etkinlik adedi"],
    cadence: "Haftalık elçi check-in · aylık elçi raporu",
    tools: "Instagram, WhatsApp grupları, Notion, Google Forms",
    trigger: "İlk 3 üniversite hedeflendiğinde",
    exit: "Elçi programı oturduktan sonra topluluk yöneticisine devredilir",
    jd: "CorteQS'in üniversite kampüs elçi programını yönetir. Elçi işe alımını yapar, eğitim materyallerini hazırlar, haftalık check-in'leri yürütür ve elçi performansını takip eder. Gönüllü tabanlı çalışır, performansa göre ESOP adaylığı değerlendirilir.",
    ad: {
      sum: "CorteQS'in üniversite kampüs elçi programını yönetecek, genç yeteneklerle çalışacak bir elçi programı yöneticisi arıyoruz. Üniversite ortamına aşina, genç kitleyle iletişim kurabilen bir profil bekleniyor.",
      does: [
        "Elçi işe alımını yapmak ve eğitmek",
        "Elçi eğitim materyallerini hazırlamak",
        "Haftalık elçi check-in'lerini yürütmek",
        "Elçi performansını takip etmek ve raporlamak",
        "Kampüs etkinliklerini koordine etmek",
      ],
      profile: [
        "Üniversite ortamına aşinalık veya öğrenci deneyimi",
        "Genç kitleyle iletişim becerisi",
        "Topluluk yönetimi veya gönüllü koordinasyonu deneyimi",
        "Notion ve Google Workspace'de yetkin",
      ],
      test: "Görev testi: Bir üniversite kampüsü için elçi iş ilanı yaz. Başvuru kriterlerini, beklentileri ve faydaları belirt.",
    },
  },
  {
    id: "cg-contrib",
    dept: "pazarlama",
    axis: "cografya",
    title: "Katkıcı Ağı Yöneticisi — Serbest İçerik Üreticileri",
    type: "topluluk",
    wave: 2,
    pri: "orta",
    status: "acik",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Haftalık 10 saat",
    pay: "Gönüllü + içerik başına ücret",
    esop: "—",
    kpi: ["Aktif katkıcı sayısı", "Katkıcı başına içerik adedi", "İçerik kalite puanı"],
    cadence: "Haftalık katkıcı iletişimi · aylık katkıcı raporu",
    tools: "Instagram, WhatsApp grupları, Notion, Google Forms",
    trigger: "Serbest içerik üreticisi ağı oluşturulduğunda",
    exit: "Katkıcı ağı oturduktan sonra içerik müdürüne devredilir",
    jd: "CorteQS'in serbest içerik üreticisi ağını yönetir. Katkıcı işe alımını yapar, içerik brief'lerini hazırlar, kalite kontrolünü yürütür ve katkıcı performansını takip eder. Gönüllü tabanlı + içerik başına ücret modeli.",
    ad: {
      sum: "CorteQS'in serbest içerik üreticisi ağını yönetecek, katkıcı işe alımını yapacak ve içerik kalitesini takip edecek bir katkıcı ağı yöneticisi arıyoruz. Topluluk yönetimi ve içerik kalitesi konusunda dikkatli bir profil bekleniyor.",
      does: [
        "Katkıcı işe alımını yapmak ve oryantasyon vermek",
        "İçerik brief'lerini hazırlamak ve iletmek",
        "Kalite kontrolünü yürütmek",
        "Katkıcı performansını takip etmek",
        "Aylık katkıcı raporunu sunmak",
      ],
      profile: [
        "Topluluk yönetimi veya freelancer koordinasyonu deneyimi",
        "İçerik kalitesi ve editörlük anlayışı",
        "İletişim becerisi yüksek",
        "Notion ve Google Workspace'de yetkin",
      ],
      test: "Görev testi: 3 farklı içerik tipi için katkıcı brief şablonu oluştur (story, feed post, uzun video). Her brief için beklenen format, süre ve kalite kriterlerini belirt.",
    },
  },
  {
    id: "cg-program",
    dept: "pazarlama",
    axis: "cografya",
    title: "Bölgesel Program Yöneticisi — Çoklu Bölge Koordinasyonu",
    type: "core",
    wave: 3,
    pri: "dusuk",
    status: "beklemede",
    owner: "",
    reports: "Head of Marketing (ld-cmo)",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%0.5–1 vesting 4y/1y cliff",
    kpi: ["Aktif bölge sayısı", "Bölge bazlı büyüme oranı", "Koordinasyon memnuniyet puanı"],
    cadence: "Haftalık bölge koordinasyonu · aylık bölgesel büyüme raporu",
    tools: "Notion, Google Workspace, Zoom, Instagram Creator Studio",
    trigger: "3+ bölge aktif olduğunda",
    exit: "Bölgesel yapı oturduktan sonra VP Growth rolüne evrilir",
    jd: "Birden fazla bölgenin aktif olduğu durumda tüm bölgesel küratörleri koordine eder. Bölgesel stratejilerin hizalanmasını sağlar, kaynak paylaşımını optimize eder ve aylık bölgesel büyüme raporunu hazırlar. Dalga 3 rolü olarak şu anda beklemededir.",
    ad: {
      sum: "Birden fazla bölgenin aktif olduğu durumda bölgesel küratörleri koordine edecek, bölgesel stratejileri hizalayacak bir program yöneticisi arıyoruz. Çoklu zaman çizelgesi yönetimi ve bölgesel koordinasyon deneyimi bekleniyor. Dalga 3 rolü.",
      does: [
        "Tüm bölgesel küratörleri koordine etmek",
        "Bölgesel stratejilerin hizalanmasını sağlamak",
        "Kaynak paylaşımını optimize etmek",
        "Aylık bölgesel büyüme raporunu hazırlamak",
        "Bölgesel best practice'leri paylaşmak",
      ],
      profile: [
        "Çoklu ekip veya bölgesel koordinasyon deneyimi",
        "Proje yönetimi ve zaman çizelgesi alışkanlığı",
        "Stratejik düşünme ve kaynak optimizasyonu",
        "Notion ve Google Workspace'de ileri düzey",
      ],
      test: "Görev testi: 3 farklı bölge için aylık koordinasyon takvimi oluştur. Her bölge için 2 öncelik ve 1 paylaşılabilir kaynak belirt.",
    },
  },
];
