import type { KadroRole } from "../kadro-types";

export const URUN_TEKNOLOJI_ROLES: KadroRole[] = [
  {
    id: "tk-fullstack",
    dept: "urun",
    axis: "merkez",
    title: "Senior Fullstack Geliştirici — Lovable",
    type: "core",
    wave: 1,
    pri: "kritik",
    status: "acik",
    owner: "",
    reports: "CTO",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%1–2 vesting 4y/1y cliff",
    kpi: ["Sprint teslim oranı", "Kod review dönüş süresi", "Kritik bug çözüm süresi"],
    cadence: "Günlük standup · haftalık sprint planlama · code review",
    tools: "Lovable, React, TypeScript, Supabase, Vercel, GitHub",
    trigger: "MVP sonrası ilk büyük özellik planlandığında",
    exit: "Ürün altyapısı oturduktan sonra tech lead rolüne evrilir",
    jd: "CorteQS'in Lovable tabanlı ürününün fullstack geliştirmesini yapar. React + TypeScript frontend, Supabase backend ve Vercel deployment hattında çalışır. Sprint planlamasına aktif katılır, kod incelemeleri yapar ve teknik kararlarında CTO ile birlikte hareket eder.",
    ad: {
      sum: "CorteQS'in Lovable tabanlı ürününün fullstack geliştirmesini yapacak, React + Supabase + Vercel hattında çalışacak bir senior fullstack geliştirici arıyoruz. Early-stage start-up belirsizliğinde hızlı teslim yapan bir profil bekleniyor.",
      does: [
        "React + TypeScript ile frontend bileşenleri geliştirmek",
        "Supabase ile backend servisleri ve veritabanı tasarlamak",
        "Vercel üzerinde deployment ve CI/CD süreçlerini yönetmek",
        "Sprint planlamasına aktif katılmak ve kod incelemeleri yapmak",
        "Teknik kararları CTO ile birlikte almak",
      ],
      profile: [
        "En az 4 yıl fullstack geliştirme deneyimi",
        "React + TypeScript'te ileri düzey",
        "Supabase veya benzeri BaaS platformlarında deneyim",
        "Erken aşama start-up ortamında çalışmış olmak",
      ],
      test: "Görev testi: Supabase tabanlı basit bir CRUD API tasarla (kullanıcı profili). Tablo şeması, RLS politikası ve React hook'unu yaz.",
    },
  },
  {
    id: "tk-design",
    dept: "urun",
    axis: "merkez",
    title: "Ürün Tasarımcısı — UX/UI",
    type: "core",
    wave: 1,
    pri: "yuksek",
    status: "acik",
    owner: "",
    reports: "CTO",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%0.5–1.5 vesting 4y/1y cliff",
    kpi: ["Tasarım teslim süresi", "Kullanıcı test bulgu sayısı", "Tasarım sistem tutarlılığı"],
    cadence: "Günlük tasarım review · haftalık sprint planlama · kullanıcı testleri",
    tools: "Figma, Lovable, Notion, Maze/UserTesting",
    trigger: "İlk kullanıcı geri bildirimi alındığında",
    exit: "Tasarım sistemi oturduktan sonra design lead rolüne evrilir",
    jd: "CorteQS'in ürün tasarımını yönetir. Figma'da wireframe ve yüksek fidelite mockup'lar oluşturur, kullanıcı testlerini planlar ve yürütür, tasarım sistemini Figma'da inşa eder. Lovable üzerinde frontend geliştirme ekibiyle yakın çalışır.",
    ad: {
      sum: "CorteQS'in ürün tasarımını yönetecek, Figma'da wireframe'den yüksek fidelite mockup'a kadar tüm süreci taşıyacak bir ürün tasarımcısı arıyoruz. Early-stage start-up'ta sıfırdan tasarım sistemi kurma deneyimi bekleniyor.",
      does: [
        "Figma'da wireframe ve yüksek fidelite mockup'lar oluşturmak",
        "Kullanıcı testlerini planlamak ve yürütmek",
        "Tasarım sistemini Figma'da inşa etmek",
        "Frontend geliştirme ekibiyle yakın çalışmak",
        "Haftalık tasarım review'de kararları belgelemek",
      ],
      profile: [
        "En az 3 yıl ürün tasarımı deneyimi",
        "Figma'da ileri düzey (auto layout, components, variables)",
        "Kullanıcı araştırması ve test planlama deneyimi",
        "Erken aşama start-up ortamında çalışmış olmak",
      ],
      test: "Görev testi: CorteQS'in mevcut bir özelliği için wireframe oluştur. 3 ekran: liste, detay, düzenleme. Her ekran için tasarım kararını bir cümleyle açıkla.",
    },
  },
  {
    id: "tk-frontend",
    dept: "urun",
    axis: "merkez",
    title: "Frontend Geliştirici — React & Tailwind",
    type: "core",
    wave: 1,
    pri: "yuksek",
    status: "acik",
    owner: "",
    reports: "CTO / Senior Fullstack (tk-fullstack)",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%0.5–1 vesting 4y/1y cliff",
    kpi: ["Sprint teslim oranı", "Bileşen tekrar kullanım oranı", "Lighthouse performans skoru"],
    cadence: "Günlük standup · haftalık sprint · code review",
    tools: "React, TypeScript, Tailwind CSS, shadcn/ui, Vite, GitHub",
    trigger: "İlk büyük frontend özelliği planlandığında",
    exit: "Frontend altyapısı oturduktan sonra senior rolüne evrilir",
    jd: "CorteQS'in React + TypeScript frontend'ini geliştirir. Tailwind CSS ve shadcn/ui bileşen kütüphanesiyle çalışır. Responsive tasarım, erişilebilirlik ve performans optimizasyonu bu rolün günlük işidir.",
    ad: {
      sum: "CorteQS'in React + TypeScript frontend'ini geliştirecek, Tailwind CSS ve shadcn/ui ile çalışacak bir frontend geliştirici arıyoruz. Performans ve erişilebilirlik konularında dikkatli bir profil bekleniyor.",
      does: [
        "React + TypeScript ile bileşenler geliştirmek",
        "Tailwind CSS ve shadcn/ui ile responsive arayüzler oluşturmak",
        "Performans optimizasyonu yapmak (Lighthouse)",
        "Erişilebilirlik standartlarını uygulamak",
        "Code review'lara aktif katılmak",
      ],
      profile: [
        "En az 2 yıl React geliştirme deneyimi",
        "TypeScript'te yetkin",
        "Tailwind CSS ve modern CSS anlayışı",
        "Erişilebilirlik temellerine aşina",
      ],
      test: "Görev testi: React + Tailwind ile responsive bir rol kartı bileşeni oluştur. Mobil ve desktop görünümünü göster. Erişilebilirlik kontrollerini listele.",
    },
  },
  {
    id: "tk-backend",
    dept: "urun",
    axis: "merkez",
    title: "Backend Geliştirici — Supabase & Edge Functions",
    type: "core",
    wave: 1,
    pri: "yuksek",
    status: "acik",
    owner: "",
    reports: "CTO / Senior Fullstack (tk-fullstack)",
    hours: "Tam zamanlı",
    pay: "Erken dönem + ESOP",
    esop: "%0.5–1 vesting 4y/1y cliff",
    kpi: ["API yanıt süresi", "RLS politika doğruluğu", "Migration başarı oranı"],
    cadence: "Günlük standup · haftalık sprint · code review",
    tools: "Supabase, PostgreSQL, Deno/Edge Functions, TypeScript, GitHub",
    trigger: "İlk karmaşık backend özelliği planlandığında",
    exit: "Backend altyapısı oturduktan sonra senior rolüne evrilir",
    jd: "CorteQS'in Supabase tabanlı backend'ini geliştirir. PostgreSQL şema tasarımı, RLS politikaları, Edge Functions ve migration yönetimi bu rolün günlük işidir. Veri modelinin doğruluğunu ve güvenliğini sağlar.",
    ad: {
      sum: "CorteQS'in Supabase tabanlı backend'ini geliştirecek, PostgreSQL şema tasarımı ve RLS politikalarını yönetecek bir backend geliştirici arıyoruz. Supabase ve PostgreSQL konusunda deneyimli bir profil bekleniyor.",
      does: [
        "PostgreSQL şema tasarımı ve migration yönetimi",
        "RLS politikaları yazmak ve doğrulamak",
        "Supabase Edge Functions geliştirmek",
        "API performansını izlemek ve optimize etmek",
        "Veri bütünlüğü ve güvenlik kontrollerini sağlamak",
      ],
      profile: [
        "En az 3 yıl backend geliştirme deneyimi",
        "PostgreSQL'de ileri düzey (index, trigger, RLS)",
        "Supabase veya benzeri BaaS platformlarında deneyim",
        "Güvenlik ve veri bütünlüğü anlayışı",
      ],
      test: "Görev testi: Supabase tabanlı bir tablo tasarla (kadro_role_states). RLS politikası, CHECK kısıtı ve updated_at trigger'ı yaz.",
    },
  },
  {
    id: "tk-mobile",
    dept: "urun",
    axis: "merkez",
    title: "Mobil Geliştirici — React Native / Expo",
    type: "proje",
    wave: 3,
    pri: "orta",
    status: "beklemede",
    owner: "",
    reports: "CTO",
    hours: "Proje bazlı — aylık 60–80 saat",
    pay: "Proje başına ücret",
    esop: "%0.25–0.5 vesting 4y/1y cliff",
    kpi: ["Sprint teslim oranı", "Crash-free session oranı", "App Store puanı"],
    cadence: "Haftalık sprint · iki haftalık release",
    tools: "React Native, Expo, TypeScript, Supabase, EAS Build",
    trigger: "Mobil MVP karar verildiğinde",
    exit: "Mobil uygulama yayına alındıktan sonra tam zamanlıya dönüşüm değerlendirilir",
    jd: "CorteQS'in mobil uygulamasını React Native / Expo ile geliştirir. Proje bazlı çalışır, aylık 60-80 saat. iOS ve Android platformları için cross-platform geliştirme yapar, App Store ve Play Store yayım süreçlerini yönetir.",
    ad: {
      sum: "CorteQS'in mobil uygulamasını React Native / Expo ile geliştirecek bir mobil geliştirici arıyoruz. Cross-platform mobil geliştirme deneyimi olan bir profil bekleniyor. Proje bazlı, aylık 60-80 saat.",
      does: [
        "React Native / Expo ile cross-platform mobil geliştirme",
        "iOS ve Android platform uyumluluğunu sağlamak",
        "App Store ve Play Store yayım süreçlerini yönetmek",
        "Crash reporting ve performans izleme yapmak",
        "Haftalık sprint planlamasına katılmak",
      ],
      profile: [
        "En az 2 yıl React Native / Expo deneyimi",
        "TypeScript'te yetkin",
        "App Store ve Play Store yayım deneyimi",
        "Mobil performans optimizasyonu anlayışı",
      ],
      test: "Görev testi: React Native ile basit bir rol listesi ekranı tasarla. Supabase entegrasyonu, loading state ve hata yönetimini göster.",
    },
  },
  {
    id: "tk-qa",
    dept: "urun",
    axis: "merkez",
    title: "QA Mühendisi — Test Otomasyonu",
    type: "part",
    wave: 2,
    pri: "yuksek",
    status: "acik",
    owner: "",
    reports: "CTO",
    hours: "Haftalık 20 saat",
    pay: "Aylık sabit ücret",
    esop: "%0.25–0.5 vesting 4y/1y cliff",
    kpi: ["Test kapsama oranı", "Bug kaçış oranı", "Otomasyon başarı oranı"],
    cadence: "Her sprint için test planı · haftalık bug triage",
    tools: "Playwright, Vitest, Supabase, GitHub Actions",
    trigger: "İlk büyük özellik release öncesi",
    exit: "Test altyapısı oturduktan sonra tam zamanlıya dönüşüm değerlendirilir",
    jd: "CorteQS'in test stratejisini ve otomasyon altyapısını kurar. Playwright ile E2E testleri, Vitest ile birim testleri yazar. CI/CD pipeline'ına test adımlarını ekler. Part-time çalışır, haftalık 20 saat.",
    ad: {
      sum: "CorteQS'in test stratejisini ve otomasyon altyapısını kuracak, Playwright ve Vitest ile testler yazacak bir QA mühendisi arıyoruz. Test otomasyonu konusunda deneyimli bir profil bekleniyor. Part-time, haftalık 20 saat.",
      does: [
        "Test stratejisi ve planı oluşturmak",
        "Playwright ile E2E testleri yazmak",
        "Vitest ile birim testleri yazmak",
        "CI/CD pipeline'ına test adımlarını eklemek",
        "Haftalık bug triage toplantısına katılmak",
      ],
      profile: [
        "En az 2 yıl QA/test otomasyonu deneyimi",
        "Playwright veya benzeri E2E test aracında yetkin",
        "TypeScript'te yetkin",
        "CI/CD pipeline deneyimi",
      ],
      test: "Görev testi: Basit bir login akışı için 5 E2E test senaryosu yaz (Playwright). Her senaryo için beklenti ve cleanup adımını belirt.",
    },
  },
  {
    id: "tk-ai",
    dept: "urun",
    axis: "merkez",
    title: "AI / ML Mühendisi — İçerik ve Öneri",
    type: "proje",
    wave: 2,
    pri: "yuksek",
    status: "acik",
    owner: "",
    reports: "CTO",
    hours: "Proje bazlı — aylık 40–60 saat",
    pay: "Proje başına ücret",
    esop: "%0.25–0.5 vesting 4y/1y cliff",
    kpi: ["Model doğruluğu", "Öneri dönüşüm oranı", "İçerik otomasyon kapsama oranı"],
    cadence: "Haftalık model review · aylık performans raporu",
    tools: "Python, OpenAI API, Supabase, LangChain, GitHub",
    trigger: "İçerik otomasyonu veya öneri sistemi planlandığında",
    exit: "AI altyapısı oturduktan sonra tam zamanlıya dönüşüm değerlendirilir",
    jd: "CorteQS'in AI/ML altyapısını kurar. İçerik otomasyonu, öneri sistemleri ve sinyal analizi için modeller geliştirir. OpenAI API, LangChain ve Python ile çalışır. Proje bazlı çalışır.",
    ad: {
      sum: "CorteQS'in AI/ML altyapısını kuracak, içerik otomasyonu ve öneri sistemleri için modeller geliştirecek bir AI mühendisi arıyoruz. LLM ve öneri sistemleri konusunda deneyimli bir profil bekleniyor. Proje bazlı.",
      does: [
        "İçerik otomasyonu için LLM tabanlı çözümler geliştirmek",
        "Öneri sistemi modelleri tasarlamak ve eğitmek",
        "Sinyal analizi ve sınıflandırma modelleri oluşturmak",
        "Model performansını izlemek ve raporlamak",
        "OpenAI API ve LangChain ile entegrasyon yapmak",
      ],
      profile: [
        "En az 2 yıl ML/AI geliştirme deneyimi",
        "Python'da ileri düzey",
        "LLM ve recommendation system deneyimi",
        "API entegrasyonu ve model deployment anlayışı",
      ],
      test: "Görev testi: CorteQS için basit bir içerik sınıflandırma pipeline'ı tasarla. Girdi, model, çıktı ve değerlendirme metriğini belirt.",
    },
  },
  {
    id: "tk-data",
    dept: "urun",
    axis: "merkez",
    title: "Veri Mühendisi — Pipeline & Analitik",
    type: "part",
    wave: 2,
    pri: "orta",
    status: "acik",
    owner: "",
    reports: "CTO",
    hours: "Haftalık 15 saat",
    pay: "Aylık sabit ücret",
    esop: "%0.25–0.5 vesting 4y/1y cliff",
    kpi: ["Pipeline güvenilirliği", "Veri tazelik süresi", "Analitik sorgu performansı"],
    cadence: "Haftalık pipeline review · aylık veri kalitesi raporu",
    tools: "Supabase, PostgreSQL, Python, dbt, GitHub",
    trigger: "Veri hacmi manuel takibi zorlaştırdığında",
    exit: "Veri altyapısı oturduktan sonra tam zamanlıya dönüşüm değerlendirilir",
    jd: "CorteQS'in veri pipeline'larını ve analitik altyapısını kurar. Supabase PostgreSQL'den veri çeker, dbt ile transformasyon yapar ve analitik dashboard'lar için hazır veri katmanı oluşturur. Part-time çalışır.",
    ad: {
      sum: "CorteQS'in veri pipeline'larını ve analitik altyapısını kuracak, dbt ve Supabase ile çalışacak bir veri mühendisi arıyoruz. Veri pipeline'ı ve analitik altyapı konusunda deneyimli bir profil bekleniyor. Part-time, haftalık 15 saat.",
      does: [
        "Veri pipeline'larını tasarlamak ve yönetmek",
        "dbt ile veri transformasyonları yapmak",
        "Analitik dashboard'lar için hazır veri katmanı oluşturmak",
        "Veri kalitesini izlemek ve raporlamak",
        "Supabase PostgreSQL'den veri çekmek",
      ],
      profile: [
        "En az 2 yıl veri mühendisliği deneyimi",
        "PostgreSQL ve dbt'de yetkin",
        "Python'da yetkin",
        "Veri kalitesi ve pipeline güvenilirliği anlayışı",
      ],
      test: "Görev testi: Supabase'den çekilen ham veriyi dbt ile analitik-ready hale getiren bir transformasyon pipeline'ı tasarla. 3 model ve 1 test belirt.",
    },
  },
  {
    id: "tk-devops",
    dept: "urun",
    axis: "merkez",
    title: "DevOps & Altyapı Mühendisi",
    type: "part",
    wave: 1,
    pri: "yuksek",
    status: "acik",
    owner: "",
    reports: "CTO",
    hours: "Haftalık 10 saat",
    pay: "Aylık sabit ücret",
    esop: "%0.25–0.5 vesting 4y/1y cliff",
    kpi: ["Deployment sıklığı", "Uptime oranı", "Incident yanıt süresi"],
    cadence: "Haftalık altyapı review · incident response on-call",
    tools: "Vercel, Supabase, GitHub Actions, Docker, Cloudflare",
    trigger: "İlk production deployment sonrası",
    exit: "Altyapı oturduktan sonra çeyreklik review'ye geçer",
    jd: "CorteQS'in production altyapısını yönetir. Vercel deployment'ları, Supabase veritabanı yönetimi, GitHub Actions CI/CD pipeline'ları ve Cloudflare CDN yapılandırması bu rolün kapsamındadır. Part-time çalışır, on-call rotation vardır.",
    ad: {
      sum: "CorteQS'in production altyapısını yönetecek, Vercel + Supabase + GitHub Actions hattında çalışacak bir DevOps mühendisi arıyoruz. Production altyapı yönetimi ve incident response deneyimi bekleniyor. Part-time, haftalık 10 saat.",
      does: [
        "Vercel deployment'larını yönetmek",
        "Supabase veritabanı yönetimi ve yedekleme",
        "GitHub Actions CI/CD pipeline'larını yapılandırmak",
        "Cloudflare CDN ve güvenlik ayarlarını yönetmek",
        "Incident response ve on-call rotation",
      ],
      profile: [
        "En az 3 yıl DevOps/altyapı deneyimi",
        "Vercel ve Supabase'de yetkin",
        "CI/CD pipeline yapılandırma deneyimi",
        "Incident response ve monitoring anlayışı",
      ],
      test: "Görev testi: Vercel + Supabase + GitHub Actions için basit bir CI/CD pipeline tasarla. Build, test, preview ve production adımlarını belirt.",
    },
  },
];
