begin;

insert into public.catalog_item_types (key, label, description)
values
  ('advisor', 'Advisor', 'Expert and consultant records'),
  ('organization', 'Organization', 'Associations, chambers, missions and other institutions'),
  ('business', 'Business', 'Commercial businesses and venues'),
  ('event', 'Event', 'Public events and gatherings'),
  ('marketplace_listing', 'Marketplace Listing', 'Listings for community exchange and classifieds'),
  ('job_posting', 'Job Posting', 'Open jobs and recruitment entries'),
  ('community_group', 'Community Group', 'WhatsApp, Telegram, Discord and other community groups'),
  ('person_profile', 'Person Profile', 'Opt-in public profiles for diaspora members')
on conflict (key) do update
set
  label = excluded.label,
  description = excluded.description,
  is_active = true,
  updated_at = now();

insert into public.feature_definitions (key, name, description)
values
  ('reviews', 'Reviews', 'User reviews and ratings'),
  ('favorites', 'Favorites', 'Saved items for signed-in users'),
  ('public_contact', 'Public Contact', 'Public contact information'),
  ('map_location', 'Map Location', 'Location filters and map display'),
  ('external_links', 'External Links', 'Public website and social links'),
  ('media_gallery', 'Media Gallery', 'Public media attachments'),
  ('verification_badge', 'Verification Badge', 'Verified or official source markers'),
  ('ownership_claim', 'Ownership Claim', 'Claim requests for ownerless imported records'),
  ('opening_hours', 'Opening Hours', 'Structured opening hours'),
  ('online_booking', 'Online Booking', 'Supports online booking'),
  ('appointment_link', 'Appointment Link', 'External appointment booking link'),
  ('consultation_request', 'Consultation Request', 'Advisor consultation request capability'),
  ('membership_application', 'Membership Application', 'Application flow to join a group or organization'),
  ('event_registration', 'Event Registration', 'Registration flow for events'),
  ('external_join_link', 'External Join Link', 'External URL to join a group'),
  ('application_link', 'Application Link', 'External application or apply link'),
  ('expiry_date', 'Expiry Date', 'Record expiry semantics for listings or jobs')
on conflict (key) do update
set
  name = excluded.name,
  description = excluded.description,
  updated_at = now();

with feature_map(item_type, feature_key) as (
  values
    ('advisor', 'reviews'),
    ('advisor', 'favorites'),
    ('advisor', 'public_contact'),
    ('advisor', 'map_location'),
    ('advisor', 'external_links'),
    ('advisor', 'media_gallery'),
    ('advisor', 'verification_badge'),
    ('advisor', 'ownership_claim'),
    ('advisor', 'appointment_link'),
    ('advisor', 'consultation_request'),
    ('organization', 'favorites'),
    ('organization', 'public_contact'),
    ('organization', 'map_location'),
    ('organization', 'external_links'),
    ('organization', 'media_gallery'),
    ('organization', 'verification_badge'),
    ('organization', 'ownership_claim'),
    ('organization', 'membership_application'),
    ('business', 'reviews'),
    ('business', 'favorites'),
    ('business', 'public_contact'),
    ('business', 'map_location'),
    ('business', 'external_links'),
    ('business', 'media_gallery'),
    ('business', 'verification_badge'),
    ('business', 'ownership_claim'),
    ('business', 'opening_hours'),
    ('business', 'online_booking'),
    ('business', 'appointment_link'),
    ('event', 'favorites'),
    ('event', 'public_contact'),
    ('event', 'map_location'),
    ('event', 'external_links'),
    ('event', 'media_gallery'),
    ('event', 'verification_badge'),
    ('event', 'ownership_claim'),
    ('event', 'event_registration'),
    ('event', 'expiry_date'),
    ('marketplace_listing', 'favorites'),
    ('marketplace_listing', 'public_contact'),
    ('marketplace_listing', 'external_links'),
    ('marketplace_listing', 'media_gallery'),
    ('marketplace_listing', 'ownership_claim'),
    ('marketplace_listing', 'expiry_date'),
    ('job_posting', 'favorites'),
    ('job_posting', 'public_contact'),
    ('job_posting', 'external_links'),
    ('job_posting', 'media_gallery'),
    ('job_posting', 'ownership_claim'),
    ('job_posting', 'application_link'),
    ('job_posting', 'expiry_date'),
    ('community_group', 'favorites'),
    ('community_group', 'public_contact'),
    ('community_group', 'external_links'),
    ('community_group', 'verification_badge'),
    ('community_group', 'ownership_claim'),
    ('community_group', 'membership_application'),
    ('community_group', 'external_join_link'),
    ('person_profile', 'favorites'),
    ('person_profile', 'public_contact'),
    ('person_profile', 'external_links'),
    ('person_profile', 'media_gallery'),
    ('person_profile', 'verification_badge'),
    ('person_profile', 'ownership_claim')
)
insert into public.item_type_features (item_type, feature_key, is_enabled, configuration)
select
  fm.item_type,
  fm.feature_key,
  true,
  '{}'::jsonb
from feature_map fm
on conflict (item_type, feature_key) do update
set
  is_enabled = excluded.is_enabled,
  configuration = excluded.configuration,
  updated_at = now();

with category_seed(module, slug, name, sort_order) as (
  values
    ('advisor', 'real-estate', 'Real Estate', 10),
    ('advisor', 'visa-immigration', 'Visa & Immigration', 20),
    ('advisor', 'company-formation-business', 'Company Formation & Business', 30),
    ('advisor', 'legal-tax', 'Legal & Tax', 40),
    ('advisor', 'trademark-patent', 'Trademark & Patent', 50),
    ('advisor', 'financial', 'Financial', 60),
    ('advisor', 'lifestyle-relocation', 'Lifestyle & Relocation', 70),
    ('advisor', 'family-children', 'Family & Children', 80),
    ('advisor', 'psychologist-coach-wellbeing', 'Psychologist / Coach / Wellbeing', 90),
    ('advisor', 'education', 'Education', 100),
    ('advisor', 'practical-life', 'Practical Life', 110),
    ('organization', 'association', 'Association', 10),
    ('organization', 'foundation', 'Foundation', 20),
    ('organization', 'chamber', 'Chamber', 30),
    ('organization', 'council', 'Council', 40),
    ('organization', 'academic-unit', 'Academic Unit', 50),
    ('organization', 'educational-organization', 'Educational Organization', 60),
    ('organization', 'turkish-media-organization', 'Turkish Media Organization', 70),
    ('organization', 'embassy', 'Embassy', 80),
    ('organization', 'consulate', 'Consulate', 90),
    ('organization', 'healthcare-organization', 'Healthcare Organization', 100),
    ('organization', 'digital-community', 'Digital Community', 110),
    ('business', 'restaurant', 'Restaurant', 10),
    ('business', 'cafe', 'Cafe', 20),
    ('business', 'market', 'Market', 30),
    ('business', 'grocery', 'Grocery', 40),
    ('business', 'bakery', 'Bakery', 50),
    ('business', 'patisserie', 'Patisserie', 60),
    ('business', 'hairdresser', 'Hairdresser', 70),
    ('business', 'beauty', 'Beauty', 80),
    ('business', 'barber', 'Barber', 90),
    ('business', 'healthcare', 'Healthcare', 100),
    ('business', 'clinic', 'Clinic', 110),
    ('business', 'pharmacy', 'Pharmacy', 120),
    ('business', 'law-office', 'Law Office', 130),
    ('business', 'accounting', 'Accounting', 140),
    ('business', 'finance', 'Finance', 150),
    ('business', 'real-estate-office', 'Real Estate Office', 160),
    ('business', 'travel-agency', 'Travel Agency', 170),
    ('business', 'hotel', 'Hotel', 180),
    ('business', 'accommodation', 'Accommodation', 190),
    ('business', 'education-center', 'Education Center', 200),
    ('business', 'language-school', 'Language School', 210),
    ('business', 'it-software', 'IT & Software', 220),
    ('business', 'design-advertising', 'Design & Advertising', 230),
    ('business', 'construction-renovation', 'Construction & Renovation', 240),
    ('business', 'transport-logistics', 'Transport & Logistics', 250),
    ('business', 'automotive', 'Automotive', 260),
    ('business', 'gym', 'Gym', 270),
    ('business', 'children-family', 'Children & Family', 280),
    ('business', 'insurance', 'Insurance', 290),
    ('business', 'retail-store', 'Retail Store', 300),
    ('business', 'ecommerce', 'E-commerce', 310),
    ('business', 'wholesale', 'Wholesale', 320),
    ('event', 'networking', 'Networking', 10),
    ('event', 'event-education', 'Education', 20),
    ('event', 'culture', 'Culture', 30),
    ('event', 'event-business', 'Business', 40),
    ('event', 'social', 'Social', 50),
    ('event', 'sports', 'Sports', 60),
    ('marketplace_listing', 'second-hand', 'Second Hand', 10),
    ('marketplace_listing', 'room-for-rent', 'Room for Rent', 20),
    ('marketplace_listing', 'home-for-rent', 'Home for Rent', 30),
    ('marketplace_listing', 'lesson-course', 'Lesson / Course', 40),
    ('marketplace_listing', 'service', 'Service', 50),
    ('marketplace_listing', 'vehicle', 'Vehicle', 60),
    ('marketplace_listing', 'ticket', 'Ticket', 70),
    ('marketplace_listing', 'job-listing', 'Job Listing', 80),
    ('marketplace_listing', 'exchange', 'Exchange', 90),
    ('marketplace_listing', 'free', 'Free', 100),
    ('marketplace_listing', 'other', 'Other', 110),
    ('community_group', 'alumni', 'Alumni', 10),
    ('community_group', 'hobby', 'Hobby', 20),
    ('community_group', 'group-business', 'Business', 30),
    ('community_group', 'doctor', 'Doctor', 40),
    ('community_group', 'whatsapp', 'WhatsApp', 50),
    ('community_group', 'telegram', 'Telegram', 60),
    ('community_group', 'discord', 'Discord', 70),
    ('community_group', 'facebook', 'Facebook', 80),
    ('community_group', 'instagram', 'Instagram', 90),
    ('community_group', 'linkedin', 'LinkedIn', 100),
    ('community_group', 'group-other', 'Other', 110),
    ('person_profile', 'city-ambassador', 'City Ambassador', 10),
    ('person_profile', 'blogger', 'Blogger', 20),
    ('person_profile', 'vlogger', 'Vlogger', 30),
    ('person_profile', 'diaspora-individual', 'Diaspora Individual', 40)
)
insert into public.catalog_categories (module, slug, name, description, is_active, sort_order)
select
  cs.module,
  cs.slug,
  cs.name,
  cs.name || ' category for ' || cs.module,
  true,
  cs.sort_order
from category_seed cs
on conflict (module, slug) do update
set
  name = excluded.name,
  description = excluded.description,
  is_active = true,
  sort_order = excluded.sort_order,
  updated_at = now();

commit;
