-- Cadde 3.0 Faz 6 (1/1): Tanıtım (Çıfıt) — sponsorlu görünürlük kampanya katmanı.
-- D-01 KARARI (2026-06-11, ürün sahibi onayı): UI adı "Tanıtım"; Çarşı (carsi_*) ile
-- ASLA aynı tablo/panel altında birleşmez (spec §3.2). Mevcut cadde_billboard_cards /
-- cadde_sponsored_placements KORUNUR (kampanyaya geçiş opsiyonel P2).
-- Spec §9.7 (şema), §15 (modül), §10.1 (RPC listesi).
--
-- * Görünürlük yetkisi persona string'i ile DEĞİL feature ile: cadde.promotion.create
--   (Business/Consultant/Organization/Admin + BloggerVlogger) ve city_highlight tipi için
--   cadde.city.highlight_free (Şehir Elçisi — yalnız city-ambassador-highlight placement'ı).
-- * Kampanya akışı: create RPC → status 'pending' → admin_review RPC → approved/rejected.
--   "Aktif/Süresi doldu" ayrı status değildir; approved + tarih aralığından türetilir.
-- * Tüketim (rail/feed) list_cadde_promotions_v1 security-definer RPC'siyledir; campaigns
--   tablosunun SELECT'i yalnız sahibi+admin'dir (taslak/red verileri sızdırılmaz).
-- * Impression/click kayıtları record_cadde_promotion_event_v1 ile; abuse limiti aşılınca
--   HATA ATMAZ, sessizce false döner (UX kırılmaz, spec §15.4).

begin;

-- ── 1. Placement kataloğu + 6 seed (spec §15.2) ─────────────────────────────
create table if not exists public.cadde_promotion_placement_catalog (
  key text primary key,
  label_tr text not null,
  description text,
  sort_order int not null default 0,
  is_active boolean not null default true
);

insert into public.cadde_promotion_placement_catalog (key, label_tr, description, sort_order) values
  ('homepage-ai-bar',           'Ana Sayfa AI Bar Altı',        'Ana sayfa AI bar altı; maksimum 3 ay.',                    10),
  ('category-first-screen',     'Kategori İlk Ekran',           'Rol kategorisi ilk ekran; mobil ilk 6 içinde.',            20),
  ('cadde-right-rail',          'Cadde Sağ Kolon',              'Global, Köprü, ülke veya şehir bazlı sağ kolon.',          30),
  ('cadde-feed-inline',         'Cadde Akış İçi',               'Organik postların arasındaki sponsor kartı.',              40),
  ('cafe-theme-right-rail',     'Cafe Tema Sağ Kolonu',         'Tema eşleşmeli cafe sağ kolonu.',                          50),
  ('city-ambassador-highlight', 'Şehir Elçisi Öne Çıkarması',   'Elçinin kendi şehrindeki ücretsiz öne çıkarma.',           60)
on conflict (key) do nothing;

-- ── 2. Kampanya + placement + event tabloları (spec §9.7) ───────────────────
create table if not exists public.cadde_promotion_campaigns (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  campaign_type text not null,
  title text not null,
  description text not null,
  target_url text not null,
  image_url text,
  status text not null default 'draft',
  starts_at timestamptz,
  ends_at timestamptz,
  approved_at timestamptz,
  approved_by uuid references auth.users(id),
  review_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$ begin
  alter table public.cadde_promotion_campaigns
    add constraint cadde_promotion_campaigns_status_check
    check (status in ('draft', 'pending', 'approved', 'rejected'));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.cadde_promotion_campaigns
    add constraint cadde_promotion_campaigns_type_check
    check (campaign_type in ('business', 'consultant', 'event', 'community', 'city_highlight'));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.cadde_promotion_campaigns
    add constraint cadde_promotion_campaigns_dates_check
    check (ends_at is null or starts_at is null or ends_at > starts_at);
exception when duplicate_object then null; end $$;

create table if not exists public.cadde_promotion_placements (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.cadde_promotion_campaigns(id) on delete cascade,
  placement_key text not null references public.cadde_promotion_placement_catalog(key),
  country_id uuid references public.cadde_countries(id) on delete set null,
  city_id uuid references public.cadde_cities(id) on delete set null,
  diaspora_key text not null default 'tr',
  theme_keys text[] not null default '{}',
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.cadde_promotion_events (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.cadde_promotion_campaigns(id) on delete cascade,
  placement_key text not null,
  event_type text not null,
  viewer_user_id uuid references auth.users(id),
  occurred_at timestamptz not null default now()
);

do $$ begin
  alter table public.cadde_promotion_events
    add constraint cadde_promotion_events_type_check
    check (event_type in ('impression', 'click'));
exception when duplicate_object then null; end $$;

create index if not exists cadde_promotion_campaigns_owner_idx
  on public.cadde_promotion_campaigns (owner_user_id, status);
create index if not exists cadde_promotion_campaigns_status_idx
  on public.cadde_promotion_campaigns (status, starts_at, ends_at);
create index if not exists cadde_promotion_placements_campaign_idx
  on public.cadde_promotion_placements (campaign_id);
create index if not exists cadde_promotion_placements_key_idx
  on public.cadde_promotion_placements (placement_key, country_id, city_id);
create index if not exists cadde_promotion_events_campaign_idx
  on public.cadde_promotion_events (campaign_id, event_type, occurred_at desc);
create index if not exists cadde_promotion_events_abuse_idx
  on public.cadde_promotion_events (viewer_user_id, campaign_id, occurred_at desc);

-- ── 3. RLS ───────────────────────────────────────────────────────────────────
alter table public.cadde_promotion_placement_catalog enable row level security;
alter table public.cadde_promotion_campaigns enable row level security;
alter table public.cadde_promotion_placements enable row level security;
alter table public.cadde_promotion_events enable row level security;

drop policy if exists "promotion placement catalog public read" on public.cadde_promotion_placement_catalog;
create policy "promotion placement catalog public read"
on public.cadde_promotion_placement_catalog for select
to anon, authenticated
using (is_active = true);

-- Kampanyalar: sahibi kendi kayıtlarını, admin tümünü görür; tüketim RPC üzerinden.
drop policy if exists "promotion campaigns owner read" on public.cadde_promotion_campaigns;
create policy "promotion campaigns owner read"
on public.cadde_promotion_campaigns for select
using (owner_user_id = auth.uid() or public.is_admin_user(auth.uid()));

drop policy if exists "promotion campaigns admin write" on public.cadde_promotion_campaigns;
create policy "promotion campaigns admin write"
on public.cadde_promotion_campaigns for all
using (public.is_admin_user(auth.uid()))
with check (public.is_admin_user(auth.uid()));

drop policy if exists "promotion placements owner read" on public.cadde_promotion_placements;
create policy "promotion placements owner read"
on public.cadde_promotion_placements for select
using (
  exists (
    select 1 from public.cadde_promotion_campaigns c
    where c.id = campaign_id and (c.owner_user_id = auth.uid() or public.is_admin_user(auth.uid()))
  )
);

drop policy if exists "promotion placements admin write" on public.cadde_promotion_placements;
create policy "promotion placements admin write"
on public.cadde_promotion_placements for all
using (public.is_admin_user(auth.uid()))
with check (public.is_admin_user(auth.uid()));

-- Analytics: sahibi kendi kampanyasının eventlerini, admin tümünü okur; insert yalnız RPC.
drop policy if exists "promotion events owner read" on public.cadde_promotion_events;
create policy "promotion events owner read"
on public.cadde_promotion_events for select
using (
  exists (
    select 1 from public.cadde_promotion_campaigns c
    where c.id = campaign_id and (c.owner_user_id = auth.uid() or public.is_admin_user(auth.uid()))
  )
);

-- ── 4. create_cadde_promotion_campaign_v1 ────────────────────────────────────
-- p_placements: [{"key": "cadde-right-rail", "country": "Almanya", "city": "Berlin", "themeKeys": []}]
create or replace function public.create_cadde_promotion_campaign_v1(
  p_campaign_type text,
  p_title text,
  p_description text,
  p_target_url text,
  p_image_url text default null,
  p_starts_at timestamptz default null,
  p_ends_at timestamptz default null,
  p_placements jsonb default '[]'::jsonb
)
returns uuid
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_title text := trim(coalesce(p_title, ''));
  v_description text := trim(coalesce(p_description, ''));
  v_target_url text := trim(coalesce(p_target_url, ''));
  v_image_url text := nullif(trim(coalesce(p_image_url, '')), '');
  v_is_highlight boolean := p_campaign_type = 'city_highlight';
  v_campaign_id uuid;
  v_placement jsonb;
  v_placement_key text;
  v_country_id uuid;
  v_city_id uuid;
  v_placement_count int := 0;
  v_sort int := 0;
begin
  if v_uid is null then
    raise exception 'cadde_auth_required';
  end if;

  if not public.is_cadde_profile_complete(v_uid) then
    if public.cadde_phone_required() and not public.is_phone_verified(v_uid) then
      raise exception 'phone_verification_required';
    end if;
    raise exception 'cadde_profile_incomplete';
  end if;

  -- Spec §15.1: kontrol feature anahtarıyla — şehir elçisi yalnız ücretsiz highlight açar.
  if v_is_highlight then
    if not (public.has_cadde_feature(v_uid, 'cadde.city.highlight_free')
            or public.has_cadde_feature(v_uid, 'cadde.promotion.create')) then
      raise exception 'cadde_promotion_permission_denied';
    end if;
  else
    if not public.has_cadde_feature(v_uid, 'cadde.promotion.create') then
      raise exception 'cadde_promotion_permission_denied';
    end if;
  end if;

  if p_campaign_type not in ('business', 'consultant', 'event', 'community', 'city_highlight') then
    raise exception 'cadde_invalid_promotion_type';
  end if;

  if length(v_title) < 3 or length(v_title) > 100 then
    raise exception 'cadde_invalid_promotion_title';
  end if;

  if length(v_description) < 1 or length(v_description) > 500 then
    raise exception 'cadde_invalid_promotion_description';
  end if;

  -- target_url zorunlu ve http(s) olmalı (spec §15.4).
  if v_target_url !~ '^(https?://|/)' then
    raise exception 'cadde_invalid_promotion_url';
  end if;

  if v_image_url is not null and v_image_url !~ '^https?://' then
    raise exception 'cadde_invalid_promotion_url';
  end if;

  if p_starts_at is not null and p_ends_at is not null and p_ends_at <= p_starts_at then
    raise exception 'cadde_invalid_promotion_dates';
  end if;

  insert into public.cadde_promotion_campaigns (
    owner_user_id, campaign_type, title, description, target_url, image_url,
    status, starts_at, ends_at
  )
  values (
    v_uid, p_campaign_type, v_title, v_description, v_target_url, v_image_url,
    'pending', p_starts_at, p_ends_at
  )
  returning id into v_campaign_id;

  for v_placement in select * from jsonb_array_elements(coalesce(p_placements, '[]'::jsonb)) loop
    v_placement_key := trim(coalesce(v_placement ->> 'key', ''));

    if not exists (
      select 1 from public.cadde_promotion_placement_catalog
      where key = v_placement_key and is_active = true
    ) then
      raise exception 'cadde_invalid_placement';
    end if;

    -- Elçi highlight'ı yalnız kendi placement'ında yaşar (ücretli slotlara taşamaz).
    if v_is_highlight and v_placement_key <> 'city-ambassador-highlight' then
      raise exception 'cadde_invalid_placement';
    end if;

    -- homepage-ai-bar maksimum 3 ay (spec §15.2).
    if v_placement_key = 'homepage-ai-bar'
       and p_starts_at is not null and p_ends_at is not null
       and p_ends_at > p_starts_at + interval '3 months' then
      raise exception 'cadde_invalid_promotion_dates';
    end if;

    select c.id into v_country_id
    from public.cadde_countries c
    where c.name = nullif(trim(coalesce(v_placement ->> 'country', '')), '') and c.is_active = true
    limit 1;

    select ci.id into v_city_id
    from public.cadde_cities ci
    where ci.name = nullif(trim(coalesce(v_placement ->> 'city', '')), '')
      and (v_country_id is null or ci.country_id = v_country_id)
      and ci.is_active = true
    limit 1;

    insert into public.cadde_promotion_placements (campaign_id, placement_key, country_id, city_id, theme_keys, sort_order)
    select
      v_campaign_id,
      v_placement_key,
      v_country_id,
      v_city_id,
      coalesce((select array_agg(t) from jsonb_array_elements_text(coalesce(v_placement -> 'themeKeys', '[]'::jsonb)) t), '{}'),
      v_sort;

    v_sort := v_sort + 1;
    v_placement_count := v_placement_count + 1;
  end loop;

  if v_placement_count = 0 or v_placement_count > 6 then
    raise exception 'cadde_invalid_placement';
  end if;

  return v_campaign_id;
end;
$$;

-- ── 5. admin_review_cadde_promotion_v1 ───────────────────────────────────────
create or replace function public.admin_review_cadde_promotion_v1(
  p_campaign_id uuid,
  p_approve boolean,
  p_note text default null
)
returns void
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_status text;
begin
  if v_uid is null or not (public.is_admin(v_uid) or public.is_moderator(v_uid)) then
    raise exception 'cadde_admin_required';
  end if;

  select status into v_status from public.cadde_promotion_campaigns where id = p_campaign_id;
  if v_status is null then
    raise exception 'cadde_promotion_not_found';
  end if;
  if v_status <> 'pending' then
    raise exception 'cadde_promotion_not_pending';
  end if;

  update public.cadde_promotion_campaigns
  set status = case when p_approve then 'approved' else 'rejected' end,
      approved_at = case when p_approve then now() end,
      approved_by = v_uid,
      review_note = nullif(trim(coalesce(p_note, '')), ''),
      updated_at = now()
  where id = p_campaign_id;
end;
$$;

-- ── 6. list_cadde_promotions_v1 (tüketim: rail / feed-inline / cafe) ─────────
-- Onaylı + tarih aralığında + placement ve geo eşleşen kampanya kartları.
-- Anonim çağrı boş döner (D-02 ile uyumlu).
create or replace function public.list_cadde_promotions_v1(
  p_placement_key text,
  p_filters jsonb default '{}'::jsonb,
  p_limit integer default 5
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_limit int := least(greatest(coalesce(p_limit, 5), 1), 20);
  v_filter_countries text[];
  v_filter_cities text[];
  v_country_ids uuid[];
  v_city_ids uuid[];
  v_items jsonb;
begin
  if v_uid is null then
    return '[]'::jsonb;
  end if;

  select coalesce(array_agg(x), '{}') into v_filter_countries
  from jsonb_array_elements_text(coalesce(p_filters -> 'countries', '[]'::jsonb)) x
  where trim(x) <> '';

  select coalesce(array_agg(x), '{}') into v_filter_cities
  from jsonb_array_elements_text(coalesce(p_filters -> 'cities', '[]'::jsonb)) x
  where trim(x) <> '';

  select coalesce(array_agg(c.id), '{}') into v_country_ids
  from public.cadde_countries c
  where c.is_active = true and c.name = any(v_filter_countries);

  select coalesce(array_agg(ci.id), '{}') into v_city_ids
  from public.cadde_cities ci
  where ci.is_active = true
    and ci.name = any(v_filter_cities)
    and (cardinality(v_country_ids) = 0 or ci.country_id = any(v_country_ids));

  select coalesce(jsonb_agg(card), '[]'::jsonb) into v_items
  from (
    select jsonb_build_object(
      'campaignId', c.id,
      'placementKey', pl.placement_key,
      'campaignType', c.campaign_type,
      'title', c.title,
      'description', c.description,
      'targetUrl', c.target_url,
      'imageUrl', c.image_url
    ) as card
    from public.cadde_promotion_campaigns c
    join public.cadde_promotion_placements pl on pl.campaign_id = c.id
    where c.status = 'approved'
      and (c.starts_at is null or c.starts_at <= now())
      and (c.ends_at is null or c.ends_at > now())
      and pl.placement_key = p_placement_key
      and (cardinality(v_country_ids) = 0 or pl.country_id is null or pl.country_id = any(v_country_ids))
      and (cardinality(v_city_ids) = 0 or pl.city_id is null or pl.city_id = any(v_city_ids))
    order by pl.sort_order asc, c.approved_at desc
    limit v_limit
  ) cards;

  return v_items;
end;
$$;

-- ── 7. record_cadde_promotion_event_v1 (abuse limitli, spec §15.4) ───────────
-- Limit aşımında HATA ATMAZ; false döner (analytics UX'i kırmaz).
create or replace function public.record_cadde_promotion_event_v1(
  p_campaign_id uuid,
  p_placement_key text,
  p_event_type text
)
returns boolean
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_recent int;
begin
  if v_uid is null then
    return false;
  end if;

  if p_event_type not in ('impression', 'click') then
    raise exception 'cadde_invalid_promotion_event';
  end if;

  if not exists (
    select 1 from public.cadde_promotion_campaigns
    where id = p_campaign_id and status = 'approved'
  ) then
    return false;
  end if;

  select count(*) into v_recent
  from public.cadde_promotion_events
  where viewer_user_id = v_uid
    and campaign_id = p_campaign_id
    and occurred_at > now() - interval '1 hour';

  if v_recent >= 30 then
    return false;
  end if;

  insert into public.cadde_promotion_events (campaign_id, placement_key, event_type, viewer_user_id)
  values (p_campaign_id, p_placement_key, p_event_type, v_uid);

  return true;
end;
$$;

-- ── 8. Grant'ler ─────────────────────────────────────────────────────────────
revoke all on function public.create_cadde_promotion_campaign_v1(text, text, text, text, text, timestamptz, timestamptz, jsonb) from public, anon;
revoke all on function public.admin_review_cadde_promotion_v1(uuid, boolean, text) from public, anon;
revoke all on function public.list_cadde_promotions_v1(text, jsonb, integer) from public, anon;
revoke all on function public.record_cadde_promotion_event_v1(uuid, text, text) from public, anon;

grant execute on function public.create_cadde_promotion_campaign_v1(text, text, text, text, text, timestamptz, timestamptz, jsonb) to authenticated;
grant execute on function public.admin_review_cadde_promotion_v1(uuid, boolean, text) to authenticated;
grant execute on function public.list_cadde_promotions_v1(text, jsonb, integer) to authenticated;
grant execute on function public.record_cadde_promotion_event_v1(uuid, text, text) to authenticated;

commit;
